### ISSUE TITLE
Plot.Copy() is not copying all information

### ISSUE THREAD

**Issue by PassionateDeveloper86** [ScottPlot/ScottPlot#1010]
Hi,

I am using the 4.1 version in WPF.

I have a plot in which the user can interact, zoom etc.
For saving the plot I use the SaveFig() method, which is fine.
Now I want to save the NOT ZOOMED chart, but without interacting with the shown chart when saving.

So the way to go for me is the idea, that I can copy the Plot information of the chart with
var newPlot = Plot.Copy();
and just 
newPlot.SaveFig(...) 
to save the not zoomed chart.

But when I copy the plot information it seemes that a lot of information is lost, e.g. the viewLimits, which are set to minX: 0, minY: 0 and a calculated maxX and maxY depending on user settings before (so not the default behaviour).

**Comment by PassionateDeveloper86** [comment]
> 
> 
> Could it be that it only copies `Plottables` ? Either way you could do something like this:
> `var MainPlot; //this is your main plot`
> `var newPlot = MainPlot;`
> `newPlot.Plot.AxisAuto(); //reset the view to fit all data within view`
> `newPlot.SaveFig(...);`

Might  be possible, but even only the plottables are not correctly copied as it seemed.
I tried AxisAuto allready, but no success, it seams because it is not rendered, that some information is not correctly set.

**Comment by breakwinz** [comment]
> > 
> 
> > 
> 
> > Could it be that it only copies `Plottables` ? Either way you could do something like this:
> 
> > `var MainPlot; //this is your main plot`
> 
> > `var newPlot = MainPlot;`
> 
> > `newPlot.Plot.AxisAuto(); //reset the view to fit all data within view`
> 
> > `newPlot.SaveFig(...);`
> 
> 
> 
> Might  be possible, but even only the plottables are not correctly copied as it seemed.
> 
> I tried AxisAuto allready, but no success, it seams because it is not rendered, that some information is not correctly set.


This is seems like a bug. Either way to get around it, and not use the copy() method for now you should be able to do 

var newPlot = MainPlot

**Comment by swharden** [comment]
Hi @PassionateDeveloper86,

Currently there isn't an easy way to deeply copy a plot. We're aware of this limitation (similar to #819) and improving this is something I recently added to the list of moderate priority triaged tasks (#1028).

This a potentially difficult thing to implement (requiring modifying almost all styling, renderable, and plottable classes) and not something I'm going to undertake in the short term, so I'm going to close this issue until work toward it begins.

> I want to save the NOT ZOOMED chart, but without interacting with the shown chart when saving.

A tactical solution to address your specific issue could be something like this:

```cs
// I'm typing in the browser here - you may need to tweak this
var originalLimits = wpfPlot1.plt.GetAxisLimits();
wpfPlot1.plt.SetAxisLimits(/* zoomed in */);
wpfPlot1.plt.SaveFig("zoomed_in.png");
wpfPlot1.plt.SetAxisLimits(originalLimits);
```

Since the `Render()` method isn't called, the user is unlikely to see the zoomed-in plot.

I hope this helps!
