### ISSUE TITLE
Remove a point from a plottable

### ISSUE THREAD

**Issue by dprevato** [ScottPlot/ScottPlot#1039]
I found myself with a problem harder than I thought: is there a way to remove a point from a plot, without having to rebuild the entire chart?
I have a chart with a ScatterPlot, where the user has to be able to change the Y value of one or more points (and no problem here, as the total number of points does not change), or to delete one of the points... and here I am stucked. Am I compelled to rebuild the entire chart from zero, or there is a way that I haven't found?
Thank to you all, as always

**Comment by swharden** [comment]
Hi @dprevato, here are some options you may find useful!

I recognize this is a difficult task currently, and making it easier is a high priority task in my triage list #1028

## Change Data in Fixed-Length Arrays

If you plot data in fixed-length arrays, you can change the values in the original arrays and request a new render. This is extremely fast.

```cs
double[] xs = { /* your data */ }
double[] ys = { /* your data */ }

// plot your original data
formsPlot1.plt.AddScatterPlot(xs, ys);
formsPlot1.Render();

// modify the original data arrays and re-render
ys[5] = 123;
formsPlot.Render();
```

## ScatterPlotList

This option is best if the number of data points changes often

This plot type is implemented as a temporary plot type but it might get you closer to your goal

```cs
// create the plottable and add it to the plot
var plt = new ScottPlot.Plot();
var spList = new ScottPlot.Plottable.ScatterPlotList();
plt.Add(spList);

// modify elements in the list whenever you want
spList.Add(x, y);
```

The limitation here is that I implemented `Add`, `AddRange`, and `Clear` but no `RemoveAt` or `RemoveRange`. If you want to create a PR for these, I'd be happy to merge it in! Otherwise this will get there eventually.

https://github.com/ScottPlot/ScottPlot/blob/729388b4f021fcf4d86480af094d53495793534a/src/ScottPlot/Plottable/ScatterPlotList.cs#L46-L78

## MinRenderIndex and MaxRenderIndex

Use min/max render index fields to limit points displayed at the edge 

This option is best if data points are added and removed at the start and end of the plot. You can create a plot with a very large array, then just control visibility at the edges.

```cs
// plot original data
var plt = new ScottPlot.Plot();
var myScatterPlot = plt.AddScatterPlot(xs, ys);

// set the index of the last point to render.
// you can increase this number as the xs and ys array is populated with more data.
myScatterPlot.MaxRenderIndex = 123;
```

## Replace Arrays

You could replace the data in the plottable with a new array of a different size when the data changes.

```cs
// plot original data
var plt = new ScottPlot.Plot();
var myScatterPlot = plt.AddScatterPlot(xs, ys);

// plot new data of a different size
myScatterPlot.Update(newXs, newYs);
```

## Clear and Replot

This is the most extreme example, but it works
```cs
// plot original data
var plt = new ScottPlot.Plot();
plt.AddScatterPlot(xs, ys);

// plot new data of a different size
plt.Clear();
plt.AddScatterPlot(newXs, newYs);
```
