### ISSUE TITLE
Draggable vertical line extremely laggy when plotting 100+ SignalXY

### ISSUE THREAD

**Issue by breakwinz** [ScottPlot/ScottPlot#1066]
**ScottPlot Version:** 4.1.14
**Operating System:** W10
**Application Type:** winforms

Draggable Vertical lines are extremely laggy when dragging across a plot. Very similar to #1055 However, running the executible outside of visual studio did little to no difference..

[https://i.gyazo.com/295bb929cf5dcae36c28cccf63a60759.mp4]

The code used to generate the graphs: 

```cs
    public void showGraph(List<Dictionary<string, dynamic>> values_for_graph, FormsPlot MainPlot)
    { //draws the signalxy lines for every set of x/y-coordinates (dictionary).

		List<ScottPlot.Plottable.SignalPlotXYConst<double, double>> signals = new 
     List<ScottPlot.Plottable.SignalPlotXYConst<double, double>>();
		
		//used to simulate data coming from database as List<Dictionary<string, dynamic>>. Simulating 200 sets of x/y data 
     ranging from 0 - 40000
        values_for_graph = randomXYData(200, 40001); 
        foreach (Dictionary<string, dynamic> DIC in values_for_graph) //step through each set of x/y-coordinates (dictionary)
        {
            Color randomColor = Color.FromArgb(0, rnd.Next(256), rnd.Next(256));
			// take keys and convert value to double. (json only supports string keys). Convert to array
            double[] x_coordinates_keys = DIC.Keys.ToArray().Select(Double.Parse).ToArray();
            Array.Sort(x_coordinates_keys);    //sort them just incase they are not in order already                 

            signals.Add(MainPlot.Plot.AddSignalXYConst(x_coordinates_keys, DIC.Values.Cast<Double>().ToArray(), randomColor));
            signals.Last().LineWidth = 0.1;
        }

        draggableVline1 = MainPlot.Plot.AddVerticalLine(x_coordinates_keys[0], Color.Black, 1, LineStyle.Dash);
        draggableVline1.DragEnabled = true;

        MainPlot.Plot.AxisAuto(); //reset the view to fit all data within view          
    }

    private List<double[]> RandomYGen(int count, double mean, double std, int signals)
    {
        List<Double[]> yss = new List<double[]>();
        double[] y;
        for (int i = 0; i < signals; i++)
        {
            y = DataGen.NoisySin(new Random(), count);
            yss.Add(y);
        }

        return yss;
    }

    private double[] RandomXGen(int count)
    {
        double[] x = DataGen.Consecutive(count);
        return x;
    }

    private List<Dictionary<string, dynamic>> randomXYData(int signals, int point_count)
    {
        List<Dictionary<string, dynamic>> values_for_graph = new List<Dictionary<string, dynamic>>();
        double[] xs = RandomXGen(point_count);
        List<Double[]> yss = new List<double[]>();
        yss = RandomYGen(point_count, 30, 0.2, signals);

        for (int i = 0; i < yss.Count; i++)
        {
            Dictionary<string, dynamic> temp = new Dictionary<string, dynamic>();
            for (int o = 0; o < xs.Length; o++)
            {
                temp.Add(xs[o].ToString(), (dynamic)yss[i][o]);
            }
            values_for_graph.Add(temp);
        }
        return values_for_graph;
    }
```

Reducing the number of signals from 200 to say 5-10 helps a lot. But my usecase will most likely have 100+ sets of signals (sets of x/y data)

I have tried `formsPlot1.Configuration.AllowDroppedFramesWhileDragging = true;
            formsPlot1.Configuration.Quality = 0;
            formsPlot1.Configuration.UseRenderQueue = true;`

All which again do little to nothing.

Is there a setting im missing. Can someone please try this on their setup and see if it is as laggy as mine?

Edit: This is running on a extremely powerful "gaming" machine

**Comment by swharden** [comment]
Hi @breakwinz, thanks for posting this!

### The reason slow plots have slow mouse interactions

ScottPlot works by rendering Bitmap images. The user controls (e.g., FormsPlot) respond to mouse events by asking ScottPlot to render Bitmaps, then when they're rendered they get displayed on the screen.

If a Bitmap is really slow to render (e.g., because you have 100+ signal plots on it), the frame rate of updates will be very slow. This is what you are observing here. The vertical lines the mouse interacts with are just lines drawn on a bitmap, and since that bitmap is burdened with the heavy plotting task the mouse interaction appears burdened too.

### A quick solution: trackbar

If you place a trackbar beneath the plot, then on every change update the position of the vertical line and request a re-render, this problem may not exist. You can call `RenderRequest()` to request a non-blocking render.

### A complex solution: custom control for mouse interaction

If you _really_ want mouse-interactive draggable lines to appear on top of your plot, the way to achieve this is with your own custom control which renders those lines (on top of a traditional scottplot control). This will also require asynchronous rendering of the Bitmap (which isn't too bad - there's already a nonblocking RenderRequest() method for this), allowing your GUI to remain non-blocked (and allow you to draw your custom vertical line) in what feels like real time no matter how long the plot takes to render beneath. 

I hope this helps!
