### ISSUE TITLE
Control: incorrect position when dropped while moving the mouse quickly

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1076]
if you drag a draggable axis line and drop it _really fast_ while continuously moving the mouse (no stopping) the plot gets confused and things you moved the graph but doesn't request a re-render. 

What you see (and where the line is) no longer matches-up with where the line actually is, so it appear like you can't move the line anymore.

https://user-images.githubusercontent.com/4165489/119750157-bb1b4400-be66-11eb-9eb2-d61a9aa68c7e.mp4

**Comment by StendProg** [comment]
Hi @swharden 

To fix this problem write in startup sequence:
```c#
formsPlot1.Configuration.UseRenderQueue = true;
```

Seriously, the problem is with the `Render(skipIfCurrentlyRendering: true)` approach, the last Render requests will most likely be skipped. The line value has the correct value, but no Render has been called for it, any scaling, paning of the contol will correct the problem.
`RenderQueue` will always call render after the last request, even though some intermediate ones have been skipped.

**Comment by swharden** [comment]
You're right the problem is with the final render. It's very disruptive because either (a) the line doesn't display in its final position or (b) the entire plot pans but isn't rendered and you don't know until you click it again (shown here):

![mouse-jump](https://user-images.githubusercontent.com/4165489/127940769-59ce1b09-712e-45eb-ba6d-6f8cd1b52ce2.gif)

The problem may be that a `MouseMove` event gets processed while the `MouseUp` event is processing. Moving the `PlottableBeingDragged = null` to the _end_ of `Backend.MouseUp()` helped, and processing one more `MouseUpClearRender` event after a plottable is dropped seemed to fix it (#1174).
