### ISSUE TITLE
AxisAutoY() not workig properly

### ISSUE THREAD

**Issue by EmanuelFeru** [ScottPlot/ScottPlot#1089]
**ScottPlot Version:** 4.1.15

**Operating System:** W10

**Application Type:** WinForms

**Bug Description:** I think the `AxisAutoY()` is not working properly, because it always does full AxisAuto, exactly as `AxisAuto()`. Expected behavior is that it does the axis fit only on the Y axis, leaving the X axis unchanged.
Initially I thought is because the Vertical Red line that I added. But behavior is the same even without the line (see videos below).

This is the code executed when I press `Y` key:
```cs
// Key Press: Y (Fit Y axis only)
if (keyData == Keys.Y)
{
      formsPlot1.Plot.AxisAutoY();
      formsPlot1.Render();
      return true;
}
```

With Vertical line:

https://user-images.githubusercontent.com/24780745/120063372-34818500-c067-11eb-9935-55f948b01882.mp4

Without Vertical line:

https://user-images.githubusercontent.com/24780745/120063375-377c7580-c067-11eb-961d-f9e606ef4ed1.mp4

**Comment by EmanuelFeru** [comment]
Hi Scott, thank you for addressing this issue. I did a quick test today and it is working, however I see it is not using the complete Y axis space. Any idea why?

I think is because it is using the whole data set to fit. Can we do something that it only looks at the visible data section and autofits based on that?

https://user-images.githubusercontent.com/24780745/120491909-eb5c6880-c3b9-11eb-8576-8023dbd714f0.mp4

**Comment by swharden** [comment]
> not using the complete Y axis space. Any idea why?

Hi @EmanuelFeru, this is actually the intended functionality. It's automatically setting the axis limits to the limits of the data for the entire curve (not just the portion of the curve in view).

If you want to set the vertical limits to just the data in view, you'll need to do something custom like:

```cs
double rangeMin= 123; // calculate it on your end
double rangeMax = 456; // calculate it on your end

formsPlot1.Plot.SetAxisLimits(yMin: rangeMin, yMax: rangeMax);
formsPlot1.Render();
```

**Comment by EmanuelFeru** [comment]
For one signal it is possible to do it on my side. But for multiple signals it becomes quite difficult on my end, because I need to loop through the signals, then find the global max and min and limit based on that. I was thinking maybe is easier on the graphical side to find the highest and lowest pixel and limit based on that. But if not I will see what I can do.

**Comment by swharden** [comment]
> for multiple signals it becomes quite difficult on my end

This is a hard problem! For ScottPlot to do it the problem would have to be solved individually for every plot type. Currently `IPlottable` just has:

https://github.com/ScottPlot/ScottPlot/blob/3ead8c204116ea95baed60df6715b70cd668beab/src/ScottPlot/Plottable/IPlottable.cs#L22

We _could_ add methods to the interface like:
```cs
// return the Y min/max of the data in the given range
(double yMin, double yMax) GetAxisLimitsY(double xMin = double.NegativeInfinity, double xMax = double.PositiveInfinity)
```

...but that looks a little messy.

Also consider the very confusing case where you zoom in to a signal plot so much that you just see a straight line because the two nearest points are off the screen. If you call autoY in that case, it's not intuitive what behavior to expect.

For these reasons I'm happy to keep things like they are, and if the user wants more fine control over automatic axis limits over a range they can implement it in the way that is best for their application. Thanks for the suggestion though! 👍
