### ISSUE TITLE
Add "step" option for low density rendering mode in Signal plots

### ISSUE THREAD

**Issue by EmanuelFeru** [ScottPlot/ScottPlot#1092]
## Features Suggestion

Hi Scott, it would be great to have a function:
```cs
public SignalPlotConstStep<T> AddSignalConstStep<T>(T[] ys, double sampleRate = 1, Color? color = null, string label = null) where T : struct, IComparable;
```
similar to `AddScatterStep(...)`. I know `AddScatterStep()` can already do the job. But if I understand correctly the `AddSignalConst` is much faster in case of high number of data points. So, I was wondering if we can do exactly as `AddSignalConst` to maintain performance but plot it as step.

 I work with microcontrollers and there the signals are discrete, so it would be ideal to display them as steps. Do you think it would be much effort to achieve something like this?

`AddSignalConst`
![image](https://user-images.githubusercontent.com/24780745/120076257-eab78f80-c0a4-11eb-8756-360f27452501.png)

`AddSignalConstStep` (Suggested feature)
![image](https://user-images.githubusercontent.com/24780745/120076266-facf6f00-c0a4-11eb-9c27-4c73a6d65ed5.png)

**Comment by bclehmann** [comment]
The reason `Signal`, `SignalConst` and `SignalXY` are faster is because they can take advantage of optimizations between points that are very close together. If there are 10 sequential points in an area smaller than an individual pixel, ScottPlot can simply draw from the first to the tenth and skip everything in between.

For points that are that densely packed on whatever zoom level, you wouldn't be able to tell that it was a stepped plot, it would look like a normal line plot.

**Comment by EmanuelFeru** [comment]
When the plot is completely zoomed out, I agree with you @bclehmann that there is no difference step or not step. And you can do some tricks to render quickly because the details are not seen anyway.

My question is what happens when we zoom until details become visible and we can see the steps? Is there a speed difference between const and non-const plot?

**Comment by swharden** [comment]
> For points that are that densely packed on whatever zoom level, you wouldn't be able to tell that it was a stepped plot, it would look like a normal line plot.

This is true, and Signal Plots call this rendering type "high density mode".

## Step Display in Low Density Mode

However in low density rendering mode the points on the screen are connected with straight lines here:

https://github.com/ScottPlot/ScottPlot/blob/b1d26dc508f15cb4ff3a0c0feeae6ca803cfe769/src/ScottPlot/Plottable/SignalPlotBase.cs#L279

This line could be modified to check if `StepDisplay` is `true` and if so draw using the step style

## Implementation

This logic can be lifted from the step display in the scatter plot class:

https://github.com/ScottPlot/ScottPlot/blob/b1d26dc508f15cb4ff3a0c0feeae6ca803cfe769/src/ScottPlot/Plottable/ScatterPlot.cs#L243-L253

**Comment by EmanuelFeru** [comment]
For my information, is there a description on how to contribute? 🙂 Maybe I am not ready to contribute right away, I still need to get familiar with the code. However, for the future just in case it would be good to know: how to run the source code and how do you develop in few steps.

**Comment by swharden** [comment]
@EmanuelFeru do you want to try making this modification yourself and seeing if it produces the output you expect, and if so creating a pull request? Adding a cookbook example demonstrating this new functionality would be great too. 

If you're up for it let me know and I'll keep an eye out for a pull request. If not, no worries, I'll leave this on the triage list (#1028) and get to it eventually myself.

**Comment by swharden** [comment]
> is there a description on how to contribute?

There is [CONTRIBUTING.md](https://github.com/ScottPlot/ScottPlot/blob/master/CONTRIBUTING.md) but it doesn't have a lot of technical details.

I should probably put some of the information below on that contributing page... I got this same question from another person earlier today via email. I find many people want to contribute, but if you haven't used git/GitHub much before it's pretty intimidating and has a steep learning curve. There are _too many_ tutorials out there, and it's hard for newcomers to know which ones to work through. Instructional videos range from 2 minutes to 2 hours in length, and it's hard to know what depth of understanding you need to achieve to make a simple code modification like this.

## How to Contribute a Code Modification

If you're new to git and GitHub, one of the easiest ways to get started is to use the GitHub Desktop Client: https://desktop.github.com/

Basically the steps will be:
* clone the repository (using GitHub website / GitHub Desktop)
* change the code as desired (in Visual Studio)
* make sure the tests pass (in Visual Studio)
* autoformat the code (./src/autoformat.bat)
* commit your code change (using GitHub Desktop)
* push your commits to GitHub (using GitHub Desktop)
* create a pull request (using GitHub website)

By doing this you'll create a `EmanuelFeru/ScottPlot` repository with your code changes, and a _pull request_ is a way for your to request those changes get _merged_ into the official `ScottPlot/ScottPlot` repository. After you make the pull request I can review the code, make changes as desired, and merge it when it's ready.

This may seem a bit confusing at first, but once you get the hang of it, it gets easier!

Note that GitHub Desktop is essentially a GUI version of the `git` command, and anything you do in that application you could also do from the command line. Many tutorials may show command line instructions, but you can use either the command line or the desktop app depending on what you find comfortable.

**Comment by EmanuelFeru** [comment]
I think i am not yet ready... I will still have to get more familiar with the source code. So, i say to not wait for me at the moment.
I was just wondering how do you develop the source code? By running the demo projects?
I will have to look myself more, so sorry for the silly questions.

**Comment by EmanuelFeru** [comment]
Thank you for the answer Scott. For me the github part is no problem, because i have my own repositories. The ScottPlot technical develoment part I miss, and that could help a lot in the CONTRIBUTING.md
- what project(s) do you run for development
- what tests and how
- what are the dependencies, for sure Cookbook is one of them to keep it updated with code

This is what I have to get more familiar 🙂 If I saw correctly you did some very nice smart things in generating the cookbook automatically.

**Comment by swharden** [comment]
> what project(s) do you run for development, what tests and how, what are the dependencies...

Pretty much everything you need is already there when you open `src/ScottPlot.sln`

> I was just wondering how do you develop the source code? By running the demo projects?

The answer to this question should probably also be added to [CONTRIBUTING.md](https://github.com/ScottPlot/ScottPlot/blob/master/CONTRIBUTING.md)

## Modify ScottPlot Behavior

Edit SignalPlotBase.cs to:
* add `public bool StepDisplay = false;` at the top
* edit line ~279 to `if (StepDisplay )` as described in https://github.com/ScottPlot/ScottPlot/issues/1092#issuecomment-850887902

## Create a Cookbook Example

ScatterPlot cookbook recipes are here:
https://github.com/ScottPlot/ScottPlot/blob/b1d26dc508f15cb4ff3a0c0feeae6ca803cfe769/src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Signal.cs#L1-L301

You can mimic those recipes and just add one more at the bottom demonstrating step mode

## Run the Demo

The demo application interactively displays all cookbook recipes, so it's an easy way to try-out your code. The demo is a project in the main solution.

![image](https://user-images.githubusercontent.com/4165489/120083905-08cbc280-c09a-11eb-8778-9ff29935858b.png)

## Run the Tests

In Visual Studio you can see all the tests by clicking "Test" and selecting "Test Explorer". Icons there let you "run all tests", as well as inspect any that may have failed.

## Run the Autoformatter

Before committing run the `src/autoformat.bat` script to ensure the code is properly formatted (otherwise the build will fail in GitHub).

That should be all the info you need! If you give it a go you'll probably find it's easier than you expected 👍 🚀

**Comment by EmanuelFeru** [comment]
This is exactly what I needed.

**Comment by EmanuelFeru** [comment]
I tried to open the project and I get these:
![image](https://user-images.githubusercontent.com/24780745/120590407-c2c88300-c43a-11eb-8094-7b518086c830.png)

And  then when I try to run:
![image](https://user-images.githubusercontent.com/24780745/120590429-ceb44500-c43a-11eb-9361-e0012f30a7bd.png)

I know it is related to .NET  version. I want to select .NET 5.0, but for some reason it does not allow me:
![image](https://user-images.githubusercontent.com/24780745/120590807-6dd93c80-c43b-11eb-82bb-3602ab7cf6c4.png)

Any suggestions?

**Comment by swharden** [comment]
I'd try the second option - installing .NET 4.8 on your machine 👍

**Comment by EmanuelFeru** [comment]
Yep, that did the trick.

**Comment by EmanuelFeru** [comment]
See PR.
