### ISSUE TITLE
Plot: GetImageBytes()

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1107]
For cloud applications we need to convert a `Bitmap` to `byte[]` to save into blob storage.

This requires interacting with `System.Drawing.Common`, which means taking that dependency on in the cloud app.

The Plot module should have a `GetBitmapBytes()` that lets you specify file format type, preventing the need to pass `Bitmap` objects around in the cloud

```cs
public static byte[] GetBytesPng(System.Drawing.Bitmap bmp)
{
    using MemoryStream stream = new();
    bmp.Save(stream, System.Drawing.Imaging.ImageFormat.Png);
    return stream.ToArray();
}
```

**Comment by bclehmann** [comment]
Bitmaps are an unfortunate choice for blob storage as each OS implements them differently. Using System.Drawing.Common on Windows will not create a bitmap that many programs on MacOS can understand. This is normally not an issue because of device-independent bitmaps (a Microsoft standard). However, System.Drawing.Common doesn't create them, presumably for backwards compatibility.

So this makes me think you should probably use PNG if you want a cross-platform bitmap. But if we're going to support multiple file formats we might as well fully open the can of worms, rather than let them slowly wriggle out. This may end up being connected to a potential SVG renderer in #1028, although simply supporting multiple raster formats is likely to be simpler.

**Comment by swharden** [comment]
> Using System.Drawing.Common on Windows will not create a bitmap that many programs on MacOS can understand

Wow, I didn't know this! Thanks for pointing it out https://en.wikipedia.org/wiki/BMP_file_format#Bitmap_file_header

Perhaps we should change language to something like:
```cs
Byte[] bytes1 = plt.GetImageBytes(ScottPlot.Drawing.ImageFormat.WindowsBitmap);
Byte[] bytes2 = plt.GetImageBytes(ScottPlot.Drawing.ImageFormat.Png);
Byte[] bytes3 = plt.GetImageBytes(ScottPlot.Drawing.ImageFormat.Jpeg, quality: 85);
```
