### ISSUE TITLE
Memory usage increases while interacting with plot

### ISSUE THREAD

**Issue by EmanuelFeru** [ScottPlot/ScottPlot#1109]
## Bug Report Template

**ScottPlot Version:** 4.1.16

**Operating System:** W10

**Application Type:** WinForms & WPF

**Bug Description:**
- While interacting with the plot e.g., continuously doing a pan action, the RAM memory increases, especially for WPF application. In case of WinForms memory increases as well but not as significant
- Once the interraction is released:
       - WPF: memory is released
       - WinForm: memory usage remains but I noticed that after a while of interraction sometimes it is also released.

I marked it as bug but I am not sure if it is a bug or normal functioning. So, please feel free to change if you consider so.

**Reproducing:** Create complete new apps in WPF and WinForms. Drag one single ScottPlot object from the Toolbox. Run the application.

WPF:

https://user-images.githubusercontent.com/24780745/120432507-4ff7d300-c37a-11eb-982d-1b9cac130d21.mp4

WinForms

https://user-images.githubusercontent.com/24780745/120432519-5423f080-c37a-11eb-89c5-caaf55d28dd7.mp4

**Comment by StendProg** [comment]
I don't see a big problem here, it's quite normal behavior.
Yes, `ScottPlot` is not very careful about memory allocations, but in the end the garbage collector will clean it all up, which is why it was made. The different behavior for different platforms can also be explained by different settings of the garbage collector.
In the example that you brought allocations of hundreds of megabytes, in 2021 I think you shouldn't even think about that. In addition, your tests are highly platform dependent, if there were less free memory, the garbage collector would be more aggressive.

**Comment by EmanuelFeru** [comment]
I did play once until I reached +2 Gb for WPF. But if you say it is normal behavior then we can close the issue.
