### ISSUE TITLE
How to position crosshair, points, arrows, etc. on DateTime axes, and how to highlight the nearest candlestick to the cursor.

### ISSUE THREAD

**Issue by Stepien** [ScottPlot/ScottPlot#1116]
## Features Suggestion

Add crosshair, points, arrows, images, tooltips to candelstick chart

**Feature description:** Describe your question here

Hi, I cant add crosshair, points, arrows, images, tooltips to candelstick chart.
When I try adding its going to 1970 on date. Crosshair is not showing and breaking after adding new candles.
Is there a way to retrive points on chart from date - price so i can add this objects properly?
Or add to candlestick arrow images to mark them, or maybe change color of single candle?

**Comment by swharden** [comment]
## Working with DateTime Axis

> When I try adding its going to 1970 on date

This is because datetime axes us OA time https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tooadate

Here's an example of how to add crosshairs on a plot with a DateTime axis: https://swharden.com/scottplot/cookbooks/4.1.16/category/plottable-crosshair/#datetime-axis-label

## Mouse-Interactive Candlesticks

> Is there a way to retrive points on chart from date - price so I can add this objects properly?

Not really. You could add an event handler to the control's `MouseMove` event to determine the cursor position, iterate your candles to find the one closest to the mouse, and display information on the plot and move crosshairs to highlight it. This is doable, but a lot of work, and high amounts of mouse interaction may merit use of a control specifically for financial charting.

See https://swharden.com/scottplot/faq/mouse-position for a code example you may find helpful.

Hope this helps!
Scott
