### ISSUE TITLE
Pipelines Badges Are Broken

### ISSUE THREAD

**Issue by bclehmann** [ScottPlot/ScottPlot#1138]
## Bug Report Template

**ScottPlot Version:** N/A

**Operating System:** N/W

**Application Type:** N/A

**Bug Description:** The badges in the readme for the build pipelines are broken:

![Screenshot_20210701-210816~2](https://user-images.githubusercontent.com/8635304/124215187-c76f6e00-dab0-11eb-8413-71f51f47937d.png)

**Reproducing:** What do others have to do to reproduce the bug? A code sample may be helpful.

Visit the readme on github.

**Comment by swharden** [comment]
I saw this today too ... Maybe these third party badges only last for one month and ScottPlot hasn't had a public commit for 4 weeks now?

I could use the official badges (which maybe never expire?) or I could do better at not letting 30d go by again...

I've been putting all my effort recently into a few of my other projects (AbfSharp and pyabf) but I'm wrapping those up and I intend to focus again on ScottPlot again within the next couple days ...

**Comment by StendProg** [comment]
I think you can make an empty commit to check/fix. Nobody will condemn for this.

**Comment by swharden** [comment]
It seems this is an Azure Pipelines thing, and changing the badge URL wouldn't fix it. 

Since I'm using a free plan, Azure Pipelines only retains build run details for 30 days.

> I think you can make an empty commit to check/fix. Nobody will condemn for this.

This is one option! Another option is to set-up Azure Pipelines to automatically build/test the latest master branch nightly. I'll look into this... 

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers
