### ISSUE TITLE
Radar Plot: Normalizing all axis with zeros produces render error

### ISSUE THREAD

**Issue by petersesztak** [ScottPlot/ScottPlot#1139]
There is a strange visual behaviour of Radar Plot in case of zero (0) values only at certain axe:
all the other (with non zero valus) axes ok, but infinity at the axe with zero value(s) only:
see. picture: 'Wa' axe with zero values only. 
![ScottPlottRadarStangeVisualZeroValuesOnly](https://user-images.githubusercontent.com/5281591/124265193-ac930d00-db35-11eb-81f7-47a689be3f5d.JPG)

Is there any way / workaround to eliminate it ?

Thanks in advance,
Grat. for your nice lib !
Best Regards,
Peter

**Comment by petersesztak** [comment]
sorry: correctly: axe  => axis

**Comment by bclehmann** [comment]
Radar plots are normalized, and if you don't specify a maximum they will use the maximum in the given data (or the max in each axis if you enabled a certain option). If The maximum is zero then they will divide by zero, which does not give good results.

The solution is to use the `maxValues` parameter in the constructor. If `independentAxes` is true you need to specify one maximum for each axis, otherwise you specify only one. You could also disable `independentAxes`, so that it uses the max from all axes, which is non-zero.

**Comment by petersesztak** [comment]
Dear bclehmann,

First of all : thanks for your quick reply and kind explanation (divide by zero problem).

Background (use case / requirement): we need independentAxes  and normalized for each axes independently.

Actually: 
we precalculate max values and use it in constructor:

var radar = WpfScottPlot.Plot.AddRadar(values, independentAxes: true, maxValues: maxValues);

But -as datas generated dinamically- sometimes  happens: at certain axis: all values zeros ..

So, what do you think to avoid above mentioned problem?: 
with post processing: leave all zero values as is and put some arbitrary value to max  ( e.g. 1) value to problematic axis ?

best regards,
Péter

**Comment by bclehmann** [comment]
> with post processing: leave all zero values as is and put some arbitrary value to max ( e.g. 1) value to problematic axis ?

That sounds like the best option, if you're already setting the `maxValues` it shouldn't require much reworking. I think if the max on an axis is zero than the correct thing to do is map all points on that axis to zero, which is what your solution does.

**Comment by swharden** [comment]
Hi @petersesztak, I'm having a hard time recreating this issue. Do you or @bclehmann have suggestions for how I can best demonstrate the problem?

Placing a zero in `maxValues` seems to cause an error, but I'm not sure if it's the same error as in the original post.

```cs
var plt = new ScottPlot.Plot(400, 300);

double[,] values = {
    { 78,  83, 84, 76, 43 },
    { 100, 50, 70, 60, 90 }
};

double[] maxValues = { 100, 100, 0, 100, 100 }; // <-- CONTAINS A ZERO

plt.AddRadar(values, independentAxes: true, maxValues: maxValues);
```

![image](https://user-images.githubusercontent.com/4165489/128646009-3774e83f-b70b-4a58-b60a-e6d3668553c7.png)

**Comment by bclehmann** [comment]
I get this if I slightly change `values`:

![image](https://user-images.githubusercontent.com/8635304/128647134-ec530f9d-3cba-4607-bbc2-4e708d898fe2.png)


```cs
var plt = new ScottPlot.Plot(400, 300);

double[,] values = {
	{ 78,  83, 0, 76, 43 },
	{ 100, 50, 0, 60, 90 }
};

double[] maxValues = { 100, 100, 0, 100, 100 }; // <-- CONTAINS A ZERO

plt.AddRadar(values, independentAxes: true, maxValues: maxValues);
```

The original issue happened when everything on that axis was zero, thus the max on that axis is zero. I think you got different results because when the axes has non-zero members you get x/0 instead of 0/0. I suppose IEEE 754 (or C#'s implementation of it) treats undefined differently from indeterminate. I think x/0 is infinite, while 0/0 is NaN.

I don't know why those would be rendered differently from each other, but I guess they are.

**Comment by swharden** [comment]
I think it's fixed now... I added an if statement to detect if it's normalizing to zero and if so set that value to zero.

It's not technically "correct", but the original rendering was super not correct, so I think it's an improvement.

The alternative is to throw an exception, but that seemed a little harsh 🤔 

before | after
---|---
![image](https://user-images.githubusercontent.com/4165489/128796884-b4afaa1a-34ac-4b87-b817-6192f2560075.png)|![image](https://user-images.githubusercontent.com/4165489/128796892-16a43b94-2f3f-448b-b9a8-615d398cd626.png)

```cs
var plt = new ScottPlot.Plot(400, 300);

double[,] values = {
    { 78,  83, 0, 76, 43 },
    { 100, 50, 0, 60, 90 }
};

double[] maxValues = { 100, 100, 0, 100, 100 };

plt.AddRadar(values, independentAxes: true, maxValues: maxValues);
```
