### ISSUE TITLE
View Limit: Improve pan/zoom behavior (4.1 vs 4.0)

### ISSUE THREAD

**Issue by at2software** [ScottPlot/ScottPlot#1148]
The `AxisBounds()` method from v4.0.48 seems to have been replaced by `SetViewLimits()` in v4.1.x. However, upon dragging, the new method now automatically scales / zooms. If exaggerated, this might result in an invalid axis in below example.

Can the old `AxisBounds()` behaviour be mimicked in v4.1.x?

We have this code in v4.0.48
```cs
double[] data = new double[35];
Random rand = new Random(0);
for (int i = 1; i < data.Length; i++)
	data[i] = data[i - 1] + rand.NextDouble() - .5;

plot1.plt.PlotSignal(data);
plot1.plt.AxisBounds(minY: 0);
plot1.Render();
```

And adapted the last 3 lines to v4.1.16 like this:
```cs
plot1.Plot.AddSignal(data);
plot1.Plot.SetViewLimits(yMin: 0);
plot1.Render();
```

In v4.0.48, the plot can be dragged upwards, as long as there is allowed space available, but stops at y=0.
`SetViewLimits` from v4.1.16 behaves similarly, but when the y=0 limit is hit, the graph gets scaled vertically (and, if exaggerated, the y-axis seems to be broken or flipped / inverted).

Here's a screencap of the behaviours:

https://user-images.githubusercontent.com/8616861/124759337-d4b4ae80-df2f-11eb-9d2c-505bcb27fbc0.mp4

**Comment by at2software** [comment]
Please ignore the remark about the middle-click zoom region, this is unrelated to `AxisBounds` and `SetViewLimits` and not an issue, sorry.

**Comment by swharden** [comment]
Thanks for reporting this @at2software! Your description and videos were excellent

I was able to recreate the issue with a (failing) test, then correct it. This will be fixed in the next NuGet release 👍🚀

```cs
double[] values = DataGen.RandomWalk(new Random(0), 100);
formsPlot1.Plot.AddSignal(values);
formsPlot1.Plot.SetViewLimits(yMin: 0);
```

before | after
---|---
![before](https://user-images.githubusercontent.com/4165489/128948622-7ad14d58-482e-4a1a-99e4-449b69c9e2c7.gif)|![after](https://user-images.githubusercontent.com/4165489/128948632-c6f79484-aaf7-4106-a736-8b2f9ab41f01.gif)

**Comment by at2software** [comment]
Great, thanks a lot!
