### ISSUE TITLE
WpfPlot: Memory not released after window closed

### ISSUE THREAD

**Issue by fallingrust** [ScottPlot/ScottPlot#1175]
**ScottPlot Version:** 4.1.16

**Operating System:** windows 10

**Application Type:** WPF

**Question:** I got a child window with a wpfplot control and not render anything,when i show this window memory increase about 20M ,but it never release when window close,it means if i show and close ten times,the memory will increase 200m,Is there a right way to release memory?

**Comment by swharden** [comment]
Hi @fallingrust, thanks for reporting this! This issue is similar to #1117 in that it may involve a memory leak when WpfPlot controls are dynamically created and destroyed.

> but it never release when window close,it means if i show and close ten times,the memory will increase 200m

I'm not sure when the garbage collector typically steps-in and releases memory. If you open/close 100 times, does it really reach 2GB? It would be nice if there were an easy way to test this automatically. I'll look into this for a few minutes now but if it starts to get complex I may have to put this issue down and come back to it in several days...

**Comment by swharden** [comment]
Hi @fallingrust, after looking into it a little more I don't think there actually is a problem here. I think WPF windows are shutting down and freeing memory properly (it just doesn't happen instantly after closing the window).

I made a video to demonstrate the current behavior. I'm not an expert on memory management or garbage collection, and this issue is similar to #1117, so I welcome input from @bclehmann, @StendProg, or @Orace if they have any feedback regarding whether this is the expected behavior and if/how it could be improved.

https://user-images.githubusercontent.com/4165489/128171699-78fb5b02-f27e-4fd9-8076-6d973fa69030.mp4

**Comment by fallingrust** [comment]
Thanks for answer my question,i also try to open window with wpfplot for about 100 times.Finally, it stabilized at about 700M.But it not a good situation for some low performance machine.
