### ISSUE TITLE
Radar: Images as category labels

### ISSUE THREAD

**Issue by Rayffer** [ScottPlot/ScottPlot#1265]
## Features Suggestion

**Feature description:** 
I would like to be able to use images, like a wpf image, instead of a text label to symbolize categories, optionally, that image might be able to display a tooltip on mouse over just so that the user can make clearer the intent of the image/icon

**Code example:** If applicable, use this space to demonstrate how you wish the new feature could be used in code.

```cs
Tuple<Image, string> interactionsIcons = { new Tuple<Image, string>{ Item1 = "Reanimation.png", Item2 = "Reanimations" }, new Tuple<Image, string>{ Item1 = "Knockout.png", Item2 = "Knockouts", new Tuple<Image, string>{ Item1 = "kill.png", Item2 = "Kills" } }};

CreateRadarPlot("Interactions", interactionsIcons , groupStrings, values, true, interactionsPlot
```

**Comment by swharden** [comment]
Hi @Rayffer, this is an interesting idea! The mouse interaction seems pretty unlikely to get implemented, but whether or not images should be supported as a possible alternative to category labels may be worth considering.

### Present Behavior

Currently users can assign category labels as a string array:

```cs
var radar = plt.AddRadar(values, independentAxes: true);
radar.CategoryLabels = new string[] { 
    "Wins", "Poles", "Podiums", "Points Finishes", "DNFs", "Fastest Laps", "Points" 
};
```
![image](https://user-images.githubusercontent.com/4165489/133170182-83ad9a31-19b2-470f-9e8f-2bce1d3df20f.png)

### Suggested Behavior

Rather than your tuple system, I may suggest something simpler like this. Any position where the `Bitmap` is `null` the label would be drawn instead.

```cs
var radar = plt.AddRadar(values, independentAxes: true);
radar.CategoryImages = new Bitmap[] { bmp1, bmp2, bmp3 ... };
```

### Should this be implemented?

Needing to place images on radar plots seems like a pretty rare use case, so this should be taken into consideration when evaluating whether or not to pursue this. There are a lot of feature requests in the backlog #1028 😅 When I google image search "radar plot" I don't see any examples where people use images for category labels... so I'm inclined not to implement this in the library. 

You could create a custom `Plottable` based on [RadarPlot.cs](https://github.com/ScottPlot/ScottPlot/blob/master/src/ScottPlot/Plottable/RadarPlot.cs) that uses images instead of labels and use it in your application (without this feature having to be added to ScottPlot).

@bclehmann do you want to weigh-in on this one?

**Comment by bclehmann** [comment]
I can't currently see much of a usecase for images as labels in this situation, the main reason we support them for axis labels is to allow math notation which (probably) doesn't apply here. I would be happy to see a mockup of your usecase however.

As for the on-hover, allowing tooltips which show the value under the cursor have been discussed a few times and might be easier now that #696 is merged in. So having alt text which is displayed when the image is hovered is not too much of a stretch in my view.

**Comment by Rayffer** [comment]
@swharden Just for the sake of completeness, [here](https://thebusinessofesports.com/2021/07/07/mobalytics-launches-gaming-companion-update-for-league-of-legends/) you can find an example of radar plot with icons, which is more commonly used in games where icons with a known purpose or meaning can help understand the category they are representing.

I searched and as you said, it is not much used so it would be fine if it was not implemented given that I would be able to implement it myself, maybe I will make a fork and try to see what I can come up with.

It's fine with me either way, keep up the great job you are doing guys!

**Comment by bclehmann** [comment]
Looking at that example I wonder if you would benefit from a lot more customizability than just showing icons. ScottPlot mostly just caters towards scientific plotting, so such stylizations are probably out of scope.

**Comment by Rayffer** [comment]
What was it that catched your interest? I thought only icons for categories were the difference here.

**Comment by bclehmann** [comment]
- The filled region of the radar has a gradient
- There is a drop shadow at the edge of the radar's web
- The radar's web seems to alternate between two background colours

There may be more that I didn't notice. Some of these may be worth bringing into ScottPlot, but I don't think any of them are a high priority.

**Comment by Rayffer** [comment]
Oh, I only mentioned what I thought was relevant to the discussion from the point that icons can enhance, at a glance, what a radar chart tries to convey, if you're bound to face the same radar chart multiple times, but all those points might be interesting to have implemented sometime in the future.

**Comment by Rayffer** [comment]
I've developed a candidate for this. Hope it's up to your standards and the conventions followed. See the changes in the [following pr](https://github.com/ScottPlot/ScottPlot/pull/1275)
