### ISSUE TITLE
Heatmap: row and column labels

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1273]
This caught my eye tonight https://ilnumerics.net/examples.php?exid=9d21d77e7e30751fe3d86a8bda26d275

@bclehmann do you think heatmap labels like this may be useful? Maybe a simple project to add to a hacktoberfest wishlist?

_EDIT: A hidden complexity trap is that `AxisAuto()` would have to measure the size of those labels to make sure everything fits_

![image](https://user-images.githubusercontent.com/4165489/133871204-4d59f931-b0fd-43af-8f98-3e6811a894df.png)

**Comment by bclehmann** [comment]
I'm recalling in #420 (nice) I brought up categorical heatmaps. An example is this in matplotlib: 
![image](https://user-images.githubusercontent.com/8635304/133877589-c360efbf-d068-4d2e-9f43-0c07dd8511de.png)

These are commonly used for confusion matrices in AI such as this one for an image classifier: 
![image](https://user-images.githubusercontent.com/8635304/133877716-4f5ba879-f391-4432-86ae-8efde51328e2.png)

To me these seem similar, but I think there are some nuances. I think that categorical heatmaps often use only 10 or so colours instead of 255, but it might be worth supporting both.

The only real concrete idea I have is placing numbers over the grid cells. My apologies for idea dumping, I can't remember why I never implemented categorical heatmaps

**Comment by swharden** [comment]
> numbers over the grid cells

I very much like this idea! It could be a separate issue/PR even (if we were enumerating tasks for #1274)

> I think that categorical heatmaps often use only 10 or so colours instead of 255, but it might be worth supporting both.

Maybe we could lean on the palette system?

https://swharden.com/scottplot/cookbooks/4.1.18/#palette

This isn't being actively worked on at this moment so I'll close this issue but I'm tracking it on #1274 and #1028
