### ISSUE TITLE
Allow Radar Chart to specify a width for the Radar's border

### ISSUE THREAD

**Issue by Rayffer** [ScottPlot/ScottPlot#1277]
## Features Suggestion

**Feature description:** 
Give the option to specify a value for the thickness of the RadarChart border to allow for improved visibility when an arm has values while the neighbouring arms do not, which produces a polygon of the same width as the radarchart arm and difficults visibility on it.

**Code example:**

```cs

WpfPlot wpfPlot = new();
int borderThickness = 2;
RadarPlot radarPlot = wpfPlot.Plot.AddRadar(values);
radarPlot.BorderThickness = borderThickness;

wpfPlot.Render();
```

If it makes no sense, I believe it would to make the Thickness of the border at least 2 instead of the current default value, which is 1.

**Comment by Rayffer** [comment]
![image](https://user-images.githubusercontent.com/34773204/134175563-5680f2d0-a72f-4690-888d-1b6684af1ce2.png)

Just to give an example of how this would look.

**Comment by swharden** [comment]
I like the idea! It looks like the pen that outlines that polygon is defined here, and since it lacks a thickness argument its thickness is always 1 in the current system.

https://github.com/ScottPlot/ScottPlot/blob/e54af09a39137ce50f0e8552d5e55595a7b5fa7e/src/ScottPlot/Plottable/RadarPlot.cs#L242

`BorderThickness` is a good and literally accurate name. Elsewhere in the library this is called `LineWidth`. Maybe `OutlineThickness` could work too. I'm probably okay with any name here - it's easily discoverable with a predictive IDE.

Seems like a good hacktoberfest PR 😎  #1274

**Comment by Rayffer** [comment]
Hello, after checking the changes I think this does not solve this issue, @bclehmann added support for customizing the width of the chart lines, not the outline of the polygon for each entry in the radar chart.

I might have expressed incorrectly but my intent was to allow for polygon outline's line width to be customizable
