### ISSUE TITLE
Feature: click legend items to toggle visibility

### ISSUE THREAD

**Issue by Narvaris** [ScottPlot/ScottPlot#1326]
Hi 

I was wondering if it is possible to have checkboxes in the legend in order to toggle the visibility of the plots?

![image](https://user-images.githubusercontent.com/39590308/136007767-16703e6a-4266-45d8-ac3f-564651694cd2.png)

Thanks!

**Comment by bclehmann** [comment]
This is not possible right now, you would have to create your own logic to set visibility.

I like this idea, I think clicking on the entry rather than a checkbox would look better, but that's not a very good design from a discoverability or usability perspective. We could probably go with something like this:
![image](https://user-images.githubusercontent.com/8635304/136088807-6e938417-52c5-44b2-b375-71c0a0f0abf7.png)

We would have to prevent it from being shown in command-line applications, and it can be fiddly to write click detection for things like this, but it could be a useful value-add.

**Comment by Narvaris** [comment]
Mhm that would also work, the idea is to avoid doing external logic to turn plots off when they are easily listed in the legend :) for now i found a work around it by using my own right-click menu and giving the user the option to turn off plots from there

**Comment by swharden** [comment]
> for now I found a work around it by using my own right-click menu and giving the user the option to turn off plots from there

I like this solution!

I'll close this issue, but may consider adding this feature in the future. I think the way I'd approach is to edit the `Legend` module (below) to add a method like `GetPlottableUnderCursor(float xPixel, float yPixel)`

https://github.com/ScottPlot/ScottPlot/blob/604b08c3c5c3f776f061a80362410b78ead1f5a4/src/ScottPlot/Renderable/Legend.cs#L1-L213

**Comment by swharden** [comment]
Following-up, a highly similar feature was added in #1589 / #1573
