### ISSUE TITLE
Square-Root Scaled Coxcomb

### ISSUE THREAD

**Issue by bclehmann** [ScottPlot/ScottPlot#1450]
## Features Suggestion

**Feature description:** [This article](https://eagereyes.org/blog/2008/linear-vs-quadratic-change) talks about how scaling the area of regions rather than the radius or side length makes it easier for readers to estimate the relative differences between them. They even give an example with Coxcomb charts.

In practice, for Coxcomb charts this means plotting the square-root of the radius instead of the radius. This would probably need an extension to `StarAxis` as well

**Code example:** If applicable, use this space to demonstrate how you wish the new feature could be used in code.

```cs
var coxcomb = plt.AddCoxcomb(values);
coxcomb.LinearlyIncreaseArea = true; // I still don't know what a good name for this would be.
```

**Comment by swharden** [comment]
Thanks for this suggestion @bclehmann! I noted this under the plottable section of the current triage list #1028 and will probably loop back around and work through lots of the plottable features in one go some time in the future. 

Regarding the API, I kind of like the idea of using an `enum` since there may be different types of scaling, and each member could have some explanative XML docs describing what it is and how it's often used

For now I'll close this since it isn't being actively worked on 👍
