### ISSUE TITLE
Disable minor ticks depending on zoom

### ISSUE THREAD

**Issue by PhilippPaetzold** [ScottPlot/ScottPlot#1457]
I have a SignalConst plot with a sampleRate of 1 and I use MinimumTickSpacing = 1 on the X-Axis. For my application it would be useful, if I could disable minor ticks depending on the current zoom level. If I zoom in very closely to see my samples sequentially with an increment of one in between, values in between are not really meaningful nor helpful.

I saw that that I can disable the minor-grid by XAxis.MinorGrid(false). Is there a nice way to implement this dynamically depending on zoom level?

**Comment by swharden** [comment]
> I saw that that I can disable the minor-grid by XAxis.MinorGrid(false). Is there a nice way to implement this dynamically depending on zoom level?

Hi @PhilippPaetzold,

There isn't a built-in way to achieve this in the existing code, but it should be pretty easy for a user to implement in on their end. Assuming they're using one of the user controls they could add something to the `AxesChanged` event handler that's called every time the axes change (panning/zooming). An example of this is on FAQ page https://scottplot.net/faq/shared-axes

That event could call a method which determines how zoomed-in the plot is (calling `Plot.GetAxisLimits()`) and use logic to determine whether to show/hide the minor ticks using something like `formsPlot1.Plot.XAxis.Ticks(false);`

Hope it helps! Sorry about the delay... here's my copy/paste blurb about that: Sorry for the delay! It took me an unexpectedly long time to get to this because I moved houses and it was a lot more disruptive than I predicted, then right after I got sick for several weeks. I'm doing better now and am happy to be picking this up again. Thanks for your patience along the way!

**Comment by swharden** [comment]
Oops, `Plot.XAxis.Ticks(false)` will disable MAJOR ticks but your goal is to manipulate visibility of minor ticks.

It may be a bit cumbersome, but you could pull the list of ticks using `formsPlot1.Plot.XAxis.GetTicks()` and set visibility individually depending on if ticks are minor or not. It's not elegant, but it would work! The rest of the comment above should work too. 

Hope it helps!
Scott

**Comment by swharden** [comment]
Actually, I see `Plot.XAxis.Ticks(major: true, minor: false)` already allows independent control of major vs. minor tick visibility, so this would be the preferred way to achieve the behavior you're looking for 👍

**Comment by PhilippPaetzold** [comment]
Thank you for your answer and for your hard work. ScottPlot is a great library especially when dealing with lots of points.

**Comment by aespitia** [comment]
> Actually, I see `Plot.XAxis.Ticks(major: true, minor: false)` already allows independent control of major vs. minor tick visibility, so this would be the preferred way to achieve the behavior you're looking for 👍

this is exactly what I was looking for, this is definitely one of the best OSS libraries i've ever used.  I might look to see if there's any "good first tasks" for v5 that I could help contribute to.

**Comment by swharden** [comment]
> this is exactly what I was looking for

Awesome!

> this is definitely one of the best OSS libraries i've ever used

Great to hear! 🚀 🚀 🚀 

> I might look to see if there's any "good first tasks" for v5 that I could help contribute to.

Pro tip, look for _closed_ "good first issues" because some may have been closed because they're not high priority, but are tagged "re-open me" and are still up for grabs!

https://github.com/ScottPlot/ScottPlot/issues?q=label%3A%22Good+First+Issue%22

Also https://github.com/ScottPlot/ScottPlot/blob/main/CONTRIBUTING.md may be useful 👍
