### ISSUE TITLE
Plot.RemoveAxis() is needed

### ISSUE THREAD

**Issue by gobikulandaisamy** [ScottPlot/ScottPlot#1458]
**ScottPlot Version:** 4.1.27

**Operating System:** WINDOWS10

**Application Type:** (console, WinForms, WPF, or Avalonia)

**Question:** 
Add Additional X-Axis and Y-Axis by using Plot.AddAxis() method.
**But How to Remove the Additional X-Axis and Additional Y-Axis already added?**

**Comment by swharden** [comment]
Thanks for the question @gobikulandaisamy! It does not look like this is possible because there is no public `Plot.RemoveAxis()`. I'll add this feature shortly 👍 

Note: The `RemoveAxis()` method should be added after the `AddAxis()` method here:

https://github.com/ScottPlot/ScottPlot/blob/604b08c3c5c3f776f061a80362410b78ead1f5a4/src/ScottPlot/Plot/Plot.Axis.cs#L247-L278

**Comment by gobikulandaisamy** [comment]
Thankyou @swharden

**Comment by swharden** [comment]
The new `RemoveAxis()` will be available in the next release! 👍 🚀 

```cs
var plt = new ScottPlot.Plot(600, 400);
plt.AddSignal(ScottPlot.DataGen.Sin(51));
plt.AddSignal(ScottPlot.DataGen.Cos(51));

var extraAxis = plt.AddAxis(ScottPlot.Renderable.Edge.Left, axisIndex: 2);
plt.SaveFig("a.png");

plt.RemoveAxis(extraAxis);
plt.SaveFig("b.png");
```

additional axis | removed
---|---
![image](https://user-images.githubusercontent.com/4165489/147839763-64833f69-7b60-4506-aaa8-d5db4499bfb6.png)|![image](https://user-images.githubusercontent.com/4165489/147839765-b393e8d5-4591-4530-85c5-ac7104cb7d03.png)
