### ISSUE TITLE
ScatterPlotList: re-evaluate API, improve documentation, and add generic support

### ISSUE THREAD

**Issue by tyrbentsen** [ScottPlot/ScottPlot#1463]
## Features Suggestion

**Feature description:** 
Currently the `AddSignal()` method only accepts an `ys` argument of type `double[]`. The API would be much more flexible if the method would accept a generic collection like an `IEnumerable<double>`. Or if ScottPlot internally needs to know the number of items in the collection then use `ICollection<double>` or if it needs to index into the collection then use an `IList<double>`.

An example case that would really benefit from this: plotting growing data. Now you need to manage the resizing of growing array by yourself. It would be much more practical if an `List<double>` could be used.

Note: Using an `IEnumerable`, `ICollection` or `IList` in most cases does not have a performance penalty with respect to a plain array. If a specific memory layout is assumed in the ScottPlot implementation, `Span<T>` may provide the necessary constraints.

**Code example:** 

Growing data with array:
```cs
// Original array.
var dataArray = new double[] { 1, 4, 9, 16, 25 };
var signalPlot = avaPlot1.Plot.AddSignal(dataArray);
avaPlot1.Plot.Render();

// Resize
Array.Resize(ref dataArray, dataArray.Length * 2);
avaPlot1.Plot.Remove(signalPlot);
var signalPlot2 = avaPlot1.Plot.AddSignal(dataArray);

// Add new element and Render
dataArray[5] = 36;
avaPlot1.Plot.Render();
```

Growing data with List:
```cs
// Original List.
var dataList = new List<double> { 1, 4, 9, 16, 25 };
var signalPlot = avaPlot1.Plot.AddSignal(dataList);
avaPlot1.Plot.Render();

// Add new element (List is resized automatically) and Render.
dataList.Add(36);
avaPlot1.Plot.Render();
```

**Comment by Niravk1997** [comment]
I think this has been discussed before. A double[] array is faster than a List when rendering the plot. 

Here is what I do:
 I create a very large size array.

`int Count = 0;`
`int Max_Allowed = 1_000_000;`
`double[] Data = new double[Max_Allowed];`

Then, I will fill the data like this
`Data[Count] = Measurement;`
`Signal_Plot.MaxRenderIndex = Count; `
`Count += 1;`

Then I will call the render() method.

At some point I will also check if the Data array is full like this
`if (Count >= Max_Allowed)`
`{`   
`     Max_Allowed = Max_Allowed + 1_000_000;`
`    Array.Resize(ref Data, Max_Allowed);`
`    Signal_Plot.Ys = Data;`
`}`

More info here: https://scottplot.net/faq/live-data/

**Comment by tyrbentsen** [comment]
Hi, thanks for the reply. I read the info at https://scottplot.net/faq/live-data/. While for this short example it does not seem to be a big deal, for the real application I'm trying to use it the View layer is separated from the Data layer. In this case I had to implement a custom class that manages the resizing of the array in the Data layer. Basically what I created is a poor-man's List<T> that exposes its internal array. Then I also had to signal to the View layer when the data array has been resized, which was a lot of code that could be avoided altogether.

I still believe that using an ICollection<T> would not impact the performance. I had a look at the source code of `SignalPlotBase<T>` and the only way the `T[] _Ys` array is used is with `_Ys.Length`, indexing into the array with `_Ys[i]` and at some point a `new ArraySegment<T>(_Ys, index1, index2 - index1)` was used, but that could be replaced with a `.Skip().Take()` expression without any performance hit in that context.

Thanks for considering this change. Great work on ScottPlot, I love it a lot so far!

**Comment by swharden** [comment]
Hi @tyrbentsen, thanks for raising this issue! 

This topic has indeed been raised before, but the fact it keeps coming up means it's worth continuing to consider it.

The justification for intentionally restricting data to `double[]` format is because we designed ScottPlot to performantly display high density data with tens of millions of data points. We assume the user already has these data in fixed-length arrays (not `ICollection`), so requiring a different format would require copying (especially if LINQ is involved) and would impair performance and memory use. It's this ***copying*** step we're referring to when we suggest this strategy is not performant.

Some excellent discussion was had recently about the use of the relatively new language features `Memory<T>` and `Span<T>` to prevent the need for these copies #766 but I haven't pulled the trigger on that because it would be pretty disruptive to the existing API.

For small numbers of points an easier method for growing data would indeed be useful. This could be done as easily as using a `List<double>` instead of `double[]`, and allowing the user to add/remove points. I started work on `Plot.AddScatterList()` but I don't think it's as flushed-out as it could be and it's not currently documented on https://scottplot.net/faq/live-data

I'll adapt this issue to track progress toward improving documentation of the `ScatterList` because it seems like a simple start that could help a lot of peoples use cases. It would also be nice to adapt it to support `<T>` at the same time.

It's also worth noting that there are some complexities worth considering about manipulating lists in multi-threaded environments where renders may occur simultaneous with threads that manipulate the data (e.g., WPF apps). This may be improved using [Thread-Safe Collections](https://docs.microsoft.com/en-us/dotnet/standard/collections/thread-safe/)

PPS: I'm copy/pasting this a lot lately - _Sorry for the delay! It took me an unexpectedly long time to get to this because I moved houses and it was a lot more disruptive than I predicted, then right after I got sick for several weeks. I'm doing better now and am happy to be picking this up again. Thanks for your patience along the way!_
