### ISSUE TITLE
ErrorBar: New plot type for advanced error bar features

### ISSUE THREAD

**Issue by bclehmann** [ScottPlot/ScottPlot#1466]
## Features Suggestion

**Feature description:** Allow errorbars which are not necessarily centered on the marker. This could be done by reviving `plt.PlotErrorBars` from 4.0.

**Code example:**

```cs
var err1 = plt.PlotErrorBars(dataX, dataY1, errorXPositive, errorXNegative, errorYPositive, errorYNegative);
```

**More Context:**

The 4.0 cookbook demonstrating this: https://scottplot.net/cookbook/4.0/#plottypes-errorbar-scatter-plot-with-asymmetric-errorbars

A recent StackOverflow question about this: https://stackoverflow.com/questions/70200872/scottplot-errorbar-with-different-top-and-bottom-values/70230626#70230626

**Comment by bclehmann** [comment]
Hey, I know I kinda abandoned this for a month, but I was wondering if you had a preference for either of these two APIs:

```cs
plt.AddErrorBars(dataX, dataY, errorX, errorY);
```

```cs
plt.AddErrorBars(xs1, xs2, ys1, ys2);
```

The first one is probably more convenient for most people, as it's most likely things they already have, their data and their error. But the second one is more flexible. I'm struggling to think of a situation where someone would prefer the second over the first, but I can't shake the feeling that there is one.

**Comment by swharden** [comment]
I'm staring to avoid using the term `data` in variable names because, technically, all variables contain data 🙃 

If I were approaching this from scratch I'd probably make arguments/overloads like this:

```cs
plt.AddErrorBars(xs, ys, xErr, yErr);
plt.AddErrorBars(xs, ys, xErrNeg, xErrPos, yErrNeg, yErrPos);
```

Matplotlib's `pyplot.errorbar()` was interesting to reference here https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.errorbar.html ... I don't think it's really idiomatic to do this with C#, but in the Python world it looks like `xErr` and `yErr` are 1D arrays if errorbars are symmetrical and 2D (with two rows) if separate positive/negative values are specified.

> I'm struggling to think of a situation where someone would prefer the second over the first, but I can't shake the feeling that there is one.

I agree! I think defining the center points separate from error magnitudes makes sense here.
