### ISSUE TITLE
Heatmap: Incorrect colors when using custom scale

### ISSUE THREAD

**Issue by ZPYin** [ScottPlot/ScottPlot#1485]
## Bug Report

**Issue:**

The custom scale for Heatmap was not right. It can be noticed from the example in the Cookbook 4.1 (winform). Below is the screenshot of the example showing in the cookbook

![image](https://user-images.githubusercontent.com/7610928/147114530-69e06dc0-562a-4f24-acdc-133a982cd302.png)

The max/min of the intensities are 200/-200. However, based on the colors after setting the scale, it shows the min value was somewhere close 100.

### System Details
* **ScottPlot Version:** 4.1.27
* **Operating System:** ( Windows 10)
* **Application Type:** (WinForms)
* **.NET Version:** (.NET 5.0?)

**Comment by swharden** [comment]
Thanks for reporting this @ZPYin! 

@bclehmann do you have any thoughts here? If you're not available to take a look I'll check it out but it may take me a few days to get to this one... 

I'm guessing the bug is in this code block:
https://github.com/ScottPlot/ScottPlot/blob/604b08c3c5c3f776f061a80362410b78ead1f5a4/src/ScottPlot/Plottable/Heatmap.cs#L174-L219

**Comment by bclehmann** [comment]
I think what's happening is that in the plottable intensities below zero are clipped, and all mapped to the middle of the colourmap. But in the axis the range is stretched so that zero is mapped to the minimum of the colourmap. Neither behaviour is necessarily wrong (in my opinion), but they need to be consistent with eachother.

I think we had a discussion before on which behaviour made the most sense, but I cannot remember what we decided on.

**Comment by mYcheng-95** [comment]
I also encountered this problem, I think when I need custom scale, I should not need the code block：
```
 min = ((scaleMin.HasValue && scaleMin.Value < min) ? new double?(scaleMin.Value) : min);
 max = ((scaleMax.HasValue && scaleMax.Value > max) ? new double?(scaleMax.Value) : max);
```
When I define the maximum and minimum values,Replace with：
```
min = scaleMin.Value;
max = scaleMax.Value;
```

**Comment by swharden** [comment]
## Python

Here's a better matplotlib example demonstrating the intended effect

```py
from math import sin, cos
import numpy as np
import matplotlib.pyplot as plt

intensities = np.zeros((100, 100))
for x in range(100):
    for y in range(100):
        intensities[x, y] = (sin(x * .2) + cos(y * .2)) * 100

plt.imshow(intensities, vmin=0, vmax=200, interpolation='bicubic')
plt.colorbar()
plt.show()
```

![image](https://user-images.githubusercontent.com/4165489/152448455-101e2956-b00a-4021-854a-9c8b1b46aa79.png)

## ScottPlot (Issue)

```cs
double[,] intensities = new double[100, 100];
for (int i = 0; i < 100; i++)
    for (int j = 0; j < 100; j++)
        intensities[i, j] = (Math.Sin(i * .2) + Math.Cos(j * .2)) * 100;

var plt = new ScottPlot.Plot(500, 400);

var cmap = ScottPlot.Drawing.Colormap.Viridis;

var hmap = plt.AddHeatmap(intensities, cmap, lockScales: false);
hmap.Interpolation = InterpolationMode.Bicubic;
hmap.Update(intensities, cmap, min: 0, max: 200); // intentionally cut-off data

var cbar = plt.AddColorbar(hmap);
cbar.MinValue = 0;
double[] tickPositions = ScottPlot.DataGen.Range(-150, 150, 50, true);
string[] tickLabels = tickPositions.Select(x => x.ToString()).ToArray();
cbar.SetTicks(tickPositions, tickLabels, -200, 200);

plt.Margins(0, 0);
TestTools.SaveFig(plt);
```

![image](https://user-images.githubusercontent.com/4165489/152448525-dcd878f6-8150-4f7a-ad4e-4413f165c427.png)

**Comment by swharden** [comment]
Figured it out! The hard-coded `0` was the problem

https://github.com/ScottPlot/ScottPlot/blob/c663da9e059ed07199fb2ad770a23592b9aaf9d7/src/ScottPlot/Plottable/Heatmap.cs#L214

Matplotlib | ScottPlot
---|---
![image](https://user-images.githubusercontent.com/4165489/152455054-5f20af68-46ad-4a0e-b0ea-41ca9db22a28.png)|![image](https://user-images.githubusercontent.com/4165489/152455063-305c46d1-2448-4bdc-9bd2-cb49dbcc7299.png)
