### ISSUE TITLE
BarPlot: add support for a custom value label formatter

### ISSUE THREAD

**Issue by jankri** [ScottPlot/ScottPlot#1542]
## Features Suggestion

**Feature description:** It would be nice to be able to format values shown with BarPlot.ShowValuesAboveBars

**Code example:** something like this:

```cs
var bar = plt.AddBar(values);
bar.ShowValuesAboveBars = true;
bar.ValueFormat = "F3";
```

**Comment by swharden** [comment]
Thanks for the suggestion @jankri!

I think the way to go is to support passing in a function as a custom label formatter like these other plot types:
* https://scottplot.net/cookbook/4.1/category/plottable-axis-line-and-span/#position-labels
* https://scottplot.net/cookbook/4.1/category/plottable-crosshair/#custom-label-format

... to let the user do something like this:

```cs
Func<double, string> myFormatter = x => $"custom {x:F3}";

var bar = plt.AddBar(values);
vline.ValueFormatter = myFormatter;
```

This could be achieved by replacing the `ToString()` calls in these two places:

https://github.com/ScottPlot/ScottPlot/blob/13200aab858d30b6e4a4a0351813a82649ff15e0/src/ScottPlot/Plottable/BarPlot.cs#L86

https://github.com/ScottPlot/ScottPlot/blob/13200aab858d30b6e4a4a0351813a82649ff15e0/src/ScottPlot/Plottable/BarPlot.cs#L125

You can use the `AxisLine` plot type as a reference:

https://github.com/ScottPlot/ScottPlot/blob/13200aab858d30b6e4a4a0351813a82649ff15e0/src/ScottPlot/Plottable/AxisLine.cs#L38

https://github.com/ScottPlot/ScottPlot/blob/13200aab858d30b6e4a4a0351813a82649ff15e0/src/ScottPlot/Plottable/AxisLine.cs#L186

If you want to give this a try and create a pull request, I'd be happy to look it over! Otherwise I'll leave this issue open for a bit and get to it eventually.

**Comment by swharden** [comment]
This feature will be in the next release:

```cs
Func<double, string> customFormatter = y => $"Y={y:N2}";

double[] values = { 27.3, 23.1, 21.2, 16.1, 6.4, 19.2, 18.7, 17.3, 20.3, 13.1 };
var bar = plt.AddBar(values);
bar.ShowValuesAboveBars = true;
bar.ValueFormatter = customFormatter;
```

![image](https://user-images.githubusercontent.com/4165489/149867968-42ca4e62-47aa-42d3-bb7c-7aa65d5abec9.png)
