### ISSUE TITLE
Render time increasing dramatically

### ISSUE THREAD

**Issue by xenedia** [ScottPlot/ScottPlot#1546]
## Bug Report

**Issue:** I have a stock data list that increases every second. I call plot render method with candlesticks when data is adding on every 5 second. on beginning render time was 8, 10 ms and very good but render time increasing as time goes by. finally it reachs 400 500 ms after a few minutes later. when I call clear method, render time backing to normal 8 10 ms.

**Reproducing:** (What do others have to do to reproduce the bug?)
try to add candlestick with live data

```cs
// a code sample may improve communication
timer1_tick(){
plot1.Plot.AddCandleSticks(data.toArray());
plot1.Render();
}

### System Details
* **ScottPlot Version:** 4.1.27
* **Operating System:** Windows 10
* **Application Type:** WinForms
* **.NET Version:**  .NET 5.0

**Comment by xenedia** [comment]
Data is OHLC list.
private List<OHLC> data;

**Comment by swharden** [comment]
Hi @xenedia, great question!

Every time you call `AddCandleSticks();` it is placing an entirely new collection of candlesticks on the plot (not just adding the _newest_ candlestick). After a few minutes you probably have tens of thousands of candles instead of just the intended hundred or so. The solution is to only call `AddCandleSticks()` _once_, save the object it returns, and call that object's `Add()` method:

```cs
public partial class Form1 : Form
{
    Random Rand = new(0);
    ScottPlot.Plottable.FinancePlot MyCandlePlot;
    List<ScottPlot.OHLC> GrowingOHLCs = new();

    public Form1()
    {
        InitializeComponent();

        for (int i = 0; i < 10; i++)
            MakeNewOhlc();

        ScottPlot.OHLC[] startingOhlcs = GrowingOHLCs.ToArray();
        MyCandlePlot = formsPlot1.Plot.AddCandlesticks(startingOhlcs);
        formsPlot1.Refresh();
    }

    private void MakeNewOhlc()
    {
        double open = Rand.NextDouble() * 50 + 100;
        double close = open + (Rand.NextDouble() * 50) - 25;
        double low = Math.Min(open, close) - Rand.NextDouble() * 20;
        double high = Math.Max(open, close) + Rand.NextDouble() * 20;
        ScottPlot.OHLC ohlc = new ScottPlot.OHLC(open, high, low, close, GrowingOHLCs.Count, 1);
        GrowingOHLCs.Add(ohlc);
    }

    private void AddNewestOhlcToPlot()
    {
        MyCandlePlot.Add(GrowingOHLCs.Last());
    }

    private void timer1_Tick(object sender, EventArgs e)
    {
        MakeNewOhlc();
        AddNewestOhlcToPlot();
        formsPlot1.Plot.AxisAuto();
        formsPlot1.Refresh();
    }
}
```

![screenshot-stock gif](https://user-images.githubusercontent.com/4165489/149155121-054899f1-2668-4c87-8f7b-b34849d7d0e2.gif)
