### ISSUE TITLE
New plot type: MultipleLineSeries

### ISSUE THREAD

**Issue by l5624** [ScottPlot/ScottPlot#1579]
![image](https://user-images.githubusercontent.com/44857786/150169467-674c7122-f91e-40d5-8d37-20c27bd83e7e.png)
Can the value on mouseover be the same as in the picture

**Comment by BambOoxX** [comment]
At the moment, I'm pretty sure it's not feasible without implementing a specific plottable. @swharden will surly have a more extensive vision on this.

**Comment by swharden** [comment]
Hi @l5624, great question! Thanks for the screenshot too - it really makes it clear what you're asking.

## MultipleLineSeries: New Plot Type? 

@BambOoxX is correct that this isn't currently implemented, but it **you can make your own `MultipleLineSeries` plot type that inherits `IPlottable` and `Add()` it to the plot.** If you do this you can achieve this behavior with the existing library available on NuGet.

If someone creates this class and it gets the job done, I encourage whoever made it to post its code here (or open a pull request) so this useful plot type can be included with a future version of ScottPlot. I'll leave this issue open for a few days in case someone in the community wants to jump-in and give this a try, and if not I'll close this issue but leave this plot type on the triage list (#1028) in the hope that it gets implemented eventually.

## Implementation Suggestions

This plot type has a single set of `Xs` and multiple `Ys` which could be stored in different ways:

```cs
double[] Xs
double[,] Ys
```

```cs
List<double> Xs
List<List<double>> Ys
```

Information about each series would probably be stored in arrays or lists too:

```
List<Color> colors
List<string> labels
```

Where to place the vertical line (and legend) should probably be logic in the plottable itself. If you implement `IDraggable` you get `IsUnderMouse` which you could use to update the position of the line and legend.

In response to this question I may split that interface because the `DragTo` method doesn't need to be there for this plot type, but the overall idea of how to implement this is outlined here.

Hope it helps!
Scott

**Comment by BambOoxX** [comment]
@swharden I think I did not understand the request in the same manner. 
My feeling is this feature is largely interactive, and should result in some sort of draggable vertical line that should reveal information about all the plottable it crosses at a specific X location.
What do you think ?

**Comment by swharden** [comment]
> I think I did not understand the request in the same manner

It seems the screenshot is a start but doesn't indicate behavior. Your impression was that the vertical line would be draggable, and mine was that it would follow the position of the mouse and automatically snap to the nearest X position

I found a JavaScript version of a similar type of plot that follows the mouse
https://www.chartjs.org/docs/3.3.1/samples/area/line-stacked.html

I guess the cool thing about ScottPlot is that we could make it behave either way!

**Comment by swharden** [comment]
Overall this is a good idea and the text above should be sufficient to get anyone started toward implementing it by creating a custom plot type.

I'm going to close this issue for now and try to focus more of my time/effort into #1036, but if any progress is made toward this implementation post the code here and others can use it too 👍

**Comment by BambOoxX** [comment]
@swharden Also, it should be noted that this kind of plot should only be used with monotonously increasing X values, such as `SignalPlots`. Otherwise it won't make much sense...
