### ISSUE TITLE
LabeledMarker: new (draggable) plot type

### ISSUE THREAD

**Issue by Niravk1997** [ScottPlot/ScottPlot#1599]
## Features Suggestion

**Feature description:** Allow users to drag the text around

**Example:**
I copied the code from the DraggableMarkerPlot.cs to Text.cs. I can move the text around but drag cursor only appears on the text's alignment point. Detecting the text's alignment point is difficult if the font size is large.

![Text_Drag_Behaviour](https://user-images.githubusercontent.com/52579388/150721556-891707e4-c47e-4b6c-90fc-7247de4399e8.gif)

**Comment by swharden** [comment]
I like this idea, thanks for suggesting it!

I also like the idea of adding a `MarkerShape` and `MarkerSize` (which defaults to zero) to [Text.cs](https://github.com/ScottPlot/ScottPlot/blob/master/src/ScottPlot/Plottable/Text.cs) so the label and the marker could move together. If this is done maybe the `Text` type and the `Marker` type could both inherit a `LabeledMarker` base class (a new plot type) that has all this functionality in it, and the only difference between the two child classes is that the text or marker is hidden by default.

@Niravk1997 are you interested in making this modification and submitting it as a pull request? If not perhaps @BambOoxX may want to (it's similar to work they've been doing recently). Otherwise I'll leave this issue open and get to implementing this myself some time over the next week or two.

> Detecting the text's alignment point is difficult if the font size is large

This is a very difficult problem to achieve! I'm happy to take a shortcut where we assume the text is not rotated and keep the math simple. Perhaps we could add logic like "if rotation is enabled treat the draggable area as a circle at the label's center with a diameter equal to the longest edge of the label"

**Comment by swharden** [comment]
> If this is done maybe the Text type and the Marker type could both inherit a LabeledMarker base class

Dang, this is more complicated than I thought 😝

It's close to possible, but the existing APIs are slightly different so I can't do it without breaking things

I'll go for a bit of duplication here and just make a new plot type `LabeledMarker`

**Comment by BambOoxX** [comment]
@swharden I tried to implement the draggable `Text` including the bounding box to the `isUnderMouse` test, but something seems broken in `RectangleF.Contains` would you have an idea about this ? See #1616

**Comment by swharden** [comment]
Implemented in #1616
