### ISSUE TITLE
Change formatting of individual bar graph labels

### ISSUE THREAD

**Issue by Terebi42** [ScottPlot/ScottPlot#1638]
Is it possible to apply formatting (bold/italics/color) to individual bar graph labels, so that they stand out more, relative to other bar graph labels?

**Comment by swharden** [comment]
After enabling values like this https://scottplot.net/cookbook/4.1/category/plottable-bar-graph/#values-above-bars

Try configuring the bar's `Font` object, something like

```cs
var bar = plt.AddBar(values);
bar.Font.Bold = true;
```

**Comment by Terebi42** [comment]
@swharden I was wanting a label under the bar to be bolded, the label on the axis.

**Comment by Terebi42** [comment]
@swharden hrm, not quite yet, though we are getting close. 

In this example, I would like say the x axis ticks 10 and 20 to be bold, but 30 40 and 50 to not be bold.  (although my actual use case is a bar graph, not a scatter)

**Comment by swharden** [comment]
Thanks for clarifying again! Unfortunately it is not possible to customize the tick labels individually at this time.

However, it is possible to achieve this type of functionality by creating a custom plot type. A similar task was recently achieved in #1635 where the user wished to display images instead of text labels below each bar plot. I hope the discussion and code there can help you implement this if you really want to achieve this effect.

Good luck!
Scott

**Comment by Terebi42** [comment]
This is perhaps a bit more than I want to implement for somewhat low return, but thanks for the answer!
