### ISSUE TITLE
Text renders as squares and rectangles on Linux

### ISSUE THREAD

**Issue by barnabaspal** [ScottPlot/ScottPlot#1729]
Issue: The labels and legend are not rendered correctly on Linux:
![image](https://user-images.githubusercontent.com/97017869/158205056-56eb1b3a-4a17-495c-be63-ebf662b0cce2.png)
It looks good on Windows 10:
![image](https://user-images.githubusercontent.com/97017869/158206253-5c74a72d-b38a-49ac-94ef-37488046d2c9.png)

I think it is a same issue as #1220, but adding the System.Drawing.Common reference (version 4.6.1) does not solve the issue.

I'm setting the labels this way:
chart1.Plot.XAxis.Label("Time (ms)");
chart1.Plot.YAxis.Label("mV");

### System Details
ScottPlot Version:** 4.1.35
Operating System: Debian 11
Application Type: Avalonia
NET Version: net 6.0

**Comment by Xerxes004** [comment]
Does this happen with all fonts?

**Comment by barnabaspal** [comment]
I'm using the default fonts, how can I set the font for the axis marks and labels/legends?

**Comment by Xerxes004** [comment]
This [section of the ScottPlot 4.1 cookbook](https://scottplot.net/cookbook/4.1/category/plottable-text/#custom-fonts) has some very good examples on how to get/set the font for titles and labels, I would give that a peek.

By default, it looks like the `Font` class is initialized with one of the system's "default" sans-serif fonts.

Peering into the `InstalledFont` helper class, I see this:

```C#
public static string Sans() =>
    ValidFontName(new string[] { "Segoe UI", "DejaVu Sans", "Helvetica" });
```

If your machine doesn't have one of these installed, it may not load properly unless a new font is chosen. Keep in mind that I'm just making an educated guess here; there's a high probability that your bug is something else and my knowledge of the ScottPlot codebase is lacking.

I can try to reproduce this issue later when I have access to my Linux machine.

**Comment by boematic** [comment]
![Capture](https://user-images.githubusercontent.com/100868008/158469150-c123197a-cd56-44ba-a6a7-10c6fc87a0cb.JPG)
Just ran into the same issue on Ubuntu 20.04 LTS.  I have a timer that puts in new random data point on each tick.  As the plot progresses some of the tick labels show up but then disappear on the next update.  See attached.  I have seen it with 0-9 displayed correctly.  Works great on Windows but not Linux.  I have not tried other fonts yet.  Using the Avalonia Nuget.

**Comment by Xerxes004** [comment]
@boematic @barnabaspal do you both have `gdiplus` installed? I noticed it was mentioned on the [Avalonia quick start page](https://scottplot.net/quickstart/avalonia/).

**Comment by barnabaspal** [comment]
Yes, the libgdiplus  is installed (it is not working without it).
I have created  a small test application, it writes a text to the chart with all installed fonts. It is working on Windows 10, but only rectagles are displayed on Linux:
![image](https://user-images.githubusercontent.com/97017869/158547609-e1994e77-e8ff-4403-8b0f-05e07a600ece.png)

The test project is attached:
[scottplot1.zip](https://github.com/ScottPlot/ScottPlot/files/8260168/scottplot1.zip)

**Comment by boematic** [comment]
I've tried several different fonts and font sizes with the same result.  I think it's a bug.

**Comment by bclehmann** [comment]
Explicitly installing System.Drawing.Common by adding this to your csproj should fix this:
```xml
<PackageReference Include="System.Drawing.Common" Version="5.0.2" />
```

**Comment by boematic** [comment]
Yes, that fixed the problem.  Thanks!
