### ISSUE TITLE
Documentation: Visual Basic Quickstart

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1770]
Is it possible to use ScottPlot in a VP application?

If so, it would be fantastic if someone could share a working code example and I can add it to the quickstart section of scottplot.net

FYI, webpage source code is https://github.com/ScottPlot/ScottPlot.NET/tree/main/content/quickstart

**Comment by MareMare** [comment]
I tried to add a sandbox for Visual Basic [hear](https://github.com/MareMare/ScottPlot/tree/1770-vb-sandbox/src/ScottPlot4/ScottPlot.Sandbox.VB).
I have it in a separate folder so as not to mix up the namespaces.

Unfortunately, I could not add the Eto sandbox because I have no knowledge about Eto.

If this is OK, I will create a PR.

**Comment by swharden** [comment]
Awesome, thanks for sharing @MareMare! I knew there had to be a VB expert out there somewhere 🙃

I used your source code to create:
* https://scottplot.net/quickstart/vb/
* https://github.com/scottplot/scottplot.net/blob/main/content/quickstart/vb/index.md

This is probably enough to get people started, and a VB sandbox app isn't required.

If you want to create a PR to edit that webpage though, it may be helpful to add a picture of the console application output and/or a screenshot of the Form. Either way this is in a great spot now so I'll close this issue.

Thanks again for your input! 🚀

**Comment by MareMare** [comment]
Hi, @swharden 
I am glad I could be of help.

> I knew there had to be a VB expert out there somewhere 🙃

I've used it a little, but I'm no expert :smile:
