### ISSUE TITLE
Allow MVVM implementation via own usercontrols

### ISSUE THREAD

**Issue by ChrisCC6** [ScottPlot/ScottPlot#1781]
## Feature Suggestion

**Feature description:** IPlottable to implement the INotifyPropertyChanged interface

**Code example:** If applicable, use this space to demonstrate how you wish the new feature could be used in code.

```cs

    /// IPlottable interface implementing INotifyPropertyChanged
    public interface IPlottable : INotifyPropertyChanged
    {
        bool IsVisible { get; set; }
        void Render(PlotDimensions dims, System.Drawing.Bitmap bmp, bool lowQuality = false);

        int XAxisIndex { get; set; }
        int YAxisIndex { get; set; }

        /// <summary>
        /// Returns items to show in the legend. Most plottables return a single item. in this array will appear in the legend.
        /// Plottables which never appear in the legend can return null.
        /// </summary>
        LegendItem[] GetLegendItems();

        /// <summary>
        /// Return min and max of the horizontal and vertical data contained in this plottable.
        /// Double.NaN is used for axes not containing data.
        /// </summary>
        /// <returns></returns>
        AxisLimits GetAxisLimits();

        /// <summary>
        /// Throw InvalidOperationException if ciritical variables are null or have incorrect sizes. 
        /// Deep validation is slower but also checks every value for NaN and Infinity.
        /// </summary>
        void ValidateData(bool deep = false);
    }

    /// avoid redundant code
    public abstract class PropertyNotifier : INotifyPropertyChanged
    {
        public PropertyNotifier() : base() { }

        [field: NonSerialized]
        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    /// <summary>
    /// The scatter plot renders X/Y pairs as points and/or connected lines.
    /// Scatter plots can be extremely slow for large datasets, so use Signal plots in these situations.
    /// </summary>
    public class ScatterPlot : PropertyNotifier, IPlottable, IHasPoints, IHasLine, IHasMarker, IHighlightable, IHasColor
    {
        // data
        private double[] xs;
        public double[] Xs { get => xs; private set { xs = value; OnPropertyChanged(); } }
        private double[] ys;
        public double[] Ys { get => ys; private set { ys = value; OnPropertyChanged(); } }
        private double[] xError;
        public double[] XError { get => xError; private set { xError = value; OnPropertyChanged(); } }
        private double[] yError;
        public double[] YError { get => yError; private set { yError = value; OnPropertyChanged(); } }

       //... 
    }
```

The extension of the IPlottable interface brings the option to write an UserControl supporting MVVM at least for the single plottables (currently doing this & willing to share the finished UC). For axes and plot MVVM, I need to check where the PropertyNotifier is needed.

Best Regards,
Chris

**Comment by swharden** [comment]
Thank you for sharing this Chris! 

I'm reminded that [`INotifyPropertyChanged`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.inotifypropertychanged?view=net-6.0) is in the `System.ComponentModel` namespace so it would be possible to implement this interface in plottables distributed with the primary ScottPlot library that targets .NET Standard... food for thought!

This code and conversation could be used to extend the FAQ page about MVVM
* https://scottplot.net/faq/mvvm/
* https://github.com/scottplot/scottplot.net/blob/main/content/faq/mvvm/index.md

I'll leave this issue open until the documentation is edited to include this content. @ChrisCC6 do you want to try to edit that file with a pull request? Once merged, the website will update automatically.

If not, that's okay, I can get to it later this week.

**Comment by ChrisCC6** [comment]
Hi Scott,

thank you for your quick reply. Give me a little time, I'm working on it... ;-)

Best Regards
Chris

**Comment by StendProg** [comment]
Hi @ChrisCC6,

With great curiosity I looked at what you did, thanks for the great work done (thoughts about creating a MVVM control have not left me for more than a year, but there is too little experience and too voluminous a task, so I just think without starting anything).

In terms of criticism, I want to note the following features of your work:
1. The key should be the minimum need to make any changes to the ScottPlot root library for the needs of the MVVM, only in really necessary places without which you can’t do without. You plowed it up notably, this will greatly complicate the support of the root library, I think Scott will be against such large-scale changes, and here I agree with him. At least the WPFMVVM control should be a separate project (I understand that you only made a demonstration, thoughts for the future).
2. If you create your own control, then for a full-fledged ability to create bindings, you need to have each property in the form of DependencyProperty. You did this for root properties like `PlottableSource,` `AxisSource` etc. and they really work well. But for secondary properties such as `Plottables` properties, you decided to go the route of creating an INotifyPropertyChanged. And this approach will not work fully. INotifyPropertyChanged cannot be a binding target, only a source. In your demo, ready-made controls like `Comboboxes`, `Sliders` etc., act as the binding target, which is why it works. But if you want to follow the pure MVVM and bind for example some value from the user VM to for example `HSpan.X1` and change the value from the VM code, then nothing will come of the approach you have given. And this is the most typical scenario (IMHO) when working with MVVM.
3. I noticed some strong freezes when viewing the demo, even with debugging disabled, I don’t know what this is connected with. The example seems to be not very loaded, maybe with some kind of redundant updates.

As I see ScottPlot MVVM control:
1, Ideal Interface something like this:
```xaml
<wpfPlot Title={Binding ChartTitle}
                ShowLegend={Binding ShowLegend}>
    <PlottableSignal 
        Data={Binding ys}
        LineWidth={Binding SignalLineWidth}
        MinRenderIndex="100"/>
   <PlottableScatter ....>
</wpfPlot>
```
2. There must be proxy classes for each source library class that contain dependency properties and pull the real methods of the root library classes. At the same time, the root library is not affected in any way, but it becomes necessary to manually synchronize all changes to the root library, this is the biggest problem that stops me, I don’t know how to solve it.
```c#
public class SignalPlotEx
{
  private SignalPlot source;

 public static DependencyProperty XS
 {
   get => GetValue(source.XS);
   set => setValue(source.YS);
 }

...

}
```
3. The root library must be filled with events signaling changes in properties during the execution of methods.
For example, if the axis limits are recalculated during the rendering process, then there must be some kind of event that notifies about this change. This is necessary for the implementation of full-fledged two-way bindings. Such changes must be made to the root library, there is no way to do without it, and there can be hundreds of such changes.
4. Big difficulty with visual update, when to call it, if after each change of some property, then a typical scenario with a change in the code of 10 parameters will cause 10 renders. If you leave it at the mercy of the user, then the whole point of creating a MVVM control is lost. It is quite possible that calling RenderReguest() will smooth the effect automatically.

The biggest and most difficult point 1. Writing a hundred proxy classes is already a very difficult task, but manually constantly synchronizing changes is an impossible task. There are thoughts that this can be solved using automatic code generation of such classes, but I have zero experience in this matter.

I hope my criticism and thoughts will not diminish your motivation, but will only direct you in a more constructive direction. That was the purpose of my post. I really liked what you did, I have very little free time, but you lit a spark in me.

**Comment by ChrisCC6** [comment]
@StendProg 
I do understand your criticism and the pure amount of changes I implemented, stopped me from creating a pull request. The design is not made for MVVM and a complete rewrite would be necessary. On the other side, an MVVM component would not work for console applications.
At the end I guess this would result in a completely separate project.

I really don't know how to proceed, but I need to admit that any try to implement something similar in ScottPlot will mess this project up.

If there is nobody with a good idea, I guess this could be closed.

Best Regards
Chris

**Comment by swharden** [comment]
Hi @ChrisCC6 and @StendProg,

This is an excellent discussion! @StendProg's list is a good summary of how MVVM could be implemented, and why it is challenging - so challenging it is not desirable at this time. 

I added a link on https://scottplot.net/faq/mvvm/ pointing to this issue, and I'm sure the topic will come up again.

> At the end I guess this would result in a completely separate project

This is the conclusion I arrived at as well. It is possible, but would require so much reworking of the existing code (and massive addition of boilerplate code) it may be best to do it in a new project. At that point it makes sense to omit 90% of ScottPlot's features and just implement the ones you intend to have in your control, greatly reducing complexity and boilerplate code.

I'll close this issue for now, but surely will continue to reference it when this topic arises in the future 👍

**Comment by kusleikar** [comment]
A possible fix for anyone looking to get this to work is:

In xaml:
<UserControl Content="{Binding Path=WpfPlot}"/>

In viewmodel:
public WpfPlot WpfPlot
    {
        get; set;
    }

    public MainViewModel()
    {
        var x = Enumerable.Range(0, 1001).Select(i => i / 10.0).ToArray();
        var y = x.Select(v => Math.Abs(v) < 1e-10 ? 1 : Math.Sin(v) / v).ToArray();

        WpfPlot = new WpfPlot();
        WpfPlot.Plot.AddSignalXY(x, y);
        WpfPlot.Refresh();

    }

**Comment by RFBomb** [comment]
So this did in fact come up again lol

Heres my thoughts on this : Currently 'Plot' is a read-only property of the WpfPlot control. I think this could be easily converted into WPF by simply converting that read-only property into a proper dependency property. Then you can do all your plot creation in mvvm, and simply bind to the plot using standard xaml.
