### ISSUE TITLE
Program crash

### ISSUE THREAD

**Issue by lwlivy** [ScottPlot/ScottPlot#1790]
---------------------------------

**ScottPlot Version:** 4.1.*

**Operating System:** Windows10

**Application Type:** WinForms

**Question:** The program occasionally crashes when I drag the curve with the left mouse button or zoom in and out. The errors are DWrite.dll and TextShaping.dll.

Has anyone come across this?

**Comment by swharden** [comment]
Hi @lwlivy 

I have not experienced this

Can you share the code you used to generate the graph? Is this a scatter plot with draggable points?

**Comment by lwlivy** [comment]
this.formsPlot1.Plot.Clear();
double[] datax = dt.AsEnumerable().Select(t => t.Field<DateTime>("时间").ToOADate()).ToArray();
double[] datay = dt.AsEnumerable().Select(t => Convert.ToDouble(t.Field<string>("特征值"))).ToArray();
this.formsPlot1.Plot.AddScatter(datax, datay, System.Drawing.Color.LightGray);
this.formsPlot1.Plot.XAxis.DateTimeFormat(true);
//this.WpfPlot.Configuration.LockHorizontalAxis = true;   //锁定x轴缩放
this.formsPlot1.Configuration.LockVerticalAxis = true;         //锁定y轴缩放
Crosshair = formsPlot1.Plot.AddCrosshair(0, 0);
BaseScatterPlot = formsPlot1.Plot.AddScatterPoints(datax, datay, System.Drawing.Color.LightGray);
this.formsPlot1.Configuration.DoubleClickBenchmark = false;
this.formsPlot1.Configuration.RightClickDragZoom = false;
this.formsPlot1.RightClicked += RightClick;
this.formsPlot1.MouseMove += WpfPlot_MouseMove;


Above is my code

**Comment by fuxinsen** [comment]
我也曾遇到过这个问题，加了自定义的MouseMove事件后，移动或缩放画图面板时（触发了自定义的MouseMove事件）会导致程序崩溃，我的解决方法是在自定义的MouseMove事件里判断一下，如果有鼠标按键被按下，直接返回，不执行任何操作。

I have also meet this problem. After adding the custom MouseMove event, moving or scaling the drawing panel (triggering the custom MouseMove event) will cause the program to crash. My solution is to judge in the custom MouseMove event：if any mouse button is pressed, return directly without performing any operation.

**Comment by swharden** [comment]
Hi @lwlivy,

I tried to recreate the error using your code but it is not complete and I cannot run it. If the code you shared is inside a function, your error may be caused by how it is called. WinForms graphics has limited support for multi-threading. A solution may be to ensure that code is called from a timer (not another thread). See https://scottplot.net/faq/async/ for details.

> After adding the custom MouseMove event ... if any mouse button is pressed, return directly without performing any operation.

Thank you for sharing your solution @fuxinsen! Indeed, the original author's custom MouseMove event is a likely cause of this error. It would be helpful if they shared the code inside that event, but it seems likely that is related to the error they are experiencing.

**Comment by lwlivy** [comment]
Sorry for being late, my problem is caused by too frequent refreshes, which can be solved by using Refresh with parameters.
However, I have a problem now that when I timed rendering the curve, it gets slower and slower later. Is there a good solution?
I am using SignalPlot.

**Comment by swharden** [comment]
Consider calling RefreshRequest() to use a render queue system... That is my only remaining idea for improving performance 🤞
