### ISSUE TITLE
Manual tick spacing alongside automatic

### ISSUE THREAD

**Issue by Xerxes004** [ScottPlot/ScottPlot#1815]
## Feature Suggestion

Feature goes with PR #1814

**Feature description:** I'd like to be able to manually label certain major ticks, but keep the automatic ticks as well.

**Code example:**

```cs
// a code sample may improve communication
var plt = new ScottPlot.Plot();
double[] myCustomTicks = { Math.PI, 2 * Math.PI };
string[] myCustomLabels = { "π", "2π" };
plt.XAxis.ManualTickPositions(myCustomTicks, myCustomLabels, union: true);
```

**Example implementation from #1814:**
![union labels example](https://user-images.githubusercontent.com/9276814/166079465-9da11549-d8b3-443f-989e-72f653873c35.PNG)

**Comment by Xerxes004** [comment]
@swharden I decided to remove the closest tick to each custom tick so that the labels didn't overlap. Some users may not want this, though. Should I add a flag for users who want to keep _all_ labels? Or maybe an enum?

**Comment by swharden** [comment]
Thanks for this @Xerxes004!

Following-up, I modified your #1814 so that this feature is an addition to automatic ticks (rather than a third type of ticks). 

Users can now enable automatic ticks like this:

```cs
plt.XAxis.AutomaticTickPositions();
```

and if they want to add additional manual ticks which will always be displayed they can now do this:

```cs
double[] positions = { Math.PI, 2 * Math.PI };
string[] labels = { "π", "2π" };
plt.XAxis.AutomaticTickPositions(positions, labels);
```
