### ISSUE TITLE
Plottables: getters and setters are both required for PropertyGrid

### ISSUE THREAD

**Issue by bradmartin333** [ScottPlot/ScottPlot#1831]
**ScottPlot Version:** 4.1.43

**Operating System:** Win10

**Application Type:** WinForms

**Question:** Users keep asking for more plot customization fields to the point where I am wrapping almost everything into a custom PropertyGrid. It is a lot easier to allow the user to select a Plottable to be assigned as the active PropertyGrid object and let them have access to everything they want and more. This works well, but some params are not exposed, [such as text rotation and background color](https://github.com/ScottPlot/ScottPlot/blob/4eb9e57ee44c428c9457bdb8176be5590f168b63/src/ScottPlot4/ScottPlot/Plottable/Text.cs#L20-L38). Any underlying reason for this?

Here is an example PropertyGrid for a Text plottable:
![image](https://user-images.githubusercontent.com/19335151/166801783-df5f43a6-fef8-478e-93af-bb79896f2a06.png)

**Comment by swharden** [comment]
Hi @bradmartin333, thanks for pointing this out! There are two issues here.

## Fields vs. Properties

Many plottables use fields instead of auto-properties. Here's a random example:
https://github.com/ScottPlot/ScottPlot/blob/4eb9e57ee44c428c9457bdb8176be5590f168b63/src/ScottPlot4/ScottPlot/Plottable/RadialGaugePlot.cs#L12-L121

There is no good reason for this, and it could be improved for [all plottables](https://github.com/ScottPlot/ScottPlot/tree/4eb9e57ee44c428c9457bdb8176be5590f168b63/src/ScottPlot4/ScottPlot/Plottable).

## Properties without both Get and Set & Nested Configuration Classes

Some plottables have properties with a getter only. The example you noted is here:
https://github.com/ScottPlot/ScottPlot/blob/4eb9e57ee44c428c9457bdb8176be5590f168b63/src/ScottPlot4/ScottPlot/Plottable/Text.cs#L27-L29

These typically exist in cases where configuration used to be a top-level field or property, but was later moved into a configuration object. A good example is `Font` settings. If I add a new advanced `Font` configuration option (hinting, alignment, ClearType vs. TrueType, etc.) I don't want to go around and update code for dozens of plottables to use it. In these cases code like that above was typically added to prevent breaking existing code when the new `Font` object was added.

1. Those properties should be made private and/or marked `obsolete`
2. Those properties could be improved by ensuring all have both getters and setters
3. Leaning on `PropertyGrid` for configuration hides configuration options behind configuration classes, doesn't it? (e.g., Font)

---

I'm curious to hear what you think, and what you recommend I do to help your application. If considering point 3 you still think using `PropertyGrid` to customize plottables is a good idea, I could go around and ensure all exposed properties have paired getters and setters

**Comment by bradmartin333** [comment]
Thanks for breaking this down. Updating all relevant properties seems valid, but also unnecessary and possibly breaking. The currently exposed properties for most plottables contain what is needed (Scatterplot color, offset x/y).

For my specific application, all that is desired are getters and setters for these `Text` plottable properties:
1) `bool BackgroundFill`
2) `Color BackgroundColor`
3) `float FontSize`
4) `bool FontBold`
5) `float Rotation`

This addition expedites the work flow for myself as well as the end users. I have been wrapping them myself, but it seemed like a small enough change to bring it up.

**Comment by swharden** [comment]
I'll go ahead and convert most of the easy fields to auto-properties with getters and setters. There may be some corner cases that won't have those, but it seems like I can get 90% of the desired functionality for free, so it's worth it. I'll try to finish it and release an updated package within the next few hours 👍

**Comment by swharden** [comment]
@bradmartin333 if you can share a little code demonstrating how you use `PropertyGrid`, that would be awesome! I don't use WinForms that much, so seeing how you prefer to use `PropertyGrid` with ScottPlot would be helpful for me and others to learn from.

**Comment by swharden** [comment]
#1834 got a lot more extensive than I initially thought it would be 😅

Virtually all configuration options are properties with getters and setters now 👍  🚀

**Comment by MareMare** [comment]
Good morning, @swharden

Maybe the following fixes have been omitted?
https://github.com/ScottPlot/ScottPlot/blob/87232055efc812f100f65524546dbdc2a4041ae4/src/ScottPlot4/ScottPlot/Plottable/Text.cs#L25

Why don't you do the following?
```cs
public readonly Drawing.Font Font = new();
```

**Comment by bradmartin333** [comment]
Awesome! This is [a new approach for me as well](https://github.com/bradmartin333/XferSuite/blob/8e502fee3b8e169a121ae52e0768a4b8c717d735/XferSuite/Apps/SEYR/Results.cs#L169-L177), but it is very convenient. The [combo box is populated](https://github.com/bradmartin333/XferSuite/blob/8e502fee3b8e169a121ae52e0768a4b8c717d735/XferSuite/Apps/SEYR/Results.cs#L82-L87) after creating the plots. There are some special cases and I will finish those up tomorrow with the new version of ScottPlot! 😁

**Comment by BambOoxX** [comment]
Very interesting! I wonder if this kind of approach could be leveraged to improve the current way of modifying plottable properties with the interactive legend... What do you think @swharden?

The idea would be to pop a property box depending on the type of the plottable, rather than propose additionally created menus.

**Comment by swharden** [comment]
> pop a property box depending on the type of the plottable, rather than propose additionally created menus

@BambOoxX it seems simple enough! Maybe a "plot object editor" could be a standalone Form. It could resemble the cookbook demo application, with a ListBox listing all the plottables on the left, and clicking one would load a PropertyBox on the right. It could be added to the default right-click menu... and if it never gets polished enough to push into production, we could always hide visibility in the menu behind a feature flag or something.

**Comment by BambOoxX** [comment]
@swharden I think such a plottable editor would be great.
However I'm unsure of the workflow.
In fact in most plotting applications I use, it always boils down to first select the plottable you want to edit, then actually edit it.
I think I've never seen a case where one would need to pop the total list of objects, then select the correct one, although that would be very close to the current scottplot behavior based on the detached legend.

In case of such an editor, I believe that allowing to modify multiple plots at once, as well as filter the list of plots based on their label would be of great interest.

**Comment by swharden** [comment]
Hi @BambOoxX, I made a proof of concept PR (#1842). The idea is pretty simple, and I was surprised it only took about 5 minutes to make. There could be lots of interesting possibilities here, but also potential for users to get plottables into bad states. I'm not sure if I'll merge this, but it's interesting to play with!

![grid](https://user-images.githubusercontent.com/4165489/167742905-2a758678-22b3-4c31-b916-0e1f429178c3.gif)
