### ISSUE TITLE
Improve MacOS and Linux instructions on website

### ISSUE THREAD

**Issue by Stepami** [ScottPlot/ScottPlot#1854]
## Bug Report

**Issue:** hieroglyphics on plot

**Reproducing:** whenever i try to make any plot i do not get figure as expected. As an example i took snippet from cookbook
```cs
// a code sample may improve communication
ar plt = new ScottPlot.Plot(600, 400);

// sample data
double[] xs = DataGen.Consecutive(51);
double[] sin = DataGen.Sin(51);
double[] cos = DataGen.Cos(51);

// plot the data
plt.AddScatter(xs, sin);
plt.AddScatter(xs, cos);

// customize the axis labels
plt.Title("ScottPlot Quickstart");
plt.XLabel("Horizontal Axis");
plt.YLabel("Vertical Axis");

plt.SaveFig("quickstart_scatter.png");
```
and got this
![](https://habrastorage.org/webt/vu/nt/9h/vunt9hbdfamjjtm4lqdnx4u7tjg.png)
I tried to invoke SetCulture method but it did not workout.
### System Details
* **ScottPlot Version:** 4.1.45
* **Operating System:** MacOS 11.2.3 (Big Sur)
* **Application Type:** console
* **.NET Version:**  .NET 5, .NET 6

**Comment by bclehmann** [comment]
It's possible that this has the same fix as https://github.com/ScottPlot/ScottPlot/discussions/1734 despite being on MacOS. The TLDR is installing `System.Drawing.Common` explicitly seemed to work.

If that is indeed the problem, I think it's a new issue, as I don't believe this was required on MacOS before. For completeness sake, is your instruction set x86 or ARM?

**Comment by Stepami** [comment]
@bclehmann my processor is 2,6 GHz 6-Core Intel Core i7

**Comment by Stepami** [comment]
Thanks a lot, that explicit installation of `System.Drawing.Common` has really helped. So you could write about the case in the docs or smth.

**Comment by bclehmann** [comment]
@swharden Looks like we might have to add the same note we have on Linux about explicitly installing `System.Drawing.Common`

**Comment by swharden** [comment]
Technically it's already there in the quickstart 

https://scottplot.net/quickstart/console/#macos--linux

Is there a more effective location to make it visible to Linux/MacOS users? 🤔

**Comment by bclehmann** [comment]
The wording "You may also need to..." is misleading, it implies that you only need to do that if you're using specific features or have a niche use-case. Normally when it shows up in docs it's something that you can (normally) ignore.

I think better wording is "You will also need to...". It may still benefit from being placed more prominently, although it's in the same place where we tell users to install `libgdiplus`, and I don't think we get lots of people reporting issues because they didn't see that. But I don't see all the issues (or get any of the emails). Plus there are likely a lot of people that cannot get it working and just switch to an alternative library, rather than open an issue.

**Comment by swharden** [comment]
I made a new page detailing cross-platform setup and issues:
* https://scottplot.net/faq/dependencies/

... and I now link to that page in step 1 of the cross-platform quickstart guides:
* https://scottplot.net/quickstart/console/
