### ISSUE TITLE
Ticks: Labels appear and disappear on an auto-scrolling axis

### ISSUE THREAD

**Issue by nassaleh** [ScottPlot/ScottPlot#1880]
## Bug Report

**Issue:** 

Currently I am trying to implement a scrolling mechanism to view live data. It differs from the example in the cookbook as the Electrocardiogram strip chart only showed a certain slice of time, and all the data was coming in at the same interval. In my case data is coming in at different intervals, in a scatter plot instead of a signal plot. In order to do the scrolling, I update the axis limits every X milliseconds. This results in a scrolling animation, but causes the axis ticks to flicker in and out.

![flickering](https://user-images.githubusercontent.com/2446825/172475354-ba2b2fda-d226-451c-bd3b-26f065615c75.gif)

Trying to do just AxisPan causes the X axis to grow as if it was set to AxisAuto.

**Reproducing:** 

```cs
  // adjust the axis limits only when needed
  var axisLimits = Plot_UserControl.Plot.GetAxisLimits();
  var currentRange = (DateTime.FromOADate(axisLimits.XMax) - DateTime.FromOADate(axisLimits.XMin)).TotalSeconds;
  double slidingPercentage = 0.95;

  var currentPoint = DateTime.Now;

  var max = currentPoint.AddSeconds(currentRange * (1 - slidingPercentage));
  var min = currentPoint.AddSeconds(-currentRange * slidingPercentage);

  Plots.SetAxisLimitsX(xMin: min.ToOADate(), xMax: max.ToOADate());
```

### System Details
* **ScottPlot Version:** 4.1.63?
* **Operating System:** Windows 10
* **Application Type:** WinForms
* **.NET Version:** .Net 6

**Comment by swharden** [comment]
Hi @nassaleh, thanks for sharing this interesting issue!

On every render ScottPlot tries to determine the best tick positions/labels based on the current axis limits, but since your plot is scrolling the recalculations are causing "flickering" between different densities of tick labels. 

## Manual Tick Spacing

You could try defining the tick _spacing_ something like:

```cs
double secondsPerDay = 60 * 60 * 24;
double oneSecondSpacing = 1.0 / secondsPerDay;
plt.YAxis.ManualTickSpacing(oneSecondSpacing );
```

## Manual Tick Positions/Labels

Or if that doesn't give you the control you want, you could manually decide where to place ticks on every render, and specify their positions and labels exactly as you want them to appear using something like:
```cs
double[] xPositions = { /* custom */ };
string[] xLabels = { /* custom */ };
plt.YAxis.ManualTickPositions(yPositions, yLabels);
```

In this case you can use the object that `plt.GetAxisLimits()` returns to determine where the horizontal axis is currently spanning.

I hope this helps!

**Comment by swharden** [comment]
I'm going to close this now assuming the information from the previous comment is sufficient for you to find a solution, but if not feel free to continue this discussion or re-open this issue. 👍

**Comment by nassaleh** [comment]
@swharden That fixed my issue. Thank you so much!
