### ISSUE TITLE
ManualTickPositions displays all values, how does one hide most of them when scrolling.

### ISSUE THREAD

**Issue by CaptainBob81** [ScottPlot/ScottPlot#1884]
**ScottPlot Version:** 4.1.35

**Operating System:** Win 10

**Application Type:** WPF

**Question:** 

Hello!

I'm trying to make it so that the labels on the Xaxis behave as they do in the Yaxis with the automatic hiding of values when scrolling. I'm using ManualTickPositions to insert strings in place of doubles. But my problem is that ALL of the strings get printed and that is not what I want. The Yaxis only uses double values as usual and works fine.
I cannot show you my code due to the line of work I am in. 
But I can show a picture. As you can see I want to hide most of the labels when they overlap. 
I was looking at issue #1512 but I don't see how changing the format of the labels also changes if they are shown or not.

Awesome stuff as always, thanks!

![Annotation 2022-06-08 115959](https://user-images.githubusercontent.com/59774105/172589700-bde0ae82-019b-467d-93ae-2e58c4146c6f.png)

**Comment by swharden** [comment]
Hi @CaptainBob81, thanks for the question!

> I cannot show you my code

This makes providing assistance quite a challenge

> I don't see how changing the format of the labels also changes if they are shown or not

Actually, understanding this is likely to solve your problem. 

By default ScottPlot automatically determines which tick labels are shown or hidden so the proper density of labels is always used and label text never overlaps. When you use `ManualTickPositions()` you disable this functionality, and every position you provide turns into a tick (causing all those overlapping labels).

> insert strings in place of doubles

It sounds like what you're trying to do is, given a certain tick position, show a custom string instead of that double. This is what the custom tick formatter does, and using it is likely to solve your problem. You provide a function that converts the double to whatever text you want to display, give that to ScottPlot, and it handles whether or not ticks are shown in such a way that overlaps do not occur.

https://scottplot.net/cookbook/4.1/category/advanced-axis-features/#custom-tick-formatter

I'll close this issue now, but feel free to open it back up if this advice doesn't help you reach a solution 👍

**Comment by CaptainBob81** [comment]
I got it to work now! Thank you so much! CustomTickFormatter worked like a charm. I used the position double as an index to pick strings from an array and then running that through a parser and returning it from the custom method. 

Thanks for all the help! =)
