### ISSUE TITLE
Plot.Axis.Pan() behaves like AxisAuto

### ISSUE THREAD

**Issue by nassaleh** [ScottPlot/ScottPlot#1886]
## Bug Report

**Issue:** 
![panning](https://user-images.githubusercontent.com/2446825/172912319-c6e4d330-d659-4f6d-967d-64938be7d734.gif)

When no plots are added, panning works as intended. When a plot is added, the XAxis scales as if we had called AxisAuto.

**Reproducing:** 

Have a plot with points being added. On a timer, call Axis.Pan

```cs
// This is the code in the timer that pans every X milliseconds
  var now = DateTime.Now;
  var diff = now.AddMilliseconds(slidingMillisecondDelay).ToOADate() - now.ToOADate();
  Plots.AxisPan(diff);

 this.Plot_UserControl.Refresh(true, false);

```

### System Details
* **ScottPlot Version:** 4.1.47
* **Operating System:** Windows 10
* **Application Type:** WinForms
* **.NET Version:** .Net 6

**Comment by swharden** [comment]
Hi @nassaleh, thanks for reporting this!

> When a plottable is added, the plot scales as if we had called AxisAuto.

Actually, this is the intended behavior. To prevent people from always having to call `AxisAuto()` after adding things to the plot, the plot makes this call automatically. This behavior aims to satisfy the 99% use case, but I can see that in this instance it is not helpful for your application. 

To prevent this behavior, save the axis limits and restore them after modifying the plot. Something like:

```cs
var originalLimits = plt.GetAxisLimits();
plt.AddPoint(x, y);
plt.SetAxisLimits(originalLimits);
```

In addition, to may find it useful to have your timer set axis limits with `SetAxisLimits()` rather than relying on `AxisPan()`. This will give you more control, and ensure your view does not drift unexpectedly over time.

If I misunderstood the problem or this advice does not help you reach a solution, feel free to re-open this issue!

**Comment by swharden** [comment]
Update: I was somewhat mistaken about what actually triggers the automatic `AxisAuto()`. It is called automatically the first time `Render()` is called, or if the previous render contained no objects.

The intent of this behavior is to automatically set axis limits when data is first added to an empty plot.
