### ISSUE TITLE
Implement IHittable for BarPlot

### ISSUE THREAD

**Issue by jhm-ciberman** [ScottPlot/ScottPlot#1891]
## Feature Suggestion

First, thanks for making such amazing library. I love it. 

Second, we are currently implementing charts in our business accounting application. They look amazing. For scatter plots we use the method described in [Highlight the Data Point Near the Cursor](https://scottplot.net/faq/mouse-position/#highlight-the-data-point-near-the-cursor) to display details about every transaction in the side panel. It works like a charm.

![image](https://user-images.githubusercontent.com/7988351/174320847-5f75163c-0469-4588-a27e-b8093a291e2e.png)

The problem arises with bar plots. Since there is no MouseOver method, or any way to detect collisions with the figure:

![image](https://user-images.githubusercontent.com/7988351/174317463-346cd90a-f01b-44d5-a68c-163d93710f8d.png)

We would like to display information when the user hovers over one bar. 

It would be pretty easy to detect mouse over one square, but the problem is that there are so may variables that controls the positioning of each bar that it becomes a bit difficult. Also, all the position calculation is done in the Draw method, so there is no way to retrieve the current position and size of each bar.

**Feature description:** 

My suggestion would be to implement the IHitable interface in the BarPlot class. I think it would be pretty easy. The same that is done for the Tooltip can be done: 

1. Inside the draw method store in a private variable the position and size of each bar.
2. In the IHittable.HitTest() method, use that information from the last render to perform a point to AABB collision test.

it would be cool to have an overload of the HitTest method that returns the index of the hit bar too. Maybe as a separate interface, like `IHittablePlot`

```cs
interface IHittablePlot : IHittable
{
    bool HitTest(Coordinate coord, out int hitElementIndex);
}
```

**Code example:**

**Comment by swharden** [comment]
> First, thanks for making such amazing library. I love it.

Sure thing! I'm happy to hear you enjoy using it ❤️🚀✨ 

> We would like to display information when the user hovers over one bar.

This seems like a common use case. I'm interested in exploring options to make this possible!

> but the problem is that there are so may variables that controls the positioning of each bar that it becomes a bit difficult

This is definitely a challenge. 

Bar positions are mostly defined by variables in [BarPlotBase.cs](https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot4/ScottPlot/Plottable/BarPlotBase.cs):
* Vertical Corrdinates: `Values`, `ValueBase`, and `ValueOffsets`
* Horizontal Coordinates: `Positions`, `PositionOffset`, `BarWidth`
* Rotation: `Orientation`

It was not the original intent to expose this complexity to the user. The goal was to have a simple API where the user defines groups and values, and these positions are handled internally, but as features were added this design became unwieldy. This complexity can't be refactored away without breaking code of existing users. 

For these reasons every once and a while I consider making an extremely simple bar plot type where the user defines bar position/size/color/label, giving them total control of positioning and style. The most recent idea was raised in #1749 but I closed it to focus on #1888.

I'll take a brief brake on #1888 and see if I can get a minimal case `BarSeries` plot type off the ground that implements `IHittable`. I'll follow-up in this issue as I make progress

**Comment by swharden** [comment]
Hi @jhm-ciberman,

I made some good progress tonight in #1892 but I can tell I won't finish it today and I'm out of town this weekend so it may be a few more days until this is done. 

If you review the code changes I made though, you may get some hints about how to implement this yourself without much effort _using the existing bar plot_ (not this new `BarSeries` I'm working on). This is because I found I can get a great effect without having to actually implement `IHittable`. Instead I just perform an action `OnMouseMove` that gets the position of the mouse (in coordinate units) and determines which bar is under that coordinate.

https://github.com/ScottPlot/ScottPlot/blob/a021144b71636901b9106d1ceb91febcf6ee330b/src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.cs#L14-L79

![bars](https://user-images.githubusercontent.com/4165489/174421183-a43fccac-1848-4377-babe-ab95fd534b96.gif)

I'll post on this issue when I make progress on this next 👍

**Comment by jhm-ciberman** [comment]
Oh, I see. That new api is fantastic. <3 There is no hurry. I still need to implement two or tree extra charts. It would be amazing to have this api on the next release.

**Comment by jhm-ciberman** [comment]
Well, I ended up implementing a helper class to detect collisions and get the nearest bar against a bunch of BarPlots:

https://gist.github.com/jhm-ciberman/0ee3a2d8e2616f0c87615eebfff29ec5

You can check it here. Maybe is helpful for other people.

**Comment by jhm-ciberman** [comment]
It works perfect: 

![Animation](https://user-images.githubusercontent.com/7988351/174848671-528e4050-85b4-401c-b4b4-64bb020908da.gif)

**Comment by swharden** [comment]
Great work! Your solution looks like it's working great, thanks for sharing your code and for the helpful animation too! 

I'll keep working on #1892 to bring this functionality into the main library, but this is moving in a great direction and it looks like you already have something working well for your application. Thanks again for the original suggestion!

**Comment by swharden** [comment]
Following-up, I'm glad your `BarCollider` solution is working for you! I probably won't add this complexity into the existing `BarPlot` class because (1) it's more to maintain, (2) the solution you linked to gets the job done, (3) horizontal bars are not supported, (4) the new `BarSeries` plot type I'm merging in #1892 has collision detection built in. This discussion led to the creation of `BarSeries` which I think is a useful plot type, and I'm excited to merge this in.

Thanks again for your input!
Scott

**Comment by jhm-ciberman** [comment]
@swharden Yes sure! I just posted my code so it can be useful for someone else. But I did't imagine you would finish adding the feature so quickly. 
Thanks for everything. At the moment I will use my solution for this chart, but I still need to add a lot of more charts to the application so I'm pretty sure I will use the new ´BarSeries´. 

Thank you! 

Edit: I saw you already made a release, amazing! Thanks!
