### ISSUE TITLE
Pie: Add support for external labels with connecting lines

### ISSUE THREAD

**Issue by Qeezy23** [ScottPlot/ScottPlot#1940]
**ScottPlot Version:** 4.1.50

**Operating System:** windows10

**Application Type:** WinForms

**Question:** When the value is small, there will be a display overlap problem. Is there any solution?

![20220709092619](https://user-images.githubusercontent.com/79734925/178086658-6c87558a-3266-4255-aaa2-d7221e4ec380.png)

```cs
            double[] pieValues = { 97, 2, 1 };
            string[] pieLabels = { "Online-Mobile", "Online-PC", "Offline" };

            Color[] sliceColors =
            {
                ColorTranslator.FromHtml("#4F81BD"),
                ColorTranslator.FromHtml("#C0504D"),
                ColorTranslator.FromHtml("#9BBB59")
            };

            Color[] labelColors =
            {
                Color.Black,
                Color.Black,
                Color.Black
            };

            var pie = formsPlot6.Plot.AddPie(pieValues);
            pie.SliceLabels = pieLabels;
            pie.ShowPercentages = true;
            pie.SliceFillColors = sliceColors;
            pie.SliceLabelColors = labelColors;

            formsPlot6.Plot.Legend();

            formsPlot6.Refresh();
```

Can we do it like this?
![20220709093718](https://user-images.githubusercontent.com/79734925/178086904-0226bfcd-e8b2-4763-936e-f1de75a4d5bb.png)

**Comment by bclehmann** [comment]
I'm wondering if we should expose an option to place all of the points outside the circle, in addition to (or instead of) automatically moving individual points outside? We can also draw lines from the pie slice to a label that is elsewhere, like in this example: 
![image](https://user-images.githubusercontent.com/8635304/178092697-6e974b91-26e5-49fb-ab6e-56848daa4226.png)


There is definitely some enhancing that can be done for the pie charts, I wonder if we could make an enhancement to the legends? Direct labeling is always kind of funky with piecharts, so labeling the values in the legend may be a good option:
![image](https://user-images.githubusercontent.com/8635304/178092567-d232c606-03e1-4de4-bc01-99a2f5dc3d3a.png)

I think of the three ideas, placing points outside the circle is the simples, and putting values in the legend is the most likely to be useful elsewhere, so I would lean towards one of those two options. Drawing lines to labels in a clean and nice way is difficult, and quite possibly not worth it, as it normally shows its usefulness in situations where you have tons of tiny categories, and you probably shouldn't be using a pie chart anyways.

**Comment by Qeezy23** [comment]
@bclehmann thanks for your comment.
I think the first solution has higher availability, Expose an option, draw lines from the pie slice to a label.

**Comment by swharden** [comment]
> I think the first solution has higher availability, expose an option, draw lines from the pie slice to a label.

I agree!

[As a colorblind person](https://media.nature.com/original/magazine-assets/d41586-021-02696-z/d41586-021-02696-z.pdf) I often find color-coded legends to be a pain point when evaluating charts.

I like the idea of an option to enable all labels to be placed outside the circle with connecting lines (rather than have some labels on slices and other labels outside them).

I also appreciate that this seems like a simple problem, but it may be one that gets more complicated than anticipated once you go about trying to implement it. Since it would be an opt-in option, I'd be happy with any functionality, even if it doesn't look great for corner cases (e.g., large numbers of extremely small slices)

@bclehmann is this something you want to have a go at?

**Comment by swharden** [comment]
> Drawing lines to labels in a clean and nice way is difficult, and quite possibly not worth it, as it normally shows its usefulness in situations where you have tons of tiny categories, and you probably shouldn't be using a pie chart anyways.

@bclehmann I didn't adequately address this in my previous comment. I also agree with these statements! Doing it cleanly is a difficult problem, and lots of tiny slices are an indication that you're probably presenting the data in a sub-ideal way.

However, for limited numbers of slices, labeled pie charts can still be nice. Here are some examples that motivate me to consider this topic further...

## Examples
![image](https://user-images.githubusercontent.com/4165489/178127461-155e0c93-6dde-4316-83c2-198ce6e551b4.png)
![image](https://user-images.githubusercontent.com/4165489/178127463-af6a4b33-f401-4f02-b1ae-d0fe84109be7.png)
![image](https://user-images.githubusercontent.com/4165489/178127466-660c1648-bf6c-4d82-84e9-22453dd786dd.png)
![image](https://user-images.githubusercontent.com/4165489/178127476-6c7c88f5-3542-4313-9468-525040928f89.png)
![image](https://user-images.githubusercontent.com/4165489/178127452-f7e275da-4b14-497f-aa2b-17623682e773.png)

**Comment by bclehmann** [comment]
> As a colorblind person...

Aye, you make a good point. Makes me wonder if hatched piecharts would be a wise addition, like in this (pretty old) PR for BarCharts: #555. As an aside, it looks like I'm watching a motor race in that screenshot...

I'm sure there's lots more places where hatched fills could be brought in (Coxcomb and Radar charts, for example), and I am wondering if we should formalize this requirement on new plottables somehow.

I think what intrigued me about putting data in the legend was bringing it into other plottables as well, a good candidate would be barcharts. And obviously Coxcomb charts, given that they're basically weird pie charts already. Perhaps population plots could put $N(\mu, \sigma^2)$ in their legends? At any rate, it likely requires some more thought as to how it would fit into an API.

**Comment by bclehmann** [comment]
> @bclehmann is this something you want to have a go at?

I think it's interesting, but potentially annoying to implement. So if anyone else is interested I would be happy to let them take a crack at it, and if not I will probably get around to it at some point.

**Comment by swharden** [comment]
> potentially annoying to implement

Agreed! I think there are higher yield tasks we can put our effort into for the short term. 

I'll add this to the triage list so the idea isn't lost, but close this issue for now since it isn't being actively worked on (#1028)

**Comment by bclehmann** [comment]
Worth noting that the triage list is a closed issue, so it gets easily lost.

**Comment by swharden** [comment]
True.

#1888 has been maintained continuously for a really long time though, and aggregating ideas there seems better than closing issues like this which would be even less likely to get noticed.

GitHub has Projects now. Have you used them before? Maybe it would be a better place to move the triage list to 🤔

**Comment by bclehmann** [comment]
> GitHub has Projects now. Have you used them before? Maybe it would be a better place to move the triage list to 🤔

I have, but not in over 2 years. I remember them being pretty basic in comparison to what I had used at work. For what it's worth, I've used Azure DevOps before, and while it's sometimes a little weird (and Microsoft changes and renames everything every 6 months), it's pretty good and we've been using it for CI already. I've also used Asana and I would advise you to stay far far away. As for other options like Trello or Jira, I haven't used them, so I don't think I'm much help.

However from what I understand the new projects are quite a bit better, and I don't think our usecase requires many features. After all, we were doing fine adding everything to a markdown list inside a god issue, so I think the free option which is more open to other contributors is probably the best one. And I think a project board is probably an improvement over the current system.
