### ISSUE TITLE
Performance and rendering issues Avalonia / OSX

### ISSUE THREAD

**Issue by radoslawik** [ScottPlot/ScottPlot#1950]
## Bug Report

**Issue:** 
Library performance on mac is very poor, even the sample application from [Avalonia quickstart ](https://scottplot.net/quickstart/avalonia/ ) with a one plot containing 5 points is a little bit laggy. When manipulating the chart (panning, zooming) the delay is visible. The plot objects (texts, lines, points) are also a bit blurry and the axis tick labels are overlapping sometimes. `System.Drawing.Common` is referenced, `libgdiplus` up-to-date, tested on two other macbooks with the same effect.

![sp_quality1](https://user-images.githubusercontent.com/55437425/178749771-94e1737f-3823-4949-b0e5-cd08709295fa.JPG)
ScatterPlot with 5 points, overlapping labels, a bit laggy when manipulation, blurry objects ("Hello world" for comparison).

![cp_quality2](https://user-images.githubusercontent.com/55437425/178749840-c8f0ac6d-67c3-46a1-bb9b-9d1cd0ea53ca.png)
SignalPlotXY with 100 points and crosshair (implementation from the cookbook), blurred and laggy, crosshair takes almost a second to update position and its labels are not aligned. The same code works perfectly fine on Windows, even with significantly larger amount of points, good enough on Linux and there are no rendering issues.

**Reproducing:** 
Create Avalonia application with any plot and run it on mac.

### System Details
* **ScottPlot Version:** 4.1.51
* **Operating System:** MacOS 11.2
* **Application Type:** Avalonia
* **.NET Version:** 5.0 / 6.0

**Comment by bclehmann** [comment]
I'm going to be upfront and say that I'm not going to be particularly helpful as I don't own a Mac, however last I knew MacOS performance was OK.

The severity of the performance issues makes me wonder if you're getting Rosettaed, do you have the correct binaries for libgdiplus, the .NET runtime, and cairo? In addition, is your Avalonia version reasonably up-to-date? I know that Avalonia in particular had a delay in supporting M1.

I believe you can verify if a process is running under x86 or ARM through the Activity Monitor, which might be easier than scouring all the dependencies of depencies of dependencies.

It is also curious that the axis text is so wrong, it makes me wonder if text measurement is broken, which could potentially cause some massive overdraw. I'd be modestly curious to see what happens if you were to hide the axes.

**Comment by swharden** [comment]
> It is also curious that the axis text is so wrong, it makes me wonder if text measurement is broken, which could potentially cause some massive overdraw. I'd be modestly curious to see what happens if you were to hide the axes.

This may relate to DPI scaling too. Consider enabling/disabling the configuration flag to see if quality improves.

https://scottplot.net/faq/dpi-scaling/

> Library performance on mac is very poor

I agree! This is a limitation of GDI. Non-windows use is warned against in .NET 6 and totally unsupported in .NET 7, so its days are numbered.

The next major version of ScottPlot will avoid these cross-platform and performance issues by using SkiaSharp instead (#1888).

Until then, troubleshooting libgdi performance issues like @bclehmann suggested is the way to go. I'm going to close this issue since it's a libgdi issue (not really a ScottPlot issue) but I'm happy to continue discussion of you have new information or figured out how to improve performance on your system

**Comment by radoslawik** [comment]
> do you have the correct binaries for libgdiplus, the .NET runtime, and cairo? In addition, is your Avalonia version reasonably up-to-date?

Yes, I have followed all the instructions on the site, mono-libgdiplus (version 6.1) is installed with all dependecies such cairo
> I'd be modestly curious to see what happens if you were to hide the axes

I made a quick test, there is no visual difference except axis being hidden

> This may relate to DPI scaling too. Consider enabling/disabling the configuration flag to see if quality improves.

It doesn't seem to fix the quality issues

I will just wait for the next major version, hopefully it will solve the issues I am currently having. Thanks for the quick responses and good luck!
