### ISSUE TITLE
IHittable: add snapping and respect data area clipping

### ISSUE THREAD

**Issue by BambOoxX** [ScottPlot/ScottPlot#1962]
## Feature Suggestion

**Feature description:** 

Hello Scott, I just played a bit with the `IHittable` interface, and here are some comments about it and potential ideas to improve it I hope

1. The current implementation of `IHittable` does not account for margins, as `IDraggable` does. There is no snap distance, making it difficult to implement and use `IHittable` on points (instead of polygons)
2. At the moment, it seems `IHittable` can only be activated/disactivated, allowing to hit an object on an event (e.g) mouse click could be a nice addition if not already possible. This would improve performance for `IHittable` `ScatterPlot`s
3. I think the detection performed on draggables with the `isUnderMouse` is redundant with what should be implemented in `HitTest`, especially considering the addition of the snap distances. There is a probable refactor to be done here since `IDraggable` seems to be a `IHittable` (or more likely `IHoverable` but that just semantics) with extra steps. 

The most difficult thing, with respect to the current implementation seems to be the ability to catch mouse events. Do you think this could be done without too much hassle ? Also that would be really nice to have that in v5 don't you think ?

**Comment by swharden** [comment]
Hi @BambOoxX! Sorry it took me so long to get to this. I've been putting all my time lately into moving #1955 forward (with discussions in #1966). I'd like to address this issue so it doesn't keep floating out there.

### Interactivity Features

> nice to have that in v5

Mouse interactivity in ScottPlot4 has been somewhat painful to develop, maintain, and extend over the years. This is in part because GUI programming is hard, it's been difficult for me to predict which behaviors users will want and to make those tasks easy to achieve, and finally ScottPlot4's clunky API hasn't been making this much easier.

With ScottPlot 5 I certainly do want all this to be easier, but I haven't figured out an API to support it that I'm happy with yet, so for the next few months ScottPlot 5 will intentionally not support any mouse interactivity 😈 

My plan is to figure out a way to make it extremely easy for users to add their own mouse interactivity to interact with plottables. I'm really motivated to work on that API and get it released as soon as possible, and I have limited enthusiasm for adding new features to ScottPlot 4. However if we can achieve some quick wins on this front, I'm all for it!

### IHittable should respect margins and support snap distance

I think I can add these features without much trouble. I'll leave this issue open to track progress on this front.

### Other topics

To be honest I don't really understand your point 2 😅 

Regarding overlap between `Hittable`, `Draggable`, and `Hoverable`, I totally agree. I don't want to break the public API by refactoring this in ScottPlot 4, so I think things will remain mostly frozen as they are, but I've definitely learned some painful lessons about how _not_ to design an API for ScottPlot 5 🙃

**Comment by swharden** [comment]
> The most difficult thing, with respect to the current implementation seems to be the ability to catch mouse events. Do you think this could be done without too much hassle ?

See the code at the bottom of #1844 - does this adequately demonstrate how to achieve the functionality you're looking for?

**Comment by swharden** [comment]
I'm creating a demo app to make usage more discoverable 

![image](https://user-images.githubusercontent.com/4165489/181381995-6e67e167-d243-4749-a320-df9ac1107810.png)

**Comment by swharden** [comment]
Dang, this is brutally complex 😝 

All the units are in coordinate units (not pixel units), so there's no way to know "units per pixel", so there's no way to know if the cursor is N pixels away from the bounding box.

I keep coding-out basic ideas for how to implement this but they either blow up in complexity or get really messy (like storing previous pixel size states from one render to another).

This may be a problem that needs to be solved on the client side (in which case I can provide an example to make it easier).

I'm going to put this down for the rest of today but pick this up tomorrow 👍

**Comment by BambOoxX** [comment]
Hi. No worries, I've seen what you are doing on v5, and I'm looking forward to trying this!

Regarding point no 2.

AFAIK, at the moment, the detection of objects on the plot, either draggable or hittable is performed continuously, so each time the mouse moves, that triggers a new set of computations, such as hitTest or isUnderMouse.

My proposal was to have the possibility to perform the triggering of these computations a bit less expensive by doing them on a specific event, here Mouse Click.

The example with the hittable scatter plot is : I have a set of points plotted and when clicking on one of these points I want to be able to find which one of them.

I hope it's clearer for you now.

**Comment by BambOoxX** [comment]
Regarding v5. I know very little about such complex designs, but would it be possible for each plottable to have a MouseEvent  and KeyboardEvent property so that one could link actions to plottables?

Also, I think some sort of ReturnOnEvent could have practical use. Because in general when I want interaction in a plottable it's because I need to retrieve some information about it related to the action I performed with either  mouse or key.

Not sure if this helps but these are my two cents

**Comment by swharden** [comment]
## How to select the nearest point on click (not on mouse move)

> I have a set of points plotted and when clicking on one of these points I want to be able to find which one of them.

Hi @BambOoxX, I think I found a solution! Let me know if this helps you get your job done, and if not I'm happy to work together to come up with one. We can continue the conversation here or on the Discord! (#1966)

Does this code/screenshot adequately demonstrate the idea? This can be achieved using the existing published library.

![click nearest](https://user-images.githubusercontent.com/4165489/181859853-764c520d-2589-48c3-97ba-95cc94d42b69.gif)

```cs
public partial class Form1 : Form
{
    Random Rand = new(0);
    double[] Xs;
    double[] Ys;
    ScottPlot.Plottable.MarkerPlot Marker;
    double SnapDistancePx = 50;

    public Form1()
    {
        InitializeComponent();
        (Xs, Ys) = DataGen.RandomWalk2D(Rand, 50);
        formsPlot1.Plot.AddScatter(Xs, Ys);
        Marker = formsPlot1.Plot.AddMarker(0, 0, MarkerShape.openCircle, 20, Color.Red);
        formsPlot1.LeftClicked += FormsPlot1_LeftClicked;
        formsPlot1.Plot.Title("Waiting for click...");
        formsPlot1.Refresh();
    }

    private void FormsPlot1_LeftClicked(object sender, EventArgs e)
    {
        (double mousePixelX, double mousePixelY) = formsPlot1.GetMousePixel();
        (double mouseX, double mouseY) = formsPlot1.GetMouseCoordinates();

        // determine the point in the scatter plot closest to the mouse
        double closestDistance = double.PositiveInfinity;
        int closestIndex = 0;
        for (int i = 0; i < Xs.Length; i++)
        {
            (double x, double y) = formsPlot1.Plot.GetPixel(Xs[i], Ys[i]);
            double dX = mousePixelX - x;
            double dY = mousePixelY - y;
            double distance = Math.Sqrt(dX * dX + dY * dY);
            if (distance < closestDistance)
            {
                closestDistance = distance;
                closestIndex = i;
            }
        }

        // take action based on whether the click engaged a point
        if (closestDistance < SnapDistancePx)
        {
            double x = Xs[closestIndex];
            double y = Ys[closestIndex];
            formsPlot1.Plot.Title($"Clicked point [{closestIndex}] (X={x:0.00}, Y={y:0.00})");
            Marker.IsVisible = true;
            Marker.X = x;
            Marker.Y = y;
        }
        else
        {
            formsPlot1.Plot.Title($"Clicked empty space (X={mouseX:0.00}, Y={mouseY:0.00})");
            Marker.IsVisible = false;
        }

        formsPlot1.Refresh();
    }
}
```

## Let's not modify IHittable

One of my big design goals for ScottPlot 5 is to make it easier to customize behavior using client-side code (rather than requiring a developer to anticipate and build-in all the various combinations of functionality users may want).

I still have some work to do figuring out the best API here, but I'm considering not supporting `IHittable` or even `IDraggable`, but instead trying to make it as easy as possible for the user to implement their own hit detection and/or dragging code on their side. We'll see how it goes 🤞 

I'm happy this issue resulted in a new WinForms demo showing how IHittable works (#1985), but I don't think I'll go all the way and add the complexity of unit/pixel state management necessary for IHittable to support pixel snapping.
