### ISSUE TITLE
Single pixel shadow

### ISSUE THREAD

**Issue by macaba** [ScottPlot/ScottPlot#1981]
I suspect that ScottPlot5 may well solve the following due to the new rendering backend but I thought I'd post anyway...

I'm crafting an engineering related log-log line chart so the primary focus is clarity/cleanliness of display. This is where I got to:

![image](https://user-images.githubusercontent.com/1031306/180756573-e7b6401e-dce6-4c3a-99db-b4e12300cdbc.png)

I'm using `Configuration.DpiStretch = false` and `Configuration.Quality = ScottPlot.Control.QualityMode.High`.

1: There is a 1 pixel shadow on all elements (lines & text) and I noticed that switching from 100% to 125% display scaling made the shadow darker (#CFCFCF). The following snippets are zoomed in with display set to 100% scaling.

![image](https://user-images.githubusercontent.com/1031306/180757579-5a1993d8-8d39-4f95-8024-7ab0aafeef12.png)

I thought I'd try disabling anti-aliasing `Configuration.Quality = ScottPlot.Control.QualityMode.Low` but the shadow persists:

![image](https://user-images.githubusercontent.com/1031306/180758288-fc3ed901-d26a-43da-abc1-1ef212c2ae7a.png)

I suspect this shadow makes the anti-aliased elements look more blurry than they should.

To make matters worse - the images in the cookbook don't seem to have this shadow. Any hints?

**Comment by macaba** [comment]
Would it be worth trying an alpha version of v5 to see if the same happens?

Source:

```
WpfPlot1.Configuration.DpiStretch = false;
WpfPlot1.Configuration.Quality = ScottPlot.Control.QualityMode.High;
WpfPlot1.Plot.Clear();
double[] logXs = x.ToArray().Select(pt => Math.Log10(pt)).ToArray();
double[] logYs = y.ToArray().Select(pt => Math.Log10(pt * yScaling)).ToArray();
var scatter = WpfPlot1.Plot.AddScatterLines(logXs, logYs);
static string logTickLabels(double y) => Math.Pow(10, y).ToString();    // "N0"
WpfPlot1.Plot.XAxis.TickLabelFormat(logTickLabels);
WpfPlot1.Plot.YAxis.TickLabelFormat(logTickLabels);
WpfPlot1.Plot.XAxis.Label("Frequency (Hz)");
WpfPlot1.Plot.YAxis.Label("Noise (nV/rHz)");
WpfPlot1.Plot.XAxis.LabelStyle(fontSize: 18);
WpfPlot1.Plot.XAxis.TickLabelStyle(fontSize: 14);
WpfPlot1.Plot.YAxis.LabelStyle(fontSize: 18);
WpfPlot1.Plot.YAxis.TickLabelStyle(fontSize: 14);
WpfPlot1.Plot.Title("NSD estimation", bold: false, size: 18);
WpfPlot1.Plot.YAxis.MinorLogScale(true, minorTickCount: 10);
WpfPlot1.Plot.YAxis.MajorGrid(true, System.Drawing.Color.FromArgb(80, System.Drawing.Color.Black));
WpfPlot1.Plot.YAxis.MinorGrid(true, System.Drawing.Color.FromArgb(20, System.Drawing.Color.Black));
WpfPlot1.Plot.XAxis.MinorLogScale(true);
WpfPlot1.Plot.XAxis.MajorGrid(true, System.Drawing.Color.FromArgb(80, System.Drawing.Color.Black));
WpfPlot1.Plot.XAxis.MinorGrid(true, System.Drawing.Color.FromArgb(20, System.Drawing.Color.Black));
WpfPlot1.Plot.SetAxisLimits(Math.Log10((double)dblXMin.Value), Math.Log10((double)dblXMax.Value), Math.Log10((double)dblYMin.Value), Math.Log10((double)dblYMax.Value));
WpfPlot1.Render();
```

**Comment by bclehmann** [comment]
The "shadow" might be a grey minor tick, if you pan downwards does the shadow move upwards? Or does disabling minor ticks make it disappear?

**Comment by swharden** [comment]
> grey minor tick

Fantastic catch! There's logic to "snap" axis limits to the nearest pixel, but I bet that logic does not exist to minor ticks.

I'll try to recreate this issue and fix it by not drawing minor ticks at the extremes of the plot which are within one pixel of the edge

> Would it be worth me trying an alpha version of v5 to see if the same happens?

I would not advise this because (1) ScottPlot 5 is missing a lot of features and still has an unstable API and (2) its rendering system is so different from ScottPlot 4 we wouldn't learn much about the issue

**Comment by swharden** [comment]
I tried and failed to reproduce this issue 😩 

I made grid lines pink so it will be more obvious if they are the cause of this problem.

![image](https://user-images.githubusercontent.com/4165489/183271816-0740f2ce-4598-4850-bb5a-a003428d6434.png)

![image](https://user-images.githubusercontent.com/4165489/183271856-88d83beb-a85f-42d6-9e25-45eeb4c6adfa.png)

```cs
public Form1()
{
    InitializeComponent();

    double[] xs = { 1, 2, 3, 4, 5 };
    double[] ys = { 10, 2_000, 50_000, 1_000_000, 1_500_000 };

    double[] logYs = ys.Select(y => Math.Log10(y)).ToArray();
    var scatter = formsPlot1.Plot.AddScatter(xs, logYs, lineWidth: 2, markerSize: 10);

    static string logTickLabels(double y) => Math.Pow(10, y).ToString("N0");
    formsPlot1.Plot.YAxis.TickLabelFormat(logTickLabels);

    formsPlot1.Plot.YAxis.MinorLogScale(true);
    formsPlot1.Plot.YAxis.MajorGrid(true, Color.FromArgb(150, Color.Magenta));
    formsPlot1.Plot.YAxis.MinorGrid(true, Color.FromArgb(50, Color.Magenta));
    formsPlot1.Plot.XAxis.MajorGrid(true, Color.FromArgb(150, Color.Magenta));

    formsPlot1.Plot.SetAxisLimits(0, 6, 0, Math.Log10(10_000_000));

    formsPlot1.Refresh();
}
```

@macaba I'm really motivated to help you solve this problem, but since I can't recreate this issue on my side I may not be able to help much. Feel free to post code I can copy/paste to recreate this error on my end and re-open this issue!

Hope it helps 🚀
