### ISSUE TITLE
Demo Live Data is not working

### ISSUE THREAD

**Issue by phamviethuy** [ScottPlot/ScottPlot#1992]
Hi Scott.
I downloaded the WPF demo application, and open live data demo. but it is not working.
I was also cloning code and tried running WPF example but the same result.

Can you find a reason and fix it? Thank you!

![image](https://user-images.githubusercontent.com/42407610/182070849-4257ec17-0dbc-48b4-8ab1-9f33f9c2fbed.png)
![image](https://user-images.githubusercontent.com/42407610/182070869-cd79be72-e138-4fad-803b-f70b91337fa9.png)

**Comment by swharden** [comment]
Hi @phamviethuy, I'm stumped with this one! It works fine on my end

![live](https://user-images.githubusercontent.com/4165489/183272066-f923835e-b17b-4268-af8c-007b57838e22.gif)

Do any of the demos at all work?

I can see on your screen its starting to work too!

![image](https://user-images.githubusercontent.com/4165489/183272073-1590e4b4-6f46-4d45-88ac-a464ab5c2332.png)

I'll probably close this since I can't recreate the issue on my end, but if anyone else has a similar issue we can open this up again

**Comment by swharden** [comment]
Maybe it's possible your system can't run the simulation as fast as mine? I wouldn't think it would freeze forever, but consider slowing down the rendering or using `wpfPlot1.RefreshRequest()` instead of `wpfPlot1.Refresh()` in this file:

https://github.com/ScottPlot/ScottPlot/blob/f473c39f6fd4dc9f7c842a8ca615e762e140459c/src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WPF/WpfDemos/LiveDataFixed.xaml.cs#L16-L72

Hope it helps!
