### ISSUE TITLE
Zooming bug

### ISSUE THREAD

**Issue by Gholamalih** [ScottPlot/ScottPlot#1997]
## Bug Report

**Issue:** (Messed up plot at zooming in)

**Reproducing:** (When we zoom the plot too much, the shape of the plot is completely messed up at sharp parts.)

### System Details
* **ScottPlot Version:** 4.1.52
* **Operating System:** (Windows 7)
* **Application Type:** (WPF)
* **.NET Version:** (.NET Framework 4.7.2)

**Comment by bclehmann** [comment]
Hello, a screenshot would be very helpful in diagnosing your issue, because as it is right now we don't know what "completely messed up" means.

Some simple code to replicate the issue would also be very helpful.

**Comment by Gholamalih** [comment]
hello.
please look at this screen capture:
[https://i.imgur.com/1rI91JE.gif](url)

**Comment by bclehmann** [comment]
I was expecting this to be something related to #1873 but that normally presents differently.

I'm assuming that this is a scatter plot, and I don't believe we've implemented a fix yet for this on scatter plots. I don't think it's high priority but it's also a relatively trivial fix.

If it happens for a different reason than #1873 then I think you might be a little out of luck, as we're already looking to move development towards ScottPlot 5 (where it'll presumably be fixed, because this seems to be the fault of the drawing library which we intend to leave behind).

**Comment by bclehmann** [comment]
FWIW this looks non-trivial to fix, but at least I can replicate it by zooming very far into this plot:

```
double[] xs = DataGen.Consecutive(51);
double[] ys = DataGen.Consecutive(51).Select(y => y % 5).ToArray();

plt.AddScatter(xs, ys);
```

**Comment by swharden** [comment]
FWIW, signal plots just disappear if you zoom in far enough

![zoom9](https://user-images.githubusercontent.com/4165489/183272411-e1db3585-ed3c-4f10-a06b-e1f161e9491a.gif)


I think this is a limitation of System.Drawing (not ScottPlot), so I'm not super motivated to come up with a fix...

A compromise could be to add a way to set a maximum zoom limit beyond which users can't zoom in anymore... and like @Gholamalih it's probably right at the edge where floating point precision errors become large enough to translate to the full data area.

**Comment by swharden** [comment]
If a hard limit were added to the `AxisDimensions` class, I think it would fix this issue. I'm on the fence if it's worth it though, because presumably not all plot types are affected the same way.

https://github.com/ScottPlot/ScottPlot/blob/065383a3b6182e35edbe39c2606528bd147bb013/src/ScottPlot4/ScottPlot/Renderable/AxisDimensions.cs#L265-L277

https://github.com/ScottPlot/ScottPlot/blob/065383a3b6182e35edbe39c2606528bd147bb013/src/ScottPlot4/ScottPlot/Renderable/AxisDimensions.cs#L225-L234

@Gholamalih If you're really motivated to solve this issue, another option would be to detect if users are getting too zoomed in and automatically zoom out using the `OnAxesChanged` event. A demonstration of how to tie into that event is here: https://scottplot.net/faq/shared-axes/

I hope this is helpful!
