### ISSUE TITLE
Website: Secondary Axis FAQ page has mislabeled axes

### ISSUE THREAD

**Issue by prime167** [ScottPlot/ScottPlot#2029]
[Multi-Axis Plots - ScottPlot FAQ](https://scottplot.net/faq/multi-axis/)

![image](https://user-images.githubusercontent.com/3722845/183846666-a517c8f4-c877-4560-8d68-b691edf4dd0f.png)

**Comment by swharden** [comment]
Thanks for reporting this @prime167! The incorrect label is here

https://github.com/ScottPlot/ScottPlot/blob/2e5fc9fc79a1cd64102416645adf773faa42175f/src/ScottPlot4/ScottPlot.Cookbook/Recipes/MultiAxis.cs#L38-L39

If you want to fix it with a PR I'd be happy to merge it, otherwise I'll get to this within the new few days 👍

**Comment by swharden** [comment]
Correction - the cookbook recipe is okay, but the source of that page is inaccurate:

https://github.com/scottplot/scottplot.net/blob/main/content/faq/multi-axis/index.md

I can fix this tonight 👍

**Comment by swharden** [comment]
fixed! Related #1627 #1632
