### ISSUE TITLE
DraggableMarkerPlotInVector is obsolete (Marker now has a DragSnap to control snapping)

### ISSUE THREAD

**Issue by cvdevol** [ScottPlot/ScottPlot#2038]
I just upgraded to 4.1.53.0 (and Wpf 4.1.54.0). Now I get an error "DraggableMarkerPlotInVector is not defined". It worked fine on the previous version.

---------------------------------

## Bug Report

**Issue:** (Bug description goes here)

**Reproducing:** (What do others have to do to reproduce the bug?)

```vb
' a code sample may improve communication
 Dim dragger As DraggableMarkerPlotInVector

### System Details
* **ScottPlot Version:** 4.1.53.0
* **Operating System:Windows 10
* **Application Type: WPF 
* **.NET Version: NET Framework 4.81

**Comment by swharden** [comment]
Hey @cvdevol, I understand the confusion! I'll leave this issue open until I update the cookbook website to demonstrate how the recent snapping improvements let the standard plot types achieve snapping.

This cookbook recipe shows how to have a draggable marker that snaps to two vectors (arrays) of X and Y points.

Since this functionality is not available to any draggable plot type, `DraggableMarkerPlotInVector` is no longer required

```cs
// create random data and display it with a scatter plot
double[] xs = DataGen.Consecutive(50);
double[] ys = DataGen.Random(new Random(0), 50);
plt.AddScatter(xs, ys, label: "data");

// place the marker at the first data point
var marker = plt.AddMarkerDraggable(xs[0], ys[0], MarkerShape.filledDiamond, 15, Color.Magenta);

// constrain snapping to the array of data points
marker.DragSnap = new ScottPlot.SnapLogic.Nearest2D(xs, ys);
```

Hope it helps!
Scott

**Comment by swharden** [comment]
https://scottplot.net/cookbook/4.1/category/plottable-marker/#draggable-marker-snap

**Comment by BambOoxX** [comment]
Hey Scott, a quick comment. On of the functionalities provided by `DraggableMarkerPlotInVector` was that it was possible to find the index in the vector of the current position, using the `CurrentIndex` property. Is there something equivalent with `DraggableMarkerPlot` and the `SnapLogic` ?

**Comment by BambOoxX** [comment]
Thanks for the example (and quick reply as always) Scott, I did not think of trying a standalone `Snapper`, nice one !

**Comment by swharden** [comment]
> I did not think of trying a standalone Snapper

I didn't think of it at first either 🙃 

I don't think I ever intended them to be used this way, and I was a little surprised it turned out to be so easy!

> quick reply as always

I don't recall if you're in the Discord #1966, but it's starting to grow I'm finding people there are able to give quick feedback and provide creative solutions there too. May be worth checking out!
