### ISSUE TITLE
How to make a nested donut chart

### ISSUE THREAD

**Issue by vietanhbui** [ScottPlot/ScottPlot#2087]
**ScottPlot Version:** 4.1.52

**Operating System:** Windows 11

**Application Type:** WinForms

**Question:** How to make a nested donut chart

I want to make a nested donut chart like this: (sub group and has Explode)
![image](https://user-images.githubusercontent.com/43196820/188061114-5782b2fa-ea8c-4f17-9be2-a0f758beb313.png)

Thanks!

**Comment by swharden** [comment]
Hi @vietanhbui! Thanks for this question. Unfortunately I think this functionality is available presently. You could copy the code for the existing pie class and modify it to achieve this functionality. As long as it implements `IPlottable` you can instantiate it then pass it in with `formsPlot1.Plot.Add(yourPieChart)`, but it would definitely take some work...

@bclehmann is this something you're interested in implementing? Maybe what it achieved here could translate well to ScottPlot 5's pie chart? It's up to you if you want to hack this into the existing pie chart, or if you'd like to create a new pie class with a simpler API so you can add this stuff without breaking existing users. If you aren't interested in working on this at this time, I'll probably close this issue since I intend to spend the next several weeks focusing on #1955. Let me know what sounds good to you!

If it helps, I tried with the existing code 🤷 It's kinda there. Maybe a halfway fix could be to add another field that controls how large the pie is, allow the inner donut to be drawn smaller than the outer one...

```cs
public Form1()
{
    InitializeComponent();

    Random rand = new (0);

    IPalette pal = new ScottPlot.Palettes.Tsitsulin();

    double[] valuesInner = DataGen.Random(rand, 8, 10);
    var pieInner = formsPlot1.Plot.AddPie(valuesInner);
    pieInner.SliceFillColors = pal.GetColors(valuesInner.Length);
    pieInner.DonutSize = .3;
    pieInner.Explode = true;

    double[] valuesOuter = DataGen.Random(rand, 3, 10);
    var pieOuter = formsPlot1.Plot.AddPie(valuesOuter);
    pieOuter.SliceFillColors = pal.GetColors(valuesOuter.Length, valuesInner.Length);
    pieOuter.DonutSize = .7;
    pieOuter.Explode = true;

    formsPlot1.Refresh();
}
```

![image](https://user-images.githubusercontent.com/4165489/188239959-cb27e7fc-cad1-4b35-b3a6-207a331dc627.png)

**Comment by swharden** [comment]
Hi @vietanhbui, I just realized the slices look okay if you don't explode them

![image](https://user-images.githubusercontent.com/4165489/188289836-02949385-bd4e-4415-99b5-86461f5dcbce.png)

You would have to calculate how large each of your sub-slice sizes should be so they align with the larger pie, but overall I think this is enough information allowing you to realize this solution 👍 

Good luck!
