### ISSUE TITLE
Bar: Add option to draw labels below bars

### ISSUE THREAD

**Issue by vietanhbui** [ScottPlot/ScottPlot#2145]
**ScottPlot Version:** 4.1.52

**Operating System:** Windows 11

**Application Type:** WinForms

**Question:** How to draw invert Vertical Bar with show values

I can draw vertical bar with XAxis2 with show values in top of each bar:
```cs
plt.XAxis.Ticks(false);
plt.XAxis.Grid(false);
plt.XAxis2.Ticks(true);
plt.XAxis2.Grid(true);

double[] values2 = { 26, 20, 23, 7, 16 };
double[] positions = { 0, 1, 2, 3, 4 };
string[] labels = { "PHP", "JS", "C++", "GO", "VB" };
var bar = new BarPlot(positions, values2, null, null);
bar.XAxisIndex = 1;
bar.Orientation = ScottPlot.Orientation.Vertical;
bar.ShowValuesAboveBars = true;
plt.Add(bar);
//plt.YAxis.TickLabelNotation(invertSign: true);
plt.XAxis2.ManualTickPositions(positions, labels);
```
![image](https://user-images.githubusercontent.com/43196820/193489678-32bea842-a6ac-4045-a0d1-0b6abbf25347.png)

But i want to draw **invert** vertical bar with show values like this: 
![image](https://user-images.githubusercontent.com/43196820/193489968-480c3095-94cb-484e-b631-4e9afa5725b8.png)
Tks!

**Comment by swharden** [comment]
Hi @vietanhbui, thanks for posing this question!

This is not currently supported, but I will implement a solution shortly.

Investigating this request led to identification of several possible improvements:

* #2146
* #2147
* #2148

## Close Solution: Bar Plot

The problem with traditional bar plots is that the value label is always drawn above the bar plot, and also that colors cannot be individually customized. It's pretty close otherwise.

```cs
ScottPlot.Plot plt = new(400, 300);

plt.XAxis.Ticks(false);
plt.XAxis.Grid(false);
plt.XAxis2.Ticks(true);
plt.XAxis2.Grid(true);
plt.YAxis.Ticks(false);
plt.YAxis2.Ticks(true);

double[] values2 = { -520, -90, -0, -2, -520, -90, -0, -2, };

var bar = plt.AddBar(values2);
bar.XAxisIndex = 1;
bar.YAxisIndex = 1;
bar.ShowValuesAboveBars = true;

static string CustomFormatter(double value) => (-value).ToString();
bar.ValueFormatter = CustomFormatter;

// customize horizontal group labels at the top
double[] tickPositions = { 1.5, 5.5 };
string[] tickLabels = { "A", "B" };
plt.XAxis2.ManualTickPositions(tickPositions, tickLabels);

// customize vertical tick labels at the right edge
plt.YAxis2.TickLabelFormat(CustomFormatter);

plt.SaveFig("test.png");
```

![test](https://user-images.githubusercontent.com/4165489/193726102-84200a6a-2a48-4301-91d5-471aa55ff0d4.png)


## Close Solution: Bar Series

https://scottplot.net/cookbook/4.1/category/plottable-bar-series

This is probably the best solution, but the current limitation is that there is insufficient support for negative bars (#2147)

## Next Steps

I'll work on these issues and follow-up here when a solution is reached! This again for pointing-out this limitation 👍

**Comment by swharden** [comment]
Hi @vietanhbui, sorry it took me so long to get to this! The following is now possible with the latest version of ScottPlot 4:

```cs
double[] values2 = { 26, -20, 23, -7, 16 };
double[] positions = { 0, 1, 2, 3, 4 };
string[] labels = { "PHP", "JS", "C++", "GO", "VB" };

ScottPlot.Plottable.BarPlot bars = new(positions, values2, null, null)
{
    XAxisIndex = 1,
    Orientation = ScottPlot.Orientation.Vertical,
    ShowValuesAboveBars = true
};

ScottPlot.Plot plt = new(400, 300);
plt.Add(bars);
plt.BottomAxis.Ticks(false);
plt.LeftAxis.Ticks(false);
plt.RightAxis.Ticks(true);
plt.TopAxis.Ticks(true);
plt.TopAxis.ManualTickPositions(positions, labels);
```

![image](https://user-images.githubusercontent.com/4165489/230504902-cbd1d5b7-61f1-4987-9c72-12a9cea58f6b.png)
