### ISSUE TITLE
Multi-Axis with stack vertically in Axis-Y and horizontally in Axis-X.

### ISSUE THREAD

**Issue by YUXI07** [ScottPlot/ScottPlot#2175]
Hi, all,

I have a little idea about multi-Axis in scottplot. 
### Feature Suggestion

**Feature description:**   The Multi-Axis function in scottplot added by stack horizontally in Axis-Y and vertically in Axis-X. Like below Fig.1.  
It will be greater for some Lines with different Axis-Y to stack Vertically in an unique Scottplot. Like below Fig.2.

I want to add this function in scottplot, but noting in my brain.
Could you give me some ideas to improve it.

Thanks.

![image](https://user-images.githubusercontent.com/56529780/195121832-08b1f9c2-fb83-4ad5-ae69-f4ba86299149.png)

**Comment by swharden** [comment]
Hi @YUXI07, thank you for this suggestion!

Unfortunately I don't think this is possible with ScottPlot, and I'm not likely to add this feature because it would break some of the current rules ScottPlot has about axes and grids.

The best way to achieve a similar function is to use two controls and place them on top of each other, then for one disable the top padding/ticks/labels and for the other disable the bottom padding/ticks/labels so both the plot controls touch each other seamlessly. Then when you drag one, the axes of the other could move with it as described on https://scottplot.net/faq/shared-axes/

Thank you again for sharing your idea! If you end-up trying the strategy I described and discover it works (or doesn't work) it would be great if you could follow-up here and share what you tried and discovered so others wanting to do the same thing in the future can benefit from your efforts 🚀
