### ISSUE TITLE
Heatmap axis

### ISSUE THREAD

**Issue by cliff-lane** [ScottPlot/ScottPlot#2185]
On the project I am working on, they require a contour plot. I have been able to use the heat map to get a similar result with the exception of the axis. We need to be able to see the X/Y values of our data points on the Axis. Can you help with that?

**Comment by bclehmann** [comment]
Hello, there are two ways to customize the heatmap axes:

- Setting `XMin`, `XMax`, ... etc: https://scottplot.net/cookbook/4.1/category/plottable-heatmap/#size-and-placement
```cs
var hm = plt.AddHeatmap(imageData, lockScales: false);

hm.XMin = -100;
hm.XMax = 100;
hm.YMin = -10;
hm.YMax = 10;
```

- Setting `OffsetX`/`OffsetY` and `CellWidth`/`CellHeight`: https://scottplot.net/cookbook/4.1/category/plottable-heatmap/#custom-dimensions
    - This is an older API and it can be a little clunky, but sometimes it's more convenient
```cs
var hm = plt.AddHeatmap(data2D, lockScales: false);
hm.OffsetX = 10;
hm.OffsetY = 20;
hm.CellWidth = 5;
hm.CellHeight = 10;
```

**Comment by sjdemoor** [comment]
@bclehmann,  Thanks for the feedback.  (Disclaimer: I work with @cliff-lane on several projects which use ScottPlott -- which is a great plotting library!).  

This approach works well when data2D consists of evenly spaced rectangular-matrix data.  However, in some cases the data might be more randomly placed, requiring a solution similar to what @swharden implemented for the VectorField() function -- re: issue #2064

**Comment by bclehmann** [comment]
@sjdemoor This is not ideal, but you can have a heatmap with gaps: https://scottplot.net/cookbook/4.1/category/plottable-heatmap/#heatmap-with-empty-squares

Unfortunately, while this does work, there are no optimizations for this sort of sparse heatmap. I would argue that that _probably_ shouldn't be a problem due to the generally very good performance of heatmaps, but it is still fundamentally pretty wasteful to be allocating and drawing a 4K image (or beyond) if you only need a fraction of that.

If your heatmap is so massive (or so frequently updated) that you cannot eat that performance differential you can try a similar trick as in #2116. In that case we needed to glue several heatmaps together because GDI+ doesn't play nicely with very wide (~65000 pixels), but you could try using it to more efficiently render sparse matrices.

**Comment by sjdemoor** [comment]
@bclehmann, that might work, but as you imply, with our data the array size would become quite large and very sparsely populated.  What we're really looking for is a contour plot -- similar to a topo map.  The logic is very similar between a heatmap and a contour plot (see python code link below from stackoverflow).  

[Stackoverflow contour plot python discussion](https://stackoverflow.com/questions/48653695/heat-map-or-contour-plot-for-x-y-z-points-in-matlab-is-it-possible-without-me)

I was thinking that if the heatmap functionality could take arbitrarily positioned coordinates as a linked list of {X,Y,intensity}, as opposed to a uniform 2D matrix of intensities, then it might be relatively simple to convert the heatmap into a contour plot -- similar to what was done for the vectorfield plot in issue #2064.  We are actually plotting the same datasets for either vectorfield or contour plots -- the difference being that for vectorfield, "intensity" is an X/Y vector, whereas for contour plots, "intensity" is a scalar.

**Comment by swharden** [comment]
The idea of adding a contour plot feature has come up before (#2230), and I appreciate it being brought-up again! This is a useful feature I would like to have eventually, and I would welcome contributions toward this goal. I probably won't focus on developing this myself (I'm focusing on #2304 presently).

Since there isn't much movement on this issue I'm going to close it now, but if someone figures it out I would be happy to review the PR.
