### ISSUE TITLE
How to use "AxisAuto" with different threads?

### ISSUE THREAD

**Issue by smohring** [ScottPlot/ScottPlot#2188]
Hi together, 

I have a WPF application. Within the application, a Worker-Thread processes/transforms incoming data from an event handler, and a dispatcher updates the chart every 500ms on the UI-Thread.

I use the `RefreshRequest()` method on the chart, to not get conflicts with different threads, accessing the data source collections.

Now my Problem:
I am using the `AxisAuto` method, shown in a example, to scale the chart during refresh - there i often get a "source collection changed" error because that method is not as thread save, as `RefreshRequest()` is - what would be the solution to this problem?

The method to refresh the chart called by the dispatcher looks like this:

```
 void RefreshChart()
{
    // Doesn't work
    if (_isAutoAxisOnEachUpdate)
        _chart.Plot.AxisAuto(horizontalMargin: 0);

    //Works
    _chart.RefreshRequest(RenderType.LowQualityThenHighQualityDelayed);
}

```

Iam on the last ScottPlott release...
Thank you very much for your help!

**Comment by bclehmann** [comment]
I think your only option is to put anything that reads or writes to that array behind a lock. Almost all of the plottables are backed by regular old `double[]` or occasionally `List<double>`, there is no way to use them simultaneously across two different threads.

For example, this would become
```cs
object _lock = new();

// Inside your worker thread
lock(_lock ) {
    // Modify data
}

// Inside RefreshChart
if (isAutoAxisOnEachUpdate)
    lock(_lock)
        _chart.Plot.AxisAuto(horizontalMargin: 0);

// I'm slightly surprised this works across threads, you might want to verify that this doesn't need locking
_chart.RefreshRequest(...);
```

Now, you could have issues with `RefreshRequest`, because it schedules a render to happen in the future, which may be after you've given up the lock. You may have to look at `RenderLock` which is something we provide specifically to prevent renders: https://scottplot.net/faq/async/

Note that if you need `RenderLock` you will have two locks, which you will have to hold simultaneously. Therefore there's a risk of deadlock if you don't make sure to take and release the locks in the same order. The `RenderLock` api is slightly suspicious because it requires you to release the lock yourself, even if you throw an exception, so if you aren't using `try/finally` blocks you could have some difficulty. Perhaps we can improve this API by using `IDisposable`.

**Comment by smohring** [comment]
Hi,

Thank you very much for your response!
Yes, you are right - the `RefreshRequest` didn't work, too. 
When i increased the frequency of incoming data, i got the same problem with inkonsistent data due to two threading issues.

My main problem is now, that i would need to introduce so many locks to my application - basically whenever an action on the chart is performed, i need to lock it.

And as i get data frames in a really high frequency, the chart is nearly all the time locked.

Wouldn't it be better, to use thread save collections in ScottPlott? 

I think i try to access the chart only from the UI-Thread, and fill incoming data from another thread into a ConcurrentQueue.
Then i add a DispatcherTimer, that copies over larger chunks within the UI thread into the chart's arrays and refreshes the chart after that.

Thank you!

**Comment by swharden** [comment]
> Wouldn't it be better, to use thread save collections in ScottPlott?

Indeed, although this was somewhat low priority since GDI+ (System.Drawing) is not thread safe to start with, so thread safety wasn't frequently on our radar. We hope ScottPlot 5 will improve some of these issues.

> I think what i try to do next, is to access the chart only from the UI Thread, and fill incoming data from another thread into a ConcurrentQueue.
> Then i add a DispatcherTimer, that copies over larger chunks within the UI thread into the chart's arrays and refreshes the chart after that.

This sounds like a good plan! I invite you to follow-up here and share what you found so it may help others in the future. Good luck! 🚀
