### ISSUE TITLE
Contour plot: new plot type?

### ISSUE THREAD

**Issue by xichaoqiang** [ScottPlot/ScottPlot#2230]
@swharden 

Dear Sir,

Contourf type figure is often used in our geology community. 

And the below code and figure is contourf type figure in matplotlib.

Best regards,
Xi

```
import numpy as np
import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_subplot(111)
x = np.linspace(0, 3, 20) 
y = np.linspace(0, 3, 20) 
x, y = np.meshgrid(x, y) 
def fz(x, y):      
    return np.sin(x)+np.cos(y)+1  
z = fz(x, y)       

ax = plt.contour(x,y,z,colors='black')   
ax.clabel(fmt='%1.1f', fontsize=16)      
ax = plt.contourf(x,y,z,cmap='rainbow')   
ax = plt.colorbar(label="contour level")  
plt.show()
```

![image](https://user-images.githubusercontent.com/30900789/200165580-6c1b65dc-d148-4eb6-abfe-04fd19f55b99.png)

**Comment by jon-rizzo** [comment]
Just to connect the dots in this thread - my [June 25th and 26 comments here](https://github.com/ScottPlot/ScottPlot/issues/3795) outline a naive (but functional) implementation for drawing contours on a Delaunay TIN of 2D points.  The TIN can be constructed by adding the code directly from DelaunatorSharp, with a small modification for providing an attribute representing the value to be contoured (Z value).  DelaunatorSharp uses the MIT license, so this use should be allowable, as long as there is proper attribution as outlined in that license.  The pieces are all here to create a TINPlot plot type, which can have various properties such settings to control whether or not to display the triangles (and what color to use), and settings to control the contour interval, color, and even heatmap options as shown above. I suggest TINPlot as the plot type instead of ContourPlot, because sometimes it might be useful to display and stylize the TIN without the contours.  Also, a TIN is only one way to contour a set of 3d points, but it is a very common solution to this problem, especially in the civil engineering world.  By naming this TINPlot, other implementations could be added in the future without causing a conflict over the name ContourPlot.
