### ISSUE TITLE
AxisAuto() after ResetAxisLimits() not working properly

### ISSUE THREAD

**Issue by vietanhbui** [ScottPlot/ScottPlot#2264]
**Issue:** AxisAuto() after ResetAxisLimits() not working properly

```cs
var plt = formsPlot.Plot;

// create sample data
double[] values1 = { 26, 20, 23, 7, 16 };

// add a bar graph to the plot
plt.AddBar(values1);

formsPlot.Plot.SetOuterViewLimits(-0.5, 5, 0, 30);
formsPlot.Plot.SetAxisLimits(-0.5, 5, 0, 30);
formsPlot.Refresh();

// Test AxisAuto function
double[] values2 = { 136, 20, 23, 7, 16 };
plt.Clear();
plt.GetSettings().ResetAxisLimits();
plt.AddBar(values2);
formsPlot.Plot.AxisAuto();  // <= Want to fit data values2
formsPlot.Refresh();           // When I debug, formsPlot.Plot.YAxis.Dims.Max still value=30
```

### System Details
* **ScottPlot Version:** 4.1.52
* **Operating System:** Windows 11
* **Application Type:** WinForms
* **.NET Version:** NET Framework 4.6.1

**Comment by swharden** [comment]
Hi @vietanhbui, thanks for reporting this!

The issue is that `SetOuterViewLimits()` was not getting properly reset by `Clear()`

You can call that method without arguments to fix this issue
```cs
plt.Clear();
plt.SetOuterViewLimits();
```

but I'll put a formal fix in the code now to do this automatically when calling `Clear()`

Thanks again!
Scott
