### ISSUE TITLE
Opening HELP Form

### ISSUE THREAD

**Issue by dusko23** [ScottPlot/ScottPlot#2282]
Hi,
inside my project, ScottPlot is nested inside a Parent Form that has the TopMost property set to **true**.
And the Help Form opens behind the Parent Form.
It would be good to make HELP Form TopMost True as well.
Alternatively and extra property can be added to make everyone happy.

**Comment by swharden** [comment]
Hi @dusko23, thank you for reporting this!

It sounds like the problem is that in the WinForms control, the right-click help menu launches a form where `TopMost` defaults `false`.

I think manually setting `TopMost` to `true` in `FormHelp` will resolve this issue. I will make this change now, but feel free to re-open this issue if this does not solve your problem!

https://github.com/ScottPlot/ScottPlot/blob/e43c534943e560b318c0584c87da5df5204cd85f/src/ScottPlot4/ScottPlot.WinForms/FormHelp.cs#L15-L20

documentation: [Form.TopMost Property](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.form.topmost?view=windowsdesktop-6.0)
