### ISSUE TITLE
Fill Above on AddScatter

### ISSUE THREAD

**Issue by FoxTes** [ScottPlot/ScottPlot#2295]
Hello.

I want to clarify a couple of questions.
1) Can only Fill Above be used? I don't need filling in the bottom.
2) How can Fill Above be used for AddScatter?

Unfortunately, I didn't find an example in the cookbook.

**Comment by swharden** [comment]
I don't think Fill Above exists for scatter plots because there is no requirement that their data points are ordered. If you make a strange shape with scatter plots, filling above does not make sense and the resulting graph will look poor.

If you have evenly-spaced values you can use Signal and shade above the plot:
https://scottplot.net/cookbook/4.1/category/plottable-signal-plot/#gradient-fill-above

If you have unevenly-spaced values you can use SignalXY and still have options to shade above the plot:
https://scottplot.net/cookbook/4.1/category/plottable-signalxy/#signalxy-with-fill

**Comment by FoxTes** [comment]
I think we misunderstood each other. I'd rather show you an example. Is it possible to do this with the help of your charts?
![image](https://user-images.githubusercontent.com/55885862/209277267-c79950f3-44da-4d34-9dbc-a1a06410373f.png)

**Comment by swharden** [comment]
Indeed! A few cookbook examples lower on that page:

https://scottplot.net/cookbook/4.1/category/plottable-signal-plot/#fill-above-and-below

![image](https://user-images.githubusercontent.com/4165489/209342739-7d42d90b-ac29-4277-89c4-cce79620a360.png)

You could set the top color to red and the bottom color to transparent and achieve an effect similar to your picture
