### ISSUE TITLE
Histogram function ignores requested bucket size

### ISSUE THREAD

**Issue by Xerxes004** [ScottPlot/ScottPlot#2299]
## Bug Report

**Issue:** Histogram bucket size is ignored when producing bin edges.

`Common.Histogram` has an overload that looks like:

```C#
(double[] hist, double[] binEdges) Histogram(double[] values, double min, double max, double binSize, bool density = false);
```

The `binEdges` returned by this function don't have a spacing of `binSize` as expected.

For example, if I specify binSize of 1.5, and my data goes from 1 to 3, I would expect the edges to be `[1.5, 3.0]`. Instead, they are `[1.0, 2.0]`. These buckets work just fine and the histogram is valid, but the bucket sizes are not the size I requested.

**Reproducing:** Run the following code and print out the results:

```C#
double[] data = new double[] {1.0, 2.0, 3.0};
var (_, leftEdges) = ScottPlot.Statistics.Common.Histogram(data, 1.0, 3.0, binSize: 1.5);
```

### System Details
* **ScottPlot Version:** 4.1.59
* **Operating System:** Windows 10
* **Application Type:** WPF
* **.NET Version:** .NET 7.0

**Comment by Xerxes004** [comment]
I'll code up a fix for this if I find some time soon.

**Comment by swharden** [comment]
Hi @Xerxes004, I'd like to better define the current behavior by adding a test (in #2403) to demonstrate it, but then also add a test to show the new Histogram class performs as expected. For this reason, I'd like to clarify what the expected behavior actually is.

> if I specify binSize of 1.5, and my data goes from 1 to 3, I would expect the edges to be [1.5, 3.0]

If we start at the minimum value (1.0) and new bens start every 1.5 units, wouldn't we expect the bins (lower edges) for this dataset to be 1.0 and 2.5?

**Comment by swharden** [comment]
Following-up, I figured it out! 

I'm happy you brought my attention to this. The same bug that affected the old static method also affected the new Histogram class, so I'm glad we were able to fix it right out of the gate 😄 

I'll share details in #2403
