### ISSUE TITLE
Upgrade System.Drawing.Common version

### ISSUE THREAD

**Issue by gobikulandaisamy** [ScottPlot/ScottPlot#2303]
**ScottPlot Version:** 4.1.59

**Operating System:** Windows and Linux

**Application Type:** (console, WinForms, WPF, etc...)

**Question:** 

A remote code execution vulnerability exists when parsing certain types of graphics files. This vulnerability only exists on systems running on MacOS or Linux. This CVE ID is unique from https://github.com/advisories/GHSA-ghhp-997w-qr28.

Affected versions of System.Drawing.Common
>= 4.0.0, < 4.7.2
>= 5.0.0, < 5.0.3

Patched versions
4.7.2
5.0.3

**Shall we upgrade** from System.Drawing.Common **4.6.1** to System.Drawing.Common **4.7.2** ?

For your reference 

https://github.com/advisories/GHSA-rxg9-xrhp-64gj

![image](https://user-images.githubusercontent.com/24189431/208473945-d31a427f-6b8f-4dfd-b462-a78de9655cfc.png)

Images or screenshots often help communication and are encouraged. You can copy/paste or drag/drop images into this box.

**Comment by swharden** [comment]
Thanks for opening this issue @gobikulandaisamy! This has definitely been on my radar, and I am fixing this now and will publish a new ScottPlot package on NuGet today.

There are many available versions:
https://www.nuget.org/packages/System.Drawing.Common#versions-body-tab

I'm uncertain which version of System.Drawing.Common to target. Here are my thoughts for our future records:

* We need at least version 4.7.2 to avoid this security issue
* I don't want to use version 5 or later because it throws warnings with modern build targets
  * https://github.com/ScottPlot/ScottPlot/issues/1413
* That leaves 4.7.2 and 4.7.3 as remaining options. I'm struggling to find their release notes.

**I'll target 4.7.2 because it's the most widely used version that does not have this security issue**

Related:
* #1004

**Comment by gobikulandaisamy** [comment]
Thankyou @swharden for your update 4.1.60. I follow your valuable points.
