### ISSUE TITLE
ScottPlot Heatmap compression.

### ISSUE THREAD

**Issue by saklanmaz** [ScottPlot/ScottPlot#2316]
Hi Scott,

I hope you're fine. I am working on a heatmap application. I have a reference example in matlab. I wasn't sure how to integrate this reference example into scottPlot. I can draw normal heatmap. When I put a double[,] variable in it, everything is great and good. But I need to compress these values to certain angle.

Is this possible? can you help me? There is a function called pcolor in matlab. When you perform a process like the one below, you get the image below. Compresses the given values into a field.

Matlab Code : 

`[X,Y] = meshgrid(-3:6/17:3);
XX = 2*X.*Y;
YY = X.^2 - Y.^2;
colorscale = [1:18; 18:-1:1];
C = repmat(colorscale,9,1);`

Output:

![PcolorParametricExample_01](https://user-images.githubusercontent.com/96776256/209131482-aba1e9b6-b6bf-4549-ad4c-10ad0bc9979d.png)

I can share more detailed information if needed.

**Comment by swharden** [comment]
Hi @saklanmaz! Right now heatmaps are actually implemented as pixels of a `Bitmap`, and zooming/panning is just resizing the `Bitmap` before it's rendered to the screen. Because of this implementation, non-rectangular cells are not possible.

However, ScottPlot does support adding arbitrary polygons to plots. https://scottplot.net/cookbook/4.1/#polygon If you're inspired to figure-out the dimensions of each of those squares, color them individually, and add them as polygons to the chart, you can achieve the effect in your screenshot with ScottPlot

If you end-up doing this it would be awesome if you could follow-up here with a code example demonstrating how to do it so that others with a similar question can have a strong starting point if they attempt something similar in the future

Hope it helps!
Scott

**Comment by saklanmaz** [comment]
Thank you for the information, I will try it quickly. If I can I will share. :)
