### ISSUE TITLE
Pie Chart: make `Radius` public so the pie does not cover large titles

### ISSUE THREAD

**Issue by Rudde** [ScottPlot/ScottPlot#2317]
## Bug Report

**Issue:** 
When using title and using pie to represent data the title get covered by the pie chart even if you try to change the styling.

Talked to Scott on discord, he suspect it's because the radius of the pie is hardcoded. 

**Reproducing:** Code shown below

```cs
var plot = new Plot(600, 400);
plot.Title("Example title");
var pie = plot.AddPie(values);

// Even if I try to change the Style of the plot it will not be honored and the size of the pie remain unaffected
plot.Layout(50, 50, 50, 50);

plot.SaveFig("pie.png");
```

### System Details
* **ScottPlot Version:** 4.1.123?
* **Operating System:** Windows 10
* **Application Type:** console, WinForms
* **.NET Version:** .NET Framework 4.7.2

**Comment by swharden** [comment]
Thanks @Rudde! I'll finish this within the next day or two as part of #2304

The issue is here, and a solution is to make the `.9` a public property that users can customize

https://github.com/ScottPlot/ScottPlot/blob/a2a45e92a4077c1c46f9bf40284283373f11b511/src/ScottPlot4/ScottPlot/Plottable/PiePlot.cs#L109
