### ISSUE TITLE
Give some common practices guide at the beginning of the Cookbook?

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#2343]
Hi!

Even if I use Scottplot a lot, I managed to fall into a trap: I re-used a Winform Formsplot control, during runtime I sometimes plot heatmaps on it, sometimes simple Scatter plots.
I totally forgot to call the formsPlot1.Reset(); method before plotting the scatter plot after plotting a heatmap.
I only used the formsPlot1.Plot.Clear(); call, and this was just not enough: you get very strange behaviour, X scaling problem, etc. Besides, the X/Y axis labels are also not cleared, only if we use the Reset() method. 

Maybe some of these important points could be listed somewhere, so beginner Scottplot users will not fall into similar "traps"? :)
What do you think?

**Comment by swharden** [comment]
Hi @bukkideme, that sounds like an easy trap to fall into!

A quickstart section is at the top of the cookbook with the most important concepts presented in order
https://scottplot.net/cookbook/4.1/#quickstart

Related, https://scottplot.net/faq/ is laid-out somewhat in a logical order

However, these resources are generated using a console app to create flat-file images. Tips related to _user controls_ are really hard to demonstrate in a cookbook or on a website since they involve interactivity.

Note that the website has its own GitHub project https://github.com/ScottPlot/ScottPlot.NET so it's easy to edit pages or add new ones. Maybe we could add a _ScottPlot User Controls Quickstart_ page where we discuss topics like `Refresh()` and `Reset()`?

Also, perhaps #2318 will cover some of these topics 🤔 It may be worth revisiting this idea after we can evaluate how helpful (or unhelpful) the ScottPlot 4 video turns out to be
