### ISSUE TITLE
Avalonia: How to use custom fonts

### ISSUE THREAD

**Issue by Xerxes004** [ScottPlot/ScottPlot#2352]
**ScottPlot Version:** 4.1.60

**Operating System:** MacOS

**Application Type:** Avalonia 11.0.0-preview4

**Question:** How can I use an embedded `.ttf` file to change the font in ScottPlot?

I would like to use my own font (`.ttf`) that is bundled with my application in ScottPlot _without_ having to install said font on the system. I know this font works fine because I use it everywhere in my app already.

The font is located in my Avalonia resources directory at: `avares://MyApp/Assets/ChelseaMarket-Regular.ttf`.

I access a lot of resources this same way, and it all works fine.

Things I've tried:

- Put the name "Chelsea Market" as the parameter to axis label style, title style, etc. This font is added as a static resource already, and this is how I get all my labels and other stuff to use the font. This resulted in a default font being used.
- Edited the `InstalledFont` code to allow me to add my own `FontFamily` to the `InstalledFonts` dictionary. I used a `PrivateFontCollection` to achieve this, and the file appeared to load just fine. I can see the name of the font family in the collection ("Chelsea Market"). The plots after this point were *completely blank* though.

Here's my code for adding the font:

```C#
public static class FontManager
{
    private static readonly PrivateFontCollection _privateFontCollection = new();
    private static readonly HashSet<string> _seenFiles = new();

    public static void Init()
    {
        AddFont("avares://MyApp/Assets/ChelseaMarket-Regular.ttf");
    }
  
    public static void AddFont(string fontPath)
    {
        if (_seenFiles.Contains(fontPath)) return;
    
        _seenFiles.Add(fontPath);
    
        var assets = AvaloniaLocator.Current.GetService<IAssetLoader>();
    
        using var fontStream = assets.Open(new Uri(fontPath));
        using var fontMemStream = new MemoryStream();
        byte[] bytes = new byte[fontStream.Length];
        fontStream.Read(bytes, 0, bytes.Length);
        var fontDataPtr = Marshal.AllocCoTaskMem(bytes.Length);
        Marshal.Copy(bytes, 0, fontDataPtr, bytes.Length);
        _privateFontCollection.AddMemoryFont(fontDataPtr, bytes.Length);
        _privateFontCollection.Families.ForEachItem(InstalledFont.AddFont);
    }
}
```

```C#
// New function added to InstalledFont.cs
public static void AddFont(FontFamily family)
{
    if (InstalledFonts.ContainsKey(family.Name)) return;

    InstalledFonts[family.Name] = family;
}
```

**Comment by swharden** [comment]
Hi @Xerxes004, there hasn't been any movement on this issue for a while and it's unlikely to receive much useful attention in the short term future, so I'm going to close it.

Probably the best path forward to resolving this issue is to write some code that uses `System.Drawing` to render text in a one-file code sample _that does not use ScottPlot_ to demonstrate the issue (font being found but DrawString() producing blank output), then ask the Avalonia community how to solve it. From there we can work backwards and incorporate the fix into ScottPlot.

Similar idea for ScottPlot 5 and SkiaSharp. This may be helpful: https://swharden.com/csdv/skiasharp/text/
