### ISSUE TITLE
Y axis auto limit does not work

### ISSUE THREAD

**Issue by pavlexander** [ScottPlot/ScottPlot#2360]
## Bug Report

**Issue:** Cannot set the y-axis auto limit
**Reproducing:**

```cs
        private void btnPlotCandlesScott_Click(object sender, EventArgs e)
        {
            var candles = GetCanles();
            var plottableCandles = ScottConverter.ConvertToPlottalble(candles);

            var form = new ScottChartForm();
            var plot = form.MainPlot;
            form.Show();

            var candlePlot = plot.Plot.AddCandlesticks(plottableCandles);

            // enable datetimes on X axis
            plot.Plot.XAxis.DateTimeFormat(true);

            var dateFrom = new DateTime(2019, 12, 13, 5, 0, 0, DateTimeKind.Utc);
            var dateTo = new DateTime(2019, 12, 13, 12, 0, 0, DateTimeKind.Utc);

            plot.Plot.SetAxisLimitsX(dateFrom.ToOADate(), dateTo.ToOADate());
            plot.Plot.AxisAutoY();

            plot.Refresh();
        }
```

Actual plot:

![image](https://user-images.githubusercontent.com/20644772/212307474-01bcfe1f-8e3c-4ea4-9e6f-8135d208de7a.png)

Expected plot:

![image](https://user-images.githubusercontent.com/20644772/212307587-3f34c99b-b81f-4821-af03-6b32b16a3964.png)

I am trying to make it so, that when I programmatically zoom onto some area on the X-axis - so the Y-axis would auto-rescale based on the min/max values within the range. The manual setting of `SetAxisLimitsY` works, but the method `AxisAutoY` does not.

You will find the code in https://github.com/pavlexander/plot_test. If you want the full repro - please replace the `btnPlotCandlesScott_Click` [contents ](https://github.com/pavlexander/plot_test/blob/main/PlotTest/Form1.cs#L41)with code above.

### System Details
* **ScottPlot Version:** 4.1.60
* **Operating System:** Win 10
* **Application Type:** WinForms
* **.NET Version:** .Net 6

**Comment by swharden** [comment]
Hi @pavlexander, 

I tried to run your code but can't because it makes calls to functions I can't see in your post.

I wrote the following program though and it generates the output I expect.

I think the problem with your code may be that `GetCanles()` is not returning the same date range defined by your manually constructed `dateFrom` and `dateTo` values. If you use LINQ to get the `First()` and `Last()` dates like I do below, I suspect your app will work as expected.

```cs
Random rand = new(0);
ScottPlot.OHLC[] ohlcs = ScottPlot.DataGen.RandomStockPrices(rand, 20);
DateTime dateFrom = ohlcs.First().DateTime;
DateTime dateTo = ohlcs.Last().DateTime;

var plt = new ScottPlot.Plot(600, 400);
plt.AddCandlesticks(ohlcs);
plt.XAxis.DateTimeFormat(true);
plt.SetAxisLimitsX(dateFrom.ToOADate(), dateTo.ToOADate());
```

![image](https://user-images.githubusercontent.com/4165489/217972740-5cbb984a-7e36-4400-9aff-51825cea6104.png)
