### ISSUE TITLE
How to get the mouse click on the curve event

### ISSUE THREAD

**Issue by 541728305** [ScottPlot/ScottPlot#2364]
Hi，swharden！
I want to judge which curve the mouse is currently clicking after the mouse clicks on the curve. I obtain the data of the current mouse click through the GetMouseCoordinates method and judge with the bound data. However, this method must ensure that the mouse clicks on the point on the curve, and it will be invalid when the mouse clicks between two points on the curve. I want to be able to click on any drawn part of the curve, so I know which curve I'm currently clicking on.
![1e9751cedffb0076e88f4a61f1d557a](https://user-images.githubusercontent.com/72003694/212859362-8f4ba007-638b-40e6-bed2-cbb346fe5407.png)
Looking forward to your reply！

**Comment by swharden** [comment]
Hi @541728305, it sounds like you are doing everything correctly! Users interested in achieving a similar effect may find useful information at this FAQ page:

* https://scottplot.net/faq/mouse-position/

However, you are correct that ScottPlot does not currently have any logic which helps detect if the cursor is over a _connecting line_ between two data points. That calculation could be costly because it has to iterate across all data points every time the mouse moves a pixel. Users could implement this themselves (and it sounds like you're on the right track for this), but you're correct in observing there's no built-in way to select a _curve_ by hovering over it.

Hope it helps!
Scott

**Comment by 541728305** [comment]
> Hi @541728305, it sounds like you are doing everything correctly! Users interested in achieving a similar effect may find useful information at this FAQ page:
> 
> * https://scottplot.net/faq/mouse-position/
> 
> However, you are correct that ScottPlot does not currently have any logic which helps detect if the cursor is over a _connecting line_ between two data points. That calculation could be costly because it has to iterate across all data points every time the mouse moves a pixel. Users could implement this themselves (and it sounds like you're on the right track for this), but you're correct in observing there's no built-in way to select a _curve_ by hovering over it.
> 
> Hope it helps! Scott

Thank you very much for your reply
