### ISSUE TITLE
DataLogger and DataStreamer: new plot types

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2377]
This is a recurring problem and it would be nice if there were a simpler way to solve it.

Consider a situation where you have incoming sensor data you wish to plot in real time:

* Multi-channel readings
* Hundreds or thousands of readings per second
* Readings stream in faster than we need to update the plot
* The plotted data grows infinitely (and data structure should expand as needed)
* Autoscaling should be smart (don't traverse all the data to rescale on every redraw)

This is hard because (1) signal plots cannot easily grow and (2) automatic axis scaling is not currently optimized for grow-only data.

## Demo

I created a fake data generator and added a demo WinForms app that tries to accomplish this goal using signal plots, but since signal plots can't change the length of their data arrays the plot has to be cleared and signals re-added on every frame redraw. This is a poor design, but I hope that a new plot type can make this better.

https://github.com/ScottPlot/ScottPlot/blob/98744cf82ce915b8aca8bd4a4d244d38553dddcc/src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/WinFormsDemos/DataLogger.cs

![data-logger](https://user-images.githubusercontent.com/4165489/217725301-ee256710-42fb-45e6-8346-dbc31f8f92f4.gif)

## Related
* https://scottplot.net/faq/live-data/
* https://github.com/swharden/FtdiSharp
* https://github.com/swharden/ADC-10-F103C
* https://github.com/swharden/SeriPlot

**Comment by swharden** [comment]
This impressive commercial product with some neat features https://electricui.com/features

**Comment by bukkideme** [comment]
Hi! 
Yes, such optimized plot type would be extremely useful! Just to add a comment, just as you show some scenarios at https://scottplot.net/faq/live-data/ , such plot type should support different data memory handling. Sometimes we need for example to show growing data but only up to a limit. In the example you show at section [Growing Data with Partial Array Rendering](https://scottplot.net/faq/live-data/#growing-data-with-partial-array-rendering) ,  we can plot in this way. However, it is not really trivial what to do when we reach the pre-defined buffer size. Usually in my case, I would like to shift the data and re-render the plot, so a kind of ring buffer. 

Just to give an example I am playing with now in a real project, I am getting 8 channels of data. The data I get with a rate of 150 msec, is 8 * 1500 data points. I need to refresh the plot with this rate of ~150 msec. I need to have a pre-defined max buffer size, for each channels, for example 50_000 data points per channel. When the 50k size buffers are full, and a new data package arrives with the 8*1500 data points, I want to remove the oldest 1500 data points, and insert the new data at the end of the plots. 
For now, based on the above mentioned example "[Growing Data with Partial Array Rendering](https://scottplot.net/faq/live-data/#growing-data-with-partial-array-rendering)", I used Array.Copy() to shift the data left when the buffer is already full, and copy in the last data section. For the 8 channels, I see some performance loss, and I wonder what would be a better solution here. Maybe I will try to use Queue-s, but then I have to convert the Queue objects to Arrays before at each renders...? Queue would be handy here though, because we can Dequeue the older data easy, and Enqueue the incoming new data...

I have still some slight Array index calc bug in my recent approach, but I do something like this:
```
int BUFFER_SIZE = 50_000;

if (BufferActualSize + arraySize <= BUFFER_SIZE)
{
       Array.Copy(progress.AuxSensorValues.SensorValuesP1, 0, SignalPiezo1, BufferActualSize, arraySize);   
       BufferActualSize += arraySize;
}
else
 {
        //shift data to left by copying over data to itself
       Array.Copy(SignalPiezo1, arraySize, SignalPiezo1, 0, BufferActualSize - arraySize);
       BufferActualSize -= arraySize;
       //copy new data to the end
       Array.Copy(progress.AuxSensorValues.SensorValuesP1, 0, SignalPiezo1, BufferActualSize - 1, arraySize);
 }
```
 
 What do you think?

**Comment by blahetal** [comment]
I needed and implemented something similar to what bukkideme posted. To sum it up, I had to deal with
- keeping all the data I wanted to chart (limited to a specific amount)
- dropping old data when new data arrives when the storage buffer for the chart was full
- setting up a timer to trigger chart refresh (new data arrive faster then the timer tick inteval)
- autoscrolling the chart so the new data point is visible in case user DID NOT zoomed or panned the chart (when the chart is zoomed/panned and the chart is refreshed I wanted to keep the visible part of the chart in focus)

As bukkideme pointed out, array copying when a new data point is added might be time consuming and `ScottPlot` should handle it internaly in case of DataLogger chart.

**Comment by bukkideme** [comment]
> edit - just found this - https://github.com/royben/RealTimeGraphX/tree/master/RealTimeGraphX - it is no more updated but the demo looks nice

Interesting! As I see it uses a thread safe Concurrent Queue...

**Comment by Johann-Schmid** [comment]
Thx...for the ideas

**Comment by swharden** [comment]
I'm picking this issue up again 🚀 

I'll be experimenting by gutting the existing _Live Data_ demo and replacing it with a new plot type

![image](https://user-images.githubusercontent.com/4165489/232631822-4aac7a8f-cbe0-48c2-be4c-a184c2a050c4.png)

**Comment by bukkideme** [comment]
Hi!

I wonder what will be your data handling strategy to avoid infinite data grow in memory? Will you add option to limit the data stored? For example if the user can set a limit N to define a buffer size, and a FIFO behaviour is used. So the oldest data gets deleted as new data chunks are coming in.
Maybe the frequency of the old data deletion could be optimized too, it is not performant to check for size and delete at high rate...
What do you think?

**Comment by swharden** [comment]
To get started I'm exploring supporting 3 major view modes over in #2599:

* **Full** - the entire data range is always in view
* **Latest N points** - the latest N points are always in view
* **N-point sweeps** - updates appear overlapping from left to right like an ECG machine

> what will be your data handling strategy to avoid infinite data grow in memory?

I hadn't thought about it before you mentioned it, but a `MaximumPointsInMemory` property could set this limit, shifting old data out as new data shifts in. I'll keep this on the list of possible features to addd!

**Comment by bukkideme** [comment]
> > what will be your data handling strategy to avoid infinite data grow in memory?
> 
> I hadn't thought about it before you mentioned it, but a `MaximumPointsInMemory` property could set this limit, shifting old data out as new data shifts in. I'll keep this on the list of possible features to addd!

Nice! Thank you! I think an option to limit the maximum data size is very important. If you let your program run for long time, you will get your RAM full earlier or later...

**Comment by codygray** [comment]
What a coincidence. I need exactly this: a real-time scatter/signal plot for data streaming in "real-time" from multiple sensor channels. The big challenge for me is that the sampling rate for each sensor can be up to 30,000 samples per second, and there may be up to 32 channels, so it's a *staggering* amount of data to deal with. I found ScottPlot, was impressed by its maturity and feature set, and decided to evaluate it for use in this case, following the "Live Data" demo/sample that you mentioned.

Of course, the other big challenge for me is that I do all of my development in C++, partially out of choice/preference but also because I now have a base of other libraries that I depend upon, so switching to C# is not really a compelling option. Therefore, I've been working on implementing this in C++/CLI, using ScottPlot for WinForms.

I (finally&mdash;C++/CLI is a pain) have a prototype up-and-running now. Basically, what I did is allocate a jagged array, where I have one array for each sensor/plottable, and each of those arrays is long enough to display N data sets on the screen at one time. (This is your "Latest N points" view mode.) Then, I basically just treat those arrays like circular/ring buffers, updating and shifting the data within them as new data sets come in.

I won't bother sharing code, because I don't think it'll help, given that it's in a weird mix of C++ and C++/CLI, but I will try to describe how it works in a bit more detail. Basically, in the constructor, I pre-allocate the arrays, which work just like standard jagged arrays in C#. Then, I set up the plot, configuring the parameters that will stay constant, and adding enough `SignalPlot`s to cover the total number of sensor channels. At this point, initially, the `MaxRenderIndex` is set to 0 for each plottable.

As new sets of data come in (basically akin to your timer ticks in the sample), I loop through each of the channels/arrays/plottables, updating each, one at a time. For each:

 - Check to see if we've filled the entire plot data buffer. In other words, if we've accumulated N sets of data, based on the pre-allocated maximum size of the array. If so, then I shift all of the data sets in the array over by one set, effectively removing the left-most (earliest) data set in the array. I settled on doing this with `System.Buffer.BlockCopy`, which seems pretty efficient. (There are more efficient ways of doing this in C++, but I'm using a .NET array for compatibility with ScottPlot, so I'm forced to stick with .NET ways of moving data around within the array.)
 - Then, I copy the new (incoming) data set into the end of the plot data buffer. I'm using `Marshal.Copy` for this, since I need to move the data from the unmanaged C++ world into the managed .NET world.
 - Finally, I adjust the plot settings&mdash;specifically, the `MaxRenderIndex`.

After that's been done for each of the channels/arrays/plottables, I `Refresh` the entire plot control.

This strategy has worked, and it's allowed me to get reasonably good performance with a sampling rate of up to 1,000 samples per second, but I can't go much faster than that, nor can I display too many sets of data in the plot at a time. I assume because that's just too many pixels for the plot to have to, well, plot. :-)

The major optimizations that I can see room for here are:

 - Being able to use a proper circular/ring buffer as the source of data for the plot. This would mean that I don't have to keep copying/shuffling data around within the plot data buffers continuously as new data is received. Unfortunately, the humble array built into .NET doesn't support anything like this. In my native C++ world, I can just move pointers into the array around, resulting in a very efficient implementation for a circular buffer. But I can't see how to do that with ScottPlot at this point. I was a .NET programmer over a decade ago, but I've forgotten most of what I used to know. Still, I have an inkling that adding a layer of indirection here, where the client can more directly control the source of the data buffer (i.e., where ScottPlot reads its data from) would give an efficiency boost.

 - Somehow reducing the number of pixels that the plot control needs to handle, perhaps by only plotting every N points in the array. (Maybe this is how the "SampleRate" parameter works? I'm not sure. That's not particularly well documented, and I haven't gotten around to investigating it yet.)

I haven't even thought about how I would implement the "Full" view mode... Even at a low sampling rate of 1k samples per second, with 32 sensor channels, that's 32k data points per second. That gets unwieldy really fast. How are you planning to deal with this? Not so much the memory pressure (although that's certainly a concern, too), but more importantly, the sheer amount of pixels that need to be plotted. Are you thinking of some kind of caching optimization, where it only redraws the data from the end of the array that has actually been updated?

I'm very interested to see what else you've done in building a `DataLogger` plot type, and I'd be happy to help discussing some ideas/strategies.

**Comment by swharden** [comment]
Hi @codygray, thank you for your extensive comment! I won't respond to everything yet, but I'll note some thoughts I've had and some recent progress.

## No single plot type can meet the needs of all use cases

It may be obvious, but I'll state that it is not possible to create one plot type that will solve everybody's data needs.

* Some use cases benefit from **simplicity**
* Some use cases benefit from **performance**
* Some use cases benefit from **flexible DataTypes**

I think I will lean toward developing my datalogger classes with the first goal in mind (simplicity), knowing that I cannot meet the use-case-specific needs of those who desire to maximize performance or use special data types.

The `ScatterDataLogger` I recently added in #2599 is not highly performant for large datasets, but it accepts arbitrary X/Y pairs and demonstrates some of the concepts I am trying to achieve. Screenshots are below.

I intend to create a `SignalDataLogger` which will use some of these concepts but use the rendering mechanism signal plots use to render fixed-spaced Y data. Maximum performance may be achieved using fixed-length arrays, meaning the "full" or "growing" data logger is not appropriate, but the sweep and scroll modes could be supported and may be highly performant.

At some point I'll try to add multi-channel support by creating a `DataChannel` class and allow these data logger plot types to maintain a `List<DataChannel>`

## DataLogger Views

Not every DataLogger plot type will support every view type, but I'm converging on the following terms to describe the common behaviors I'd like to support.

### Full

The "full" mode grows infinitely and is good for low sample rate data like a temperature sensor or something. I'm using `List<Coordinate>` to hold the data.

![datalogger-full](https://github.com/ScottPlot/ScottPlot/assets/4165489/395a9804-53e9-4107-af5f-cf29fba0ee10)

### Scroll

Scrolling views appear to shift data in the right side of the chart. Notice that the horizontal axis changes as new data comes in. Fixed length arrays could be use to hold this data, and shifting in memory would not be required.

![datalogger-scroll](https://github.com/ScottPlot/ScottPlot/assets/4165489/8470a065-ac38-4fbd-9826-b1b9e53f84f5)

### Sweep

Sweeping updates data form left to right. There's an alternate view (not shown) where the new data "erases" old data as it comes in (like an ECG machine) so at some points in time you can see new data on the left and old data on the right. A configuration flag could indicate whether or not to update the horizontal axis.

![datalogger-sweep](https://github.com/ScottPlot/ScottPlot/assets/4165489/3e5a6edd-b52a-4999-889f-62725ccc53ff)

### Custom Types and High Performance

My thinking is that by making these simple plot types, users can copy-and-modify the code to support their specific use cases.

I'll keep this issue open and continue working on this topic as one of my highest priorities!

**Comment by heartacker** [comment]
I think we should add another type, `RollFixed`
- [x] Full
- [x] Scroll
- [x] Sweep
- [ ] RollFixed

![a](https://scottplot.net/faq/live-data/src/RollFixedSignal-WinForms/screenshot.gif)

**Comment by swharden** [comment]
Thanks for reminding me of that view!

I'll probably call it "Scroll" or "Wipe". 

I'll create a new PR to add it now...

**Comment by swharden** [comment]
Actually, the "wipe" view only works for fixed-length data (not growing data), so it will probably require its own plot type... `ScatterPlotFixedLength` or something. It would accept a sample rate and Y data only, not X/Y pairs

**Comment by blahetal** [comment]
What about FullScroll - Full displays all data in one view and Scroll displays latest x points (old points that do not fit in the view are thrown away, right?). FullScroll would display latest x points but user can scroll the view to see older points (all points would be kept).

**Comment by swharden** [comment]
> What about FullScroll ... displays latest x points ... but user can scroll the view to see older points (all points would be kept)

> old points that do not fit in the view are thrown away, right?

Actually, the implementation that's in the demo app now supports this behavior. All the data is there (and the user could zoom out to see it), but the view is automatically shifted to focus on the latest data.

I'll make this more obvious by adding a checkbox to toggle the "auto focus on latest data" feature on and off.

**Comment by swharden** [comment]
Updated the WinForms DataLogger demo (#2640)

![automatic-view](https://github.com/ScottPlot/ScottPlot/assets/4165489/a4ccd042-84c0-4a91-b8dd-e305f9d3296f)

Still working on the "wipe" view...

**Comment by heartacker** [comment]
> Actually, the "wipe" view only works for fixed-length data (not growing data), so it will probably require its own plot type... or something. It would accept a sample rate and Y data only, not X/Y pairs`SignalPlotFixedLength`

now, I think we can render latest data using a `Window`.

![image](https://github.com/ScottPlot/ScottPlot/assets/1876302/30dc3541-fce6-49c5-970c-5bd8c1ec3b83)

**Comment by swharden** [comment]
I think we're converging on a solution! The major modes are now:

Full | Slide (smooth) | Slide (jump) | Wipe
---|---|---|---
![datalogger-full](https://github.com/ScottPlot/ScottPlot/assets/4165489/395a9804-53e9-4107-af5f-cf29fba0ee10)|![datalogger-scroll](https://github.com/ScottPlot/ScottPlot/assets/4165489/8470a065-ac38-4fbd-9826-b1b9e53f84f5)|![datalogger-sweep](https://github.com/ScottPlot/ScottPlot/assets/4165489/3e5a6edd-b52a-4999-889f-62725ccc53ff)|![window](https://github.com/ScottPlot/ScottPlot/assets/4165489/e30afe09-5bcb-47fd-b2fc-382f8a368e97)

Note that all all support X/Y data points except for Wipe which only use Y data points and a `SamplePeriod`. I'm rendering everything with connecting lines like a scatter plot, but the Wipe mode could be implemented using a signal plot.

**Comment by heartacker** [comment]
`Wipe` is very useful, And I think user will have the fixed Y-axis Like ECG

**Comment by prime167** [comment]
Wipe is what I'm looking for. Thank you.

Can we have a static and reverse x axis like taskmanager? After all, we set ViewWidth in code, and we know they are last N points, the moving x axis ticks is somewhat distracting.
![image](https://github.com/ScottPlot/ScottPlot/assets/3722845/2ddbb0f6-2c41-4832-be90-23973eff760f)

**Comment by swharden** [comment]
Good ideas! The running list of views to support for growing data is now:

### Views that update their axis limits:
* Full (continuously shows all data)
* Slide (focuses on latest data, continuous smooth scrolling)
* Slide (focuses on latest data, moving view only when new data goes off the screen) 

### Views with axis limits that do not move:
* ShiftRight (data shifts in left-to-right)
* ShiftLeft (data shifts in left-to-right, like task manager)
* Wipe (new data overlaps old data left-to-right, like ECG)

**Comment by swharden** [comment]
This task turned out to be MUCH larger than I initially intended! It took several weeks of experimenting, but I eventually landed on an API which I think solves most use cases and should be easy to extend to achieve custom behavior or performance goals.

I'm going to close this issue when I merge #2641 tonight, and will push all this to NuGet within the next few days. All are welcome to give it a try and offer suggestions! I'm happy to make breaking changes to this API while the plot type is still new, and what we learn here we can apply to ScottPlot 5 🚀 

## DataLogger
- For logging infinitely growing points.
- This is a scatter plot and points are X/Y pairs.
- Old data is not deleted as new data is added.
- Can display all data, or automatically adjust axis limits to focus on the latest N points.
- Views include: `full`, `jump`, and `slide`

![DataLogger](https://github.com/ScottPlot/ScottPlot/assets/4165489/72217d01-0645-4858-b5cc-21ea632a5ad3)

## DataStreamer
- For displaying the latest N values of a live data source.
- This is a signal plot with evenly-spaced X values.
- New data overwrites old data using a circular buffer.
- Views include: `wipe` and `scroll` (with left/right options for each)

![DataStreamer](https://github.com/ScottPlot/ScottPlot/assets/4165489/d0b12338-3e90-4e54-8abb-80f6cc6e5633)

**Comment by swharden** [comment]
Took a while but I finally added this to the FAQ page:
https://scottplot.net/faq/live-data/

**Comment by xiaomuwing** [comment]
masterpiece!
I use IMC DATA API curve component to serve 100K per sec and above. it builds a cache file on hard disk first to fill data, like Microsoft FAST.

**Comment by Diddlik** [comment]
Is it possible to fill the chart below the line?

**Comment by swharden** [comment]
> Is it possible to fill the chart below the line?

Not yet, but perhaps #3380 will add this feature 👍
