### ISSUE TITLE
LineWidth is floored to an int

### ISSUE THREAD

**Issue by ImpulseDeer** [ScottPlot/ScottPlot#2407]
## Bug Report

**Issue:** 
Setting the LineWidth to a fractal value such as 1.5 will yield a actually rendered line width of 1. 2.3 -> 2 etc etc.

There are a confusing variation of types here.
AddScatter and AddScatterLines takes a float for the lineWidth.
The LineWidth public property is a double.

And the off-course as the issue reports, the actual used value is a int.
A bit confusing and a bummer as I had loved to use a LineWidth somewhere between 1 (to thin => renders as a lighter color with AA) and 2 (to thick for the data I want to display).

**Reproducing:** (What do others have to do to reproduce the bug?)

```cs
// a code sample may improve communication
var examplePlot = new ScottPlot.Plot();

examplePlot.AddScatter(x, y, color, 1.5);
```
Yields a plot with line width 1.

### System Details
* **ScottPlot Version:** 4.1.60
* **Operating System:** Windows 10
* **Application Type:** WPF
* **.NET Version:** .NET 6.0

**Comment by bclehmann** [comment]
We're not actually rounding to ints (at least not in ScatterPlots where I checked), it's up to our graphics library (System.Drawing) to decide how it treats fractional pen widths. I would hope that it would treat non-integer widths as a hint when anti-aliasing, but it's entirely possible that they just allow fractional widths for better upscaling or something obscure like making pre-multiplied pen tips easier to use.

I would make sure that you have requested anti-aliasing correctly (see [here](https://scottplot.net/faq/anti-aliasing/)) but if so I think this is just another instance of System.Drawing being a little disappointing. This is also something that might differ on Linux and MacOS since they use a different implementation of GDI+ (which is what System.Drawing is based on).

Hopefully this isn't an issue with SkiaSharp, which is what version 5 will be using instead.

**Comment by ImpulseDeer** [comment]
I have AA settings set to:
Configuration.Quality = ScottPlot.Control.QualityMode.High;

Tried ScottPlot5 and it works as expected there:
![Scottplot5 LineWidth](https://user-images.githubusercontent.com/111496869/220303589-09b39c30-def2-4aaa-a0ff-f5efb60b160b.png)

So probably a System.Drawing problem as you say. I will just patiently wait for ScottPlot5 for this to be resolved then.

Thank you for a very nice, fast plotting lib!
