### ISSUE TITLE
Avalonia quickstart does not perform as expected

### ISSUE THREAD

**Issue by Resonanz** [ScottPlot/ScottPlot#2414]
Following the "Quickstart" instructions, it took about 5 seconds to get the WPF Quickstart working.

But I cannot for the life of me get the Avalonia demo to work.

NuGet package installs fine.
`this.Find` in the .cs fails

This has wiggly underlines: 
```xaml
<ScottPlot:AvaPlot Name="AvaPlot1"/>
```

Not sure if the Quickstart code is out of date?

**Comment by swharden** [comment]
Hi @Resonanz, thanks for reporting this!

@bclehmann do you have any quick thoughts on this?

https://scottplot.net/quickstart/avalonia/

https://github.com/scottplot/scottplot.net/blob/main/content/quickstart/avalonia/index.md

**Comment by swharden** [comment]
@Resonanz, can you share the whole content of your XAML file? Is it possible that [step 2](https://scottplot.net/quickstart/avalonia/) was skipped by accident?

**Comment by Resonanz** [comment]
Steps:

1. Create new project > Avalonia application (Avalonia client application)
3. Install NuGet Scottplot.Avalonia 4.1.60
4. Steps 3 and 4 code shown below. 

If I change `this.Find` to `this.AvaPlot1.Find` then `this` is no longer wiggly underlined.

If I change `internal class Program` to `internal partial class Program` then `Program` is no longer wiggly underlined.



```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
		xmlns:ScottPlot="clr-namespace:ScottPlot.Avalonia;assembly=ScottPlot.Avalonia"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaTestForScottplot.Program"
        Title="AvaloniaTestForScottplot" Width="500" Height="350">
    Welcome to Avalonia!
	<ScottPlot:AvaPlot Name="AvaPlot1"/>

</Window>
```



```using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.ApplicationLifetimes;
using ScottPlot.Avalonia;
using System;

namespace AvaloniaTestForScottplot
{
    internal class Program
    {
        // Initialization code. Don't use any Avalonia, third-party APIs or any
        // SynchronizationContext-reliant code before AppMain is called: things aren't initialized
        // yet and stuff might break.
        [STAThread]
        public static void Main(string[] args) => BuildAvaloniaApp()
            .StartWithClassicDesktopLifetime(args);

        // Avalonia configuration, don't remove; also used by visual designer.
        public static AppBuilder BuildAvaloniaApp()
            => AppBuilder.Configure<App>()
                .UsePlatformDetect()
                .LogToTrace();


        public void SomeMethod()
        {
            double[] dataX = new double[] { 1, 2, 3, 4, 5 };
            double[] dataY = new double[] { 1, 4, 9, 16, 25 };

            AvaPlot avaPlot1 = this.Find<AvaPlot>("AvaPlot1");
            avaPlot1.Plot.AddScatter(dataX, dataY);
            avaPlot1.Refresh();
        }

    }
}
```

**Comment by bclehmann** [comment]
This line:
```xml
x:Class="AvaloniaTestForScottplot.Program"
```

Is not valid, the associated class for an Avalonia window has to inherit from [`Avalonia.Controls.Window`](https://reference.avaloniaui.net/api/Avalonia.Controls/Window/), but the class you specified just looks like your program entrypoint.

If you're using Visual Studio (and you have the Avalonia extensions installed) you should have the option to make a new blank Avalonia window through the same dialogs you would make a class through. This should create 2 files, a xaml file called `NewWindow.axaml` and a C# file called `NewWindow.axaml.cs`

**Comment by swharden** [comment]
>  `internal class Program`

> class for an Avalonia window has to inherit from [Avalonia.Controls.Window](https://reference.avaloniaui.net/api/Avalonia.Controls/Window/)

Thanks for the clarification @bclehmann! I think this is sufficient to mark this issue as closed, but below are some ideas which could make this easier for future users.

Do you think additional information should be added to the Avalonia quickstart page to make this more clear? 
* https://scottplot.net/quickstart/avalonia/
* https://github.com/scottplot/scottplot.net/blob/main/content/quickstart/avalonia/index.md

I also see there's not an Avalonia sandbox, but having something simple there may be something we can point to to help others get started
* https://github.com/ScottPlot/ScottPlot/tree/main/src/ScottPlot4/ScottPlot.Sandbox

**Comment by Resonanz** [comment]
Thanks for your comments. I'm sorry that I don't understand XAML well enough to understand your answers.

First question is: what sort of project should I be making in VS? Avalonia? WPF? Blank?

Once the project is open, and NuGet packages are installed, then I think I can access the blank Avalonia window thru the Add... option. But why would I do that? Avalonia is a project type that can be selected when creating a new project.

The WPF Quickstart is simple and works, but the Avalonia one could do with some clarifications :-)

The "this" issue... perhaps that will go away if the window inherits from `Avalonia.Controls.Window` however it didn't work for me.

The new files are named `Window1.axaml` and `Window1.axaml.cs` btw.

**Comment by bclehmann** [comment]
> what sort of project should I be making in VS? Avalonia? WPF? Blank?

Avalonia, the project template you use should match what you're making. If you want to make a WPF app you use the WPF template, if you want to make an Avalonia app you use the Avalonia template.

> I think I can access the blank Avalonia window thru the Add... option. But why would I do that? Avalonia is a project type that can be selected when creating a new project.

Avalonia projects have at least one window. The project template will create a project with one window (MainWindow.axaml and MainWindow.axaml.cs). If you still have those files feel free to place the ScottPlot control in the main window, I bring up window creation because it looks like you tried to create a window but something went wrong.

> The "this" issue... perhaps that will go away if the window inherits from Avalonia.Controls.Window however it didn't work for me.

Turning `Program` into a subclass of `Window` is not enough, it's still not a valid window because Avalonia windows need to call `AvaloniaXamlLoader.Load(this)` in their constructors. It may get rid of the errors you saw but the application will not work at runtime. This is taken care of for you if you create a window from the template.

> The WPF Quickstart is simple and works, but the Avalonia one could do with some clarifications :-)

It's interesting that you mentioned the WPF quickstart, since the two frameworks are incredibly similar (to the point that copy-pasted WPF code often "just works" in Avalonia). Hence the two quickstarts are basically the same except for when the Avalonia quickstart needs to bring up namespaces.

In any case, your problem doesn't seem to be "how do I add ScottPlot to my Avalonia project" so much as it is "how do I create an Avalonia project" since the issues you're running into aren't really related to ScottPlot. I would probably suggest copying this [directory](https://github.com/bclehmann/Website/tree/main/src/quickstart/src/quickstart-avalonia) so you can jump ahead to actually working with ScottPlot and Avalonia. This is the source code for the quickstart, ripped from an old version of the ScottPlot website because I can't find it on the new one.
