### ISSUE TITLE
Recommended use of Clipboard.SetText from FormsPlot event

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#2478]
Hi!
I realized I get thread exception if I use Clipboard.SetText() method directly from my FormsPlot event. I have found a workaround shown below, it works. I wonder, is this the proper solution in this case?
Thanks! :)

```cs
private void formsPlot1_KeyUp(object sender, KeyEventArgs e)
{
    if (Control.ModifierKeys == Keys.Control && e.KeyCode == Keys.C)
    {
        (double mouseCoordX, double mouseCoordY) = formsPlot1.GetMouseCoordinates();
        string message = $"{mouseCoordX / 1000:F3}\t{mouseCoordY / 1000:F3}";
        Thread thread = new Thread(() => Clipboard.SetText(message));
        thread.SetApartmentState(ApartmentState.STA); //Set the thread to STA
        thread.Start();
        thread.Join(); //Wait for the thread to end                
    }
}
```

**Comment by swharden** [comment]
Whoa, this is something I've never experienced before!

It may help if you can copy/paste the exact exception to get along with the code that produced it.

I asked ChatGPT how to set clipboard text from inside a Windows Forms event and it gave me a wrong answer 😅 

I'll close this issue since it's outside the scope of plotting, but I'm interested in the answer so if you or someone else figures this out I'd appreciate a follow-up!

(also, maybe someone in the Discord has an idea? #1966)

**Comment by swharden** [comment]
Actually, this may be an alternate solution

https://stackoverflow.com/questions/930219/how-to-handle-a-blocked-clipboard-and-other-oddities

```cs
System.Windows.Forms.Clipboard.SetDataObject(
    "some text", // Text to store in clipboard
    false,       // Do not keep after our application exits
    5,           // Retry 5 times
    200);        // 200 ms delay between retries
```
