### ISSUE TITLE
Improve FormsPlot "open in new window" feature - what is the expected behaviour?

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#2493]
Hi!

I like the built-in feature that you can open a new window using right mouse click:
"open in new window".
I always thought when I do this, I get a deep clone of the data, an independent copy. However, I realized that if I change the data in the parent formsPlot, and I click inside the spawned child window, its data will be synced back to the original formsPlot. 
It is ok if this is the intended behavior, but other users might fall into this trap just like me :) Also, the user might not aware when and when not the data in the spawned window gets synced back. 
What about if we give two options to the user via this right click menu? 
I am not sure about what the proper naming could be, but we could have a "deep clone", which is totally independent of the parent formsPlot, without any data binding, and a "copy plot" option, working as now...

What do you think?

**Comment by swharden** [comment]
Hi @bukkideme, thanks for noting this!

There's presently no way to deep close a plot (there are so many little configuration settings that would have to be cloned), so the behavior you describe here is probably what will remain. 

Probably the best solution is to disable the default right-click menu, make your own, create your own launcher, and instead of showing the original `Plot` in the pop-up window, create your own from scratch that you show in the pop-up window (which could be mutated then discarded). It's a lot of work, but possible!
