### ISSUE TITLE
Add Custom GridLines SP5

### ISSUE THREAD

**Issue by GuiWolff** [ScottPlot/ScottPlot#2546]
How is it done to create and add horizontal and vertical lines in ScottPlot 5?

**Comment by swharden** [comment]
Hi @GuiWolff! I appreciate your question, but the preview version of ScottPlot 5 is not intended to be used yet and although this may be possible it is intentionally undocumented since it is still being worked on and its API may change. 

https://scottplot.net/versions/

I recommend using ScottPlot 4 for all tasks - it's extremely stable, mature, customizable, and extensively documented 👍 

https://scottplot.net/cookbook/4.1/category/axis-and-ticks/#grid-style
