### ISSUE TITLE
ScottPlot5: Support legend alignment

### ISSUE THREAD

**Issue by chhh** [ScottPlot/ScottPlot#2584]
## Bug Report

**Issue:**
Plotting off-screen, setting legend location with `plt.GetLegend().Alignment` seems to have no effect.

**Reproducing:**
```csharp
double[] xData = Enumerable.Range(0, 10).Select(x => x * 0.1).ToArray();
double[] yData = Enumerable.Range(0, 10).Select(x => x * 0.1).ToArray();
Plot plt = new ScottPlot.Plot() { };
Scatter scatter = plt.Add.Scatter(xData, yData);
s1.Label = "Plot 1";
plt.GetLegend().Alignment = Alignment.UpperRight;
plt.SavePng("test.png", 640, 480);
```
Sample from an actual plot I was making, `UpperRight` (or any other location) didn't help moving the legend.
![test](https://user-images.githubusercontent.com/107902/231059766-9bcf04fa-a147-460d-8e7c-777b88df1412.png)

### System Details
* **ScottPlot Version:** 5.0.2-beta
* **Operating System:** Win10
* **Application Type:** console
* **.NET Version:** NET 6.0

**Comment by swharden** [comment]
Thanks for reporting this @chhh!

The bug is caused by a hard-coded alignment here:

https://github.com/ScottPlot/ScottPlot/blob/5e32c265485405afaa6fbb0152b263702f59b18d/src/ScottPlot5/ScottPlot5/Legends/StandardLegend.cs#L48

The solution would be to expose a public `Alignment` property and use it in that spot.

If you (or someone else) wants to open a PR to make this change, I'll be happy to review it and merge in good time! Otherwise it may take me a little while to get to as I'm currently prioritizing clearing out the ScottPlot version 4 backlog.
