### ISSUE TITLE
SP4 Bar plot: groups display incorrectly for horizontal bars

### ISSUE THREAD

**Issue by Rayffer** [ScottPlot/ScottPlot#2615]
## Bug Report

**Issue:** 
When setting the orientation of bar groups to horizontal, when rendering, the axis are not correctly displayed, what would be the labels remain on the X axis and the values remain on the Y axis.

**Reproducing:** 

1. Use the wpf.Plot.AddBarGroups with the correct parameters so an array of BarPlot is created.
2. Change the orientation to horizontal
3. Observe axis are not correctly set

```cs
wpfPlot.Plot.Clear();
wpfPlot.Plot.Title(title);
var barGroupsPlot = wpfPlot.Plot.AddBarGroups(series, partyEntityNames, values, null);

foreach (var plot in barGroupsPlot)
{
  plot.BorderLineWidth = 0F;
  plot.Orientation = ScottPlot.Orientation.Horizontal;
}

wpfPlot.Plot.Legend(location: Alignment.UpperRight);

var xAxis = wpfPlot.Plot.XAxis;
var yAxis = wpfPlot.Plot.YAxis;

var yMax = values.Max(value => value.Max());
wpfPlot.Plot.SetAxisLimitsY(0, yMax == 0 ? 1 : yMax);
wpfPlot.Render();
```

### System Details
* **ScottPlot Version:** 4.1.63?
* **Operating System:** Windows 10
* **Application Type:** WPF
* **.NET Version:** .NET 7.0

**Comment by Rayffer** [comment]
![imagen](https://user-images.githubusercontent.com/34773204/236639557-d614ebf8-9602-4e2e-ab5a-1513f0c35963.png)

Example of the problem

**Comment by swharden** [comment]
Hi @Rayffer! Wow it took me a while to get back to you on this one 😅 

This should do it

```cs
// fix tick labels
plt.XAxis.AutomaticTickPositions();
plt.YAxis.ManualTickPositions(ScottPlot.DataGen.Consecutive(groupNames.Length), groupNames);
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/4a8cfca0-9aa8-4aa1-a148-96dac97e90c3)

full code:
```cs
var plt = new ScottPlot.Plot(400, 300);

// generate random data to plot
int groupCount = 5;
Random rand = new(0);
double[] values1 = ScottPlot.DataGen.RandomNormal(rand, groupCount, 20, 5);
double[] values2 = ScottPlot.DataGen.RandomNormal(rand, groupCount, 20, 5);
double[] values3 = ScottPlot.DataGen.RandomNormal(rand, groupCount, 20, 5);
double[] errors1 = ScottPlot.DataGen.RandomNormal(rand, groupCount, 5, 2);
double[] errors2 = ScottPlot.DataGen.RandomNormal(rand, groupCount, 5, 2);
double[] errors3 = ScottPlot.DataGen.RandomNormal(rand, groupCount, 5, 2);

// group all data together
string[] groupNames = { "Group A", "Group B", "Group C", "Group D", "Group E" };
string[] seriesNames = { "Series 1", "Series 2", "Series 3" };
double[][] valuesBySeries = { values1, values2, values3 };
double[][] errorsBySeries = { errors1, errors2, errors3 };

// add the grouped bar plots and show a legend
var barPlots = plt.AddBarGroups(groupNames, seriesNames, valuesBySeries, errorsBySeries);

// make bars horizontal
foreach (var barPlot in barPlots)
{
    barPlot.Orientation = ScottPlot.Orientation.Horizontal;
}

// fix tick labels
plt.XAxis.AutomaticTickPositions();
plt.YAxis.ManualTickPositions(ScottPlot.DataGen.Consecutive(groupNames.Length), groupNames);

plt.Legend(location: ScottPlot.Alignment.UpperRight);
plt.SaveFig("demo.png");
```

**Comment by LieslH** [comment]
This was really helpful, thank you! And thank you for the really great plotting tool!

One slight change I wanted to the above was to have the y-axis labels in line with the middle of the bar group rather than in line with the bottom bar in the group. The following works (using your above lines and adding a few extra things to match how it was done in `AddBarGroups` for the vertical bar chart):

`plt.XAxis.AutomaticTickPositions();`
`double groupWidthFraction = 0.8;`
`int seriesCount = valuesBySeries.Length;`
`double barWidth = groupWidthFraction / seriesCount;`
`plt.YAxis.ManualTickPositions(ScottPlot.DataGen.Consecutive(groupNames.Length, offset: (groupWidthFraction - barWidth) / 2), groupNames);`

Is there a better way to do it though?

Also, is there a way to move the legend outside of the plot area to avoid covering up the bars? I am currently just setting the xMax to a number higher than the maximum x value but there is then a large space underneath the legend.

**Comment by swharden** [comment]
> Is there a better way to do it though?

I think your way is probably the best

> is there a way to move the legend outside of the plot area

Yeah, you can use formsPlot1.Plot.GetLegendBitmap() to get the legend image and display it somewhere else in your form that's not inside the plot control

Hope it helps! 🚀

**Comment by LieslH** [comment]
Thank you for your quick response! I will give that a try.

**Comment by Rayffer** [comment]
Github did not notify me of your answer @swharden, thanks for investing your time to answer me!
