### ISSUE TITLE
scatterPlot has NAN gap，AddFillAboveAndBelow has problem

### ISSUE THREAD

**Issue by tomuGo** [ScottPlot/ScottPlot#2619]
## Bug Report

**Issue:**    scatterPlot has NAN gap，AddFillAboveAndBelow has problem.can make the NAN area  transparent?

**Reproducing:** (What do others have to do to reproduce the bug?)

```cs
using System;
using System.Drawing;
using System.Windows;
using ScottPlot;
using ScottPlot.Plottable;

namespace sleep_monkey.View.Charts
{
    public partial class PoltTest : Window
    {
        public PoltTest()
        {
            InitializeComponent();
            WpfPlot _wpfPlot = new();
            ChartGrid.Children.Add(_wpfPlot);
            double[] xs = ScottPlot.DataGen.Consecutive(51);
            double[] ys = ScottPlot.DataGen.Sin(51);
            for (int i = 10;i<=20;i++) {
                ys[i] = Double.NaN;
            }
            var scatter = _wpfPlot.Plot.AddScatter(xs, ys, markerShape: MarkerShape.none);
            scatter.OnNaN = ScatterPlot.NanBehavior.Gap;
            _wpfPlot.Plot.AddFillAboveAndBelow(xs, ys, 0, colorAbove: Color.Brown, colorBelow: Color.Blue);
            _wpfPlot.Dispatcher.Invoke(() => { _wpfPlot.Refresh(); });
        }
    }
}
```
![image](https://github.com/ScottPlot/ScottPlot/assets/24789356/eed2824e-035e-43fe-9445-b88e064cc8b5)

### System Details
* **ScottPlot Version:**  4.1.60
* **Operating System:**  win11
* **Application Type:**  wpf
* **.NET Version:**  net6

**Comment by swharden** [comment]
Hi @tomuGo, thanks for reporting this!

Note that some additional tips about plotting data containing `double.NaN` can be found here: https://scottplot.net/faq/nan/

Regarding the shading, I don't think there is a simple way to fix this problem. I think the best available option is to write a function that replaces `double.NaN` with `0`, but even then the result may be unsatisfying because the shaded area may slope toward zero.

An alternative solution is to write some more logic on your side to draw sharp edges where `double.NaN` values are and create a polygon instead of a scatter plot: https://scottplot.net/cookbook/4.1/category/plottable-polygon/

Sorry I don't have a simpler solution, but I hope this helps!
