### ISSUE TITLE
AxisTicks: custom label tick with default one

### ISSUE THREAD

**Issue by Alexander778** [ScottPlot/ScottPlot#2644]
**ScottPlot Version:** 4.1.64

**Operating System:** Windows

**Application Type:** Console (.NET 6/ .NET 7)

**Question:** Hello. Could you please tell if it's possible to render/configurate custom labels with default one? I fully reviewed FAQ and Cookbook page, but didn't find anything related. Thanks.

If I missed an example from CookBook or something, please show me.

![image](https://github.com/ScottPlot/ScottPlot/assets/29919352/90c91d5b-2f83-492f-bd0a-c394a2ee722d)

![image](https://github.com/ScottPlot/ScottPlot/assets/29919352/97f5a56a-0d94-45b6-9ef5-e3e9f08f71c9)

**Comment by swharden** [comment]
Hi @Alexander778, I don't think there is anything built in that can do this exactly, but there's something that's pretty close and you can edit it to achieve this goal if you like.

Check out the labeled axis line. it shows how to place labels in the axis area (outside the plot area):

https://scottplot.net/cookbook/4.1/category/plottable-axis-line-and-span/#position-labels

https://github.com/ScottPlot/ScottPlot/blob/14017d8f7d3f06114bba8e8d864f5eb2734daa37/src/ScottPlot4/ScottPlot/Plottable/AxisLine.cs#L189-L253

There's a lot of logic there because it has code blocks for drawing on all 4 sides of the plot, but your code can be simpler if oyu just intend to draw beneath the plot.

You can create a custom plot type using the code in that file as a reference. I bet you can remove ~80% of the code because that plot type has a lot of features you don't need (e.g., mouse interaction and ability to be dragged)

To create a custom plot type you can follow the guide here: https://scottplot.net/faq/custom-plot-type/

If you end up creating this plot type and it looks good, feel free to share its code here or create a pull request and we can add it to ScottPlot so it's available for others to use too! 🚀
