### ISSUE TITLE
Draggable issue

### ISSUE THREAD

**Issue by iannChen** [ScottPlot/ScottPlot#2680]
**ScottPlot Version:** ???  v4.0

**Operating System:** ???  win10

**Application Type:** (console, WinForms, WPF, etc...)  Winform

**Question:** Describe your question here

Hi Scott,

1. Is there any solution to avoid tap the draggable text after zoom in?
2. Is it possible that draggable Vline can tap drag from the label?

Thanks

https://github.com/ScottPlot/ScottPlot/assets/108121261/675c9f4c-7a7b-4016-81b9-1a2cef7d6f1c

Images or screenshots often help communication and are encouraged. You can copy/paste or drag/drop images into this box.

**Comment by swharden** [comment]
Hi @iannChen, here is some code which demonstrates the effect you are seeking but fails to recreate the issue described above. Maybe this is sufficient to solve your problem? Feel free to re-open this issue if you can share a code sample that helps us recreate the problem.

![drag](https://github.com/ScottPlot/ScottPlot/assets/4165489/fd7724bc-a2ca-4973-a18c-447b5ce6d526)

```cs
public Form1()
{
    InitializeComponent();

    Random rand = new(0);
    for (int i = 0; i < 10; i++)
    {
        double x = rand.NextDouble();
        double y = rand.NextDouble();

        // add a marker
        var pt = formsPlot1.Plot.AddPoint(x, y);

        // add a label to the marker
        var txt = formsPlot1.Plot.AddText($"test {i + 1}", x, y);
        txt.DragEnabled = true;
        txt.FontSize = 22;
        txt.Color = pt.Color;

        // move the marker when the text is dragged
        txt.Dragged += (s, e) => { pt.X = txt.X; pt.Y = txt.Y; };

        // move crosshairs to track the first point
        if (i == 0)
        {
            var cross = formsPlot1.Plot.AddCrosshair(x, y);
            cross.Color = pt.Color;
            txt.Dragged += (s, e) => { cross.X = txt.X; cross.Y = txt.Y; };
        }
    }

    formsPlot1.Refresh();
}
```

PS: There's a chance your issue relates to display scaling. If you disable display scaling, is your problem fixed? If so, this issue is a problem with the automatic display scaling detection and it's worth re-opening this issue so we can look  further into it.
