### ISSUE TITLE
Index of dragged point in the ScatterPlotDraggable

### ISSUE THREAD

**Issue by mocakturk** [ScottPlot/ScottPlot#2682]
**ScottPlot Version:** 4.1.64

**Operating System:** Win10

**Application Type:** WinForms

**Question:** _IDraggable_ interface contains **Dragged** and **DragSnap** possibility to fix the coordinate of the dragged point.
However, it is not possible to know dragged point's index.

```cs
public Coordinate Snap(Coordinate value)
{
    // "value" is the coordinate after dragging
    // what is the index of this coordinate inside whole plot?
    // or, what is the coordinate before dragging?
    ...
}
```

I'm using **ScatterPlotListDraggable** as Plot type.
When I check ScatterPlotListDraggable class, I can see the dragged index as private variable.
```cs
private int IndexUnderMouse { get; set; } = -1;
```
Perhaps, it can be public.

Thanks for this awesome library.
Murat

**Comment by sopgenorth** [comment]
I think it'd also be great to get the index from a Draggable (like a marker and vertical line). It looks like it was removed in the deprecation/transition done by #2038  Previously I was using this to sync two Draggable items on two separate plots with the Dragged event. 

I see that a SnapIndex was added in #2100, but the implementation is O(n), which is a bit unfortunate since it seems like it'd be information that could be had with O(1), and the previous usage with CurrentIndex seemed to do this. The below I put together in the move from an older ScottPlot library to the latest.

Here for example, there's a Draggable marker on the main XY plot, and then a Draggable vertical line on the bottom time based plot. The user might drag the XY marker around, where then the vertical line moves to stay in sync. Then similarly, dragging the vertical line, and moving the XY marker around so it stays in sync.
![scottPlot_dragging](https://github.com/ScottPlot/ScottPlot/assets/16996036/4cdc224d-23b6-42bb-8963-73110f1f1849)

Here's a snippet of the events I was trying to put together in my update of the ScottPlot library in my project:
    ```
// user moved the XY marker, move the time plot's vertical line to sync them
    private void XyMarkerOnDragged(object? sender, EventArgs e)
    {
        var marker = _xyMarker.DragSnap as Nearest2D;
        if (marker == null)
             return;

        _vTimeLine.X = marker.SnapIndex(new Coordinate(_xyMarker.X, _xyMarker.Y));

        WpfTimePlot.RenderRequest();
        WpfXYPlot.RenderRequest();
    }

    // user moved the time plot's vertical line, move the XY marker to sync them
    private void VTimeLineOnDragged(object? sender, EventArgs e)
    {
        // set positions directly to avoid triggering the marker's event
        _xyMarker.X = _xValues[(int)_vTimeLine.X];
        _xyMarker.Y = _yValues[(int)_vTimeLine.X];

        WpfTimePlot.RenderRequest();
        WpfXYPlot.RenderRequest();
    }
```

This works, but is a little slow with a decent amount of time spent in the for loop in the SnapIndex function.

**Comment by mocakturk** [comment]
Thx for suggestion. I will try that.

**Comment by bukkideme** [comment]
maybe beside the suggested new methods in https://github.com/ScottPlot/ScottPlot/pull/2711 we could also add methods to read out the index?

**Comment by swharden** [comment]
There's a lot of good discussion here! I'll keep my comments focused narrowly at the original issue:

> However, it is not possible to know dragged point's index.

> `private int IndexUnderMouse { get; set; } = -1;`
> Perhaps, it can be public.

I'll make this public, then when the `Dragged` event fires it will still contain the index of the item which was most recently interacted with. It's not elegant, but it's a non-breaking solution.
