### ISSUE TITLE
is this possible to render sequence chart/analog sequence chart

### ISSUE THREAD

**Issue by heartacker** [ScottPlot/ScottPlot#2715]
## Feature Suggestion

**Feature description:** 
some link this

![image](https://github.com/ScottPlot/ScottPlot/assets/1876302/c08a32c5-ad25-4c7e-acb8-97a8502b40b7)

**Code example:** If applicable, use this space to demonstrate how you wish the new feature could be used in code.

**Comment by swharden** [comment]
Hi @heartacker,

This isn't currently supported, but is totally possible to create! If you end up creating a plot type like this, share it here and we can work it into a future version of ScottPlot! Funny the "SignalPlot" name is already in use lol... maybe we could call it a "DataLinePlot" or something.

This page describes how to make a custom plot type: https://scottplot.net/faq/custom-plot-type/

It may be easiest to have your "DataLinePlot" display a single signal, so the chart at the top of the page would be achieved by adding four data line plots.

I'm personally interested in this because I work with hardware sometimes, and I'd love to be able to generate nice SPI/I2C diagrams programmatically. Related: https://github.com/swharden/FtdiSharp

I'll close this issue for now, but if progress is made on this front we can open it back up! 🚀
