### ISSUE TITLE
Is `recalculateLayoutOnMouseUp` deprecated in ScottPlot 4.1?

### ISSUE THREAD

**Issue by vrdriver** [ScottPlot/ScottPlot#2751]
Hi Scott,

I'm finally doing an upgrade from 40.2 (or a similar early version) and I'm coming across a few quirks. The biggest however right now is finding a solution to "recalculateLayoutOnMouseUp"

I can't find where it is documented any more, and my app is littered with statements for this call.

 Did I miss something in the upgrade? Is it deprecated? I see plenty of other examples using it, but it's not working for me.
 

` 'Configuration' does not contain a definition for 'recalculateLayoutOnMouseUp' and no accessible extension method 'recalculateLayoutOnMouseUp' accepting a first argument of type 'Configuration' could be found (are you missing a using directive or an assembly reference?)	` 

Cheers,
Steve

**Comment by vrdriver** [comment]
And yes, it's a .NET 4.8 c# winforms app.

**Comment by KroMignon** [comment]
@vrdriver It looks like you are upgrading your project from a far away version.

I am not a ScottPlot specialist (I am using it since about 6 month), but after taking a look at the source code and the Git history, the parameter `recalculateLayoutOnMouseUp` has been removed.
In fact, the complete initialisation of ScottPlot has drastically changed between 4.0.xx and 4.1.xx, perhaps you should take a look at the very good documentation:
* https://scottplot.net/quickstart/winforms/
* https://scottplot.net/faq/version-4.1/
* https://scottplot.net/cookbook/4.1/

**Comment by vrdriver** [comment]
Thanks @KroMignon. I've had a look at the upgrade page about 4.1 and the basic function changes, but it didn't mention anything about deprecated functions such as this one.

**Comment by swharden** [comment]
Hi @vrdriver and the group,

Unlike ScottPlot 4.0 which only recalculated the layout after the mouse button was released, ScottPlot 4.1 recalculates the layout continuously (before each rendered frame). This means the `recalculateLayoutOnMouseUp()` function is no longer necessary!

If you wish to have more advanced control over the layout (or disable the automatic adjustment) more information can be found here: https://scottplot.net/faq/layout/

**Comment by vrdriver** [comment]
Ok, thanks @swharden and @KroMignon That all makes sense now.

Yes, I was coming from a much earlier version, and I've managed to get the program running again after changing plenty of things. Now to work on the new layout methods and the 4.1 way of doing things and tweaking even more. Thanks again.
