### ISSUE TITLE
SP5 Avalonia: Wrong colors in Android projects

### ISSUE THREAD

**Issue by oktrue** [ScottPlot/ScottPlot#2818]
Candlesticks in Avalonia control generates with wrong color in WASM and Android projects.

Windows:
![Plot](https://github.com/ScottPlot/ScottPlot/assets/58470982/0a6ec396-1333-4476-accc-79f012932740)

WASM:
![2023-07-27](https://github.com/ScottPlot/ScottPlot/assets/58470982/1424a4f3-476a-4e03-a95c-e497ffc48eb2)

Android:
![photo_2023-07-27_11-14-00](https://github.com/ScottPlot/ScottPlot/assets/58470982/285c5c71-48d4-48dc-9738-6796cfec075a)

**Comment by swharden** [comment]
Hi @oktrue, thanks for reporting this!

Does it affect all plot types (like scatter plots) or is it only the finance plots? Can you share a code sample that helps us recreate this issue?

**Comment by oktrue** [comment]
Hi @swharden, yes it affects all plot types. Here is a minimal example to reproduce https://github.com/oktrue/ScottPlot5ColorTests

**Comment by swharden** [comment]
Hi @oktrue, 

I think this may be an issue with your graphics card. The following code renders well on my computer:

```cs
using Avalonia.Controls;
using ScottPlot.Avalonia;
using ScottPlot;

namespace Sandbox.Avalonia;

public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();

        RandomDataGenerator dataGen = new();
        var ohlcs = dataGen.RandomOHLCs(100);
        AvaPlot.Plot.Add.Candlestick(ohlcs);
    }
}
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/e149d136-cca3-411c-9c2b-6f1a5ac1fca5)


Without being able to reproduce this issue, it's hard to give more advice! Maybe update your graphics drivers?

**Comment by swharden** [comment]
@bclehmann have you used Avalonia for Android projects before?

**Comment by oktrue** [comment]
@swharden not only Android. It appears in WASM (WebAssembly) browser version as well.
![2023-07-28 (3)](https://github.com/ScottPlot/ScottPlot/assets/58470982/4046c4cd-ec4c-46e5-9459-30896610d211)

**Comment by KroMignon** [comment]
@bclehmann maybe you could do some more test to help to find the issue.

Could you change your code to force colors to known values?
ScottPlot uses `Color.FromHex()`  to generates default colors, maybe this is not valid for Avalomia.

Please try out this:
```
var fp = PlotModel.Plot.Add.Candlestick(prices);

fp.ColorDown = Color.Red;
fp.ColorUp = Color.Green;
fp.WickColor = Color.Blue;
```

and 
```
var fp = PlotModel.Plot.Add.Candlestick(prices);

fp.ColorDown = Color.FromHex("#FF0000");
fp.ColorUp = Color.FromHex("#00FF00");
fp.WickColor = Color.FromHex("#0000FF");
```

Booth code should generate same graph colors.

**Comment by oktrue** [comment]
@bclehmann you're right. I checked this with BGRA (changed #089981 to #819908 and #f23645 to #4536f2) and colors are correct. But how can we make it consistent across all platforms?
![2023-08-01](https://github.com/ScottPlot/ScottPlot/assets/58470982/d4d6a666-ac0f-4690-bca1-903d87656a4a)

**Comment by KroMignon** [comment]
> But how can we make it consistent across all platforms?

It seems to be a **known** SkiaSharp issue => https://github.com/unoplatform/uno/issues/8580

`SKImageInfo.PlatformColorType` returned value seems not to be correct for all platforms.

**Comment by KroMignon** [comment]
@swharden @oktrue @bclehmann 

> But how can we make it consistent across all platforms?

It seems to be a known SkiaSharp issue => https://github.com/unoplatform/uno/issues/8580

After taking a look at the class `Color` in `ScottPlot` 5, I guess the easiest way to solve this would be to change `Color.ToSKColor()`  to take `SKImageInfo.PlatformColorType` in account.

For example by adding a new property `ABGR`, and `ToSKColor()` will use `ABGR` when `SKImageInfo.PlatformColorType == SKColorType.Bgra8888` instead of  `ARGB`

```
   public SkiaSharp.SKColor ToSKColor()
    {
        return new SkiaSharp.SKColor(SKImageInfo.PlatformColorType == SKColorType.Bgra8888 ? ABGR : ARGB);
    }

```

**Comment by swharden** [comment]
Hi @KroMignon, thank you so much for figuring this out! I really appreciate the sleuthing required to get to the bottom of this confusing topic.

> change Color.ToSKColor() to take SKImageInfo.PlatformColorType in account.

I'm so happy we have been leaning on an extension method for this 😄

I will make the change you suggest and I hope it will fix @oktrue's problem in the next release!

**Comment by swharden** [comment]
Got it working!

Interestingly when I switched on `SKImageInfo.PlatformColorType` it got confused. Maybe when I run a WebAssembly app with the debugger attached it detects the wrong thing or something?

Either way the fix was not to try to flip the order of bytes in the `uint`, but instead to use the simpler constructor with distinct arguments

```cs
public SKColor ToSKColor()
{
    return new SKColor(Red, Green, Blue, Alpha);
}
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/4ef45c39-3953-4ad0-ae25-9ca9f1942bfd)

**Comment by KroMignon** [comment]
> Either way the fix was not to try to flip the order of bytes in the `uint`,

Yes of course, this is a much better and cleaner way to do!

**Comment by oktrue** [comment]
@swharden after your fix this issue is still reproducible in Avalonia WASM projects so we need to figure out how to fix it separately for Avalonia.

**Comment by oktrue** [comment]
@swharden good idea! I'll add it soon.

**Comment by KroMignon** [comment]
@oktrue I have no experience with Avalonia, but I will try it out because it make me curious 😏 

As I could see on Avalonia, the WASM port is quiet new.
Do you have tried any other platform (Android, IOS, RPi, macos)?
Is there the same issue or is it only with the WASM platform?
Maybe the bug is on Avalonia side???

**Comment by oktrue** [comment]
@KroMignon I tried this on Windows - ok,  Linux via WSL - ok, WASM - colors wrong, Android - colors wrong. You can also try all this platforms after merge PR #2830 with sandbox projects for them. This is not Avalonia problem because all Avalonia native controls displayed correctly on all platforms.
