### ISSUE TITLE
ScottPlot Insufficient accuracy

### ISSUE THREAD

**Issue by 2638662731** [ScottPlot/ScottPlot#2821]
![image](https://github.com/ScottPlot/ScottPlot/assets/64895402/4ea2845e-77c5-4325-b736-016c8d33f017)
![Uploading image.png…]()

Hello, please take a look at the picture. I want to replace the X-axis coordinates with the time (string type) I obtained from the temporal database, but I found that the conversion between double type and long type will lose accuracy. For example, the timestamp obtained from InfluxDB is 638246898160000500, and ScottPlot will change it to 638246898160000000 for coordinate display, resulting in insufficient accuracy. How to avoid this problem? I have also thought about using ManualTickPositions or TickLabelFormat, but the loading of ManualTickPositions is very slow in the case of a large amount of Big data (10W points in the test). TickLabelFormat

**Comment by swharden** [comment]
Hi @2638662731,

Only one of your images appeared in your original post so it's hard to understand what the problem is.

It seems like you're tracking the position of the mouse. This means you're figuring out what _pixel_ the mouse is on, and returning the time of that _pixel_. Could it be that `int pixelX` is where you are losing precision? You're rounding the position to an integer, then converting that integer to a coordinate (that's what `GetMouseCoordinates()` does). 

Let me know if this isn't enough information to solve your problem. 

If you copy/paste some code here that we can run to reproduce the issue, it will help us offer more specific suggestions as well.
