### ISSUE TITLE
SP4 Datalogger: Fix support for DateTime axes

### ISSUE THREAD

**Issue by p4pravin** [ScottPlot/ScottPlot#2849]
Data arrives at 250ms, the XAxis has XMin Limit = 0,   XMax limit = 1(mins). When the plot reaches the right most  tick and has to jump  left, the XAxis gets rescaled . Please see video. This video is for XMaxLimit = 1 . I trie dit for 30 mis interval as well, with same outcome. 

I tried using DateTimeFormat - same thing happens.

Could you please advise on how can I ensure that the xaxis is not rescaled on a 'jump' ?

Thanks !

https://github.com/ScottPlot/ScottPlot/assets/15835871/582a17e7-538c-474b-a497-124e71705322

**ScottPlot Version:** 4.1.65
**Operating System:** Windows 11
**Application Type:**  WinForms

**Comment by swharden** [comment]
Hi @p4pravin, it is difficult to offer advice because you did not share the code necessary to reproduce this issue

I suspect the problem relates to how far the plot is jumping when the plot runs off the screen.

Try something like:

```cs
var logger = formsPlot1.Plot.AddDataLogger();

logger.ViewJump(TimeSpan.FromMinutes(60).TotalDays);
```

The way Microsoft handles dates is very confusing. Basically the `ViewJump()` number is _days_ forward to jump after new data runs off the screen.

Let me know if this doesn't do the trick! 👍

**Comment by p4pravin** [comment]
Hi @swharden  Thank you for your reply! I was trying to use ViewJump to jump by 'minutes' instead of 'days'.   In the meantime, based on an example in the documentation, I used SignalPlot to plot the continuous data with sample rate=4 and jump left after new data runs off the screen. It is working well for a 1 min interval so far. Will test for 30 mins interval.   SignalPlot seems like the right plot type to use. 

Will try out what you have suggested. Thanks again!

**Comment by song106639** [comment]
If I use ViewSlide, the minimum time span is much larger than the value I set. Is there any way to fix this?
