### ISSUE TITLE
SP4: new plot type for drawing rectangles

### ISSUE THREAD

**Issue by dpieve** [ScottPlot/ScottPlot#2866]
## Feature Suggestion

**Feature description:** 

Possibility to add rectangles to a Plot.
It could be an interesting feature to highlight a specific area.

**Code example:**

```cs
var plt = new ScottPlot.Plot(600, 400);
plt.AddSignal(DataGen.Sin(51));
var rect = plt.AddRectangle(x, y, width, height); 
```

I'm using the `AddPolygon` to add a rectangle. I'll leave it here as an example.
```cs
/// <summary>
/// Displays a rectangle starting from the top-left X/Y coordinates.
/// </summary>
private Polygon AddRectangle(double x, double y, double width, double height, Color? fillColor = null, double lineWidth = 0, Color? lineColor = null)
{
    double[] xs = { x, x + width, x + width, x };
    double[] ys = { y, y, y - height, y - height };

    return plt.AddPolygon(xs, ys, fillColor, lineWidth, lineColor);
 }
```

I think this feature doesn't exist. Let me know if it does.

**Comment by swharden** [comment]
Thanks for this suggestion @dpieve!

This issue is the result of a conversation in the Discord #1966 

I ended-up making a whole new plot type that can be used like this:

```cs
plt.AddSignal(DataGen.Sin(51));
plt.AddSignal(DataGen.Cos(51));

// add a rectangle to the plot
plt.AddRectangle(xMin: 5, xMax: 15, yMin: .1, yMax: .7);

// customize its appearance
var rp = plt.AddRectangle(xMin: 20, xMax: 30, yMin: -.5, yMax: .5);
rp.BorderColor = Color.Blue;
rp.BorderLineWidth = 3;
rp.BorderLineStyle = LineStyle.Dot;
rp.Color = Color.FromArgb(100, Color.Yellow);
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/14bb61a8-ce0b-44ec-b420-a3d05dee3749)

I recognize I could have inherited and modified the `Polygon` plot type, but keeping them separate improves performance and allows it to be a bit simpler
