### ISSUE TITLE
Can not set min axis limit Radar Plot

### ISSUE THREAD

**Issue by vietanhbui** [ScottPlot/ScottPlot#2908]
**ScottPlot Version:** 4.1.52

**Operating System:** Windows 11

**Application Type:** WinForms

**Question:** How to set min axis limit Radar Plot

Max Axis can be update by:
```cs
radarPlot.Update(values, true, maxAxis);
```
but min axis always 0. How to update min axis (Eg: -10)

**Comment by swharden** [comment]
Hi @vietanhbui, 

This issue hasn't had any movement in a while, probably because it does not include code that allows others to reproduce the issue. If you're still interested in pursuing this I recommend creating a console app demonstrating the issue, sharing that code here, and re-opening this issue 👍

more information: https://scottplot.net/faq/repro/
