### ISSUE TITLE
SP5 Blazor: Display cookbook recipes online

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2962]
Now that there's a Blazor control #2960 it would be great if we could get all the cookbook examples working in it

After this is the case I can automate build/deployment to the ScottPlot.net website so each cook recipe could have a "try online" button

Here's a minimal example showing the current state of the blazor control:
https://swharden.com/tmp/sp/02/

**Comment by StendProg** [comment]
HI @swharden,

I checked out the link, looks impressive.
The only thing is that the performance is an order of magnitude lower than "native". If you make such an online mode, there should be well-defined limitations on the performance of the browser mode. So that newcomers do not have a false impression of performance. Otherwise it can become anti-advertising.
