### ISSUE TITLE
SP5: ArrowCoordinated constructor bug

### ISSUE THREAD

**Issue by StuartWilloughby** [ScottPlot/ScottPlot#2976]
## Bug Report

**Issue:** Typo in ArrowCoordinated constructor.

**Reproducing:** Call constructor.

```cs
        public ArrowCoordinated(Coordinate arrowBase, Coordinate arrowTip)
        {
            Base.X = arrowBase.X;
            Base.Y = arrowTip.Y;
            Tip.X = arrowTip.X;
            Tip.Y = arrowTip.Y;
        }
```

```Base.Y = arrowTip.Y;``` should read ```Base.Y = arrowBase.Y;```

### System Details
* **ScottPlot Version:** 4.1.68
* **Operating System:** Windows 10
* **Application Type:** WinForms
* **.NET Version:** .NET 7.0

**Comment by swharden** [comment]
Hi @StuartWilloughby, thanks for reporting this!

Specifically the issue is here:
https://github.com/ScottPlot/ScottPlot/blob/16eec73098cb932332a42b19d18a3ab1cccd14a2/src/ScottPlot4/ScottPlot/Plottable/ArrowCoordinated.cs#L81-L87

It would be fantastic if you or someone else could open a pull request to fix this issue! If several days pass and there's no progress, I'll fix it myself before the next release 👍

**Comment by Gray-lab** [comment]
@swharden, I would be happy to open a pull request for this issue! This is my first time contributing to this project so I wanted to ask before I do it, but it looks like quite a safe change given that nothing seems to be referencing that particular overload of ArrowCoordinated. :)

**Comment by swharden** [comment]
> I would be happy to open a pull request for this issue!

Awesome! I can review and merge-in the change quickly

> This is my first time contributing to this project

Let me know if you have any questions along the way! 🚀

> quite a safe change

Famous last words 😜

**Comment by StuartWilloughby** [comment]
> @swharden, I would be happy to open a pull request for this issue! This is my first time contributing to this project so I wanted to ask before I do it, but it looks like quite a safe change given that nothing seems to be referencing that particular overload of ArrowCoordinated. :)

Finally finished a crazy busy week and was just going to do this. More than happy to leave it to you though. :)

**Comment by Gray-lab** [comment]
@StuartWilloughby It occurs to me now that I should have checked if you are ok with someone else doing the fix since you were the one who found the issue, my apologies - I am still getting familiar with open source collaboration. I will be sure to check next time! Thank you for gracefully letting me take this one.

**Comment by swharden** [comment]
> I should have checked if you are ok with someone else doing the fix

No worries! The more help I get, the better 😄 🚀 

#3001 looks great! I'm merging now

**Comment by StuartWilloughby** [comment]
> @StuartWilloughby It occurs to me now that I should have checked if you are ok with someone else doing the fix since you were the one who found the issue, my apologies - I am still getting familiar with open source collaboration. I will be sure to check next time! Thank you for gracefully letting me take this one.

No need to check as there's no concept of issue ownership in open source. That's not how works. All help on any project is always very welcome. Grateful to you for taking it on and allowing me to turn off my machine 5mins earlier at the end of a very long week.

Hope you continue to enjoy contributing to OSS. Wish I had the time to do more myself.
