### ISSUE TITLE
SP5: scatter plot shows circular markers when `MarkerStyle.Shape` is set to `MarkerShape.None`

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3057]
not sure yet if the issue is in the scatter plot or the marker rendering code

**Comment by Gray-lab** [comment]
I think the problem is this line in MarkerShape:
`MarkerShape.FilledCircle or MarkerShape.OpenCircle or MarkerShape.None => new Markers.Circle(),`

One solution would be to make a renderer for Marker.None, which just doesn't draw anything. I think that is preferable to having a conditional in the rendering code. I am opening a PR for the issue.
