### ISSUE TITLE
Website: improve anchors for slow loading pages

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3085]
@bclehmann from Discord #1966 suggested adding an onload event to scroll to an anchor after the page is finished loading

**Comment by swharden** [comment]
Following-up, @bclehmann does this seem reasonable? 

```html
<body onload="scrollToUrlAnchor()">
```

```js
function scrollToUrlAnchor() {
    const urlAnchor = window.location.href.split('#')[1];
    if (urlAnchor) {
        window.scrollTop = document.querySelector(`#${urlAnchor}`).offsetTop;
    }
}
```

**Comment by bclehmann** [comment]
You can simply use `window.location.hash` rather than splitting on the hashtag.

But yeah, this sounds good, I've looked since and I think we have to use `window.load`, since `document.DOMContentLoaded` does not wait for things like stylesheets which are likely to change the `offsetTop` of the target.

**Comment by swharden** [comment]
> You can simply use window.location.hash rather than splitting on the hashtag.

Nice! Changing to:

```js
function scrollToUrlAnchor() {
    if (window.location.hash) {
        window.scrollTop = document.querySelector(window.location.hash).offsetTop;
    }
}
```
