### ISSUE TITLE
SP5 Cookbook: Duplicate line style examples

### ISSUE THREAD

**Issue by MCF** [ScottPlot/ScottPlot#3166]
This is a very small deal, but I noted that in our enthusiasm to add an additional line style recently I think we ended up creating a duplicate recipe in the cookbook.

Under _Styling Plots_ there is a _Line Styles_ recipe.
Under _Scatter Plot_ there is a _Scatter Line Patterns_ recipe.

They are close to being identical, although the _Scatter Line Patterns_ includes labels with the names of each line style which is nice.

**Comment by MCF** [comment]
Apologies, I added the bug label inadvertently.  More a suggested improvement.

**Comment by swharden** [comment]
Thanks for raising this point! 

My inclination is to keep them both, and add even more similar examples for the other plot types that use them (line, axis line, etc.) to make these customizations easier to locate because people researching a specific plot type (e.g., scatter plot) and who may not think to look in the "styling" section. There will be some duplication, but I think it's okay in this case because my aim is to make it more likely for the reader to see it.

However, I'll work to simplify the example in the styling section and ensure it doesn't appear as a duplicate 👍 

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/f1b1d830-39b0-48bb-98e7-11f14083e173)

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/de0c6719-2bbf-48a9-89e4-4caa1f9f610a)

**Comment by swharden** [comment]
this new line pattern demo for the styling section is a lot simpler and I think it more clearly communicates what patterns are

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/77045e0b-7c35-4de3-be71-5401c94dab94)
