### ISSUE TITLE
Controls: refactor input binding system

### ISSUE THREAD

**Issue by MohammadSadeghSalimian** [ScottPlot/ScottPlot#3186]
## Feature Suggestion

**Feature Description:** To change the mouse and keyboard keys for panning, zooming, etc., for Actions in Plot Viewer in WPF, I had to create a class from the IPLotInteraction interface and change it based on my needs. However, I think in some cases, users need to assign a key combination to these plot actions. For example, I prefer to pan the axis while the space key is being held and dragged with the mouse's middle button. 

**Code example:** If applicable, use this space to demonstrate how you wish the new feature could be used in code.

```cs
public InputBindings Inputs = new InputBindings()
{
    DragPanButton = MouseButton.Middle+KeyBoardKeys.Space.Holding,
    DragZoomRectangleButton = MouseButton.Right,
    DragZoomButton = MouseButton.Middle+KeyBoardKeys.Alt.Holding,
    ClickAutoAxisButton = MouseButton.Middle,
    ClickContextMenuButton = MouseButton.Unknown,
    DoubleClickButton = MouseButton.Left,
    ZoomInWheelDirection = MouseWheelDirection.Up,
    ZoomOutWheelDirection = MouseWheelDirection.Down,
    LockHorizontalAxisKey = Key.Shift,
    LockVerticalAxisKey = Key.Ctrl,
    PanZoomRectangleKey = Key.Alt,
};
```

**Comment by swharden** [comment]
> I prefer to pan the axis while the space key is being held and dragged with the mouse's middle button

This is a great example of a behavior that is a challenge with the current design! I'll leave this issue open and continue to think about how I can streamline control behavior customizations.

I'm thinking that I may have gotten too complex by all those interfaces, binding classes, etc. A simple `ControlBehavior` class may be the way to go, every method could be `virtual` so the user can inherit-and-override to customize specific behaviors without having to re-implement everything.

I'll keep thinking about this topic and prioritize refactoring this system in a future release 👍 

PS: https://scottplot.net/demo/ has updated information about customizing some elements of user inputs

**Comment by swharden** [comment]
Spillover from #3622, when this refactoring is done ensure there is consistency across controls for how to get the mouse position. This is platform-specific when it comes to display scaling and styling, especially for WPF controls.

**Comment by bclehmann** [comment]
I'm not sure if I love the idea of just throwing strings around, stringly-typed fields are typically quite difficult to work with. I think if you want that sort of generality you should make it an interface, where users are required to override all the relevant classes to handle that interface.

In C++ you would make the entire thing generic, people specify `TInputEvent` and they're required to also specialize the relevant classes for that specific type. Not sure if there's a clean way to do that in C# (other than dynamically by branching based on `typeof(inputEvent)`).

I also just wonder if this can be done by implementing `IPlotInteraction`, I don't think anything stops a user from adding behaviour like this via that route. It looks like `WpfPlot.Interaction` is public get-settable. There shouldn't be any difficulty in writing an implementation such that you can drag-pan with Space+Mouse3 (except as listed below). Most of the fiddly stuff like keeping track of keyboard state can be copy-pasted from our current implementation.

The only problem is I think most keys other than Ctrl, Alt, and Shift are simply flushed to `Key.Unknown`. We can fix this the right way (adding all the keys and the corresponding code such that the controls all send the right key) _or_ we can do it the wrong way, and just cast the scancode to the enum and say good luck (probably with the high bit set to ensure they don't conflict with our current definitions). I am pretty sure that this is kosher, but I would check that the CLR isn't allowed to assume that enum values correspond to fields when the `[Flags]` attribute isn't present. And check that these enums will have a large enough size (I believe they're always ints). Or the middle way, which is to offer an alternative API that takes the scancodes in addition to our enum-based API.

**Comment by bclehmann** [comment]
Also, scancodes are only the same cross-platform for USB keyboards. I don't want to know how dank it gets if a user uses two different PS2 keyboards. It may be better to just pass through the reported key code (which may not be a scancode, and is probably _not_ the same between WPF and other platforms) and expect the user to use the same enum.

**Comment by swharden** [comment]
> stringly-typed fields are typically quite difficult to work with

This is a good point! It doesn't feel right to me either... but it's simple, and I'll probably keep using them for now as I'm building this out and exploring designs. After we know more about the final design, I do like the idea of shifting toward a strategy that better leverages the type system.

> make it an interface, where users are required to override all the relevant classes to handle that interface.

I like the idea! Creating an `IUserInputEvent` allows us to pass a single object around too, instead of separate name/x/y values. I'll definitely do that next.

Regarding tracking key presses, I'm thinking about adding a `HashSet<string>` to track what "things" are pressed and released. That `string` type can change if/when the new type strategy discussed above is decided. Mouse button clicks and keyboard presses would be all be tracked in the same hash set, and each `UserAction` could look at the collection of things that are currently pressed and determine if and how to respond. This would probably resolve the key code issue.

> Most of the fiddly stuff like keeping track of keyboard state can be copy-pasted from our current implementation.

Indeed! Also as I copy/paste functionality over I will write unit tests to ensure the behaviors perform as expected and continue to in the future.

Thanks for your feedback Ben!

**Comment by MichaelKuelshammer** [comment]
I dont understand, why its so complicated, in my opinion some simple boolean flags do the job.
Add for each axis an somevboolean flags:

Boolean ActivatePan;
Boolean ActivateZoomIn;
Boolean Activate ZoomOut;

and you are independent from key combinations and mouse keys.

**Comment by swharden** [comment]
> simple boolean flags do the job

This is true for the events you described! however, consider the middle-click-drag zoom rectangle: The zooming action needs to know the mouse down pixel, the mouse up pixel, the dimensions of the plot in pixel units, and the range of axis units in coordinate units. Some user inputs send more information than a Boolean flag can convey. Also consider pinch-zoom in the Blazor web interface on mobile devices, and perhaps 3-finger-swipe pan on mobile devices too. It gets pretty complicated pretty quick!

**Comment by bclehmann** [comment]
If you want to sidestep ScottPlot input handling that should already be possible by creating your own `WpfPlot.Interaction` which is given its input directly rather than filtered through ScottPlot code.

**Comment by swharden** [comment]
I'm merging #4053 now. See the "custom mouse behavior demo" to get an idea for how the new API works. The key code is shown here: https://github.com/ScottPlot/ScottPlot/pull/4053#issuecomment-2237773602

This new merge is not a breaking change because you can still use the old system, but if you opt-in to the new `UserInputProcessor` system you get all the newest features and abilities. Eventually we'll probably mark the original `Interaction` system obsolete.

@MohammadSadeghSalimian all the features in your original comment should now be possible. If you get stuck on one, let me know and we can take a closer look together 👍
