### ISSUE TITLE
Ticks: check tick density

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3203]
Ticks on this recipe look bad
![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/a2666cd7-9189-4676-9b37-230da6b1f590)

https://scottplot.net/cookbook/5.0/SignalXY/SignalXYQuickstart/

**Comment by raburton** [comment]
I'd noticed this too.

v5 at the tope, v4 at the bottom:
![image](https://github.com/ScottPlot/ScottPlot/assets/433543/b3ee67b6-c825-48ea-9e01-a1ab7a32ff45)

Part of the the issue here in my case, is that v5 chart (actual drawing part) is narrower in the same same size window than at v4. Also, the amount of space between the first/last data points and their corresponding side axis is greater when autofitted (I actually think a bit too much space, was better size margin at v4, but in this case especially as it crunches the ticks up too more).

**Comment by swharden** [comment]
I think the issue is here...

https://github.com/ScottPlot/ScottPlot/blob/e3a4efede26fc17ca15e148fe127d577fdd3c34e/src/ScottPlot5/ScottPlot5/TickGenerators/NumericAutomatic.cs#L51-L52

The tick measurement system used to calculate ideal density is not using the paint that contains information about the font and font size, and it consistently under-reporting tick label sizes
