### ISSUE TITLE
SP5: Signal is slow in low density mode

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3229]
This affects signal plots after they zoom in enough to allow visualizing individual points

I suspect all points are being rendered rather than just those in the view

Thanks Marven from the Discord (#1966) for reporting this

EDIT: it's reported to happen when working with `float[]` but not `double[]` ... need to benchmark #2677 this

**Comment by minjjKang** [comment]
Hello.

I'm using in ScottPlot5 5.0.14-beta, and i have same problem.

I proceeded Benchmark for all SignalSources, I got the following result.

  | FPS |  
-- | -- | --
  | Low Density | High Density
SignalSourceDouble (double[]) | 700 | 65
SignalSourceGenericList (float[]) | 26 | 39
SignalSourceGenericArray (List<double>) | 25 | 39

For other sources except SignalSourceDouble, it is basically slow & much slow in LowDensity.

I think this is caused by GenericToDouble and GetYs.

RenderHighDensity -> GetPixelColumn, only a specific index of Ys was converted to GenericToDouble,
so there was only a small speed decrease,

RenderLowDensity -> GetYs : it converts all indexes.

To solve this problem,

using Enumerator for not convert Ys values that are not used in RenderLowDensity.
(In this case, the slowdown in High Density remains the same )

or

When creating SignalSource, all values must be converted to double[].

Thanks.

**Comment by swharden** [comment]
Hi @minjjKang, thanks for adding context! 

The library has undergone a lot of evolution since this issue was first opened so consider benchmarking it now. ScottPlot 5 is still only a few months into release and I'm focused on major features and bugfixes over performance optimization, but if you or someone else from the community is able to narrow-down the issue and open a PR, I would be happy to review it!
