### ISSUE TITLE
Pie charts and a few suggestions

### ISSUE THREAD

**Issue by sterenas** [ScottPlot/ScottPlot#3273]
A few suggestions:
V 5.0.16 was used.
1. In the Cookbook if you filter by "Pie" or "AddPie" it should show a quick sample. I couldn't find documentation for Pie charts (there was in v4).
2. In V4 I used to have `plt.YAxis.TickLabelFormat("#,##0,,M", dateTimeFormat:=False)`, not sure how it's now handled in V5? Couldn't find details in the docs.
3. `plt.Legend.Orientation = Orientation.Horizontal` has changed. Couldn't find how to keep this in V5.
4. `ScottPlot Demo 5.0.16.exe` has no app icon. V4 had a nice one. V4 also shows a URL to the site which is pretty useful but got lost in v5.

This is a gem of a repo!

**Comment by swharden** [comment]
Hi @sterenas, thanks for these suggestions! I'll tackle them in separate issues:

1, It's there but your browser may be serving old content. You can check out https://scottplot.net/cookbook/5.0/Pie/ and I created #3278 to improve the cache issue

2. https://scottplot.net/cookbook/5.0/search/ can help get you started but I agree a DateTime-specific example would be helpful so I'll create one and add it to the cookbook #3279

3. Horizontal legend orientation is not yet supported. I'll create a ticket to track that feature being added.  #3280

4. Good catch! I'll fix that in the next version of the demo. #3281

Since items have their own tickets I'll close this issue and follow-up individually as I get to each. Thanks again for the suggestions!

**Comment by swharden** [comment]
Related to suggestion 2,

```cs
// plot sample DateTime data
DateTime[] dates = Generate.DateTime.Days(100);
double[] ys = Generate.RandomWalk(100);
myPlot.Add.Scatter(dates, ys);
myPlot.Axes.DateTimeTicksBottom();

// add logic into the RenderStarting event to customize tick labels
myPlot.RenderManager.RenderStarting += (s, e) =>
{
    Tick[] ticks = myPlot.Axes.Bottom.TickGenerator.Ticks;
    for (int i = 0; i < ticks.Length; i++)
    {
        DateTime dt = DateTime.FromOADate(ticks[i].Position);
        string label = $"{dt:MMM} '{dt:yy}";
        ticks[i] = new Tick(ticks[i].Position, label);
    }
};
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/4417349b-30f9-4ad9-86d4-b17f95115719)
