### ISSUE TITLE
SP5: How to update heatmap and colorbar

### ISSUE THREAD

**Issue by redrabbit007** [ScottPlot/ScottPlot#3360]
I have a plot with a heatmap that I need to update when new data is loaded. It's easy enough to remove the old heatmap and create a new one. The issue I'm running into is how to update the colorbar or remove and add a new one. It seems that the only way to remove an existing colorbar is to call `Plot.Axes.Clear()`. But then that blows away all of my axes. Is there a proper way to handle this?

ScottPlot.Avalonia (5.0.21)

**Comment by csbebetter** [comment]
I have a similar problem. when I try to update, it goes like this
![Snipaste_2024-02-18_16-35-30](https://github.com/ScottPlot/ScottPlot/assets/70866844/b4a80fa1-0018-403a-82b1-8700e6f440da)

**Comment by xichaoqiang** [comment]
Same problem

**Comment by Excustic** [comment]
Same problem as well

**Comment by Excustic** [comment]
@redrabbit007 Found a quick workaround for this. 
When you call clear() on Axes you essentially clear the grids, axes and panels (ColorBar implements IPanel).
If you leave the Plot object as it is and later render it, the WpfPlot will throw an InvalidOperationException when ReplaceNullAxesWithDefaults() is called since it tries to assign the X and Y axes the default bottom and left axes, which are deleted by then. So, to fix this exception all you have to do is create new defaults:
       
        //Axes.Clear() calls clear on grids, axes and panels (colorbar implements IPanel).
        plot.Plot.Axes.Clear();
        //We can restore axes by calling the following methods.
        plot.Plot.Axes.AddBottomAxis();
        plot.Plot.Axes.AddLeftAxis();
