### ISSUE TITLE
Displaying a real-time graph in Linux

### ISSUE THREAD

**Issue by frodik13** [ScottPlot/ScottPlot#3428]
**Question:** I need to display a real time graph. In the preview version everything worked well, but when I updated to the latest version, the graphics on Linux began to slow down a lot. What could be the reason? Moreover, everything works well on Windows, and on a virtual machine too.

**ScottPlot Version:** 5.0.21

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

```cs
public void RefreshData(IEnumerable<double> xs, IEnumerable<double> ys)
{
    Graph.Plot.RenderManager.EnableRendering = false;
    while (Graph.Plot.RenderManager.IsRendering) { }


    coordinates.Clear();
    for (int i = 0; i < xs.Count(); i++)
        coordinates.Add(new Coordinates(xs.ElementAt(i), ys.ElementAt(i)));

    Graph.Plot.RenderManager.EnableRendering = true;


    Graph.Plot.Axes.AutoScale();
    Graph.Refresh();
}
```

**Comment by swharden** [comment]
Hi @frodik13, thanks for reporting this! I think this is the same issue described in #3439 so I'll close this one and follow updates there. I added some comments in that issue which may lead toward figuring this issue out, but since I don't run Linux on my desktop it's hard for me to evaluate this issue and I could really use the feedback of others who do!
