### ISSUE TITLE
SP5: Minimal WPF Demo

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3465]
I plan to use the WinForms demo to demonstrate virtually all GUI-specific functionality (mouse interactions, etc), but there are a few WPF-specific topics that may be nice to demonstrate and reference in a small standalone WPF demo: display scaling and mouse tracking.

* @MCF started to add this information to the WPF quickstart page (https://github.com/ScottPlot/ScottPlot.NET/pull/34) but a working code example may be a more useful way to document these behaviors

**Comment by MCF** [comment]
FWIW, there are some bugs in some of the Plot functions that must take into account ScaleFactor.  I have been slowly picking away at a PR to fix them but it is relatively complicated and I've been busy.  It may be ready in the next few days.  But that is why I couldn't fix up the documentation PR - I couldn't describe how to use these functions because they don't work properly.  These bugs will have to be fixed before any demo app can make use of the functions as well.

Regarding the use of ScaleFactor and DisplayScale to deal with high DPI displays: some of the same issues need to dealt with in the WinForms control as well.  For example the WinForms demo app shows all of the plots as being much too small on my laptop (which is set at 200% display scaling by Windows as it is a high DPI display).

**Comment by swharden** [comment]
> there are some bugs in some of the Plot functions that must take into account ScaleFactor

Thanks for reporting this! Maybe having a WPF demo for scale factor will help shine a light on some of those bugs and help us knock them out one by one.

> But that is why I couldn't fix up the documentation PR

Makes sense!

> Regarding the use of ScaleFactor and DisplayScale to deal with high DPI displays: some of the same issues need to dealt with in the WinForms control as well. For example the WinForms demo app shows all of the plots as being much too small on my laptop (which is set at 200% display scaling by Windows as it is a high DPI display).

Good point! Solving these issues will be a win for all the controls (not just the WinForms control)

Also, oof, integration testing using different system DPI scaling settings is so complicated and annoying 🤪

Even if we just make a list of all the broken functions that don't support scaling well, that's a good start! I created #3469 for this purpose

Thanks for all your help on this @MCF! I'd love to get these all fixed up in the next release or two 🚀

**Comment by Rusty** [comment]
I replicated the issue here.
FWIW, my main monitor (win11) has the Scale set to 200%. My other monitors (x2) are at 100%.  
The example is just trying yo create a plot with a cross hair that tracks the mouse.
The app misbehaves on all monitors.

WPF code here->

XAML---
<Window x:Class="ScottPlotMouseIssue.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:ScottPlot="clr-namespace:ScottPlot.WPF;assembly=ScottPlot.WPF"
        xmlns:local="clr-namespace:ScottPlotMouseIssue"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <ScottPlot:WpfPlot x:Name="chart" MouseMove="WpfPlot1_MouseMove"/>
    </Grid>
</Window>

C#----
using ScottPlot.Plottables;
using ScottPlot;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace ScottPlotMouseIssue
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        private readonly ScottPlot.Plottables.Crosshair _crosshair;
        public MainWindow()
        {
            InitializeComponent();
            _crosshair = new ScottPlot.Plottables.Crosshair();
            chart.Plot.Add.Plottable(_crosshair);
        }

        private void WpfPlot1_MouseMove(object sender, MouseEventArgs e)
        {
            var p = e.GetPosition(chart);
            Pixel mousePixel = new(p.X, p.Y);
            _crosshair.Position = chart.Plot.GetCoordinates(mousePixel); ;
            chart.Refresh();
        }
    }
}

And here is my (horrible) hack to fix it
```
        private void WpfPlot1_MouseMove(object sender, MouseEventArgs e)
        {
            PresentationSource source = PresentationSource.FromVisual(this);
            double dpiX=1, dpiY=1;
            if (source != null)
            {
                dpiX = source.CompositionTarget.TransformToDevice.M11;
                dpiY = source.CompositionTarget.TransformToDevice.M22;
            }

            var p = e.GetPosition(chart);
            Pixel mousePixel = new(p.X*dpiX, p.Y*dpiY);
            _crosshair.Position = chart.Plot.GetCoordinates(mousePixel); ;
            chart.Refresh();
        }



```

**Comment by MCF** [comment]
I think the best way to solve the problem of converting WPF pixel position to plot Coordinates is to apply the ScottPlot WPF control's DisplayScale to your raw pixels that come from e.GetPosition.  So something like:

```csharp
var position = e.GetPosition(chart);
if (chart.DisplayScale != 1.0)
{
    position.X *= chart.DisplayScale;
    position.Y *= chart.DisplayScale;
}
Pixel mousePixel = new Pixel(position.X, position.Y)
_crosshair.Position = chart.Plot.GetCoordinates(mousePixel)
```

I suspect you are effectively doing the same thing with your own code that ScottPlot's WPF control is doing to [determine DisplayScale](https://github.com/ScottPlot/ScottPlot/blob/e22a5c4e0724353efab683d62ae3320398d0c450/src/ScottPlot5/ScottPlot5%20Controls/ScottPlot.WPF/WpfPlotBase.cs#L108-L111):

```csharp
        public float DetectDisplayScale()
        {
            return (float)VisualTreeHelper.GetDpi(this).DpiScaleX;
        }
```

The closed documentation PR that is mentioned at the top of this issue _is_ factually correct.  It provides more detailed background about the WPF control's DisplayScale.  There are also additional notes in that PR about how to make your ScottPlot plots look the same no matter the Windows scaling that is in effect.  I would recommend you read that PR for more details about this stuff.

**Comment by Rusty** [comment]
Thanks so much.
That is exactly what I was looking for.

I’ve reduced my code to this now, which I think is relatively clean.

            var p = e.GetPosition(chart);
            Pixel mousePixel = new(p.X * chart.DisplayScale, p.Y * chart.DisplayScale);
            _crosshair.Position = chart.Plot.GetCoordinates(mousePixel); ;
            chart.Refresh();

Cheers
Rusty Johnson
CTO - CoFounder
SharpCloud Software Limited
Sign for FREE up here: https://hubs.li/Q01DQhLj0
M +44 7798 692 369
D  +44 2079 039 201
E   ***@***.******@***.***>
W  www.sharpcloud.com<https://t.sidekickopen77.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPfhMynW2zWLG81qMCsgN56dTQvdpKjj102?te=W3R5hFj26QkHmW4mKDt93QZnrTW3F9cVL3GGYWV348S2&si=8000000002683472&pi=5cd713fa-bccc-4d85-abfa-8a35ca8698f2>
[A blue and black logo  Description automatically generated]

**Comment by swharden** [comment]
Thanks @Rusty for sharing your question here and @MCF for hopping in to answer! 🚀
