### ISSUE TITLE
DataLogger: create new `Add()` overloads that accept arrays

### ISSUE THREAD

**Issue by h25019871990** [ScottPlot/ScottPlot#3555]
**Issue:** (Describe the bug here)
![image](https://github.com/ScottPlot/ScottPlot/assets/3319150/d5a2f616-8952-4b2b-b5ef-0cdee33907df)
![image](https://github.com/ScottPlot/ScottPlot/assets/3319150/fccbd9a1-bb3c-40f0-8cfd-09b476879a65)

**ScottPlot Version:** (What NuGet package are you using?)
5.0.23
**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

**Comment by swharden** [comment]
Hi @h25019871990, thanks for sharing this!

Unfortunately we can't work on this issue without some sample code that helps is recreate it.

This issue may be the result of modifying collections (like lists) _while_ a plot is actively being rendered. https://scottplot.net/faq/async/ may have information that can help you resolve this issue.

If you provide code we can run to recreate this issue we can re-open this ticket and closer look 👍

**Comment by Herbgh** [comment]
![微信截图_20240606170928](https://github.com/ScottPlot/ScottPlot/assets/32830146/e3256868-fdd7-411a-9056-0b0ecc836e64)
@swharden  Whether foreach can be replaced with for?

**Comment by swharden** [comment]
I believe the suggestion is to replace this code:

https://github.com/ScottPlot/ScottPlot/blob/d003f9a1f19aae487cb03a25becc2d54efd0a2e4/src/ScottPlot5/ScottPlot5/Plottables/DataLogger.cs#L64-L78

with code that uses indexing instead of `foreach`

Although this would work, the extra `ToArray()` step is costly (with time and memory) so I do not recommend it.

However, we could add overloads like this which use indexing logic:
```cs
public void Add(double[] ys) { /* ... */ }
public void Add(Coordinates[] coordinates) { /* ... */ }
```
