### ISSUE TITLE
Scatter plot: rendering fails on inverted horizontal axis

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3570]
Recreating:
```cs
formsPlot1.Plot.Add.Signal(Generate.Sin());
formsPlot1.Plot.Axes.SetLimitsX(0, -100);
```

This line throws:
https://github.com/ScottPlot/ScottPlot/blob/b12cb0c1ae5ddd76fe4e7a686fac79cc57519fbb/src/ScottPlot5/ScottPlot5/Plottables/Signal.cs#L111

```
System.ArgumentOutOfRangeException: 'Index was out of range. 
Must be non-negative and less than the size of the collection. (Parameter 'index')'
```

**Comment by bwedding** [comment]
I took a quick look at this. The reason it throws is obviously because there are no points to move to. If you just handle that and return from RenderLowDensity(), it won't throw, but it won't plot anything either.

The reason there are no points to render is much deeper. Signal, by virtue of how it handles the X axis with a period and not actual point values, doesn't easily invert its x-axis. **Perhaps it shouldn't either. It is a signal. Inverting it means plotting from the future to the past, which doesn't make sense.**

If you do want to handle it, it's going to take a major refactor, from what I can see.

All this code here in SignalBase.cs will need to change because it doesn't expect negative values. 

```
public int MinimumIndex { get; set; } = 0;
public int MaximumIndex { get; set; } = int.MaxValue;

public int MinRenderIndex => Math.Max(0, MinimumIndex);
public int MaxRenderIndex => Math.Min(Length - 1, MaximumIndex);

public double XOffset { get; set; }
public double YOffset { get; set; }

public int GetIndex(double x, bool visibleDataOnly)
{
    int i = (int)((x - XOffset) / Period);

    if (visibleDataOnly)
    {
        i = Math.Max(i, MinRenderIndex);
        i = Math.Min(i, MaxRenderIndex);
    }

    return i;
}

```
