### ISSUE TITLE
Can't revert to ScottPlot 4.1.73

### ISSUE THREAD

**Issue by fzobel59** [ScottPlot/ScottPlot#3581]
**Question:**  I was using ScottPlot 4.1.73 and ScottPlot.WinForms 4.1.73 packages and they were working fine.  I thought I might try the  5.0.23 versions instead, so I uninstalled the old and installed 5.0.23.  However, I kept getting errors that it couldn't find
C:\Users\Fred\source\repos\SCADA2\packages\SkiaSharp.NativeAssets.macOS.2.88.7\build\net462\..\..\runtimes\osx\native\libSkiaSharp.dylib

  I'm using .NET Framework 4.8.09 and Visual Studio Ver 17.8.7 and NuGet Package Manager 6.8.1

So I decided to go back to 4.1.73.  I uninstalled 5.0.23 and installed 4.1.73 again (ScottpPlot and Scottplot.WinForms).  Now I'm getting this error:

Found conflicts between different versions of "ScottPlot" that could not be resolved.There was a conflict between "ScottPlot, Version=4.1.73.0, Culture=neutral, PublicKeyToken=86698dc10387c39e" and "ScottPlot, Version=5.0.23.0, Culture=neutral, PublicKeyToken=86698dc10387c39e".    "ScottPlot, Version=4.1.73.0, Culture=neutral, PublicKeyToken=86698dc10387c39e" was chosen because it was primary and "ScottPlot, Version=5.0.23.0, Culture=neutral, PublicKeyToken=86698dc10387c39e" was not.    References which depend on "ScottPlot, Version=4.1.73.0, Culture=neutral, PublicKeyToken=86698dc10387c39e" [C:\Users\Fred\source\repos\SCADA2\packages\ScottPlot.4.1.73\lib\net462\ScottPlot.dll].        C:\Users\Fred\source\repos\SCADA2\packages\ScottPlot.4.1.73\lib\net462\ScottPlot.dll          Project file item includes which caused reference "C:\Users\Fred\source\repos\SCADA2\packages\ScottPlot.4.1.73\lib\net462\ScottPlot.dll".            ScottPlot, Version=4.1.73.0, Culture=neutral, PublicKeyToken=86698dc10387c39e, processorArchitecture=MSIL    References which depend on "ScottPlot, Version=5.0.23.0, Culture=neutral, PublicKeyToken=86698dc10387c39e" [].        C:\Users\Fred\source\repos\SCADA2\packages\ScottPlot.WinForms.4.1.73\lib\net472\ScottPlot.WinForms.dll          Project file item includes which caused reference "C:\Users\Fred\source\repos\SCADA2\packages\ScottPlot.WinForms.4.1.73\lib\net472\ScottPlot.WinForms.dll".            ScottPlot.WinForms, Version=4.1.73.0, Culture=neutral, PublicKeyToken=86698dc10387c39e, processorArchitecture=MSIL

Any ideas on how to resolve the conflicts between 4.1.73 and 5.0.23 (which supposed to be uninstalled and removed)?

**Comment by swharden** [comment]
Hi @fzobel59, 

It looks like you're developing a .NET Framework 4.6.2 application, and after upgrading the ScottPlot NuGet package from `4.1.73` to `5.0.23` you had a build error so you tried to downgrade and get a new error.

I suspect this issue is caused by ScottPlot 5's dependency SkiaSharp, which itself has several dependencies which may have been upgraded in your project, and after downgrading there are version mismatches.

My recommendation is to use the version of your project before you performed the upgrade (rather than try to figure out how to upgrade then downgrade). Hopefully your software project is in source control or backed up somewhere so this should be an easy task 😅 If this is not the case, oof, it could get complicated... I'd start by removing all NuGet packages and adding them one-by-one as needed until the project builds.

Hope this helps!
Scott

**Comment by fzobel59** [comment]
Thanks for your response, Scott!  I'll be working on it....
