### ISSUE TITLE
WinUI: Inaccurate minimum supported version?

### ISSUE THREAD

**Issue by diluculo** [ScottPlot/ScottPlot#3582]
I'm curious about the requirement for Target OS version 10.0.22200.0 or later to use ScottPlot in WinUI3. This information is sourced from this [documentation](https://scottplot.net/quickstart/winui/). It seems like there might be a typo here as 10.0.22200.0 is not a valid TargetPlatformVersion for Windows and should likely be interpreted as 10.0.22000.0.

The package specifies that net6.0-windows10.0.18362 is required.

![image](https://github.com/ScottPlot/ScottPlot/assets/12293818/4325942a-9a89-43f7-8c4b-e35a2cccd41c)

Here are the steps I've taken:

1. Created a project using the Blank App, Packaged (WinUI 3 in Desktop) project template in Visual Studio 2022.
1. Updated `Microsoft.WindowsAppSDK` and `Microsoft.Windows.SDK.BuildTools` to their latest versions.
1. Attempted to add `ScottPlot.WinUI`, but encountered build errors. (see below image)
1. Changed `TargetFramework` to `net6.0-windows10.0.22000.0`, after which the build succeeded. Why isn't net6.0-windows10.0.18362 working? If it's not supported, perhaps the nuget description should be updated accordingly. Alternatively, if feasible, could the build process accommodate lowering the Target OS Version to 10.0.18362?

![image](https://github.com/ScottPlot/ScottPlot/assets/12293818/daddbcca-0de9-491e-a947-41eaf6e4b50a)

**Comment by swharden** [comment]
Hi @diluculo, thank you for this interesting question!

> Why isn't net6.0-windows10.0.18362 working?

I'm not sure, I suspect I also hit this issue because the WinUI sandbox app also targets `net6.0-windows10.0.22000.0`

https://github.com/ScottPlot/ScottPlot/blob/c7346d103f519aba8ab5d19842ae8becbe288258/src/ScottPlot5/ScottPlot5%20Sandbox/Sandbox.WinUI.Desktop/Sandbox.WinUI.Desktop.csproj#L5

When I look closer at the plot control's csproj, it seems there is some version-specific logic which I may not fully understand...

https://github.com/ScottPlot/ScottPlot/blob/c7346d103f519aba8ab5d19842ae8becbe288258/src/ScottPlot5/ScottPlot5%20Controls/ScottPlot.WinUI/ScottPlot.WinUI.csproj#L50-L60

When building for `net6.0-windows10.0.18362` it seems the `10.0.22000.27` SDK is getting used.

I'll ping @rafntor (a contributor who worked on the WinUI control and is a lot more familiar with WinUI than I am) to see if they're available to provide feedback here. I'm not sure about the lifecycle of WinUI versions, but if it makes things easier I'm happy to increase the minimum supported version if it makes things easier.

**Comment by diluculo** [comment]
@swharden, Thanks for your quick reply.

It seems that the issue might be related to `SkiaSharp.Views.WinUI v2.88.*`. In my testing, I created a WinUI 3 project using `ScottPlot v5.0.23` and `SkiaSharp.Views.WinUI v2.88.7`. I then copied the `WinUIPlot` control into the project. It appears to work fine on TargetFramework  `net6.0-windows10.0.19041.0` or higher.

Considering this, it might be possible to lower the supported version of ScottPlot 5 for WinUI to `net6.0-windows10.0.19041.0`.

![image](https://github.com/ScottPlot/ScottPlot/assets/12293818/d62e547a-7bcc-434c-a599-30bcb1088e28)

Here's the WinUI 3 project that I used for testing: 
[ScottPlotTestApp.zip](https://github.com/ScottPlot/ScottPlot/files/14892085/ScottPlotTestApp.zip)

 I hope this information helps. Thanks again.

**Comment by rafntor** [comment]
I am also not very confident in how to manage versions and dependencies with winsdk, it is rather complicated I think.

But I made some tests and the culprit is what you have already shown above:
`
<FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.22000.27" />   
 <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.22000.27" />
`
These references makes it necessary for the consuming app to target a very new winsdk it seems.

I made a couple of [commits ](https://github.com/ScottPlot/ScottPlot/compare/main...rafntor:ScottPlot:issue%233582) that seem to solve it:
First commit holds back the references to 10.0.19041 which is the lowest that worked out.
Second bumps the targetframework from 18362 to 19041 so they actually match and the resulting nuget would contain more consistent information.

**Comment by diluculo** [comment]
Based on my testing of a WinUI 3 app that includes `SkiaSharp.Views.WinUI v2.88.7`, I can confirm that it indeed requires `net6.0-windows10.0.19041`, which contradicts the specification in the NuGet description. Consequently, @rafntor, I agree with your suggestion to set the minimum target to 19041.

**Comment by rafntor** [comment]
Super, I also played with SkiaSharp.Views.WinUI and when holding it back to 2.88.3 it works for targetframework 18362. 
After that something seem to be broken.

so I think either this ;
```
    <ItemGroup Condition="'$(TargetFramework)'=='net6.0-windows10.0.18362'">
        <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.*" />
        <PackageReference Include="SkiaSharp.Views.WinUI" Version="2.88.3" />
        <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.18362.33" />
        <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.18362.33" />
    </ItemGroup>
```
or this ;
```
    <ItemGroup Condition="'$(TargetFramework)'=='net6.0-windows10.0.19041'">
        <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.*" />
        <PackageReference Include="SkiaSharp.Views.WinUI" Version="2.*" />
        <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.19041.33" />
        <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.19041.33" />
    </ItemGroup>
```
will work out

**Comment by rafntor** [comment]
Actually I think the entire ```<FrameworkReference Update= .. />``` may have come in by an accident and should be removed.
The advise comes from [Uno documentation](https://platform.uno/docs/articles/features/winapp-sdk-specifics.html) but I found it builds fine without these also (at least with current versions of AppSdk, maybe it was a required workaround at one point)

So this should be enough:
```
    <ItemGroup Condition="'$(TargetFramework)'=='net6.0-windows10.0.19041'">
        <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.*" />
        <PackageReference Include="SkiaSharp.Views.WinUI" Version="2.*" />
    </ItemGroup>
```

**Comment by rafntor** [comment]
I also added net8.0/net8.0-windows-targeting in my latest commit.
It generates a NETSDK1206 warning but that can be suppressed and will probably go away soon when next AppSdk goes live : https://github.com/microsoft/WindowsAppSDK/discussions/3967
