### ISSUE TITLE
Box: Default stroke width is zero

### ISSUE THREAD

**Issue by Kareltje1980** [ScottPlot/ScottPlot#3741]
**Issue:** Whiskers are not showing in boxplots

**ScottPlot Version:**
Up until 5.0.26  all is working as expected, but from 5.0.27 onward it does not show. 

**Code Sample:** 
I was lazy and just grabbed the code from the website (https://scottplot.net/cookbook/5.0/Box/). Here you can also see that the whiskers are not showing. 

```cs
ScottPlot.Plot myPlot = new();

ScottPlot.Box box = new()
{
    Position = 5,
    BoxMin = 81,
    BoxMax = 93,
    WhiskerMin = 76,
    WhiskerMax = 107,
    BoxMiddle = 84,
};

myPlot.Add.Box(box);

myPlot.Axes.SetLimits(0, 10, 70, 110);

myPlot.SavePng("demo.png", 400, 300);
```

**Comment by swharden** [comment]
Hi @Kareltje1980, thanks for reporting this! The issue seems to be that the stroke width size is defaulting to 0.

```cs
box.Stroke.Width = 1; // this workaround fixes it for now
```

![demo](https://github.com/ScottPlot/ScottPlot/assets/4165489/cd729688-78ce-4745-87c3-dbcb417e56dc)

A true fix will be to modify this line:
https://github.com/ScottPlot/ScottPlot/blob/74239f7d7d0d26a773c219525a60433573a6370d/src/ScottPlot5/ScottPlot5/Primitives/Box.cs#L22

to be something like: 
```cs
public LineStyle Stroke { get; set; } = new() { LineWidth = 1 };
```
