### ISSUE TITLE
Axis: add option to wrap text

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3770]
Originally discussed in #3759, it would be nice if long titles could be wrapped so they don't fall off the screen. Measuring all that text is costly so it may be best to add as an opt-in feature.

* https://swharden.com/csdv/skiasharp/drawtext-rectangle/

![image](https://github.com/ScottPlot/ScottPlot/assets/16214078/8cf73966-b9ad-4aa0-b998-39ba9d7018b5)

![](https://swharden.com/csdv/skiasharp/drawtext-rectangle/skiasharp-word-wrap.gif)

**Comment by bclehmann** [comment]
This is annoying with Skia, I think it's come up before, but Skia doesn't even let you have newlines in strings. So you'd have to do word-wrapping logic yourself, and they'd have to be in separate draw calls, which is surprisingly tricky to make aesthetically appealing. 

There is a nice loophole I've used before, but I'm pretty sure you'll hate it. Essentially, you programmatically create an SVG. But SVGs also don't support line wrapping. So in the SVG you embed an XHTML foreignObject, which does support line wrapping. Then you simply render the resulting SVG. I personally have no idea if this will work, since I wouldn't expect skia to be lugging around an HTML rendering engine as well (I did this in the web context where we could just make the browser do it).
