### ISSUE TITLE
Where is the "open in new window" right-click menu option in the latest Ver 5.0?

### ISSUE THREAD

**Issue by kareem469** [ScottPlot/ScottPlot#3785]
Where is the "open in new window" right-click menu option in Ver 5.0?

**ScottPlot Version:5.0.33** 

It is there by default in Ver 4.1.61.

**Comment by MCF** [comment]
Does not exits (yet): https://github.com/ScottPlot/ScottPlot/issues/3730

**Comment by swharden** [comment]
Hi @kareem469, I updated #3730 to be high priority so it'll be added soon. I'll close this issue because it's a duplicate.

Note that you can add a right-click "open in new window" option pretty easily, and I posted the code here: https://github.com/ScottPlot/ScottPlot/issues/3730#issuecomment-2097117433
