### ISSUE TITLE
Heatmap: displayed image is reversed

### ISSUE THREAD

**Issue by Zakharovvas** [ScottPlot/ScottPlot#3787]
**Heatmap bug (both 4 and 5 versions).**

Element intensities[0,0] is displayed in left upper corner, corresponding to x=0, y=1000.
Element intensities[1000,0] is displayed in left bottom corner, corresponding to x=0, y=1000.

The same bug can be seen in your example https://scottplot.net/cookbook/4.1/recipes/heatmap_limitscale/

the function :
```cs
intensities[x, y] = (Math.Sin(x * .2) + Math.Cos(y * .2)) * 100; 
```
doesn't correspond to what we see on the image.

**Comment by swharden** [comment]
Hi @Zakharovvas, I believe this is the correct behavior. If you disagree or I am not understanding the issue, let me know how I can modify the console application below to demonstrate the issue you are describing:

```cs
using ScottPlot;

double[,] data =
{
    { 1, 2, 3 },
    { 4, 5, 6 },
    { 7, 8, 9 },
};

Plot plt = new();
var hm = plt.Add.Heatmap(data);
plt.Add.ColorBar(hm);
plt.SavePng("test.png", 400, 300).LaunchFile();
```

![test](https://github.com/ScottPlot/ScottPlot/assets/4165489/56c1eabb-f3f8-4296-be71-8a3c5eabfcdf)

**Comment by swharden** [comment]
Note that if you want to flip the orientation of the heatmap, flags are available to make this easier https://scottplot.net/cookbook/5.0/Heatmap/HeatmapFlip/

**Comment by Zakharovvas** [comment]
Unfortunately, I don't understand the issue. That's a first problem.
And you've been so impolite, that closed the issue without even trying to
understand. This is second problem.

When you look in the image, you compare it with matrix, which is not a
correct way how to check it. Your plot displays a matrix with 0,0 in left
upper corner, x for cols, y for lines.
Your heatmap not a plot at all and what your axes mean in that case no one
knows, what numbers on axes mean?

For that reason your images on the examples, notably here
https://scottplot.net/cookbook/4.1/category/plottable-heatmap/#2d-waveform
and below displaying bullshit on the axes like values x and y. I've written
this already on GitHub, but you, it seems to be a simple coder.
It is clear for everyone how remembers the trigonometry from a middle
school, not Mona Lisa only.

I have no intention to help you anymore,

Good luck

**Comment by swharden** [comment]
Hi @Zakharovvas, thank you for your follow-up message! It is unfortunate you found my initial response impolite. It seems I was unable to understand your original question, which is why I created the code sample to help facilitate communication with you.

> Your plot displays a matrix with 0,0 in left upper corner, x for cols, y for lines.

From what I read from your latest message, it sounds like you disagree with the design decision where the first row of heatmap image data (y index 0) is at the top. This decision was made to be consistent with common image formats (e.g., how pixels are encoded in memory in the bitmap file format). Users who find this thread and wish to change this behavior will find the following resources useful:
* https://scottplot.net/cookbook/5.0/Heatmap/HeatmapFlip/
* https://en.wikipedia.org/wiki/BMP_file_format

> Your heatmap not a plot at all and what your axes mean in that case no one knows, what numbers on axes mean?

Thank you for pointing this out! The test images in the cookbook are paintings, but a better example would be to plot real sensor data like atomic force microscopy readings, and add labels to the horizontal and vertical axis to indicate the tick marks represent positions in space. Users interested in displaying a heatmap as an image (and not displaying axis labels and ticks marks) may be interested in activating the "frameless" option.
* https://scottplot.net/cookbook/5.0/AxisAndTicks/Frameless/
* https://en.wikipedia.org/wiki/Atomic_force_microscopy
