### ISSUE TITLE
Scatter plot with fill doesn't clip line

### ISSUE THREAD

**Issue by BendRocks** [ScottPlot/ScottPlot#3792]
**Issue:** (Describe the bug here)
When ```FillY``` is enabled with a scatter plot, the trace lines are not correctly clipped. 

**ScottPlot Version:** (What NuGet package are you using?)

5.0.34.0

I cloned the repo and modified the Sandbox.Winforms.Form1.cs

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

The following code was put into the Form1 constructor in the Sandbox.Winforms 

```
  double[] xs = { 1, 10, 100, 1000, 10_000, 100_000 };
  double[] ys = { -50, -50, 10, -50, -80, -80 };

  // add log-scaled data to the plot
  ScottPlot.Plottables.Scatter sp = formsPlot1.Plot.Add.Scatter(xs, ys);
  sp.LineWidth = 5;
  sp.FillY = false;
  sp.FillYValue = -200;
 
  formsPlot1.Plot.Axes.Bottom.Min = 100;
  formsPlot1.Plot.Axes.Bottom.Max = 10000;
```

The output is as expected, with the trace clipped at the left and right edges of the plot:

![image](https://github.com/ScottPlot/ScottPlot/assets/24760857/772ee84f-78ab-4e3c-b4e4-e090d24f2122)

If the same code is used, with ```sp.FillY``` set to true, we see the following output:

![image](https://github.com/ScottPlot/ScottPlot/assets/24760857/701fd182-afc2-4510-a1e8-04365122171e)

Notice above that the lines are no longer clipped at the left and right. Note the different shading of the fill is due to the bug https://github.com/ScottPlot/ScottPlot/issues/3791. That same block of  code in ```scatter.cs``` code is likely the culprit since the lines render correctly when ```FillY``` is ```false```.

**Comment by CoderPM2011** [comment]
https://github.com/ScottPlot/ScottPlot/blob/093994e1b020d2d1f349e4e0a06c9d67e2577b44/src/ScottPlot5/ScottPlot5/Plottables/Scatter.cs#L144-L154

This is because `rp.CanvasState.Restore()` does not restore the state to what it was before calling `rp.CanvasState.Clip()`.

Before calling `rp.CanvasState.Clip()`
![image](https://github.com/ScottPlot/ScottPlot/assets/7456441/4a66ee64-da55-4126-ba66-1b208de7e860)

After calling `rp.CanvasState.Clip()`
![image](https://github.com/ScottPlot/ScottPlot/assets/7456441/a766bf2d-a96e-4f04-a488-7438e3fd86cb)

After calling `rp.CanvasState.Restore()`
![image](https://github.com/ScottPlot/ScottPlot/assets/7456441/0f49c6e2-929e-4522-bcf7-8418e9e96f37)

**Comment by swharden** [comment]
Fixed in https://github.com/ScottPlot/ScottPlot/commit/79e19187be6f7c781d0409082017ab5af429e128 - thanks both of you for your help! This fix will be in the next release 👍 🚀
