### ISSUE TITLE
Contour line (aka isoline), as new plot type or additionally to heat map

### ISSUE THREAD

**Issue by CodeBehemoth** [ScottPlot/ScottPlot#3795]
**Idea 1.**
Contour line additionally to heat map can make the plot more clearer. E.g. :
![image](https://github.com/ScottPlot/ScottPlot/assets/31969971/a028288e-db4d-4dad-98f9-01399444da51)
or
![image](https://github.com/ScottPlot/ScottPlot/assets/31969971/1a37ac1d-3d8f-423f-a014-e3f86fb51794)

In the first version only the color of the contour line should be configurable.

**Idea 2.**
Isoline as new plot type, such as:

![image](https://github.com/ScottPlot/ScottPlot/assets/31969971/0f0cf885-86f1-4fa8-b375-e048179fdf85)

In this case the values (heights) can be displayed on the lines.

**Comment by jon-rizzo** [comment]
Putting these comments here, so they don't get lost on Discord.  Many (most?) engineering and mapping applications solve this problem using Delaunay Triangulation.  That is, given a set of 2D points, create a Triangular Irregular Network (TIN) that establishes a straight line interpolation between every point and neighboring points.  Attached to these 2D points can be any additional attribute, which might represent an elevation, temperature, light intensity, or any other value that needs to be contoured.  Building the TIN is the hard part.  The edges of each triangle represents a straight-line interpolation between values.  Once the TIN is built, contours can be drawn by simply looking at each triangle, and iterating from the lowest to the highest (elevation/temperature, etc) value, and using the edges of the triangle to interpolate the locations of the contours (and draw them) within that triangle.  Repeat for each triangle, and all contours have been drawn.

There is an open-source project, DelaunatorSharp, (here: https://github.com/nol1fe/delaunator-sharp) which is a C# implementation of the original Delaunator project.  DelaunatorSharp uses the MIT license, so as long as its copyright notice remains intact, the code can be included, adapted, modified, etc in other projects.  That is perfect, since it would likely be necessary to add a Z value to the points (the value to be contoured).  

I was able to add contouring to the demo application in DelaunatorSharp by simply adding the two functions below.  The object PlayGround is a WPF Canvas object.  obviously, an implementation in ScottPlot would require more features, such as labels, colors, changing contour intervals, etc, but this is enough to build the contours, which is the hard part. Contour smoothing is also a whole separate discussion by itself but the rough contours are technically the most accurate interpolation, though not the prettiest.  optional smoothing algorithms could be added later for those who want that but what I have described here would be a good start.

```
private void DrawContours()
{
           RefreshDelaunator();
           delaunator.ForEachTriangle(t =>
            {
                // Find the minimum and maximum Z values of the triangle
                var zValues = t.Points.Select(p => p.Z);
                var minZ = zValues.Min();
                var maxZ = zValues.Max();
                for (double z = Math.Ceiling(minZ); z <= maxZ; z++)
                {
                    var polyline = new Polyline();
                    polyline.Stroke = Brushes.Green;

                    var pt = FindPointAtElevation(t.Points.ElementAt(0), t.Points.ElementAt(1), z);
                    if (pt != null)
                    {
                        polyline.Points.Add(new System.Windows.Point(pt.X, pt.Y));
                    }
                    pt = FindPointAtElevation(t.Points.ElementAt(1), t.Points.ElementAt(2), z);
                    if (pt != null)
                    {
                        polyline.Points.Add(new System.Windows.Point(pt.X, pt.Y));
                    }
                    pt = FindPointAtElevation(t.Points.ElementAt(2), t.Points.ElementAt(0), z);
                    if (pt != null)
                    {
                        polyline.Points.Add(new System.Windows.Point(pt.X, pt.Y));
                    }
                    if (polyline.Points.Count > 1)
                    {
                        PlayGround.Children.Add(polyline);
                    }
                }
              }
}
private IPoint FindPointAtElevation(IPoint startPoint, IPoint endPoint, double elev)
 {
     // If the elevation is outside the range of the edge, return null
     if (Math.Min(startPoint.Z, endPoint.Z) >= elev || elev >= Math.Max(startPoint.Z, endPoint.Z))
     {
         return null;
     }
     // If the elevation is on the edge, return the point
     if (startPoint.Z == elev)
     {
         return startPoint;
     }

     if (endPoint.Z == elev)
     {
         return endPoint;
     }

     // Otherwise, find the point on the edge at the elevation
     var t = (elev - startPoint.Z) / (endPoint.Z - startPoint.Z);
     var x = startPoint.X + t * (endPoint.X - startPoint.X);
     var y = startPoint.Y + t * (endPoint.Y - startPoint.Y);
     return new Point(x, y, elev);
 }
```

**Comment by jon-rizzo** [comment]
to contour a random set of 3D points, I would suggest creating a TIN plot type, rather than modifying the heat map or creating a contour line or iso line plot type.  In its simplest form, the TIN plot type would have a collection of 3D points that are used to build the TIN, where the Z attribute is the value being contoured.  It could be rendered as a collection of polygons (triangles), which means that the TIN could have properties to control the marker style of the points and the line and fill style of the polygons (or each component could be hidden completely).  The plot type would need a contour interval property to control the display of the contours.  a contour interval of zero would mean don't draw the contours. Additional properties could be added to draw fill in the area between contours

**Comment by swharden** [comment]
Completed in #4296
