### ISSUE TITLE
ScottPlot 4, take text labels into account during renders

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#3834]
Recently the library does not respect the text labels bounding space, so when we call render then the autoscaling might cut off the text labels from the screen. 
We could find some solution to address this issue.

**Comment by swharden** [comment]
Hi @bukkideme, I'm leaving this high priory but marking it defer because I want to prioritize getting high priority ScottPlot 5 issues published before looping back around to this.

In case someone gets to it sooner than me, I think the best solution is to add a "LastRenderedRectangle" property to the Label, then write to it inside the render loop. Perhaps it could be stored in pixel units and coordinate units. Pixel units could be used for mouseover hit detection, and coordinate units could be used for autoscaling.

**Comment by swharden** [comment]
Actually, that description of the recommended implementation is good enough that I'll probably close this issue for now, and if someone wants to give it a go I'd be happy to review a PR!
