### ISSUE TITLE
Scatter: Add support for Scale and Offset

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#3835]
There could be an XOffset/YOffset for the Scatter.Data .

**Comment by swharden** [comment]
Implementation suggestion: rather than modify `IScatterSource` and all the different classes that use it, you could add `OffsetX`, `OffsetY`, `ScaleX`, and `ScaleY` properties to the `Scatter` plottable, then intercept this line to scale and shift the collection returned by `Data.GetScatterPoints()`

https://github.com/ScottPlot/ScottPlot/blob/d02126f0366533b8b8d8f1abf94919f2c4e9ce78/src/ScottPlot5/ScottPlot5/Plottables/Scatter.cs#L117

**Comment by swharden** [comment]
... and I guess also add some logic in here so autoscaling is aware of the new properties too

https://github.com/ScottPlot/ScottPlot/blob/d02126f0366533b8b8d8f1abf94919f2c4e9ce78/src/ScottPlot5/ScottPlot5/Plottables/Scatter.cs#L102-L109

**Comment by swharden** [comment]
Done! 🚀
