### ISSUE TITLE
Legend: demonstrate how to toggle visibility when items are clicked

### ISSUE THREAD

**Issue by nilsakesson** [ScottPlot/ScottPlot#3842]
**Suggestion:** (Add functionality to show/hide a plottable with clicking the corresponding legend)

There are similar closed issues to this but there is nothing in SP 5.

Feature: click legend items to toggle visibility #1326
Legend: how to toggle visibility for each plottable #1482
Preferred way to plot numerous SignalPlot #1573
Legend: detach and toggle visibility of plottables (WinForms) #1589

In SP4 winforms there was a possibility to detach the legend from the plot and get the functionality to toggle the visibility of each plottable. It's best described in #1589.
I'm looking for a feature where you can click the legend within the plot to toggle it. 

There is a way to do this in matlab showed below
![ClickableLegend](https://github.com/ScottPlot/ScottPlot/assets/87042707/e081b3b1-2453-4a99-8a19-0e5a30c81227)

**Comment by BambOoxX** [comment]
@nilsakesson Yes, it was a super nice addition, I thought it was already ported in SP5 but I'm missing it there too ! 
@swharden  If you want some help, I might have a bit of time there.

**Comment by swharden** [comment]
I took a look at this tonight with the goal of implementing a solution, but called it off because it will take more time than I'm interested in investing at this time.

I'd be happy to review a pull request if someone decides to give this a go though!

I think the best implementation strategy would be as follows:

Edit somewhere around here:
https://github.com/ScottPlot/ScottPlot/blob/f84ee27e0956cf3dc17f8b8bab807faadcc25a57/src/ScottPlot5/ScottPlot5/Primitives/Legend.cs#L272-L280

...and save a list of `PixelRect` objects, one per rendered legend item.

Then add a method to this class like `GetItemIndexUnderMouse()` so users can add code to their OnClick events like:

```cs
int legendItemIndex = formsPlot1.Plot.Legend.GetItemIndexUnderMouse(pixel);
```

Perhaps return -1 if no item is under the mouse?

Yeah, this doesn't return the _plottable_ under the mouse, but many legend items are not tied to plottables and manual legends exist too, so I'm thinking this is the closest we're going to get without modifying a lot of code to add a nullable plottable to the `LegendItem` class then editing every plottable to tie itself to all the legend items it creates

**Comment by BambOoxX** [comment]
@swharden I'll try and take a shot at this. One question though, is there any obvious link between the legend item and the plottable when a legend is built this way ? 
I think the list of items linked to plottables in terms of indices due to the way the legend items list is built: first plottable linked ones, then manual ones given
https://github.com/ScottPlot/ScottPlot/blob/f84ee27e0956cf3dc17f8b8bab807faadcc25a57/src/ScottPlot5/ScottPlot5/Primitives/Legend.cs#L123-L133
Just wanted to have your opinion to see if this is reliable or not. 
I'll try to revive the detacheable legend as well.

**Comment by swharden** [comment]
> is there any obvious link between the legend item and the plottable when a legend is built this way ?

I don't think so. A new `IPlottable?` property would have to get added to `LegendItem`, and every plottable modified to construct legend items with `this` assigned to it. It's feasible, but a lot of busy work.

> I think the list of items linked to plottables in terms of indices due to the way the legend items list is built: first plottable linked ones, then manual ones given

Yeah, it's not the best option... but it's probably the simplest in a pinch and could do the trick for basic use cases
