### ISSUE TITLE
Vertical lines are disappearing while zooming or panning

### ISSUE THREAD

**Issue by kareem469** [ScottPlot/ScottPlot#3850]
Vertical Lines are disappearing while zooming or panning

ScottPlot Version: 5.0.34

Vertical lines should not disappear while zooming and panning. 
It should remain in the same position until moved.

**Comment by VibrationAnalystCN** [comment]
Different from you, please refer to # 3836

**Comment by swharden** [comment]
Hi @kareem469, thanks for reporting this! However, when I pan and zoom a plot with vertical lines, things look okay. Can you include sample code, a screenshot, or video that helps demonstrate more clearly what your issue is? https://www.screentogif.com/ may help. I'll close this issue for now, but with more information we can open it up again and take a look together. Thanks!

![vline](https://github.com/ScottPlot/ScottPlot/assets/4165489/137455d9-a798-4094-9225-5748fa77bf55)

**Comment by kareem469** [comment]
My requirement is, the vertical line should remain in a same position even after zooming or panning.

It should move based on dragging

**Comment by swharden** [comment]
I understand now! When you pan you want the data and axis limits to move, but you want the vertical axis lines to appear fixed in pixel space.

I think the way to do this is to use events like `OnMouseDown`, `OnMouseMove`, etc. to determine how far the plot has been panned and place the axis line at that place. I think you can use `Plot.GetPixel()` and `Plot.GetCoordinates()` to convert between coordinate space and pixel space. Let me know if you're unable to implement this effect and we can open this issue back up and take a closer look 👍

**Comment by VibrationAnalystCN** [comment]
The vertical line is fixed at the X-axis coordinate, and regardless of how the chart is scaled or dragged, its X-axis coordinate should remain unchanged. I did not find any issues on my platform. I am using Windows 11 and VS2022, and the Scottplot version is 5.0.34

In addition, I posted # 3836, which mentioned that there is no problem with the vertical line, but there is a bug in the x coordinate position of the labeltext.







At 2024-05-22 09:50:27, "kareem469" ***@***.***> wrote:

My requirement is, the vertical line should remain in a same position even after zooming or panning.

It should move based on dragging

**Comment by kareem469** [comment]
> I understand now! When you pan you want the data and axis limits to move, but you want the vertical axis lines to appear fixed in pixel space.
> 
> I think the way to do this is to use events like `OnMouseDown`, `OnMouseMove`, etc. to determine how far the plot has been panned and place the axis line at that place. I think you can use `Plot.GetPixel()` and `Plot.GetCoordinates()` to convert between coordinate space and pixel space. Let me know if you're unable to implement this effect and we can open this issue back up and take a closer look 👍
> 
> Resources:
> 
> * https://scottplot.net/demo/#draggable-axis-lines has very similar code

I tried storing previous X, Y values in mousedown and mousemove and using those values I am updating the vertical line while zooming and panning. It’s updating vertical line at previous position buts redrawing the line everytime (when zoomed or panned) which need to avoid.

**Comment by VibrationAnalystCN** [comment]
kareem469，

Hi,your description is difficult to understand.

Do you need a cursor that can be moved with a mouse and its coordinates remain unchanged when zooming or dragging the chart?













At 2024-05-22 12:45:16, "kareem469" ***@***.***> wrote:

I understand now! When you pan you want the data and axis limits to move, but you want the vertical axis lines to appear fixed in pixel space.

I think the way to do this is to use events like OnMouseDown, OnMouseMove, etc. to determine how far the plot has been panned and place the axis line at that place. I think you can use Plot.GetPixel() and Plot.GetCoordinates() to convert between coordinate space and pixel space. Let me know if you're unable to implement this effect and we can open this issue back up and take a closer look

Resources:

https://scottplot.net/demo/#draggable-axis-lines has very similar code

I tried storing previous X, Y values in mousedown and mousemove and using those values I am updating the vertical line while zooming and panning. It’s updating vertical line at previous position buts redrawing the line everytime (when zoomed or panned) which need to avoid.

**Comment by kareem469** [comment]
> kareem469， Hi,your description is difficult to understand. Do you need a cursor that can be moved with a mouse and its coordinates remain unchanged when zooming or dragging the chart? At 2024-05-22 12:45:16, "kareem469" ***@***.***> wrote: I understand now! When you pan you want the data and axis limits to move, but you want the vertical axis lines to appear fixed in pixel space. I think the way to do this is to use events like OnMouseDown, OnMouseMove, etc. to determine how far the plot has been panned and place the axis line at that place. I think you can use Plot.GetPixel() and Plot.GetCoordinates() to convert between coordinate space and pixel space. Let me know if you're unable to implement this effect and we can open this issue back up and take a closer look Resources: https://scottplot.net/demo/#draggable-axis-lines has very similar code I tried storing previous X, Y values in mousedown and mousemove and using those values I am updating the vertical line while zooming and panning. It’s updating vertical line at previous position buts redrawing the line everytime (when zoomed or panned) which need to avoid. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

The vertical line should remain in same position even after zooming & panning

The line should move only when dragging
