### ISSUE TITLE
Label: incorrect horizontal alignment for multiline strings

### ISSUE THREAD

**Issue by karlipl** [ScottPlot/ScottPlot#3859]
**Question:** Hi, I have a barplot with a multiline label. Is there a way to center each row of the label?
![image](https://github.com/ScottPlot/ScottPlot/assets/9418078/ec29f039-4121-4162-9130-3c18b5357e04)
I would like the following result:
-------Row top
--Row in the middle
-----Row bottom

**ScottPlot Version:** ScottPlot 5.0.34

**Code Sample:**

```cs
Bar[] bars =
{
        new()
        {
            Position = 1,
            Value = 60000,
            BorderColor = Colors.White,
            FillColor = Color.FromHex("E56646"),
            ValueBase = 0,
            Label = $"Row top\nRow in the middle\nRow bottom",
            CenterLabel = true
        },
        new ()
        {
            Position = 1,
            Value = 60000 + 40000,
            BorderColor = Colors.White,
            FillColor = Color.FromHex("68BC5A"),
            ValueBase = 60000,
            Label = $"Row top\nRow in the middle\nRow bottom",
            CenterLabel = true
        }
    };

var barPlot = plot.Add.Bars(bars);

barPlot.ValueLabelStyle.ForeColor = Colors.White;
barPlot.ValueLabelStyle.Bold = true;
barPlot.ValueLabelStyle.FontSize = 16;
```

This is just a snippet of my code. I could provide a minimum full example if needed.

I would really appreciate some help.

Regards
Karl

**Comment by swharden** [comment]
Thanks for reporting this @karlipl! Recently a lot of plottable objects were upgraded to use advanced label styling features, but I think `Bar` got overlooked because it's in the primitives folder and not the plottables folder. I'll use this issue to track adding these features (including alignment).

In a pinch you could place a text object over your bars! Actually, that has the same problem. Here's the code I used to test that:

<details>

```cs
using ScottPlot;

ScottPlot.Plot plot = new();

Bar[] bars =
[
    new()
    {
        Position = 1,
        Value = 60000,
        BorderColor = Colors.Transparent,
        FillColor = Color.FromHex("E56646"),
        ValueBase = 0,
    },
    new ()
    {
        Position = 1,
        Value = 60000 + 40000,
        BorderColor = Colors.Transparent,
        FillColor = Color.FromHex("68BC5A"),
        ValueBase = 60000,
    }
];

plot.Add.Bars(bars);
plot.Add.Text($"Row top\nRow in the middle\nRow bottom", bars[0].Position, bars[0].Value);
plot.Add.Text($"Row top\nRow in the middle\nRow bottom", bars[1].Position, bars[1].Value);

foreach (var txt in plot.GetPlottables<ScottPlot.Plottables.Text>())
{
    txt.LabelFontColor = Colors.White;
    txt.LabelBold = true;
    txt.LabelFontSize = 16;
    txt.Alignment = Alignment.UpperCenter;
}

plot.Title(ScottPlot.Version.VersionString);
plot.SavePng("demo.png", 400, 300).LaunchFile();
```

</details>

I think the core issue is that horizontal centering of multiline labels is failing. Here's a simpler demonstration of this issue:

```cs
ScottPlot.Plot plot = new();
var txt = plot.Add.Text($"aaa\nbbbbbbbbbbb\nccc", 0, 0);
txt.Alignment = ScottPlot.Alignment.MiddleCenter;
txt.LabelBackgroundColor = ScottPlot.Colors.SkyBlue;
plot.SavePng("demo.png", 400, 300).LaunchFile();
```

![demo](https://github.com/ScottPlot/ScottPlot/assets/4165489/86c6d0ff-2185-48f9-b3f3-0787f62b46a4)

I'll mark this issue high priority and use it to track fixing this problem too 👍

**Comment by karlipl** [comment]
Hi, thanks for the reply and working on this.

Regards
Karl
