### ISSUE TITLE
FormsPlot: KeyDown event is not getting fired when press the Left or Right key 

### ISSUE THREAD

**Issue by ddayzzz** [ScottPlot/ScottPlot#3890]
**Issue:** 
`KeyDown` event is not getting fired  when press the Left or Right key in ScottPlot v5.x. I have set the property `KeyPreview` to `true` in its parent `Form`. It seems like issue [3819](https://github.com/ScottPlot/ScottPlot/issues/3819)

**ScottPlot Version:** ScottPlot Version: 5.0.34 in .Net 8.0

**Code Sample:** 

```cs
public Form1()
{
    InitializeComponent();
    this.KeyPreview  = true;
    this.PreviewKeyDown += new PreviewKeyDownEventHandler(formsPlotMain_PreviewKeyDown);
    formsPlot1.KeyDown += formsPlot1_KeyDown;
}
private void formsPlotMain_PreviewKeyDown(object sender, PreviewKeyDownEventArgs e)
{
    switch (e.KeyCode)
    {
        case Keys.Left:
        case Keys.Right:
            e.IsInputKey = true;
            break;
    }
}

private void Form1_KeyDown(object sender, KeyEventArgs e)
{
   // Event is getting fired when pressing Left or Right key
}
private void formsPlot1_KeyDown(object sender, KeyEventArgs e)
{
   // Event is not getting fired when pressing Left or Right key
}
```
In the user

**Comment by swharden** [comment]
Related issue in ScottPlot 4:
* #999

**Comment by CoderPM2011** [comment]
This issue seems to be related to `WinForm` itself.
Most of the solutions I found involve overriding `protected override bool ProcessCmdKey(ref Message msg, Keys keyData)`.

### Reference
- https://stackoverflow.com/a/25697585
- https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.control.previewkeydown?view=windowsdesktop-8.0#remarks
- https://umaranis.com/2013/07/09/handle-arrow-key-events-in-windows-forms-net/
