### ISSUE TITLE
SignalXY: step mode has incorrect off-screen interpolation

### ISSUE THREAD

**Issue by seishinkouki** [ScottPlot/ScottPlot#3894]
**Issue:** (Describe the bug here)
Incorrect rendering of points near the left axis in SignalXY plots with "ConnectStyle.StepHorizontal"

The following gif shows the actual appearance
![scottplot](https://github.com/ScottPlot/ScottPlot/assets/8842321/3bd0a3af-002f-4e70-b430-bb8a69202148)

**ScottPlot Version:** (What NuGet package are you using?)
ScottPlot.Avalonia 5.0.34
**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

```cs
 AvaPlot avaPlot1 = this.Find<AvaPlot>("AvaPlot1");
 int[] xdata = new int[50];
 int[] ydata = new int[50];

 Random randNum = new Random();
 for (int i = 0; i < ydata.Length; i++)
 {
     xdata[i] = i;
     ydata[i] = randNum.Next(0, 2);
 }
 var abc = avaPlot1.Plot.Add.SignalXY(xdata, ydata);
 abc.ConnectStyle = ConnectStyle.StepHorizontal;
 avaPlot1.Refresh();
```

**Comment by StendProg** [comment]
The reason for this error is that the points on the plot boundaries are obtained by linear interpolation of 2 points, one outside and one inside the area being drawn. Step display simply builds a step from each point displayed on the plot, and the point on the boundary is not from real data, but interpolated.

The solution to this problem would be to get the interpolated point in different ways depending on the StepDisplay mode.
In the case of step display we need a simple interpolation to the left/right neighbor instead of linear interpolation
