### ISSUE TITLE
Controls: Zoom region drawing behaves oddly when draw starts outside data area

### ISSUE THREAD

**Issue by MCF** [ScottPlot/ScottPlot#3897]
There is some inconsistent behaviour when drawing zoom regions starts outside the data area.  It is difficult to get specific repeatable behaviour with this, but it does consistently behave _differently_. 

1. Sometimes the zoom rectangle is drawn as you might expect, coming in from the top of side.  the zoom rectangle appears, butted up tight to the axis being crossed as the zoom region is being drawn.  Sometimes the zoom region is applied and the zoom occurs upon click release, sometimes it simply disappears upon release and nothing happens.
2. But sometimes the zoom region immediately becomes very tall or very wide upon entering the data area.  If you draw straight down from above the top axis for example, a long narrow rectangle often is drawn.  These zoom regions never seem to be applied.

I'm not sure what the expected or desired behaviour is here.  Perhaps no zoom rectangle should be started unless the mouse click begins inside the data region?

**ScottPlot Version: 5.0.34**

**Comment by swharden** [comment]
Hi @MCF, thanks for reporting this! I suspect this is the same behavior described by #3810. I'll close this issue

>  desired behavior 

My intent was to have middle-click-drag "zoom window" to only operate on a single axis if the drag was started on that axis. Some of the weirdness happens when drags are started on "invisible" axes that have no data.

I'll close this issue and track the solution in #3810, but let me know if I misunderstood and we can open this one back up and take a closer look 👍
