### ISSUE TITLE
Checkboxes in legend

### ISSUE THREAD

**Issue by Graat** [ScottPlot/ScottPlot#3905]
**Suggestion:** Option to include checkboxes in the legend to turn on&off the visibility of plottables.

Someone else had asked me if this would be possible, and I quite liked the idea, so I wanted to pass it on.

Example plot made in paint:
![image](https://github.com/ScottPlot/ScottPlot/assets/77859733/78fae6b7-0c0a-4fb9-a555-8a25f97f96b8)

**Comment by swharden** [comment]
Hi @Graat, thanks for this question! I assume you're using Windows Forms. I think the best strategy is to place a `CheckedListBox` outside your plot and use it to control visibility of the plotted items. I think you'll need to use `System.Drawing` calls to draw the colored lines on top of each listbox item. You can search for code examples online that use the `OnDrawItem` event to achieve custom functionality. https://www.codeproject.com/Articles/1062442/A-Multi-Color-Multi-Font-CheckedListBox has some advice about this.

I'm going to close this issue since I think the solution is a WindowsForms solution and not a ScottPlot solution, but hopefully this points you in the right direction and if you are able to achieve this effect I'd love it if you could follow-up and share some screenshots and the code you used to achieve it!

Best,
Scott
