### ISSUE TITLE
System.Runtime.InteropServices.RuntimeInformation issue on .NET Framework

### ISSUE THREAD

**Issue by swaitvor** [ScottPlot/ScottPlot#3911]
```
unable to find dependency 'SYSTEM.RUNTIME.INTEROPSERVICES.RUNTIMEINFORMATION'
(Signature='B03F5F7F11D50A3A' Version='4.0.1.0') of assembly ['ScottPlot.dll']
```

![1](https://github.com/ScottPlot/ScottPlot/assets/166271501/2accfd2c-da82-4dbb-b08f-e0f491a40490)

**ScottPlot Version:** Scottplot.Winform 5.0.15

NuGet Package Manager show its depents on System.Runtime.InteropSerices.Runtimelnformation(>= 4.3.0)
![2](https://github.com/ScottPlot/ScottPlot/assets/166271501/b08f96e8-f3e4-4326-a5e1-007ac4f0218c)

**Comment by swharden** [comment]
Indeed, ScottPlot 4 requires System.Runtime.InteropSerices.Runtimelnformation(>= 4.3.0)

https://github.com/ScottPlot/ScottPlot/blob/d003f9a1f19aae487cb03a25becc2d54efd0a2e4/src/ScottPlot4/ScottPlot/ScottPlot.csproj#L88

Perhaps add the https://www.nuget.org/packages/system.runtime.interopservices.runtimeinformation/ package to your project?

**Comment by chhh** [comment]
@swharden I had the same problem.
I had InteropServices.RuntimeInformation 4.3.0 in my project already, that was added to App.config (I was building it for NetFramework 4.8 :((( ) automatically, the error was:
```
System.TypeInitializationException : The type initializer for 'ScottPlot.Fonts' threw an exception.
  ----> System.TypeInitializationException : The type initializer for 'SkiaSharp.SKTypeface' threw an exception.
  ----> System.TypeInitializationException : The type initializer for 'SkiaSharp.LibraryLoader' threw an exception.
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

The issue seems to be with different builds of RuntimeInformation, they were signed differently - maybe somebody re-uploaded that package to nuget? I don't really understand the details of how this works. However:

**Two solutions that did work:**
1. In App.config remove publicKeyToken for dependentAssembly System.Runtime.InteropServices.RuntimeInformation (from: https://stackoverflow.com/questions/40368208/mongodb-client-throws-a-filenotfoundexception-in-mscorlib/52785620#52785620)
2. Just remove the whole dependentAssembly System.Runtime.InteropServices.RuntimeInformation node completely. It then gets resolved to the proper thing automatically/

**Comment by swharden** [comment]
It looks like that dependency is only used here

https://github.com/ScottPlot/ScottPlot/blob/028cd0e79e07af7b9c1d9a10aa09368034561044/src/ScottPlot5/ScottPlot5/Primitives/Platform.cs#L15-L27

Maybe we should use preprocessor directives to always return `OS.Windows` if compiled for .NET Framework, and make the dependency conditional by editing the `.csproj` file?

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives

**Comment by chhh** [comment]
@swharden That sounds like a great idea!
