### ISSUE TITLE
DataStreamer: newest point is not being drawn

### ISSUE THREAD

**Issue by HalChoo** [ScottPlot/ScottPlot#3960]
**Suggestion:**  Hope to add control over how the DataStreamer type of controls are drawn

ScottPlot is a great project and a pleasure to use, but I ran into some problems with it. The thing is, I observed that when I defined a graph of the DataStreamer data type of length 10, adding 13 points to the data source would never connect all the points. The last point cannot be connected.I was working on some oscilloscope like waveform refresh charts, so I wanted to use DataStreamer for some functionality 

The following code and screenshots hope to describe my problem more accurately.

```cs
WpfPlot PlotChart { get; set; }
Plot Plot => PlotChart.Plot;
DataStreamer dataStreamer { get; set; }
private void WpfPlot_Loaded(object sender, RoutedEventArgs e)
{
    PlotChart = sender as WpfPlot;
    dataStreamer = Plot.Add.DataStreamer(10);
    dataStreamer.Data.AddRange(Generate.RandomNumbers(13, 10, 20));
    PlotChart.Refresh();
}
```
![image](https://github.com/ScottPlot/ScottPlot/assets/134126134/1c423716-cc5f-473a-88f4-8f55d3e4b62f)

So if I want to add some kind of control do I need a control method that connects all the points, or what should I do to connect the empty parts into a line?

**Comment by swharden** [comment]
Hi @HalChoo, thanks for reporting this! I effectively recreated the issue with the following code

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        // create a data streamer with 10 points
        var streamer = formsPlot1.Plot.Add.DataStreamer(points: 10);

        // add 13 points to it
        for (int i = 0; i < 13; i++)
        {
            streamer.Add(Generate.RandomNumber());
        }
    }
}
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/c4602d95-e656-46d8-8bbb-54642a5d3101)

**Comment by swharden** [comment]
Following-up, this is the expected behavior. The default view style for data streamer is "wipe" which shows a disconnect between new data and old data at the location where it begins to overlap. These behaviors are easier to observe when you watch live data come in:

```cs
namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    readonly System.Windows.Forms.Timer NewDataTimer = new()
    {
        Interval = 100,
        Enabled = true
    };

    public Form1()
    {
        InitializeComponent();

        var streamer = formsPlot1.Plot.Add.DataStreamer(points: 10);
        streamer.ViewScrollLeft();

        NewDataTimer.Tick += (s, e) =>
        {
            streamer.Add(Random.Shared.Next(-10, 10));
            formsPlot1.Refresh();
        };
    }
}
```

### Default view (wipe)
![streamer-1](https://github.com/ScottPlot/ScottPlot/assets/4165489/6dfc72d5-0412-4404-a978-adcfba288347)

### Scroll Left view

### Additional Information
![streamer-2](https://github.com/ScottPlot/ScottPlot/assets/4165489/36186b87-ce81-4d1b-a966-7d3d0878dcbc)

https://scottplot.net/demo/5.0/#plot-streaming-data

https://scottplot.net/demo/5.0/#plot-growing-data
