### ISSUE TITLE
Calling DateTimeTicksBottom() twice causes crash

### ISSUE THREAD

**Issue by githubkau** [ScottPlot/ScottPlot#4001]
Calling DateTimeTicksBottom() twice causes crash. Infinite TimeSpan is not handled.

**ScottPlot Version:** 5.0.35
```cs
            double[] data1 = ScottPlot.RandomDataGenerator.Generate.RandomWalk(count: 5001, mult: 1);

            var rnd = new Random();
            double[] x_vals = new double[data1.Length];
            for (int i = 0; i < data1.Length; i++)
                x_vals[i] = (DateTime.Now +TimeSpan.FromSeconds(i)).ToOADate();

            //ScottPlot.Plot myPlot = new();
            scottPlot.Plot.Add.SignalXY(x_vals, data1);
            scottPlot.Width = 300;
            scottPlot.Height = 100;
            scottPlot.Plot.Axes.DateTimeTicksBottom();
            scottPlot.Plot.Axes.DateTimeTicksBottom();
```

**Comment by swharden** [comment]
Hi @githubkau, thanks for reporting this!

Here's a simpler way to reproduce this issue

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        double[] ys = Generate.RandomWalk(100);
        DateTime[] xs = ScottPlot.Generate.ConsecutiveDays(100);
        formsPlot1.Plot.Add.Scatter(xs, ys);
        formsPlot1.Plot.Axes.DateTimeTicksBottom();
        formsPlot1.Plot.Axes.DateTimeTicksBottom();
    }
}
```

This is the line that throws:
https://github.com/ScottPlot/ScottPlot/blob/9f9b1147c9b0280074f5504941a3403e6f002a30/src/ScottPlot5/ScottPlot5/TickGenerators/DateTimeAutomatic.cs#L75

```
System.OverflowException: 'TimeSpan overflowed because the duration is too long.'
```

**Comment by swharden** [comment]
Here's the sequence of events causing this issue:

* When the scatter plot is added, its axes are `null` until the first render or autoscale
* When `DateTimeTicksBottom()` is called, it calls autoscale which assigns the new axis to the scatter plot
* When `DateTimeTicksBottom()` is called again, it removes the old axis even though the scatter plot "remembers it"
* At render time the first axis (which is now removed from the plot) never got sized in pixel space, so it has an invalid pixel range, so pixel/coordinate conversions are invalid, resulting in this error

I'll add a fix to check for invalid axis spans to fail gracefully (just showing no ticks) rather than throwing an exception, but calling `DateTimeTicksBottom()` twice before the first render will probably continue to be an issue.

A workaround is to update plottable axes after resetting horizontal axis ticks:
```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        double[] ys = Generate.RandomWalk(100);
        DateTime[] xs = ScottPlot.Generate.ConsecutiveDays(100);
        formsPlot1.Plot.Add.Scatter(xs, ys);
        formsPlot1.Plot.Axes.DateTimeTicksBottom();
        IXAxis xAxis = formsPlot1.Plot.Axes.DateTimeTicksBottom();
        formsPlot1.Plot.PlottableList.ForEach(x => x.Axes.XAxis = xAxis);
    }
}
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/1e5ecf10-ee28-4ac1-8fb3-69ab5d71a44f)
