### ISSUE TITLE
 Annotation and Text，Suggest adding tooltips

### ISSUE THREAD

**Issue by chrisli8899** [ScottPlot/ScottPlot#4028]
**Suggestion:** (Describe your idea here)
Suggest adding tooltips attributes, such as Annotation and Text, sometimes requiring some prompt information
```cs
ScottPlot.Plot myPlot = new();
/* a code sample may improve communication */

var anno = myPlot.Add.Annotation("hell world");
anno.ToolTips = "tooltips msg";

 var text=myPlot.Add.Text("hello world",1,1);
 text.ToolTips = "test msg";


myPlot.SavePng("bug.png");
```

**Comment by swharden** [comment]
Hi @chrisli8899, thanks for this suggestion!

I probably won't implement this on the ScottPlot side because it's GUI-platform-agnostic (and runs in console apps), but users can probably achieve this effect by tracking where the mouse moves and manually opening a tooltip (in WinForms, WPF, WinUI or whatever) based on where the mouse is.

https://scottplot.net/demo/5.0/#show-value-under-mouse shows how to track the mouse position and modify the plot, but the same idea could be used to open a tooltip
