### ISSUE TITLE
How to use `GetNearest()` in plots with multiple axes

### ISSUE THREAD

**Issue by lee38237489** [ScottPlot/ScottPlot#4059]
**Question:** I have multiple axes and multiple lines for each axis. I want to add line annotations to each line. I also need to add an Arrow (and require text). Using GetNearest() cannot correctly obtain the coordinates of each line, so it cannot be achieved. My expected results, or have any better suggestions?
**ScottPlot Version:** 5.0.36
The blue dotted line in the picture below is my expected value
![image](https://github.com/ScottPlot/ScottPlot/assets/29251934/dbf46c47-397e-4c12-b90e-0288abd0bb76)

**My Code :** 

```cs
var myPlot = scottPlotWpf.Plot;
DateTime[] dataX = {
        DateTime.Parse("2024-07-09 12:12:59.100") ,
        DateTime.Parse("2024-07-09 13:13:55.200"),
        DateTime.Parse("2024-07-09 14:11:50.050"),
        DateTime.Parse("2024-07-09 15:11:50.050"),
        DateTime.Parse("2024-07-09 16:11:50.050")};
double[] dataY = { 1, 4, 9, 16, 25 };
var scatter = myPlot.Add.ScatterLine(dataX, dataY);
scatter.Axes.XAxis = myPlot.Axes.Bottom;  
myPlot.Axes.Left.Label.Text = "Primary Y Axis";
scatter.Smooth = true;
scatter.MarkerSize = 5;
scatter.LegendText = myPlot.Axes.Left.Label.Text;

myPlot.Axes.DateTimeTicksBottom();

 var newLeftAxisPoints = new double[] { 2, 6,8, 10, 15 };
 var axesLeft1 = myPlot.Axes.AddLeftAxis();
 var sigLeft1 = myPlot.Add.ScatterLine(dataX, newLeftAxisPoints);

 sigLeft1.Smooth = true;
 sigLeft1.MarkerSize = 5;
 sigLeft1.Axes.XAxis = myPlot.Axes.Bottom;
 sigLeft1.Axes.YAxis = axesLeft1;
 sigLeft1.LineColor = ScottPlot.Colors.Black;

 sigLeft1.LegendText = "New Liner";
 axesLeft1.LabelText = sigLeft1.LegendText;

newLeftAxisPoints = new double[] { 20, 22, 12, 5, 30 };
var sigLeft2 = myPlot.Add.ScatterLine(dataX, newLeftAxisPoints);
sigLeft2.Smooth = true;
sigLeft2.MarkerSize = 5;
sigLeft2.Axes.XAxis = myPlot.Axes.Bottom;
sigLeft2.Axes.YAxis = axesLeft1;
sigLeft2.LegendText = "New Liner1";

scottPlotWpf.MouseDoubleClick += ScottPlotWpf_MouseDoubleClick;

 var MtvsHighlightMarker = myPlot.Add.Marker(0,0);
 MtvsHighlightMarker.Shape = MarkerShape.OpenCircle;
 MtvsHighlightMarker.Size = 15;
 MtvsHighlightMarker.LineWidth = 2;
 MtvsHighlightMarker.IsVisible = false;

scottPlotWpf.Refresh();

private void ScottPlotWpf_MouseDoubleClick(object sender, MouseButtonEventArgs e)
{
    var wpfPlot = sender as WpfPlot;
    if (wpfPlot == null) return;
    var position = e.GetPosition(wpfPlot);
    if (position != null)
    {
        CoordinateRect rect = myPlot.GetCoordinateRect((float)position.X, (float)position.Y, radius:15);
        (var item, DataPoint dataPoint) = GetUnderMouse(myPlot, position.X, position.Y);

        var linerNotNull = item is not null;
        MtvsHighlightMarker.IsVisible = linerNotNull;
        if (linerNotNull)
        {
            MtvsHighlightMarker.Location = dataPoint.Coordinates;
            MtvsHighlightMarker.Color = item.Color;
        }

        wpfPlot.Refresh();
    }
}

private (Scatter obj, DataPoint dataPoint) GetUnderMouse(Plot plot, double x, double y)
{ 
    Pixel pixel=new (x, y);
    Coordinates mouseCoordinates = myPlot.GetCoordinates(pixel);
    var mouseCoordinateRect = myPlot.GetCoordinateRect(pixel,radius:30);

    foreach (var item in myPlot.GetPlottables<Scatter>().Reverse())
    {                
        DataPoint dataPoint = item.Data.GetNearest(mouseCoordinates, plot.LastRender);
        if (dataPoint.IsReal)
        {
            return (item, dataPoint);
        }
    }
    return (null, DataPoint.None);
}
```

**Comment by swharden** [comment]
Hi @lee38237489, I think this line may be the issue:

```cs
Coordinates mouseCoordinates = myPlot.GetCoordinates(pixel);
```

That returns coordinates for the primary axes (left and bottom). Since you're using nonstandard axes (right and bottom) you may have to call the `GetCoordinates()` overload that lets you explicitly pass in the axes you're trying to get coordinates for.

Let me know if that doesn't do the trick!

**Comment by RFBomb** [comment]
I believe I'm running into pretty much the same issue. I copied the code verbatim from the cookbook example for getting a cross hair and highlight text, but the mouse it roughly 1/4" away from a line when it gets places the cross hair. 

While tackling this issue, I was using both scatter plots and signalXY in the same chart. (XY is from a polled signal and scatter is for square wave signals with much less data points). 

I haven't looked into it extensively for the other plot types, but several (most?) don't include an interface or method for GetNearest(). Why isn't this a common interface? What I wound up doing is creating a wrapper class that has various constructors for charts types that have GetNearest(), and check an array of the wrapper objects instead of iterating through the plot. 

That said, I'll report back today in an edit if the line change you recomended fixes my issue.

**Comment by swharden** [comment]
There hasn't been movement on this topic for a while so I'll close it.

Some of these methods have been improved since this was first posted, so there's a good chance this issue may already be resolved.

@lee38237489 I'll be honest, the code sample is overwhelmingly complex. If you can create a code sample I can run in just a few lines that demonstrates the core issue at hand, me or someone from the community would be much more likely to pick this up and try to arrive at a solution!

**Comment by RFBomb** [comment]
@swharden @lee38237489 

The work I put towards the IGetNearest interface should resolve this I think if @lee38237489 uses the latest nuget package. (I had same issue, and it solved it for me)

But also, this line would have to change:

`DataPoint dataPoint = item.Data.GetNearest(mouseCoordinates, plot.LastRender);`

To use `item.GetNearest`, which now will automatically use the correct XY axes on the plottable. (The data doesn't account for those)

If using wpf, @lee38237489 woukd also need to account for wpf scaling, as I did in my example (and in cookbook)
