### ISSUE TITLE
SquareZoomOut: Repeated zooming in and out causes scale to grow

### ISSUE THREAD

**Issue by CoderPM2011** [ScottPlot/ScottPlot#4061]
**Issue:** After applying the axis rule "SquareZoomOut" and repeatedly scaling the chart, it will cause the axis scales to become increasingly larger.

**ScottPlot Version:** 5.0.36
**Code Sample:** Based on Sandbox.WinForms

```cs
formsPlot1.Plot.Axes.Rules.Add(new ScottPlot.AxisRules.SquareZoomOut(formsPlot1.Plot.Axes.Bottom, formsPlot1.Plot.Axes.Left));
formsPlot1.Plot.Add.Signal(Generate.Sin());
formsPlot1.Plot.Add.Signal(Generate.Cos());
```
First
![image](https://github.com/ScottPlot/ScottPlot/assets/7456441/455b9bdb-f437-447a-a4ce-cc64602cf967)

After several large scaling
![image](https://github.com/ScottPlot/ScottPlot/assets/7456441/ce040923-f12b-4dc5-a8a8-1b9be8892cd8)

**Comment by swharden** [comment]
Hi @CoderPM2011, great catch!

This is because ZoomOut and ZoomIn use fractions that "feel good" but don't perfectly reverse each other if applied sequentially. I'm in favor of fixing this! We have to tweak one or both of these numbers to achieve the desired effect:

https://github.com/ScottPlot/ScottPlot/blob/f1a7b316b1fae08d0ffbdb943bed987629f8bf73/src/ScottPlot5/ScottPlot5/Control/StandardActions.cs#L15

https://github.com/ScottPlot/ScottPlot/blob/f1a7b316b1fae08d0ffbdb943bed987629f8bf73/src/ScottPlot5/ScottPlot5/Control/StandardActions.cs#L29

Do you want to try to modify those lines of code and find two numbers that reverse each other?

**Comment by CoderPM2011** [comment]
> Can you clarify what the issue is?

The reason I brought up this issue is that I thought it would simply maintain the grid proportions, and resizing the form wouldn't affect it.😅

Actually, this was discovered while testing the polar coordinate chart.
I repeatedly resized the sandbox form and eventually found that my coordinate chart was reduced to just a single point.
