### ISSUE TITLE
Plan to implement ToolTip feature in ScottPlot 5.0

### ISSUE THREAD

**Issue by parthybhatt** [ScottPlot/ScottPlot#4073]
**Question:** Is there a plan to implement the ToolTip feature in ScottPlot 5.0 in the near future? I see an API to AddToolTip in v4.0 but nothing in v5.0. ToolTip is one of the essential features of my project. Do you recommend I use ScottPlot4 instead?

**ScottPlot Version:** 5.0.36

**Comment by KroMignon** [comment]
Hello @parthybhatt, you should take a look at [`Callout`](https://scottplot.net/cookbook/5.0/Callout/) and [`Annotation`](https://scottplot.net/cookbook/5.0/Annotation/)

**Comment by MarcArmbruster** [comment]
Callout and Annotation are great features. 
Unfortunately, they cannot really replace tooltips.
It would be great if this feature could still be implemented. The feature would make the control perfect (for my purpose) ;-)
Thanks

**Comment by markgr** [comment]
Likewise - having the tooltip is also something I would require

The Scenario I have is that I show a bunch of charts on a dashboard page - with NO Titles, No Axis, No Legend - it's more to be demonstrative of how the trend of various things are going - Storage Size, Cost Evaluation etc - but I want to display Markers on the charts so that when a user hovers over a marker it displays the X and Y information e.g. March - 200gb, or April - $1,000 etc.

**Comment by CoderPM2011** [comment]
> Likewise - having the tooltip is also something I would require
> 
> The Scenario I have is that I show a bunch of charts on a dashboard page - with NO Titles, No Axis, No Legend - it's more to be demonstrative of how the trend of various things are going - Storage Size, Cost Evaluation etc - but I want to display Markers on the charts so that when a user hovers over a marker it displays the X and Y information e.g. March - 200gb, or April - $1,000 etc.

https://github.com/ScottPlot/ScottPlot/pull/4829
The PR has been merged, but no new version has been released yet.
