### ISSUE TITLE
Successive scatter plots don't adjust the X-axis to display all data

### ISSUE THREAD

**Issue by RobertM-413** [ScottPlot/ScottPlot#4098]
I'm using ScottPlot to display some log data in scatter plots.  I've noticed that when I add the first scatter the X-Axis scales in order to fit all of the data, but when I add subsequent scatters this does not happen.  Is there a way I can make this happen?  I have the bottom axis set to display DateTime values if that matters.

I'm using ScottPlot.WPF version 5.0.36.  Thanks!

**Comment by Deson999** [comment]
Hello, suggest to try adding the code: myPlot.Axes.AutoScale(); or myPlot.Axes.AutoScaler.InvertedX = true;

**Comment by garyblythe** [comment]
I have the same issue and I use the Plot.Axes.AutoScale(). I just posted my issue to Discord and I'm a little concerned that there's no traction on your issue in 2 weeks...

**Comment by swharden** [comment]
>  I've noticed that when I add the first scatter the X-Axis scales in order to fit all of the data

Indeed! The very first time a plot is rendered, `myPlot.Axes.AutoScale()` is called automatically. This is what allows plots to good when they are created in console applications. 

This design is because ScottPlot doesn't assume plots are created in interactive GUI applications. Many times (console apps, servers, etc.) a plot is created once and returned as an image. Modifying plots after they are rendered is something that only happens in interactive applications, and those have a few extra considerations (most of which are demonstrated in the interactive demos https://scottplot.net/demo/5.0/)

> but when I add subsequent scatters this does not happen. Is there a way I can make this happen? 

Indeed! Since you're modifying plots after they've been rendered, call `myPlot.Axes.AutoScale()` to force the axis limits to be adjusted to fit the data. Because this operation is a bit costly (it has to iterate every data point, and ScottPlot supports plots with millions of data points) this isn't called more than once at startup, so users who make changes to interactive plots can decide when the best time is to call this method.

> I'm a little concerned that there's no traction on your issue in 2 weeks

This is a fair concern! Issues with code examples and/or screenshots tend to get responses faster from the open source community.
