### ISSUE TITLE
Website: track number of issues opened per week

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#4106]
Add "new issues per week" to https://scottplotstatsstorage.z20.web.core.windows.net/

It will be interesting to know if this value is accelerating, or if it just feels that way because issue complexity is increasing

**Comment by aespitia** [comment]
i think it's partly because on this page it says the recommended way to get support is to open issues
https://scottplot.net/support/

however, i have found the *quickest* way to get answers is through discord.  

but I agree, i have the same issue on a project i'm working on, on the whole, the project is stable, but the issues that now come up are very specific scenarios, which makes it harder to account for in a general way.

**Comment by swharden** [comment]
This is my dream ✨ I wonder if it's achievable lol

![image](https://github.com/user-attachments/assets/d2c69978-ca32-45b7-8d4b-b320ad2785d6)

**Comment by swharden** [comment]
70 new issues in a week? really? 😅

![image](https://github.com/user-attachments/assets/c04c7b2f-4364-410a-8099-107b284cace7)
