### ISSUE TITLE
Crash when resizing window due to System.InvalidOperationException

### ISSUE THREAD

**Issue by niall895** [ScottPlot/ScottPlot#4128]
**Issue:** When resizing the window with a graph that contains, in my case, 5 dataloggers it crashes. It only seems to occur with upwards of 1500 data points on each datalogger, and only when the graph is live (being updated at about 50ms intervals).

That makes me think it could be due to how I am scaling the x axis manually with each data point. These lines are ran after each update:
```
 _numberOfDataPoints++;
WpfPlot.Plot.Axes.SetLimitsX(0, _numberOfDataPoints); 
WpfPlot.Refresh();
```

Also `ManageAxisLimits()` is set to false for each datalogger.

Visual Studio seems to point to line 15 in `Straight.cs` with this excpetion: `System.InvalidOperationException: 'Collection was modified; enumeration operation may not execute.'`

**ScottPlot Version:** NuGet package version is 5.0.36

**Comment by bclehmann** [comment]
That error message comes from a loop over the points and it typically suggests that the collection was changed out from under it. It shouldn't be possible for that loop to modify its own input. That makes me wonder if you're doing something in a separate thread? Changing the data (or possibly the axes, though I'm unsure if LINQ is capable of detecting that issue) in a separate thread could cause this issue. It may just be that you only see this with 1500+ points because the race condition is so unlikely unless rendering takes a non-negligible amount of time.

And since you're on WPF, you don't actually need multithreading to cause this issue, since you don't control when WPF decides it needs to rerender due to (for example) mouse events, which can happen on a separate thread. I haven't touched much of the datalogger code, but I think you may want to look at this FAQ page on multihreaded stuff: https://scottplot.net/faq/async/ This essentially allows you to force renders to wait until you've modified everything you need to modify. @swharden may have more DataLogger-specific tips for you.

**Comment by bclehmann** [comment]
I do wonder if this could be made a little more robust. It might be prudent to introduce locks into `DataLoggerSource` to essentially make `DataLogger` threadsafe, though this may be difficult as it would need to also hold a lock on the plot axes (which are held by the plot class, not the plottable or the source class.

One option to make this race condition drastically less likely is to make this line copy into an array, so the critical section contains only the copy (which should be very quick) and not all the drawing code as well. https://github.com/ScottPlot/ScottPlot/blob/5ccb5e1fa6a1f90798a9e5bd43dd57d25977a87d/src/ScottPlot5/ScottPlot5/Plottables/DataLogger.cs#L123 This does kinda fit with how I think most of the library works, as most plottables are *technically* unsafe to modify on multithreaded GUI controls (i.e. most of them) without locks but the issue is also typically borderline negligible. That may be harder to achieve with dataloggers though, since they're explicitly designed to be updated often.

One of my niche wants for ScottPlot is to make everything threadsafe with no locks in user code at all. Unfortunately, I think Reader-Writer locks are still a little problematic in .NET (especially .NET Framework, which we still support), and we would absolutely want to ensure objects like axes can be read by many threads at once, since writing to them is much more rare than reading from them. And because it would change so much user code it would end up being a ScottPlot 6 (or 7 lol) sorta thing.

**Comment by niall895** [comment]
I'm amazed with how much information you were able to get from my description - you are absolutely right I am running a separate thread that polls for data and adds it to the datalogger objects.

I've implemented skipping render requests from [https://scottplot.net/faq/async/](https://scottplot.net/faq/async/) and it works flawlessly even at very quick intervals.

Thanks for the help
