### ISSUE TITLE
Scroll at YAxis

### ISSUE THREAD

**Issue by VitorKawao** [ScottPlot/ScottPlot#4159]
Hello,

I am using multiple Y axis  (on my image there is 10 signal XY, each one has its YAxis), so it occupies too much space from my plot.  
I would like to know if it is possible to add a scroll viewer at the YAxis area.  
I am using the 5.0 version

![image](https://github.com/user-attachments/assets/34b8601c-f55c-40cd-ab86-2ce1720d10d9)

Best Regards,
Vítor Guedes

**Comment by RFBomb** [comment]
Somewhat unrelated, but I anticipate running into the same issue. I have been able to plot multiple lines in a single plot with what I've written. But I'm unsure how to get it to show like yours.  

Can you post a snippet or example to show how to get multiple Y axes each scaled independently? I couldn't find an example in the cookbook. ( for example, one will scale 0-1, and another might be 0-10000). 

Also, my plot bogs down (5fps rendering) pretty hard with my data, is yours responsive?

**Comment by RFBomb** [comment]
Ok, after some perusing, I don't know how to do this exactly, But I have a clue. The best bet is to create a custom class that inherits from and overrides some stuff in the plot view of your choice (for me it's wpf).

The Plot.RenderManager at some point (I haven't found it) tells each axis to render. So this action will have to be intercepted.

A new control template will have to be created that houses two SKCanvases, one inside of a scrolling view. The easiest things to do might be to have two render packs

**Comment by swharden** [comment]
> A new control template will have to be created that houses two SKCanvases, one inside of a scrolling view. The easiest things to do might be to have two render packs

This sounds pretty advanced 😅 

Actually, this topic came up a looooooong time ago, but it's obviously still relevant today

* https://github.com/ScottPlot/ScottPlot/issues/358

Are you still interested in looking further into this? If so, I'd be willing to help make a demo app to mimic functionality shown here https://github.com/ScottPlot/ScottPlot/issues/358#issuecomment-616859583 and the animation doesn't show it but scrolling the scrollbars pans the plot.

I'll close this for now since there isn't active development on this front, but if you want to put some effort into getting this off the ground I'd be happy to match it! I think I favor using your platform's native controls (WinForms, WPF, etc) rather than drawing those on with SkiaSharp... but actually maybe we could try it both ways and see what works better?

**Comment by swharden** [comment]
Here's some code to get you started if you're interested!

![scroll](https://github.com/user-attachments/assets/3a5b6d57-31bf-4e01-9a3c-671c670424ec)

```cs
public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        formsPlot1.Plot.Add.Signal(Generate.Sin());
        formsPlot1.Plot.Add.Signal(Generate.Cos());

        vScrollBar1.ValueChanged += (s, e) =>
        {
            double scrollbarFrac = (double)vScrollBar1.Value / (vScrollBar1.Maximum - vScrollBar1.LargeChange);
            double centerY = (0.5 - scrollbarFrac) * 3;
            double ySpan = formsPlot1.Plot.Axes.GetLimits().YRange.Span;
            double yMin = centerY - ySpan / 2;
            double yMax = centerY + ySpan / 2;
            formsPlot1.Plot.Axes.SetLimitsY(yMin, yMax);
            formsPlot1.Refresh();
        };
    }
}
```
