### ISSUE TITLE
Generate.Range() accumulates floating point errors

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#4179]
#4119 was a great start, but I noticed that it produces unexpected results due to accumulated floating point error when I call:

```cs
double[] fractions = ScottPlot.Generate.Range(0, 1, 0.05);
```

I expect a value representing 100% but I never get one 😅

**Comment by StendProg** [comment]
Hi @swharden,

0.1+0.2 != 0.3 is widely known.
It's not the accumulation of rounding errors, it's the way floating point numbers are made.
The problem here is that the (0.05) step is rounded to a binary representation during initialization.

1. To get to the last point you can set the number of points instead of the step.

```c#
Range(double from, double to, int n)
{
    return Enumerable.Range(0, n).Select( i => (from - to)  * i / (n-1) + from);
}
```

2. Or you can round off a given step to get to the last point.
```c#
RangeInclusive(double from, double to, double step)
{
    int n = (int)Math.Round( (from - to) / step) + 1;
    return Range(from, to, n); 
}
```
