### ISSUE TITLE
SP5: Context menu and Shift + Right click + Drag feature parity with SP4

### ISSUE THREAD

**Issue by ris-work** [ScottPlot/ScottPlot#4213]
First of all, thank you for developing this. Much graph!

**Suggestion:** Multiple features, including the `Help` entry in the context menu has disappeared when upgrading to ScottPlot 5 (Eto.Forms). Right-click context menu had far more options, including a Help form to navigate the plot. It also had interesting features like Right Click + Ctrl or Alt + Right Click to zoom to have zoom horizontally or vertically only. Opening the plot in a new window was also very helpful. I think it would be great if we could have the previous builtins as SP4 but maybe more configurable as to whether each entry is displayed or not.

Some additions like being able to save in multiple formats have been really helpful!

I have no idea whether it is specific to Eto.Forms. My knowledge regarding WinForms is very outdated.

```cs
/* Normal, minimal ScottPlot code with Eto.Forms */
```

**Comment by swharden** [comment]
Hi @ris-work, thanks for this feedback! Indeed, some features were intentionally omitted in ScottPlot 5 to let users have more control over the behavior of their apps in complex GUI environments.

> Help entry in the context menu

> Right-click context menu had far more options, including a Help form to navigate the plot
> Some additions like being able to save in multiple formats have been really helpful

Users may customize items in the context menu as demonstrated in https://scottplot.net/demo/5.0/#custom-context-menu and that strategy may be used to launch a save file dialog in the GUI platform being used.

> Right Click + Ctrl or Alt + Right Click to zoom to have zoom horizontally or vertically only. 

I think this is now present and enabled by default. Keyboard arrows pan too.

> Opening the plot in a new window was also very helpful

I suspect this has been added since this post was made as well.

> I think it would be great if we could have the previous builtins as SP4 but maybe more configurable as to whether each entry is displayed or not.

"but maybe more configurable" is why I chose to omit these features 😆 We now support WinForms, WPF, Eto, Avalonia, WinUI, Maui, Blazor, and surely more on the way. Every little GUI feature added has to be added (and maintained) times seven. Some actions like opening windows and saving files get pretty dicey on platforms like Blazor which runs in the browser.

Hopefully this helps clarify why things are the way they are today and points you to some resources that could be used to help you customize your app. If you have further recommendations, we certainly welcome them! 👍
