### ISSUE TITLE
How update HeatmapData with different size data?

### ISSUE THREAD

**Issue by xichaoqiang** [ScottPlot/ScottPlot#4239]
If the size of HeatmapData is change how update it?
Same question about scatter plot. 

```cs
private void ChangeData() 
 { 
     Text = $"Updated {++UpdateCount} times"; 
    
     Random rand = new(); 
     for (int y = 0; y < HeatmapData.GetLength(0); y++) 
     { 
         for (int x = 0; x < HeatmapData.GetLength(1); x++) 
         { 
             HeatmapData[y, x] += rand.NextDouble() - .5; 
         } 
     } 
}
```

**Comment by swharden** [comment]
You can use

```cs
formsPlot1.Plot.Remove<ScottPlot.Plottables.Heatmap>(); // remove all heatmaps from the plot
```

Then add a new heatmap with your data of a different size and call `formsPlot1.Refresh()` to redraw the screen.

_For the case of heatmaps note that you can set the values of cells to `double.NaN` and that makes them transprent, so that's an alternative strategy for growing/changing heatmaps_ https://scottplot.net/cookbook/5.0/Heatmap/HeatmapTransparentCells/
