### ISSUE TITLE
Extend `IndexRange`

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#4249]
I recently made an object to represent a range of index values

```cs
public readonly struct IndexRange(int index1, int index2)
{
    public int Index1 { get; } = index1;
    public int Index2 { get; } = index2;
    public int MinIndex => Math.Min(Index1, Index2);
    public int MaxIndex => Math.Max(Index1, Index2);
    public IndexRange Rectified => new(MinIndex, MaxIndex);
}
```

...and I noticed ScottPlot already has some really similar primitives, `IndexRange` and `Range`

It may be a good time to take a closer look at those and make sure they're working as intended and expressive, as well as adding tests to document and lock-in the behavior.

**Comment by RFBomb** [comment]
I proposed an addition to IndexRange in my PR : #4270  where the Length property is set to 0;

```cs 
/// <summary>
/// The IndexRange that represents an empty collection
/// </summary>
public static readonly IndexRange None = new(-1, -1);
```

My PR also introduced this utility method to a `DataSourceUtilities` class: 

```cs
public static IndexRange GetRenderIndexRange(this IDataSource dataSource)
{
    if (dataSource is null || dataSource.Length == 0) return IndexRange.None;
    int min = Math.Min(dataSource.Length - 1, dataSource.MinRenderIndex);
    int max = Math.Min(dataSource.Length - 1, dataSource.MaxRenderIndex);
    if (min > max || min < 0 || max < 0) return IndexRange.None;
    return new IndexRange(min, max);
}
```

While writing that PR, I also realized that the Min/Max index properties do not validate typically. Meanings Max may be less than Min, but also either one may be negative, which would result in an `ArgumentOutOfRangeException` Further, a negative `Min` would be additive to the specified `Max` when calculating the length. 

Due to how record structs initialize when they have a primary constructor, my thoughts were to either remove the primary constructor in favor of a normal one, and perform validation (and length calculation) within that, or do some workaround like this:

```cs
public int Length { get; } = Validate(Min, Max);

/// <summary>
/// <see langword="true"/> if the Min &amp; Max represent valid indexes, otherwise <see langword="false"/>
/// </summary>
public bool IsValid => Min >= 0;
private static int Validate(int Min, int Max)
{
    if (Min == Max && Min == -1) return 0; // special case
    
    if (Min < 0) throw new ArgumentException($"{nameof(IndexRange.Min)} must be at least 0", nameof(IndexRange.Min));
    if (Max < Min) throw new ArgumentException($"{nameof(IndexRange.Max)} cannot be less than {nameof(IndexRange.Min)}", nameof(IndexRange.Max));
    return Max - Min + 1;
}
```

**Comment by RFBomb** [comment]
After further testing and the other work (the PRs merged today) I think the new IsValid check suffices here instead of complicating the construction of the object. (Especially since SignalXY could produce an exception give my above example code, when there actually is no issue with code that follows since IsValid =false in that scenario.)
