### ISSUE TITLE
The axis ticks look blurry

### ISSUE THREAD

**Issue by axiba04** [ScottPlot/ScottPlot#4282]
**Question**:I  encountered a problem, in a usercontrol, I placed a UniformGrid, in which there are 4 wpfPlot, when I change the Columns property of the UniformGrid, the 4 wpfPlot seem to have different clarity.

**ScottPlot Version: 5.0.39**
**Operating System: Windows 10**
**Application Type: WPF**
**.NET Version: NET 6**

**Code Sample:

```xaml
<UserControl
    x:Class="TestMachine.Views.TestView"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:ScottPlot="clr-namespace:ScottPlot.WPF;assembly=ScottPlot.WPF"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local="clr-namespace:TestMachine.Views"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:s="https://github.com/canton7/Stylet"
    xmlns:telerik="http://schemas.telerik.com/2008/xaml/presentation"
    xmlns:tools="clr-namespace:TestMachine.Tools"
    d:DesignHeight="900"
    d:DesignWidth="1600"
    mc:Ignorable="d">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="80" />
            <RowDefinition Height="2.5*" />
            <RowDefinition />
            <RowDefinition />
        </Grid.RowDefinitions>
        <UniformGrid Grid.Row="1" Columns="2">
            <ScottPlot:WpfPlot />
            <ScottPlot:WpfPlot />
            <ScottPlot:WpfPlot />
            <ScottPlot:WpfPlot />
        </UniformGrid>
    </Grid>
</UserControl>
```

**Comment by axiba04** [comment]
![2024-09-21_172431](https://github.com/user-attachments/assets/937f0bb2-55b9-4813-9a0a-a7da1604f17a)
![2024-09-21_172631](https://github.com/user-attachments/assets/c8139332-3394-4a23-9f06-6794e89551a2)

**Comment by bforlgreen** [comment]
Whats happening here is that when laying out the grid into 4 elements, unless the numbers work out evenly, you'll get some elements with whole number sizes, and others with decimal sizes.

e.g if the window width is 100, then 100/4 is 25. Nice whole numbers

but if you resize the window to 99, then it's 99/4 = 24.75. Which probably gets rounded up or down to create the back buffer in SKIA (underlying library). But when presented in WPF, will get stretched (and anti-aliased) again to 24.75, resulting in blurring or pixilation.

As for why some elements are blurry and others are not. This is entirely down to the layout algorithm WPF does for the panel. There is probably some logic where it tries to use whole numbers if possible, but inevitably there will be some elements that must use the remaining space.

As for the workaround.

I always use `UseLayoutRounding="True"` on the root element.

This tells WPF to use whole pixels when laying out the panel (i.e snap to pixels). The downside to this pixel snapping behaviour is that the UI might appear less consistent. For example, you might request a margin of 2, but if that can't be fulfilled (due to now requiring whole number pixels) you might end up with 1 in some places, or maybe 3.

So its a trade-off basically.

**Comment by axiba04** [comment]
Thank you very much, I'm learning WPF and your answer solved the problem I was having.
