### ISSUE TITLE
SignalXY rendering bug （ScottPlot.Avalonia 5.0.39）

### ISSUE THREAD

**Issue by chenjing1294** [ScottPlot/ScottPlot#4297]
**Issue:** 

When you drag the polyline to the right or left with the mouse, the window will become transparent.

https://github.com/user-attachments/assets/07be3770-c06c-401d-b9fc-05bec7d3446d

**ScottPlot Version:** 

ScottPlot.Avalonia 5.0.39

**Code Sample:**

```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:ScottPlot="clr-namespace:ScottPlot.Avalonia;assembly=ScottPlot.Avalonia"
        x:Class="AvaloniaApplication1.MainWindow"
        Title="Avalonia Quickstart" Width="1000" Height="450">
  <ScottPlot:AvaPlot Name="AvaPlot1" />
</Window>
```
```cs
public MainWindow()
{
    InitializeComponent();

    double[] dataX = {1, 2, 3, 4, 5};
    double[] dataY = {1, 4, 9, 16, 25};
    AvaPlot1.Plot.Add.SignalXY(dataX, dataY);
    AvaPlot1.Refresh();
}
```

**Comment by Gauravsinghrajputt** [comment]
Thank you for sharing this opportunity I would love to contribute to this project. The polyline drag to  transparency feature sounds interesting  and I had like to explore it further. Could you assign me this task  So , I can fix that issues properly ??

**Comment by swharden** [comment]
Hi @chenjing1294, your video isn't playing for me. Can you clarify what the issue is? Perhaps https://www.screentogif.com/ would help

@Gauravsinghrajputt you are welcome to create a pull request at any time. An assignment is not required 👍

**Comment by swharden** [comment]
... actually, the video just loaded! I guess it took a few minutes. I'll take a closer look now.

**Comment by swharden** [comment]
I think this is the effect you are describing 

![image](https://github.com/user-attachments/assets/89e3e0de-c300-4a68-903d-0578c92f1bda)

I'm unable to recreate that on my system 😅 so I will lean on the advice (and pull requests) of others to offer a solution! Thanks for reporting this issue though - I really appreciate it, and I wish I could be of more help, but I'll leave this issue here in the hope that someone has a similar issue in the future and discovers a fix 🤞
