### ISSUE TITLE
Need layers

### ISSUE THREAD

**Issue by MhAllan** [ScottPlot/ScottPlot#4405]
This is very nice project but performance is not great! I suggest we need layers so instead of refresh the whole drawing, we just refresh a layer, that will perform much faster. 

Somthin like: plot.Layer(1).Add..  plot.Layer(1).Refresh()

**Comment by swharden** [comment]
Hi @MhAllan, thanks for this suggestion!

> performance is not great

Some large datasets may be a challenge. Ensure you are using `Signal`, `SignalXY`, or `SignalConst` plots instead of `Scatter` plots where possible to achieve high performance with large datasets containing millions of points.

If there's a specific performance issue with another plot type, let us know and we can see about improving it!

> I suggest we need layers so instead of refresh the whole drawing, we just refresh a layer

I don't intend to implement this in the core of ScottPlot at this time, but users may implement this themselves if they wish to have similar behavior. Here are some implementation suggestions that others may find useful:
* To create plottable objects that don't have to redraw every frame, save each render as a SkiaSharp image and only redraw it if the data changes or if the plot dimensions change, otherwise serve the previously-drawn image
* To prevent other parts of the plot from re-rendering (axis ticks, etc.) the plot can be saved as an image and displayed that way, and optionally drawn on according to the requirements for the user's data visualization

I hope it helps!
Scott
