### ISSUE TITLE
Graphics glitch in Maui windows and iOS

### ISSUE THREAD

**Issue by King-Taz** [ScottPlot/ScottPlot#4416]
ScottPlot 5.0.42 in Maui

Has anyone else observed a graphics glitch when panning in Windows and iOS? Android does not appear affected. When panning is started, the plot momentarily jumps off screen and comes back on screen again. The only method that corrects the behavior is to "autoscale" after app loads using context menu. Autoscale and Refresh in the program will not correct the behavior, it has to be autoscale in the plot window.

The maui app is simple. In the XAML 

`    <Grid ColumnDefinitions="*" RowDefinitions="*" Padding="30,20,30,20">
        <ScottPlot:MauiPlot x:Name="MauiPlot1" />
    </Grid>
`
In the code behind, call this method after app initialization

`        private void SimpleDrawPhasorPlot()
        {

            //Create arrow base coordinates used for all vectors
            Coordinates arrowBase = new(0, 0);

            // create arrow 1
            Coordinates arrow1Tip = new(5, 0);
            CoordinateLine arrow1Line = new(arrowBase, arrow1Tip);
            // add a simple arrow
            var arrow1 = MauiPlot1.Plot.Add.Arrow(arrow1Line);
            arrow1.ArrowFillColor = Colors.Red;
            arrow1.ArrowLineWidth = 0;
            arrow1.ArrowWidth = 5;
            arrow1.ArrowheadLength = 20;
            arrow1.ArrowheadAxisLength = 20;
            arrow1.ArrowheadWidth = 20;
            var dl1 = MauiPlot1.Plot.Add.Text("T(1)", arrow1Tip);
            dl1.LabelFontSize = 36;
            dl1.LabelFontColor = Colors.Black;

            //Enable touch
            MauiPlot1.EnableTouchEvents = true;

            //Autoscale
            MauiPlot1.Plot.Axes.AutoScale();

        }`

Without Touch enabled, the behavior is even more erratic. Feel free to add Refresh, it doesn't change anything.

**Comment by KosmosWerner** [comment]
Hi! I just published a PR [here](https://github.com/ScottPlot/ScottPlot/pull/4417), fixing the glitchs you mentioned. I have corrected them, and now everything should work well.

It is no longer necessary to call `MauiPlot1.EnableTouchEvents = true`; it is set according to the platform in the constructor. Also, if the plot appears too large, it can be corrected by adjusting `MauiPlot1.Plot.ScaleFactor = 0.9`, for example, and refreshing, or by reducing the sizes of the objects to be displayed. I hope it will be available in the next update.

Thank you for pointing out this glitch!"

**Comment by King-Taz** [comment]
@KosmosWerner

> I have corrected them, and now everything should work well.

Just got the update, works very well indeed!

**Comment by King-Taz** [comment]
Ported the update using the example plot above to iOS and Android. 

Zoom sensitivity on both platforms is (too) high. Android on the order of 2 or 3. iOS on the order of 20 to 30 (maybe more). Max zoom can be set on iOS but even at setting = 1, the plot zooms in/out too much. In fact, I lost the plot completely at one point.

I also have a need to use 
```
            MauiPlot1.Plot.HideGrid();
            MauiPlot1.Plot.Layout.Frameless();
```
on some plots. In addition to the zoom issue, the above commands disable right/left panning. Windows does not have this behavior and works fine in all cases. I have not ported to MacOS though, which is another target platform for my app, so i can't comment on that.

Any suggestions on how to proceed?

**Comment by KosmosWerner** [comment]
Hi, I think this issue is due to the part I modified: `IgnorePixelScaling = true;` because panning and zooming were not working properly before.

A temporary solution would be to set `MauiPlot.IgnorePixelScaling = false` when initializing the plot. If you could attach an image of the issue, I could look into it later to see what is happening

I hope this temporary solution works!

**Comment by swharden** [comment]
...good points about zoom sensitivity though! I started #4443 to track progress toward adding this feature. It may take me a while to get to it, but if someone gets to it before I do and creates a pull request I would be happy to review it in good time 👍

**Comment by King-Taz** [comment]
Adding ``MauiPlot1.IgnorePixelScaling = false;`` has no effect on zooming or right/left panning

**Comment by KosmosWerner** [comment]
I spent quite some time searching for the issue because the touch controls use `UserInputProcessor` the same way as the mouse, so it didn't make sense that there was only vertical panning

By default, MAUI only returns relative movement, from (0,0) to a position (x,y), and that's where the problem lies. When the screen is pressed (equivalent to a left mouse click), I use `Interactivity.UserActions.LeftMouseDown(Pixel.Zero)`. For some reason, it only moves along the Y-axis, but making a small change like `Interactivity.UserActions.LeftMouseDown(new(1,1))` makes it work, and it moves as expected. This suggests that starting from the origin fails for some reason

Regarding zoom, MAUI returns the scale factor, which indicates the current distance between my fingers compared to the previous one, returning values like 1.04, 1.07, 0.98, etc., which are more natural. `Interactivity.UserActions.MouseWheelUp(pixel)` and `MouseWheelDown` adjust by approximately 1.15 and 0.85. So, if MAUI detects even a slight change, like 1.01, the zoom will increase by 1.15

I'm making the modifications and will submit a PR soon.

**Comment by swharden** [comment]
In the next release, click-drag zoom sensitivity can be changed like this:

```cs
foreach (var response in formsPlot1.UserInputProcessor.UserActionResponses)
{
    if (response is ScottPlot.Interactivity.UserActionResponses.MouseDragZoom zoom)
    {
        zoom.SensitivityX = 10;
        zoom.SensitivityY = 10;
    }
}
```

* #4443
