### ISSUE TITLE
Axes.SquareUnits() causes plots to zoom out when repeatedly resized

### ISSUE THREAD

**Issue by King-Taz** [ScottPlot/ScottPlot#4422]
**Issue:** Plot does not resize as expected when window size changes using SquareUnits feature in Maui.

**ScottPlot Version:** 5.0.42

**Code Sample:** 

In XAML on MainPage
```cs
    <Grid ColumnDefinitions="*" RowDefinitions="*" Padding="30,20,30,20">
        <ScottPlot:MauiPlot x:Name="MauiPlot1" Scale="1"/>
    </Grid>
```
In the code behind, call this method after app initialization
```cs
using Colors = ScottPlot.Colors;

        private void SimpleDrawPhasorPlot()
        {
            //Create arrow base coordinates used for all vectors
            Coordinates arrowBase = new(0, 0);

            // create arrow 1
            Coordinates arrow1Tip = new(5, 0);
            CoordinateLine arrow1Line = new(arrowBase, arrow1Tip);

            // add a simple arrow
            var arrow1 = MauiPlot1.Plot.Add.Arrow(arrow1Line);
            arrow1.ArrowFillColor = Colors.Red;
            arrow1.ArrowLineWidth = 0;
            arrow1.ArrowWidth = 5;
            arrow1.ArrowheadLength = 20;
            arrow1.ArrowheadAxisLength = 20;
            arrow1.ArrowheadWidth = 20;
            var dl1 = MauiPlot1.Plot.Add.Text("T(1)", arrow1Tip);
            dl1.LabelFontSize = 36;
            dl1.LabelFontColor = Colors.Black;

            // force pixels to have a 1:1 scale ratio
            MauiPlot1.Plot.Axes.SquareUnits();

            //Autoscale
            MauiPlot1.Plot.Axes.AutoScale();
        }
```
When app starts, resizing the window several times shrinks the plot. Right click AutoScale after resizing restores correct plot size.

**Comment by swharden** [comment]
Hi @King-Taz, I'm pretty sure the issue is this line:

```cs
MauiPlot1.Plot.Axes.SquareUnits();
```

That calls this method with automatically zooms out to make units square:

https://github.com/ScottPlot/ScottPlot/blob/f6f80714b506fe3fb7b7782e3e34488c30dd6dbc/src/ScottPlot5/ScottPlot5/AxisManager.cs#L942-L946

If you want a different behavior, manually add one of the different axis rules. Perhaps something like this:

```cs
ScottPlot.AxisRules.SquarePreserveX rule = new(Bottom, Left);
MauiPlot.Plot.Axis.Rules.Add(rule);
```

**Comment by King-Taz** [comment]
@swharden , I don't think you're understanding the issue. Perhaps my fault for not explaining adequately.

Running the code above produces this window

![image](https://github.com/user-attachments/assets/a6c02e4e-6fb1-4bc4-b772-b39950417332)


Now, grabbing a window corner, and without letting go, resizing the window to very small size and bring it back to its (approx) original size produces this window


![image](https://github.com/user-attachments/assets/e3cd4302-fb60-47ff-a824-4b7eac0e1a75)

Is this really proper behavior? In fact, By holding the mouse button and repeatedly resizing the window (small - big), the arrow vanishes completely with only the arrowhead remaining.

**Comment by swharden** [comment]
> Is this really proper behavior?

I believe so. This behavior depends on which square axis rule was added (there are 3 options, and the default is to always zoom out which I think is the behavior you are describing):
* https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5/AxisRules/SquareZoomOut.cs
* https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5/AxisRules/SquarePreserveY.cs
* https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5/AxisRules/SquarePreserveX.cs

Maybe the missing piece is that you can add both "PreserveX" and PreserveY" rules and that will get you where you want to be?

This is described and demonstrated in https://scottplot.net/demo/5.0/#axis-rules which is WinForms but the API is identical in WPF, Maui, and all plot controls.

I hope this helps!

**Comment by swharden** [comment]
If you've tried all 3 axis rules (and the X and Y one together) and it still doesn't work, let me know and I'll try to replicate this behavior in WinForms and help come up with a solution and document it here, in the demo app, and on the website.

I'll re-open this issue and am interested to hear what you find!

**Comment by King-Taz** [comment]
You are correct, this is expected behavior. I only had to preserve 1 axis (chose Y), used demo coding method.

```
SquarePreserveY rule = new(xAxis: MauiPlot1.Plot.Axes.Bottom, yAxis: MauiPlot1.Plot.Axes.Left);
MauiPlot1.Plot.Axes.Rules.Clear();
MauiPlot1.Plot.Axes.Rules.Add(rule);
```

I just thought it strange not to preserve the axes by default! Many thnaks, you've been a great help!

**Comment by KosmosWerner** [comment]
I've seen the same behavior in WPF and WinForms; it can also be observed in the Demo
![Rec004](https://github.com/user-attachments/assets/a8f27ef4-f3d3-42f2-bc22-2ad18810c6ae)

Instead of `MauiPlot1.Plot.Axes.SquareUnits()`, you can use this:
```csharp
ScottPlot.AxisRules.SquarePreserveX preserveX = new(MauiPlot1.Plot.Axes.Bottom, MauiPlot1.Plot.Axes.Left);
MauiPlot1.Plot.Axes.Rules.Add(preserveX);
```
Or...
```csharp
ScottPlot.AxisRules.SquarePreserveY preserveY = new(MauiPlot1.Plot.Axes.Bottom, MauiPlot1.Plot.Axes.Left);
MauiPlot1.Plot.Axes.Rules.Add(preserveY);
```
Since if both are added, the first one added will be the one that takes effect

![Rec003](https://github.com/user-attachments/assets/867798c4-d807-4a62-9306-b6f8650f33b1)

@King-Taz optionally, if for mobile devices you find that `SquarePreserveX` works better than `SquarePreserveY`, or vice versa (a different behavior from the desktop), you can assign the Rules according to the platform, as the width will change on devices each time the orientation changes...
```csharp
if (DeviceInfo.Idiom == DeviceIdiom.Desktop)
{
    // Your rules here
}
else
{
    // Your other rules here
}
```
`SquareUnits()` works best for plots with a fixed size

This should resolve that behavior. I hope this was helpful!

**Comment by swharden** [comment]
Thanks for the addition info @KosmosWerner!

This topic has come up before, so I'll see if I can make an improvement to make the default behavior less surprising. I'll try to add an argument to mimic the `DeviceInfo` strategy from the previous comment.

**Why is the default behavior "zoom out"?** It's because if it's one of the options that preserves X or preserves Y, the first "AutoScale" may fail to show all data on the screen.

**What is causing this problem?** Unlick click-drag panning and zooming which stores the axis limits at the mouse down position, resizing the user control don't store the "axis limits for the original size", so the plot doesn't know how to return to the original axis limits when a plot is shrunk and expanded again.

**Better solution?** I don't think most platform controls have "click-drag resize started" and "click-drag resized" events, but if we could simulate these somehow then we could fix this issue and present users with more natural behavior by saving AxisLimits when the resize was restarted then returning to those limits in the resize events before the axis rules are applied. I don't intend to dive into this right now, but if someone figures it out I would be happy to implement the solution across all the controls

**Comment by swharden** [comment]
> you can assign the Rules according to the platform

This is how I did it in #4426 but if you think of a better way let me know and we can refine this

```cs
IAxisRule rule = Plot.PlotControl is null
    ? new AxisRules.SquareZoomOut(Bottom, Left) // best for console apps
    : new AxisRules.SquarePreserveX(Bottom, Left); // best for interactive apps

Rules.Add(rule);
```

**Comment by King-Taz** [comment]
Thanks for all this help! Yes, I discovered the mobile issue. Desktop will have the same issue in portrait mode. Generally, I found you want to Preserve the axis that has the lower pixel density (I believe that's the correct terminology). Landscape mode needs to PreserveY while portrait mode needs to PreserveX. However, axis Preserve also depends on the plot extents. 

In landscape with PreserveY, a horizontal arrow (length 5 units) looks like this

![image](https://github.com/user-attachments/assets/28e12abb-f14d-414d-be58-e69419a1aba9)

In landscape with PreserveX, the same arrow looks like this

![image](https://github.com/user-attachments/assets/cd32f2ba-e700-41af-9e8e-b52d2020774e)

So, all these things have to be checked including run-time mode mode changes in mobile devices, which are common in my app. I was expecting SquareUnits (along with AutoScale) to account for this since ScottPlot already has plot extents, monitors redraw, and (presumably) checks Idiom.  It would be a great feature and benefit to Users if SquareUnits behaved this way. Please consider this in future releases!

**Comment by swharden** [comment]
> I found you want to Preserve the axis that has the lower pixel density

Good observation! If you're inspired to write some code for that, you could create something like a `SquareUnitsPreserveAuto` class that reads `rp.DataRect` width and height to decide which axis to preserve.

If you create a pull request, I can merge it quickly and release it in the next NuGet package going out today 🚀

**Comment by swharden** [comment]
... actually looking over the code of this

https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5/AxisRules/SquareZoomOut.cs

it should be pretty easy to make a `SquarePreserveSmallestAxis` rule, and if you add that in with a pull request (or even paste the code here so I can add it) I'll make that the new default when users call `SquareUnits()` in plots used inside interactive controls

**Comment by King-Taz** [comment]
I don't know (or can imagine) all the possible use scenarios, but would argue for the "new code" to be part of SquareUnits. Only a suggestion!
