### ISSUE TITLE
SVG: XML contains duplicated content

### ISSUE THREAD

**Issue by sunefred** [ScottPlot/ScottPlot#4436]
**Issue:**

I am using ScottPlot to render plots in PDFs using QuestPdf. I was confused why the render time in QuestPdf was so much higher than expected - until I noticed that the SVG produced by `GetSvgXml` and `GetSvgHtml` is duplicated fives times! That is, it contains the initial `svg` element and then the content is repeated five times 

```xml
<?xml version="1.0" encoding="utf-8" ?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="400" height="300">
    <rect fill="white" width="400" height="300"/>
    ...
    <rect fill="white" width="400" height="300"/>
    ...
    <rect fill="white" width="400" height="300"/>
    ...
    <rect fill="white" width="400" height="300"/>
    ...
    <rect fill="white" width="400" height="300"/>
    ...
</svg>
```

**ScottPlot Version:**

5.0.43

**Code Sample:**

```cs
using ScottPlot;

var plt = new Plot();
var svgString = plt.GetSvgXml(400, 300);

Console.WriteLine(svgString);
```

The repeated content overlays each other perfectly, so it is not visually noticeable. You have to inspect the SVG output.

**Comment by swharden** [comment]
Great catch @sunefred! I think this happens because the first render loops a few times to get the layout right (e.g., figure padding depends on tick label size, tick labels depend on data area size, and data area size depends on figure padding).

A fix may be to force the first render to happen in memory, then render once onto the SVG. You could try adding this line:

```cs
RenderInMemory(width, height);
```

to the top of this method:

https://github.com/ScottPlot/ScottPlot/blob/ede0a913b6cedc116392a3f57c1764554a07ab90/src/ScottPlot5/ScottPlot5/Plot.cs#L329-L337

If it works and you create a pull request, I can merge it in right away! Thanks again for reporting this 👍

**Comment by sunefred** [comment]
@swharden Thanks for your prompt reply. There seem to be two issues involved:

1. It seems unreasonable to me that SVG should ever be added to the canvas for each render. There is a flag there `ClearCanvasBeforeEachRender` in the code you referenced that is intentionally set to `false`. I would assume it should be set to `true` for SVG rendering, but changing it did nothing. Could I get an explanation what this one is meant to do?

2. The reason the SVG is added _exactly_ five times to the canvas, is that the `AxisLimitsChangedSinceLastRender` never returns false for "unused" axes, i.e. axis without data. The min/max values will alternate between -Infinity/Infinity and Infinity/-Infinity. 

https://github.com/ScottPlot/ScottPlot/blob/ede0a913b6cedc116392a3f57c1764554a07ab90/src/ScottPlot5/ScottPlot5/Rendering/RenderManager.cs#L171-L189

The workaround for this issue is to remove any axes you are not using. It will then work as expected and only render SVG into the canvas once.

I wouldn't mind contributing, but these causes seem to be tightly coupled to rendering and I am worried I will break some other type of rendering.
