### ISSUE TITLE
WPF: modifying display device settings while app is running causes crash

### ISSUE THREAD

**Issue by kwonganding** [ScottPlot/ScottPlot#4437]
**Issue:**
When using multiple screens, switching the display device causes the program to crash.
- With two monitors connected and the projection mode set to "Extend," the program runs normally.
- However, when changing the screen projection mode to "PC screen only," the program freezes and crashes.

**ScottPlot Version**: 5.0.43

**The type of control used: ScottPlot.WPF.WpfPlotGL.**
WpfPlot does not have this issue.

**Comment by swharden** [comment]
Thanks for reporting this @kwonganding!

I think there is a typo in the last line of your message... Can you clarify whether this affects the normal control or the opengl control? 

Thanks!

**Comment by swharden** [comment]
... also if the crash has an error message (or better yet the full message of an exception), if you could paste that here it would be really helpful 👍

**Comment by kwonganding** [comment]
The type of control used: ScottPlot.WPF.WpfPlotGL.
**WpfPlot** does not have this issue.
-- sorry，I remember modifying it， I might have forgotten to commit.

**Comment by swharden** [comment]
Hi @kwonganding, thanks for the follow-up!

> When switching displays, the program freezes (no response) with no error message.

In my case it just went black, but clicking and dragging the control to pan made it appear again. Is this the same behavior you experience? If so, perhaps you can detect the display change then force a redraw.

This page may be helpful for that?
https://stackoverflow.com/questions/11983111/detect-when-new-display-is-connected

I think this may be out of the scope of "ScottPlot" since the behavior in question is `SKGLControl` and is part of the SkiaSharp package managed by Microsoft. I'll close this issue for now, but if it turns out there's something concrete I can do to make this better let me know and we can open this back up and implement a fix 👍
