### ISSUE TITLE
I have a proposal.

### ISSUE THREAD

**Issue by CBrauer** [ScottPlot/ScottPlot#4461]
**Suggestion:** 

I have a proposal.

Users of LLM's quickly learn that AI systems are confused by having both ScottPlot 4 and ScottPlot 5 on the net.  Even if you tell the LLM not to use ScottPlot 4, they still give bad code advice.

Please deprecate ScottPlot 4. There will always be users that refuse to move forward. Give them 30 days to download the source code.  After that, it will disappear from the net.

I believe that you will be providing a great service to you user base if you do this.

Charles

**Comment by swharden** [comment]
haha, mega hot take here: I'd _much_ rather deprecate .NET Framework support 👿 Supporting that aging platform causes a lot of ongoing pain, and takes tons of time away from me which could otherwise be invested improving the library for everyone who uses modern .NET

I've chosen to continue to support all officially supported .NET platforms, and it appears that means .NET Framework will continue to be a supported target for a long time. There is no end date in sight. 
* https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-framework
* https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core
