### ISSUE TITLE
SignalConst: Update GetAxisLimits() to include data offsets

### ISSUE THREAD

**Issue by matej-mnoucek** [ScottPlot/ScottPlot#4485]
**Issue:** Some days ago, we have successfully exposed `Data` property of SignalConst (https://github.com/ScottPlot/ScottPlot/pull/4440). Now `XOffset` can be set from the outside but it's still not taken into account. 

**ScottPlot Version:** ScottPlot.WPF, 5.0.44 

**Code Sample:**
```cs
    var ys = [1, 2, 3, 4, 5]
    var period = 1;
    var offsetX = 100;
    
    // With Signal, the offset works fine
    var signalPlot = plot.Plot.Add.Signal(ys, period)
    signalPlot.Data.XOffset = offsetX;
    
    // For SignalConst, offsetX has no effect
    var signalConstPlot = plot.Plot.Add.SignalConst(ys, period)
    signalConstPlot.Data.XOffset = offsetX;
```

**Comment by StendProg** [comment]
It is very strange that `Signal<T>` and `SignalConst<T>` have different implementations. In fact, they should differ only in the way of finding the minimum and maximum for the X range. This is provided by GetLimitsY(int firstIndex, int lastIndex) method.

It is easy to do this through inheritance by removing almost all duplicate code from SignalConstDataSource (SignalConstPlottable). But I am still not completely clear about the reason and current differences in capabilities between these 2 types of Plottable.

I will try to implement the above if there are no objections.

**Comment by swharden** [comment]
Hi @matej-mnoucek, 

I tested your code (adapted for simplicity) and the offsets work as expected

```cs
var sig1 = formsPlot1.Plot.Add.Signal(Generate.Sin());
sig1.Data.XOffset = 100;
sig1.Data.YOffset = 100;

var sig2 = formsPlot1.Plot.Add.SignalConst(Generate.Cos());
sig2.Data.XOffset = 100;
sig2.Data.YOffset = 100;
```

![image](https://github.com/user-attachments/assets/40b7f2cb-b241-411f-ab2b-bd24a84f82f4)

There _is_ an issue where the default automatic axis limits isn't working as well as expected though, so I'll use this issue to track a fix for that.

**Comment by swharden** [comment]
> It is easy to do this through inheritance by removing almost all duplicate code from SignalConstDataSource (SignalConstPlottable?). But I am still not completely clear about the reason and current differences in capabilities between these 2 types of Plottable.

> I will try to implement the above if there are no objections.

Hi @StendProg, if you wish to add inheritance to this system I would be happy to review a pull request!

I believe the reason this inheritance was not brought from ScottPlot 4 is because very early in ScottPlot 5's development I wanted to get a minimal functioning `Signal` plot working while I experimented with the ScottPlot 5 API. I recall finding it difficult to copy signal plot code from ScottPlot 4 because the inheritance system was somewhat complex. I don't remember for sure, but I think that support for both fixed-length arrays and variable-length lists (a ScottPlot 5 feature) is one of the factors that made it difficult.

Now that the major plot types are present and the API has matured, I am happy to investigate ways to use inheritance (favoring composition where possible) to minimize logic duplication.
