### ISSUE TITLE
WPF Demo of ScottPlot5,  the operation is relatively slow

### ISSUE THREAD

**Issue by mytudousi** [ScottPlot/ScottPlot#4494]
**Question:** 
When I run WPF Demo of ScottPlot5,  the operation is relatively slow.  When I run WinForm Demo, the operation is very smooth. I don't know why?

**ScottPlot Version:** 5.0.44
![image](https://github.com/user-attachments/assets/c2149b00-3536-48d8-bff7-d909c3ad40d1)

**Comment by swharden** [comment]
Hi @mytudousi, thanks for this feedback!

I've found it can be slow (1) during resizing and (2) while the debugger is attached and (3) if using the OpenGL control on systems which do not support it. I suspect these behaviors are outside of our control, and perhaps a performance front that could be advanced by the SkiaSharp team that manages the `SKControl`.

When it comes to typical operation (panning and zooming) I've found performance to be similar. Is this also what you found?

Note that you can evaluate performance by double-clicking the plot and a benchmark will appear in the corner of the plot

**Comment by mytudousi** [comment]
hi @swharden  thanks for this feedback!
After reading your reply, I thought is it my own computer problem? I did the test with another computer, and the performance of the WPF version is the same as that of the Winform, there is no problem. So it seems that something is wrong with my computer. I'll keep testing and find out why. Thanks again for your feedback.

**Comment by swharden** [comment]
> So it seems that something is wrong with my computer.

Haha, I'm so happy you figured this out because this is the kind of thing I could accidentally spend days troubleshooting 🤪 

I think WPF has the ability to use DirectX for rendering and and can utilize hardware acceleration which makes performance a complicated thing to debug and compare across different computers which have different gear, and the possibility of misconfiguration of drivers and whatnot makes it even more complicated.

I'm so glad you were able to figure this one out! Thank you so much for following-up and sharing your findings

> the performance of the WPF version is the same as that of the WinForms, so there is no problem

This is the best "bug fix" ever 😇

**Comment by swharden** [comment]
Hi @mytudousi, thank you for this fantastic follow-up! I learned a lot from your message, and it's great to have this documentation here for others to find who may encounter a similar issue.

Additional resources:
* [`RenderMode` Enum](https://learn.microsoft.com/en-us/dotnet/api/system.windows.interop.rendermode) (MS docs)
* [Use `RenderCapability.Tier` to set `ProcessRenderMode`](https://stackoverflow.com/questions/4951058/software-rendering-mode-wpf) (StackOverflow)
