### ISSUE TITLE
Signal: how to get the vertical range (not just point) near the cursor

### ISSUE THREAD

**Issue by NiRott** [ScottPlot/ScottPlot#4496]
In analogy to your function  AxisLine.IsUnderMouse in the example of draggable axis lines(cookbook 5.0.36), I tried to do the same with signal plots. The only problem is that I only find points and no lines. Is there is probably a better solution?

**ScottPlot Version:**  5.0.44

```cs
private int GetIndexOfSignalPlot(Pixel mousePixel)
{
    Coordinates coord = SP.Plot.GetCoordinates(mousePixel);

    double Mindistance = double.PositiveInfinity;
    int IndexNearest = -1;
    for (int i = 0; i < SignalPlots.Count(); i++)
    {
        var Index = SignalPlots[i].GetNearestX(coord, SP.Plot.LastRender, float.MaxValue);
        if (plotViewModel.ListView_Model.Count > i) plotViewModel.ListView_Model[i].ChannelValue = Index.Y.ToString();
        if (!SignalPlots[i].IsVisible) continue;
        DataPoint nearest = SignalPlots[i].GetNearest(coord, SP.Plot.LastRender);
        if (nearest.IsReal)
        {
            double distance = Math.Sqrt(Math.Pow(nearest.X - coord.X, 2) + Math.Pow(nearest.X - coord.X, 2));
            Log.WriteDebug(i.ToString(), distance.ToString());
            if (distance < Mindistance)
            {
                Mindistance = distance;
                IndexNearest = i;
            }
        }
    }
    return IndexNearest;
}
```

**Comment by NiRott** [comment]
I don't think I've explained my problem properly. The function works, it finds the signal plot that is closest to the mouse coordinate if the sample points are close enough together. But if I click on a line segment whose endpoints are too far away, I would still have to calculate the course of the signal plot.

By the way, my GetLimitsY does not take any parameters

**Comment by StendProg** [comment]
Hi @NiRott,

Are you trying to find hits in linear segments of the signal?
This is not an easy task and was rejected due to complexity.
If you are still serious about it, you can look up the developments in #1111 

https://github.com/ScottPlot/ScottPlot/pull/1111/files#diff-4eb2bc05f3892fceefba0a3997cc14528d5a42d290950c57e70446e884893a2c ). 
They are badly outdated, but there they implemented snap-based intersection checks with segments.

**Comment by NiRott** [comment]
The maths would be simple. Find the two neighbouring x-values. Compare whether we are between the y-values and then calculate the distance to the line between them.

**Comment by StendProg** [comment]
> The maths would be simple. Find the two neighbouring x-values. Compare whether we are between the y-values and then calculate the distance to the line between them.

It actually gets more complicated when you want to look for intersections with extra margin. And you'll want to do that for a comfortable user experience.
For Signal Plottable, a range of a few pixels, depending on the density of the data, may contain thousands of segments that need to be checked. For a Scatter, you will have to check absolutely every segment. Therefore, you will want to have a fast algorithm. 
Finding the distance to a segment is more complicated than the distance to a line:
1. You need to find the distance to a line.
2. You need to check that the projection of the point on the line lies inside the segment.
3. If it doesn't, you need to find the distance from the point to the nearest end of the segment.

Then it is not clear what to compare this distance to, when you have different SnapX and SnapY values.
If you make inaccuracies/errors/assumptions in the algorithm that give an approximate result, this will very quickly and easily become apparent when interacting.

In the PR #1111, a slightly different approach is proposed. The segment is converted into 2 parallelograms, one is obtained by thickening the segment by SnapY in height, the other by thickening it by SnapX in width. Then we look for a point hitting inside any of these parallelograms.
We are left with an unchecked rectangle with sides (SnapX, SnapY) around each end of the segment, this is checked separately.
So if we hit any of these primitives, the point is closer than on Snap to the segment we are looking for (it hits it taking into account Snap). And you can set different SnapX and SnapY.
There are no distance calculations (square roots are slow) and it works fast enough.

**Comment by swharden** [comment]
Hi @StendProg, I want to start by thanking you for creating the graphic in your last comment - it really helps communicate the implementation! Also, I appreciate that a large amount of work and thought went into #1111 (and discussion in #1002), and I always feel disappointed when a lot of effort goes into a pull request that doesn't get merged.

Quickly reviewing some of that old discussion, the reason that PR didn't get merged back then was because I was trying to minimize the amount of "interactivity logic" that goes into the code of plottables, because there's a large maintenance burden with those features - they add a lot of additional complexity, can be cumbersome to test, and once added to one plot type users may expect similar functionality in all the various plot types (e.g., diagonal line detection for scatter plots).

However, since ScottPlot 5 shifted mouse interaction logic largely to the user, perhaps a draggable signal plot may be achieved without requiring any changes to the ScottPlot library. If you or someone else creates an example of this (ideally using the parallelogram strategy outlined above, using #111 as reference) I would be happy to include it in the demo app.

I'll close this issue for now since I think the path toward a solution has been sufficiently outlined, but if someone picks up this work and creates code to solve the problem, I would be happy to look it over and include it in the demo app and perhaps add pages to the website describing this technique.

Thanks again for all of your input 👍

**Comment by StendProg** [comment]
https://github.com/user-attachments/assets/010c80d1-bed0-4cdb-ba5a-6069aa0c1995
