### ISSUE TITLE
Axis inversion is controlled by its own Inverted property

### ISSUE THREAD

**Issue by CoderPM2011** [ScottPlot/ScottPlot#4499]
**Suggestion:** `Axis` inversion is controlled by its own `Inverted` property.

This suggestion is to simplify range types. 

`CoordinateRange` only records the corrected range and does not include the meaning of inversion, so `IsInverted`, `Span`, `Value1`, and `Value2` can be removed.

However, there are many types with connotation reversal, which also need to be adjusted accordingly, for example: `AxisLimits`.

But I think the **inversion** implicit in `Range` is the cause of many bugs. 🤔

**Comment by swharden** [comment]
Hi @CoderPM2011, thanks for this suggestion!

> But I think the inversion implicit in `Range` is the cause of many bugs. 🤔

I agree with you 100%! Even since you commented this a new issue related to an inverted axis bug was reported (#4513)

Consistent with https://github.com/ScottPlot/ScottPlot/pull/4394#issuecomment-2466304431 I think the best solution here will be to stop using `CoordinateRange` for axis management, and instead create an `AxisRange` type specifically for this purpose. 

I don't intend to make that change right now because it will be very time intensive (I expect changing `CoordinateRange` to cause many complex bugs that are hard to test, especially related to mouse interactivity) and I want to focus on some other high priority issues in the short term, but it is definitely a goal for the future of this library.

**Comment by swharden** [comment]
Following up on this topic, it turns out the fix for #4394 was complicated by a bug introduced by the last inverted axis modification 🤪 

Check out this fix ... 81b8e113bff4e360fabda437c34d66694e469644 

I'm not sharing this to make you feel bad - I didn't catch it either until now - but this is the type of bug we have to manually investigate throughout the entire code base when changes are made to behavior of primitives 😅 and that is a huge amount of work and it's prone to error, which is why I'm super hesitant to undertake such a task.

**Comment by CoderPM2011** [comment]
> I'm not sharing this to make you feel bad - I didn't catch it either until now - but this is the type of bug we have to manually investigate throughout the entire code base when changes are made to behavior of primitives 😅 and that is a huge amount of work and it's prone to error, which is why I'm super hesitant to undertake such a task.

No worries, I understand how tricky this issue is since it goes so deep into the core functionality. 😓
Honestly, I also feel a bit lost when it comes to tackling this problem because most of my attempts inevitably break a bunch of unit tests. 😅
Even after making changes, there's a risk that the altered behavior could cause existing user programs to fail due to changes in semantics. 😥
So, this fix might take a long time to address and might even have to wait until the next incompatible version. 🙄

**Comment by swharden** [comment]
> So, this fix might take a long time to address

FYI, this is the strategy I was thinking of. I won't do it now, but maybe over the Christmas break in case it takes a lot more time than I expect (because I want to add tests as I go to ensure this doesn't happen again)...

* Split `CoordinateRange` into 3 types with distinct use cases
  * `AxisRange` - carefully designed to clearly work with invertible ranges
  * `CoordinateRangeReversible` - for non-axis use cases (very few)
  * `CoordinateRangeAscending` - for non-axis use cases (very few)
* Delete `CoordinateRange` and watch everything break ☠️ 
* Work through all the compiler errors, carefully replacing everything with one of the three new classes according to its use case.
* Add `CoordinateRange` back so typical users won't experience breaking changes, but be mindful not to lean on it with our internal code. Tests could be added to enforce this in the core library. Perhaps the 3 types above could even inherit this class.
