### ISSUE TITLE
WPF plot control resize leads to chart becoming smaller

### ISSUE THREAD

**Issue by Fruchtzwerg94** [ScottPlot/ScottPlot#4502]
**Issue:** Resizing the WPF plot control repeatly leads to pie chart becoming smaller due to the axis range steadily increases:
![ResizeBug](https://github.com/user-attachments/assets/5db8f4e5-9c0b-44d8-bb84-47537a6bf9b2)

**ScottPlot Version:** 5.0.44 (latest)

**Code Sample:**
Create a new .net8.0 WPF project with a minimal window:
```xaml
<Window x:Class="ScottPlotTest.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:ScottPlot="clr-namespace:ScottPlot.WPF;assembly=ScottPlot.WPF"
        Title="MainWindow" Height="450" Width="800">
    <ScottPlot:WpfPlot x:Name="Plot"/>
</Window>
```

```cs
using System.Windows;

using ScottPlot;

namespace ScottPlotTest
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            List<PieSlice> slices = new()
            {
                new()
                {
                    FillColor = Colors.Red,
                    Value = 10
                },
                new()
                {
                    FillColor = Colors.Yellow,
                    Value = 20
                },
                new()
                {
                    FillColor = Colors.Orange,
                    Value = 30
                }
            };
            Plot.Plot.Add.Pie(slices);
        }
    }
}
```

**Steps to reproduce:**
Use the mouse to repeatly resize the window up and down.

**Comment by swharden** [comment]
Hi @Fruchtzwerg94, thanks for reporting this!

Adding additional context, this behavior is because the `Pie` will always zoom out to make sure that axis limits are "square", so repeatedly changing the aspect ratio only zooms out. Related: #4422

https://github.com/ScottPlot/ScottPlot/blob/db251c67d9e6a3f393fde4d1704eabb6318d4ffc/src/ScottPlot5/ScottPlot5/Plottables/PieBase.cs#L33-L44

See these for more context:
* https://github.com/ScottPlot/ScottPlot/issues/4422#issuecomment-2453474843
* https://github.com/ScottPlot/ScottPlot/issues/4422#issuecomment-2453476928
* https://github.com/ScottPlot/ScottPlot/issues/4422#issuecomment-2453506755

I'm not totally sure an easy fix is achievable... but it may be worth implementing that `SquarePreserveSmallestAxis` axis rule and using it in `PieBase` to see if it fixes this problem.

I'll keep researching for a simpler/temporary fix until I decide what action I should take tonight...

**Comment by swharden** [comment]
> I'll keep researching for a simpler/temporary fix until I decide what action I should take tonight...

This seems to work! Now it makes me wonder if the entire square units behavior can be discarded...
```cs
var pie = formsPlot1.Plot.Add.Pie([10, 20, 30]);
pie.ManageAxisLimits = false;
```

**Comment by swharden** [comment]
I'll close this issue for now without taking action, but these are my conclusions:

**Temporary fix:** disable the "automatic zoom out" behavior like this:
```cs
var pie = formsPlot1.Plot.Add.Pie([10, 20, 30]);
pie.ManageAxisLimits = false;
```

**Remaining problem:** Slice labels are placed using the coordinate system so if "square units" aren't enabled, the placement of labels gets really bad.

**Best solution (contributions are welcome!):** `PieBase` could be refactored to remove `IManagesAxisLimits`, `ManageAxisLimits`, and `UpdateAxisLimits()` so pie charts no longer require square units. However, the logic that determines where slices are so text can be rendered there must be adapted to place text correctly since the coordinates would now have to be multiplied by the ratio of the horizontal and vertical axis limit span. This information is available inside the `Render()` method like this:

```cs
float WidthHeightRatio = rp.DataRect.Width / rp.DataRect.Height;
```
