### ISSUE TITLE
Support for .NET Framework 4.6.0

### ISSUE THREAD

**Issue by Or8e4m4n** [ScottPlot/ScottPlot#4512]
I'm currently developing a few apps professionally with Visual Studio 2015. I believe I only have access to .NET Framework 4.6.0 at best.

Is it possible to still use the library? I've browsed a few versions on NuGet which require .NET Framework 4.6.2 at least...

Otherwise, am I actually allowed to use regarding the licenses? It is intended for an aeronautical subcontractor and will only be used in-house by about 10 people.

**Comment by swharden** [comment]
Hi @Or8e4m4n, thank you for this question!

## Is Visual Studio 2015 supported?

> I'm currently developing a few apps professionally with Visual Studio 2015

Interesting! It looks like mainstream supported ended in 2020, but "extended support" extends through Oct next year

https://learn.microsoft.com/en-us/lifecycle/products/visual-studio-2015

> I believe I only have access to .NET Framework 4.6.0 at best.

This may not be the case. According to:

https://stackoverflow.com/questions/43420178/can-i-use-visual-studio-2015-to-target-net-framework-4-7

_"The .NET Framework 4.7 Developer Pack lets developers build applications that target the .NET Framework 4.7 by using Visual Studio 2015."_

This may be enough to say "problem solved" since ScottPlot supports .NET Framework 4.6.2 and newer.

## Can I use Visual Studio Community for free?

> Am I actually allowed to use [Visual Studio Community] regarding the licenses? It is intended for an aeronautical subcontractor and will only be used in-house by about 10 people.

You may be able to use the latest version of Visual Studio Community for free

https://visualstudio.microsoft.com/vs/community/

_"In non-enterprise organizations, up to five users can use Visual Studio Community"_

_"enterprise organizations meaning those with >250 PCs or >$1 Million US Dollars in annual revenue"_

## Does ScottPlot run on older versions of .NET?

Old versions do. They're not supported, but they may get the job done.

* https://www.nuget.org/packages/ScottPlot#versions-body-tab
* https://www.nuget.org/packages/ScottPlot/3.1.6
* ScottPlot 3.1.6 appears to run on .NET Framework 4.5
* ScottPlot 6.1 docs: https://scottplot.net/cookbook/3.1/

**Comment by Or8e4m4n** [comment]
Hello Scott,

Thanks for your explanations. Honestly, I have almost no hope to upgrade to a higer version of Visual Studio / .NET because I have no controls! Some of my colleagues have access to more recent version of Visual Studio (and probably higher version of .NET)... but not me :-( . Of course, I've just moved to .NET 9 on my personal projects...

Unfortunately, it seems that there no version for **WPF**. The earliest seems to begin with the 4.0.1. Is it still possible to use it? The example shown on docs will perfectly corresponds to the needs.

**Comment by Or8e4m4n** [comment]
Alright, I found out that the version 3.1.6 also targets WPF and believe that the library was specifically split for WPF later on. Everything works fine!

**Comment by swharden** [comment]
> Alright, I found out that the version 3.1.6 also targets WPF and believe that the library was specifically split for WPF later on. Everything works fine!

I'm glad you reached a solution! Here are links for future readers who may have the same question:

* NuGet package: https://www.nuget.org/packages/ScottPlot/3.1.6

* ScottPlot 3.1 docs: https://scottplot.net/cookbook/3.1/
