### ISSUE TITLE
DataLogger: improve axis management for inverted axes

### ISSUE THREAD

**Issue by Jofstera** [ScottPlot/ScottPlot#4513]
Hi guys, is it possible to set a limit on the Y-axis when using a Datalogger?
I know I can set a rule to lock the Y-axis and manually give it tick values, but doing so means the y-axis cannot be expanded dynamically.

**ScottPlot Version:** WPF SP5 v5.0.45

**Code Sample:** 
```cs
    public partial class MainWindow : Window
    {
        readonly System.Windows.Forms.Timer AddNewDataTimer = new() { Interval = 50, Enabled = true };
        ScottPlot.Plottables.DataLogger Logger1;

        public MainWindow()
        {
            InitializeComponent();
            InitializeGraph();
        }

        private void InitializeGraph()
        {
            myPlot.Plot.Axes.InvertY();

            Logger1 = myPlot.Plot.Add.DataLogger();
            Logger1.Axes.YAxis = myPlot.Plot.Axes.Left;

            // Attempting to set some kind of limit ...
            myPlot.Plot.Axes.MarginsY(0);
            myPlot.Plot.Axes.SetLimitsY(0, 50);
            Logger1.Axes.YAxis.Range.Set(0, 50);

            DateTime startOfGraphTime = DateTime.Now;
            Random numGenerator = new Random();
            AddNewDataTimer.Tick += (s, e) =>
            {
                // Attemping to set some kind of limit ...
                myPlot.Plot.Axes.Left.Min = 0;
                Logger1.Axes.YAxis.Min = 0;       
                
                TimeSpan timeSinceStart = DateTime.Now - startOfGraphTime;
                double seconds = timeSinceStart.TotalSeconds;
                Logger1.Add(seconds, numGenerator.Next(0, 50));
                myPlot.Refresh();
            };
        }
    }
```
![image](https://github.com/user-attachments/assets/62791792-76a6-4f2a-82a9-61859a5cbfcb)

1. In this example it is impossible to get a value under 0 or over 50, yet the y-axis shows values outside of this range which are not needed.

2. I inverted the y-axis with `myPlot.Plot.Axes.InvertY();`. But as soon as a DataLogger is added to the plot, the Y-axis becomes uninverted. Is there a way to fix this?

**Comment by swharden** [comment]
Hi @Jofstera, thanks for these questions! I _really_ appreciate the complete code example that helped me to get started answering these right away 😎 

## How to change vertical padding around Data Logger values

> In this example it is impossible to get a value under 0 or over 50, yet the y-axis shows values outside of this range which are not needed.

Users may create their own classes that manage axis limits to achieve fully custom behavior. Luckily the built-in default axis manager already has an exposed property that can be used to restrict "padding" around values vertically:

```cs
Logger1.AxisManager = new ScottPlot.AxisLimitManagers.Full()
{
    ExpansionRatio = 0
};
```

## How to use Data Logger with inverted axis limits

> I inverted the y-axis with myPlot.Plot.Axes.InvertY();. But as soon as a DataLogger is added to the plot, the Y-axis becomes uninverted. Is there a way to fix this?

Oof, this sounds like it may be a bug! Thanks for reporting it. I'm running out of time to take a look at it myself today, but I'm guessing the accidental reversion is happening in one of these areas. I'll leave this issue open to track a fix, but if you're able to get to it before I can I would be happy to review a pull request within the next day or two! 🚀 

https://github.com/ScottPlot/ScottPlot/blob/1f44931697efb5fcc0c8589057039256522e3ee9/src/ScottPlot5/ScottPlot5/AxisLimitManagers/Full.cs#L28-L45

https://github.com/ScottPlot/ScottPlot/blob/1f44931697efb5fcc0c8589057039256522e3ee9/src/ScottPlot5/ScottPlot5/Plottables/DataLogger.cs#L229-L242

**Comment by swharden** [comment]
Hi @Jofstera, following-up, I don't think this is a bug after all. The behavior demonstrated is exactly what the "axis management" feature of the data logger was designed to do. However, we can add a flag to support inverted axis limits.

Note that this call:
```cs
formsPlot1.Plot.Axes.InvertY();
```

Inverts the axis limits _one time_, but the data logger's "axis management" system resets the axis limits every time `Add()` is called, which is why we observe the behavior we do.

DataLoggers have an `AxisManager` property which holds an `IAxisLimitManager`, so you could create your own class that copies the `Full` class source code (referenced in the previous comment) and make the one-line change to invert the axis limits, then instantiate it and assign it into your data logger. That would work immediately with the existing library.

However, I'll use this issue to track adding "inverted" flags to the various axis managers 👍

**Comment by swharden** [comment]
Regarding support for inverted axes, I ended up adding a flag into the `DataLogger` itself. I'll create a pull request in a couple minutes. This is how it can be used in the future:

```cs
var logger = formsPlot1.Plot.Add.DataLogger();
logger.InvertY = true;
```

![inverted](https://github.com/user-attachments/assets/3a5f4845-ecbf-4b31-8f79-b6b98c8e835e)

**Comment by Jofstera** [comment]
Hi @swharden, thanks so much for getting back to me, looking into the axis management for me and providing a solution. I really appreciate how you explained the code and pointed me in the right direction! It's a huge help for inexperienced developers like myself. Keep up the great work!

**Comment by swharden** [comment]
> It's a huge help for inexperienced developers like myself

To be fair, this was a super tricky bug to figure out 🤪 and a bug in the `AxisLimits` constructor was also involved, so this fix turned out to be a bit more complicated than most!

> Keep up the great work!

Thanks for your encouragement! Let us know if you encounter any more unexpected behavior or have ideas for improvements in the future 🚀
