### ISSUE TITLE
Plot.Axis() method should accept NULL array

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#698]
Hi!

`public double[] Axis(double? x1 = null, double? x2 = null, double? y1 = null, double? y2 = null);` can handle null input parameters (in this case it does not modify the corresponding axis limit).
To be consistent, the `public double[] Axis(double[] axisLimits); ` should also accept a NULL array as input. Recently it throws error.
So in my code now, I need extra code to handle NULL case.
What do you think about such change?

**Comment by Benny121221** [comment]
I think the complement to passing in 4 nulls is passing in an array of four nulls, not passing in a null reference instead of an array.

That said, I think an array of four nulls would be a good overload, although I think I disagree on passing in null instead of an array.

**Comment by swharden** [comment]
Hey @bukkideme, thanks for the suggestion! You may find my response unsatisfying, but I welcome feedback!

***It was a mistake for me to to make a method that accepts an array as a way to input 4 values.*** As you've observed, there can be uncertainty of outcome when arrays are null, or more insidiously the wrong length! My thinking is that exceptions should be thrown in these cases, but I recognize that the expected behavior is ambiguous.

In ScottPlot 4.1 this method has been removed and replaced with `SetAxisLimits()` and `GetAxisLimits()`. Notice support has been added for multiple axes.

https://github.com/ScottPlot/ScottPlot/blob/05f0f4da2c68d1b9067b82462bf45b321fa8ea66/src/ScottPlot/Plot/Plot.Axis.cs#L261-L266

https://github.com/ScottPlot/ScottPlot/blob/05f0f4da2c68d1b9067b82462bf45b321fa8ea66/src/ScottPlot/Plot/Plot.Axis.cs#L271-L280
