### ISSUE TITLE
Coordinated Heatmap

### ISSUE THREAD

**Issue by StendProg** [ScottPlot/ScottPlot#701]
**What can we do to make ScottPlot better?**

For now `PlottableHeatmap` binds to coordinate system in simple way `x = heatmap_x_index`, `y = heatmap_y_index`.
Zooming and panning works fine.

It would be useful to set the boundaries for the map along the x and y axes.
Let's say `Xmin`, `Xmax`, `Ymin`, `Ymax`.
Coordinate step will be calculated using heatmap dimensions and provided boundaries.

For example i want to plot heatmap from x=-100 to x = 200, from y = 100 to y = 101;
Heatmap size is 300x1000.
```c#
double[,] intensities = new double[300, 1000];
plt.PlotHeatmap(intensities, xmin:-100, xmax: 200, ymin: 100, ymax:101);
```
xStep will be 300 / 300 = 1,
yStep will be 1 / 1000 = 0.001.

At first glance, this does not look like a difficult task for the Heatmap developer, but it is quite difficult for me since I need to understand the existing code...

**Comment by Benny121221** [comment]
This was actually in #457 over six months ago. I ended up mapping the bitmap to fixed coordinates because I didn't know how to treat axes that don't preserve the aspect ratio.

Here are the options that I can think of:
- Simply stretch or crop the heatmap, which is not ideal.
- Coerce axes to ones that preserve aspect ratio:
    - e.g. if the user passed in a 200x100 bitmap then attempting to rescale the axes to x ∈ [0, 400] and y ∈ [0, 250] actually yields x ∈ [0, 400] and y ∈ [0, 200]
    - I think this flies in the face of the whole point of being able to change the axes. This is only actually useful if they only care about the numbers on one axis.
- "Poke through" into the axis and rewrite the numbers to be disconnected from the actual rendering
    - One might be able to turn the axis into a facade and plottables can arbitrarily remap coordinates (messy)
    - Probably better achieved by turning off the "real" axes and letting them draw their own axes with their own numbers
 
I think "poking through" is the only option which helps the user and it may be more viable now that multiple axes are supported. I have not looked very hard at the new `Renderable.Axis` class but my understanding is that the axes with `AxisIndex` of 0 will be matched to the bitmap's dimensions, and other indices will not be (unless the plottable's `XAxisIndex` or `YAxisIndex` specifies otherwise). `AxisIndex` of 1 is also taken by the top and right axes.

## My Attempt:

This was the best I could do in a demo: 
![image](https://user-images.githubusercontent.com/8635304/105223285-cfe27680-5b18-11eb-9561-54c38e489e52.png)

Even though the primary axis is invisible it's still leaving space for it. I tried `Axis.Layout` and `Axis.SetOffset` and it wouldn't budge. Regardless, this is the code I used:

```cs
    public class HeatmapCustomAxes : IRecipe
	{
        public string Category => "Plottable: Heatmap";
        public string ID => "heatmap_customaxes";
        public string Title => "Heatmap with Custom Axes";
        public string Description =>
            "The axes of a heatmap can be easily customized.";

        public void ExecuteRecipe(Plot plt)
        {
            double[,] imageData = DataGen.SampleImageData();
            plt.AddHeatmap(imageData);

            plt.XAxis.IsVisible = false;
            plt.YAxis.IsVisible = false;

            var newXAxis = plt.AddAxis(Renderable.Edge.Left, 2);
            var newYAxis = plt.AddAxis(Renderable.Edge.Bottom, 2);

            newXAxis.Dims.SetAxis(0, 500);
            newYAxis.Dims.SetAxis(-70, 70);
        }
    }
```

It's also available on this branch of my fork: https://github.com/Benny121221/ScottPlot/tree/coordinated-heatmap

@swharden Am I doing something wrong? Or are is there something wrong with either `Axis.Layout` or `Axis.SetOffset`?

**Comment by StendProg** [comment]
Hi @Benny121221,
Thanks for your answer,
>Simply stretch or crop the heatmap, which is not ideal.

This is what I want to get.
Are you embarrassed that rectangular Heatmap cells will not look as nice as square ones, or are there any difficulties with the implementation of disproportionate cells? Personally, I would like to be able to zoom one cell into a very oblong rectangle, I have nothing against it.
I noticed that `zoom in` is already working very well and thinked it not so hard to implement, but I didn't notice that you always keep the aspect ratio.

ScottPlot already have `EqualAxis` mode in which the axes are always stay proportional. At the very least, you can set a restriction (check) on the fact that this mode is enabled.

> This was actually in #457 over six months ago

Don't worry, I am ready to take the time and figure out how it works, I just wanted to find an easy way, I didn't think there were big difficulties.

**Comment by Benny121221** [comment]
> Are you embarrassed that rectangular Heatmap cells will not look as nice as square ones, or are there any difficulties with the implementation of disproportionate cells?

My objection is to the aesthetics, not because there's any difficulty in displaying non-square cells.

> ScottPlot already have EqualAxis mode in which the axes are always stay proportional. At the very least, you can set a restriction (check) on the fact that this mode is enabled.

I mean yes, but it's not really the axes that are being stretched (the axes don't mean much for heatmaps), it's the plot being stretched as well. On a scatter plot for example, the spaces between points is stretched or squished, but circular points do not become ovals. In my opinion Heatmaps should preserve aspect ratio by default, but I acknowledge that supporting both is a decent idea.

> Don't worry, I am ready to take the time and figure out how it works, I just wanted to find an easy way, I didn't think there were big difficulties.

You can achieve this by replacing `minScale` in the `RenderHeatmap` method of `Heatmap` with the x and y axis scales. Then make sure you call `AddHeatmap` with the `lockScales` parameter set to false.

**Comment by Benny121221** [comment]
As an aside, in addition to the stacking on invisible axes, it turns out that when you scroll the fake axis is also zoomed in/out, and this is not reset by a middle click. My potential solutions are either add an auto-axis behaviour on the `Axis` renderable, which sounds like mixing concerns, or to create a special heatmap axis class (probably a subclass of `Axis`), whose instances need to be treated specially by the backend, which is better but still inelegant.

Also the demo maps the whole window to the given coordinates, not the area taken up by the heatmap. This is solvable, but not the priority of the demo.

**Comment by StendProg** [comment]
`Plottable.CoordinatedHeatmap` introduced in 4.1.6-beta works perfect for my porpouse.
