### ISSUE TITLE
Highlight point near cursor with pixel space awareness

### ISSUE THREAD

**Issue by oszymczak** [ScottPlot/ScottPlot#709]
Hi,

I have an issue that visually it appears that the mouse is closer to a point but is highlighting another point because of the way the calculation is made and doesn't take into account the axis scale. Looking into the method HighlightPointNearest the formula is only looking at the actual coordinates of the points (x1 - x) * (x1 - x) + (y1 - y) * (y1 - y) and not looking how the points are drawn on the screen.

Note how visually the mouse appears closure to (2, 200) point
![image](https://user-images.githubusercontent.com/16024904/105620411-f245fe00-5e50-11eb-84af-5f99ac1a13ce.png)

As I move the mouse vertically the highlighted point eventually moves from (1, 100) to (2, 200)
![image](https://user-images.githubusercontent.com/16024904/105620429-2a4d4100-5e51-11eb-92fe-642752b09150.png)

Is there way to factor in the pixel location or the scale of the X and Y axis when different so that the point is highlighting correctly?

### Sample Project
* [TestHighlight.zip](https://github.com/ScottPlot/ScottPlot/files/5861534/TestHighlight.zip)

### MainWindow.xaml.cs
```cs
/// <summary>
/// Interaction logic for MainWindow.xaml
/// </summary>
public partial class MainWindow : Window
{
    ScottPlot.PlottableScatterHighlight sphTest;
    PlottableVLine vLine;
    PlottableHLine hLine;

    public MainWindow()
    {
        InitializeComponent();

        double[] xs = new double[] { 1, 2 };
        double[] ys = new double[] { 100, 200 };

        sphTest = pltTest.plt.PlotScatterHighlight(xs, ys, lineWidth: 0, color: System.Drawing.Color.Blue, markerSize: 10);

        vLine = pltTest.plt.PlotVLine(1, color: System.Drawing.Color.Red, lineStyle: LineStyle.Dash);
        hLine = pltTest.plt.PlotHLine(100, color: System.Drawing.Color.Red, lineStyle: LineStyle.Dash);

        pltTest.Render();
    }

    private void pltTest_MouseMove(object sender, MouseEventArgs e)
    {

        (double mouseX, double mouseY) = pltTest.GetMouseCoordinates();
        sphTest.HighlightClear();

        var (x, y, index) = sphTest.HighlightPointNearest(mouseX, mouseY);


        int pixelX = (int)e.MouseDevice.GetPosition(pltTest).X;
        int pixelY = (int)e.MouseDevice.GetPosition(pltTest).Y;

        (double coordinateX, double coordinateY) = pltTest.GetMouseCoordinates();

        XPixelLabel.Content = $"{pixelX:0.000}";
        YPixelLabel.Content = $"{pixelY:0.000}";

        XCoordinateLabel.Content = $"{coordinateX:0.00000000}";
        YCoordinateLabel.Content = $"{coordinateY:0.00000000}";

        vLine.position = coordinateX;
        hLine.position = coordinateY;

        pltTest.Render(skipIfCurrentlyRendering: true);
    }
}
```

**Comment by swharden** [comment]
Hi @olofszymczak, thanks for sharing your question! I modified your original post to include source code as text.

The problem you are running into is that the `HighlightPointNearest()` methods use _coordinate space_, not _pixel space_, to determine distance between points. Unfortunately there's not an easy way to identify the nearest point using pixel space. 

> **details:** Pixel space is only calculated when a `Render()` method is called (passing-in dimensions for the image), the layout is calculated, then unit/pixel relationships are briefly calculated (based on that layout) and used only inside the `Render()` method then discarded. In short, all plot types are unaware of the "pixels per unit" because that value is not stored. It may be possible to store something like `LastRenderPixelsPerUnitX` and `LastRenderPixelsPerUnitY`, but that is only partially useful because those values might be different on the next render if the plot is resized or a change in tick label length causes the layout to be resized then the pixel space will change.

**Would your problem be solved by calling `HighlightPointNearestX()` instead of `HighlightPointNearest()`?** This would always highlight the point nearest the cursor _on the X axis_, which might be the effect you're looking for. Since it only has to search 1d space to find the nearest point, this method would be faster too.

I hope this helps!
Scott

**Comment by olofszymczak** [comment]
Hi @swharden, I cant just use HighlightPointNearestX() as I am using a larger set of data. The example I provided was to highlight the issue. If there is a way to :
- Expose the points that are visible in a list or array that contain the pixel location.
- use the pixel values to determine the nearest point to the mouse.
- then determine the index to get the actual data (coordinates)

Not sure why you closed this discussion?

**Comment by swharden** [comment]
Hi @olofszymczak, I closed the issue because I thought `HighlightPointNearestX()` would solve your issue, but I now realize your demo was intentionally simplistic and this solution does not adequately address your issue.

Unfortunately, the 3-step process you outlined isn't a great solution for this library. Indeed, it sounds reasonable, but the gotcha here is that pixel locations may change on every render, so storing them after one render doesn't give perfect predictive power for the next render. Re-stating the "details" from the comment above, this library is designed to dynamically calculate the layout on every render. This changes the size and location of the data area based on things like tick label sizes on every render. When the data area size changes, pixel/coordinate conversions all change too. Storing lists of pixel positions at the end of a render could result in inaccurate predictions of where those points will be in the next render, and storing pixel state is largely opposed to the design goals of the rest of the library (which intentionally does not store pixel space as state). I recognize this is a bit of a confusing answer, but all that said I want to work with you to come up with some type of a solution for this problem. 

I have a few ideas how this might be possible, but they're pretty complex, require modifying the core library, and I think I should implement them and share working example code rather than try to explain how to do it verbally. I'll probably also do this work in the 4.1-beta (master) branch (pre-release on NuGet) which deprecates the `PlotScatterHighlight` in favor of simpler solutions. 

I'll leave this issue open until I have a better idea about the feasibility of this! Thanks for the follow-up details 👍

**Comment by olofszymczak** [comment]
Thanks,

I looked at the code which calculates the nearest point.

If there where 10000 points and you zoomed in to only show 10 points. It would still loop over all the 10000 points and perform the pointDistanceSquared calculation.

There is room for optimization
**public class ScatterPlot**
 public (double x, double y, int index) GetPointNearest(double x, double y)
        {
            List<(double x, double y)> points = Xs.Zip(Ys, (first, second) => (first, second)).ToList();

            double pointDistanceSquared(double x1, double y1) => (x1 - x) * (x1 - x) + (y1 - y) * (y1 - y);

            double minDistance = pointDistanceSquared(points[0].x, points[0].y);
            int minIndex = 0;
            for (int i = 1; i < points.Count; i++)
            {
                double currDistance = pointDistanceSquared(points[i].x, points[i].y);
                if (currDistance < minDistance)
                {
                    minIndex = i;
                    minDistance = currDistance;
                }
            }

            return (Xs[minIndex], Ys[minIndex], minIndex);
        }
        
The array could also be reduced to the Axis Limits as well.

In the following, I am not sure which will be less CPU and memory intensive?

**public class ScatterPlotHighlight**
Why is a bool[] array used to indicate which point to highlight? the bool array is the size of the data.
protected bool[] isHighlighted;

Why not create a List<int>HighlightedIndexes and add the index
HighlightedIndexes.Add(index)
Only thing I can think of is the code wanted to highlight a large amount of points but if you only wanted to highlight one point the array seems like a lot of wasted memory..

that way you can skip the following highlighted line
public new void Render(PlotDimensions dims, Bitmap bmp, bool lowQuality = false)
        {
            base.Render(dims, bmp, lowQuality);

            if (isHighlighted is null || isHighlighted.Length == 0)
                return;

            using (var gfx = GDI.Graphics(bmp, dims, lowQuality))
            {
                **var highlightedIndexes = Enumerable.Range(0, isHighlighted.Length).Where(x => isHighlighted[x]);**
                foreach (int i in highlightedIndexes)
                {
                    PointF pt = new PointF(dims.GetPixelX(Xs[i]), dims.GetPixelY(Ys[i]));
                    MarkerTools.DrawMarker(gfx, pt, highlightedShape, highlightedMarkerSize, highlightedColor);
                }
            }
        }

**Comment by StendProg** [comment]
Hi there,
As @swharden write above, main problem is that axis limits available only on Render() call. But HighlightPoint make decission in other place.
To solve this problem, it's possible to move nearest point calclulation to Render().
On `HighlightPointNearestWithScales(double x, double y)` call, we can just store arguments (x, y), In render loop we will find nearest point to stored coordinates additionaly using scales provided to `Render` call.
It's possible to make additional interface `IHasHiglightablePointsWithScales`:
```c#
       (double x, double y, int index) HighlightPointNearestWithScales(double x, double y);
        void HighlightClearWithScales();
```
and implement it for `ScatterHighlightable`.

@olofszymczak a few counterarguments about the proposed optimizations:
> If there where 10000 points and you zoomed in to only show 10 points. It would still loop over all the 10000 points and perform the pointDistanceSquared calculation.
There is room for optimization

ScatterPlot can contain not ordered pairs of x,y. To find visible in current scales points you any way must loop over all points. So it gives nothing.

>Why is a bool[] array used to indicate which point to highlight? the bool array is the size of the data.
protected bool[] isHighlighted;
Why not create a List<int>HighlightedIndexes and add the index
HighlightedIndexes.Add(index)
Only thing I can think of is, when somebody wanted to highlight a large amount of points but if you only wanted to highlight one point the array seems like a lot of wasted memory..

Set highlighPoint on bool array take constant time `O(1)`.
But adding it to list take `O(n)`, where `n` is current highlighted points count. Because you need to add only unique point. And this is a very common case when you try add an already added one. I think that's why it was done.
In addition, if you evaluate the amount of additional memory, it turns out that you any way have 2 double[n] arrays (xs, ys). So adding additional bool[n] array not such a big problem.

**Comment by Benny121221** [comment]
> Why is a bool[] array used to indicate which point to highlight? the bool array is the size of the data.
protected bool[] isHighlighted;
Why not create a ListHighlightedIndexes and add the index
HighlightedIndexes.Add(index)
Only thing I can think of is, when somebody wanted to highlight a large amount of points but if you only wanted to highlight one point the array seems like a lot of wasted memory..

You are describing the original implementation. It was changed in https://github.com/Benny121221/ScottPlot/commit/d357830712d4bcfbc44fc4bdc3c9731f33c6b6a6

You are correct, memory usage is generally higher, as the whole `bool[]` is allocated. So for n points it uses n bytes. Whereas the original implementation stored each highlighted point's index, which means if you have m highlighted points it uses 4m bytes (as the indexes are int32s). Technically this means if you highlighted 25% of the points then they would have the same memory usage, and if you highlighted more than that then the array of bools would actually be faster, but the point of highlighting points is that they stand out, so this is unlikely to happen. Note that both options use a very small amount of memory regardless. For example, I believe there's a demo signal plot with 5 million points. The memory cost of this array is 5 MB. The memory cost of storing the points is 40 MB. The memory cost of 1 HD frame is 8294400 bytes, or about 8.3 MB, and there's at least 1 of these frames at all times (2 if there is double-buffered rendering).

However, if you look at time complexity:
- `bool[]` option is O(1) access, O(1) insert.
- Unsorted `List<int>` is O(n) search, O(1) insert (amortized)
- Sorted `List<int>` is O(log n) search, O(n) insert (`List<T>` is a dynamic array, aka ArrayList, inserting into the middle of them requires copying)
- Unsorted `LinkedList<int>` is O(n) search, O(1) insert
- Sorted `LinkedList<int>` is O(n) search (binary search is useless on linked lists), O(n) insert (maintaining sorted insertion requires a search)
- `SortedSet<int>` (Red-Black Tree) is O(log n) search, O(log n) insertion
- `HashSet<int>` is O(1) search (amortized), O(1) insertion (amortized)

Now, given that we pay the time complexity cost _**n**_ times on each render, and the memory cost is negligible, I don't think it makes sense to revert to the previous version, however, a `HashSet<int>` would actually reduce memory consumption and have the same time complexity.

**Comment by Benny121221** [comment]
As for the problem of getting the closest point, I wonder if one could do something like this:

```
GetClosest(x,y)
	minDistanceSquared = distanceSquared(GetPixelX(points[0].x), GetPixelY(points[0].y))
	minIndex = 0;
	
	for i = 1 to n - 1:
		tmp = distanceSquared(GetPixelX(points[i].x), GetPixelY(points[i].y))
		if tmp < minDistanceSquared
			update minIndex and minDistanceSquared
	
	return points[minIndex]
```

I think this should address @olofszymczak's concerns, and without requiring the library to hold unnecessary pixel state.

**Comment by swharden** [comment]
Hey @Benny121221, I only got to skim this briefly so I apologize if I miss the point here, but I think the core issue that makes this difficult to solve is that `GetPixelX()` and `GetPixelY()` are part of the `PlotDimensions dims` object which is only created inside the `Render()` method and passed around to the different plottables (it is intentionally never stored). When the user calls `HighlightPointNearest()`, those pixel dimensions are unavailable.

**Comment by swharden** [comment]
Hi @olofszymczak, @StendProg, and @bclehmann, this is an interesting discussion! There's a lot to unpack here, and there are multiple ways to solve this problem. I think I found an efficient working solution to the primary issue. A few different topics are addressed here, so I'll mention them separately:

## Pixel-Aware GetPointNearest()

I'm still working on the PR, but briefly I modified the code that measures distance between two points so it now optionally incorporates the ratio of scales (pixels per unit) of X and Y axes. See #722 for details.

```cs
// Use it like this
double xyRatio = formsPlot1.Plot.XAxis.Dims.PxPerUnit / formsPlot1.Plot.YAxis.Dims.PxPerUnit;
(double x, double y, int index) = MyScatterPlot.GetPointNearest(mouseCoordX, mouseCoordY, xyRatio);
```

```cs 
// This is how it works
public (double x, double y, int index) GetPointNearest(double x, double y, double xyRatio = 1)
{
    double pointDistanceSquared(double x1, double y1) =>
        (x1 - x) * (x1 - x) * (xyRatio * xyRatio) + (y1 - y) * (y1 - y);

    /* rest of the function is unchanged */
}
```

## Optimization may be improved

As discussed above, it may be possible to further optimize this method for speed. I haven't benchmarked it, if LINQ and tuples are replaced with discrete statements it may run faster. This is outside the scope of the original issue, but worth considering. I added it as a low-priority triaged task in #716 and I probably won't do it soon, but if someone wants to do this and make a PR I'd be happy to take a look.

## ScatterPlotHighlight is Deprecated in ScottPlot 4.1

This plot type was useful for a while, but it has a highly undesirable design: it mixes _point distance detection_ with _rendering_. This design limits what the user can do. For example, the user could not use this plot type to render something different (like an arrow) as a highlight. Also this plot type cannot be used for Signal plots or other plot types.

In ScottPlot 4.1 a `IHasPoints` interface was created that has a few `GetPointNearest()` methods. Plottables where highlight functionality is desired can simply implement this interface. Since it does not control rendering, users can display the highlight however they want.

The recommended way to display a highlighted point is to use `AddPoint()` to place a point (a scatter plot with a single X/Y value), set its marker shape to filled circle, then set its color and size how you like. When the mouse moves you can find the point nearest the mouse, then change this point's X/Y position and visibility, and request a render. This method is demonstrated verbosely in this WinForms app: [Form1.cs](https://github.com/ScottPlot/ScottPlot/blob/b09e6dd902378c5818e64ed8efb81ae408b40e37/src/sandbox/WinFormsFrameworkApp/Form1.cs)

![scales](https://user-images.githubusercontent.com/4165489/106069993-a05fdb00-60d1-11eb-9e7c-27f3a1e300c1.gif)

**Comment by olofszymczak** [comment]
@swharden thanks for the solution... tested it on my data set works perfect.
