### ISSUE TITLE
Can plots be saved as vector images rather than raster/bitmap format?

### ISSUE THREAD

**Issue by KlaskSkovby** [ScottPlot/ScottPlot#717]
I'm trying to set up a pdf print module where the scottplot is included on the page.
 
Is it possible to include it as vector graphic?
I only found a solution to use a Bitmap, but the resolution isn't the best when zooming on the pdf.

**Comment by swharden** [comment]
Hi @KlaskSkovby, vector output is not supported at this time, and output is indeed currently limited to bitmaps (bmp, png, jpg, etc).

I'll leave this issue open to remind me to explore the topic a bit further though, because it may be possible to output an `Image` instead of a `Bitmap`, and `Image` can be exported as WMF which is a format that supports vectors. I'm not sure if all the drawing operations are vectorized in memory before they're finally rendered though, so I'll investigate this one. Thanks for the question!

**Comment by bukkideme** [comment]
Being able to save plots as vector graphics would be a great thing. For example people using ScottPlot would be able to directly include a plot into a publication quality document (using TeX/Latex for example).

**Comment by swharden** [comment]
Thanks for raising the question @KlaskSkovby!

## Saving Vector Formats is not Currently Supported

I looked into this further, and although `System.Drawing.Common` can create WMF (vector) images and even display them, it looks like they cannot be saved as images.

> [Metafile Class](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.imaging.metafile?view=dotnet-plat-ext-5.0#remarks): When you use the Save method to save a graphic image as a Windows Metafile Format (WMF) or Enhanced Metafile Format (EMF) file, the resulting file is saved as a Portable Network Graphics (PNG) file instead. This behavior occurs because the GDI+ component of the .NET Framework does not have an encoder that you can use to save files as .wmf or .emf files.

Supporting this is a long-term goal of mine though. A bit part of the work I've done from 4.0 to 4.1 is refactoring to make this path easier to go down in the future. After the features and API stabalize, I'd like to move toward optional support for Skia using SkiaSharp. Not only would this let ScottPlot save images as vector formats, but it would also let it be used on more targets (like Xamarin) and support hardware acceleration with OpenGL.

## Improving Bitmaps in PDFs

@KlaskSkovby, I recognize your primary issue: a small plot looks bad in a PDF because when you zoom in it is blurry or pixelated. A workaround would be to increase the font size of the axis ticks, line widths, markers, etc. and save the plot as a higher resolution image. It's not a perfect solution, but it will probably give you a quick improvement.

See this example for how to customize tick and axis label fonts:
https://swharden.com/scottplot/cookbooks/4.1.5-beta/plottable_text.html#text_fonts

**Comment by KlaskSkovby** [comment]
Yeah upscaling the plot was what I did with the png file and stored it in a dictionary which i'm getting the bitmap from when printing.

How ever I realised that the scottplot is using GDI graphic.
GDI graphic can i use directly in the pdf printer.
But can I store the plot window as GDI graphic?

**Comment by swharden** [comment]
> can I store the plot window as GDI graphic?

You can get the plot as a `Bitmap` with `FormsPlot.Plot.Render()`.

If you have an existing `Bitmap`, you can render onto it with `FormsPlot.Plot.Render(yourBitmap)`

> GDI graphic can i use directly in the pdf printer.

It sounds like you're asking about how to print ScottPlot figures. Does code from this discussion help? https://github.com/ScottPlot/ScottPlot/discussions/769

**Comment by hughesjs** [comment]
Is this likely to make it into version 5?

**Comment by swharden** [comment]
> Is this likely to make it into version 5?

ScottPlot 5 renders graphics using SkiaSharp.

It looks like the official SKSvg library is now deprecated
https://github.com/mono/SkiaSharp.Extended/issues/84#issuecomment-674318866

...so first-class SVG export support seems unlikely

However, lots of the logic in this library could be recycled (e.g., colors, axes, and the overall API) to create a separate `SvgPlot` and special `ISvgPlottable` that accomplishes similar functionality. The code gets way simpler if you intentionally omit features like mouse interactivity and multiple axes, so it would be some duplication, but not an extraordinary amount.

Hope it helps!

**Comment by dusko23** [comment]
One, probably good option is to get hold of all graphic elements scotplot exposes (hopefully it does) and create matching pdf elements using a well-designed pdf creation library. Like this one. [https://www.o2sol.com/pdf4net/overview.htm]( https://www.o2sol.com/pdf4net/overview.htm) It is worth every penny.
I am new to ScottPlot and will start using it in order to check if and how elements are exposed in order to create matching PDF elements. The rest is simple like playing with Lego bricks.
