### ISSUE TITLE
Very slow when writing time-dependent data.

### ISSUE THREAD

**Issue by saklanmazozgur** [ScottPlot/ScottPlot#728]
I have data saved as binary. And I want to read this data and print it on a time course chart. The chart is having a hard time writing 20,000 data at the same time. The data size I have to write is 6,500,000. Is there a mistake I made? I would be glad if you inform me. My code is as follows. The point where the code is waiting Graphic.Render (); command.

`            DateTime time = DateTime.Now;

            var readByte =  File.ReadAllBytes(fileName);

            double[] conDoubleData = readByte.Select(n => { return Convert.ToDouble(n); }).ToArray();

            double[] xAxisTime = new double[conDoubleData.Length];

            for (int i = 0; i < xAxisTime.Length; i++)
            {
                time = time.AddMilliseconds(5);
                xAxisTime[i] = time.ToOADate();
            }

            Graphic.plt.PlotScatter(xAxisTime, conDoubleData, color, markerSize: 1);
            Graphic.plt.AxisAuto();
            Graphic.Render();`

**Comment by swharden** [comment]
**Hi @saklanmazozgur, your mistake is using the _scatter_ plot instead of the _signal_ plot.** Since all your data points are evenly spaced (by 5 milliseconds), you can take advantage of the signal plot. This will let you easily display datasets with tens of millions of points. Note that the signal plot takes a _sample rate_ and an _x offset_ instead of an array of X positions. 

I find dates in C# to be extremely frustrating to work with. Keep in mind that these two values must be `double`, not `DateTime`, so you must use `DateTime.ToOADate()` to do the conversion. Your X offset will be `startDateTime.ToOADate()`.

Sample rate will be the number of data points per day. `DateTime.ToOADate()` represents days as a floating point number, where each day spans 1.0 units (I didn't invent this standard). If your samples are 5 ms apart, your sample rate will be the number of samples per day. This will be `24*60*60*1000/5`, or `17280000` samples per day.

Hope it helps!
Scott
