### ISSUE TITLE
Add sender to AxisChanged event

### ISSUE THREAD

**Issue by at2software** [ScottPlot/ScottPlot#743]
In the current WPF implementation, `AxisChanged` (from stable 4.0.48) and `AxesChanged` (from 4.1.5-beta) always provide `null` as `sender`. Is there a reason why the WpfPlot instance cannot specify `this` as the sender?

A typical and convenient way to match the axes of e.g. 10 plots would be like this:
```c#
private void WpfPlot_AxesChanged(object sender, EventArgs e)
{
	if (sender is WpfPlot plot)
	{
		foreach (WpfPlot p in linkedPlots)
		{
			if (!p.Equals(plot))
			{
				// disable and enable event to prevent loops is omitted for brevity
				p.Plot.SetAxisLimits(plot.Plot.GetAxisLimits());
				p.Render();
			}
		}
	}
}
````
and have all anonymous WpfPlot user controls route the AxesChanged event to this single handler. This is not possible though currently, as the sender is `null` and so we cannot know the WpfPlot whose axes changed. One would need to make 10 different handlers (WpfPlot1_AxesChanged, WpfPlot2_AxesChanged, ...) like it is done in the examples here  https://github.com/ScottPlot/ScottPlot/blob/4.0-stable/src/ScottPlot.Demo.WPF/WpfDemos/LinkedPlots.xaml.cs#L36-L46

**Comment by swharden** [comment]
Thanks for the suggestion @at2software! 

This would be an improvement, as `null` isn't particularly useful. I'll make this change in 4.0 and 4.1, then release new packages on NuGet this weekend.

Just this week I wrote a little program which could have benefitted from this, since (like you said) I had to write separate handlers for every plot. https://github.com/swharden/AP-Phase-Analysis

**Comment by at2software** [comment]
Great, thanks!

**Comment by swharden** [comment]
I changed the controls as suggested, updated all the demos, merged it in, and will release it on NuGet tonight. Thanks again for the suggestion @at2software!
