### ISSUE TITLE
Uno Control

### ISSUE THREAD

**Issue by bclehmann** [ScottPlot/ScottPlot#751]
**What can we do to make ScottPlot better?**

I was thinking now that the controls have a common backend it may be easier to create additional controls for more platforms. One that's intrigued me (perhaps helped by the fact that they signed me up for their email newsletter without me asking) is [Uno](https://github.com/unoplatform/uno). It supports Windows, Mac, Linux, iOS, Android, and web through WASM. I don't know whether the mobile side makes sense to support, and even with the improvement of WASM compilers I would be impressed if they could get `System.Drawing` with all of its native dependencies working on WASM.

I haven't looked much into Uno and developing controls for it because of the license, it's under [Apache 2.0](https://github.com/unoplatform/uno/blob/master/License.md). However, it does look like ScottPlot wouldn't be considered a derivative work (emphasis my own):
> "Derivative Works" shall mean any work, whether in Source or Object form, that is based on (or derived from) the Work and for which the editorial revisions, annotations, elaborations, or other modifications represent, as a whole, an original work of authorship. ***For the purposes of this License, Derivative Works shall not include works that remain separable from, or merely link (or bind by name) to the interfaces of, the Work and Derivative Works thereof.***

This makes me think that the terms of the license don't require us to do anything different from how we treat any other platform. Still, I wanted your thoughts, both on the license side as well as whether you think the platform makes sense. It shouldn't be too dissimilar from WPF and Avalonia because it takes a lot of the same design cues, but I recognize that supporting as many platforms as it does (including WASM which isn't yet mature) could cause some issues. Assuming we're hoping to support MAUI when it comes out that will support mobile as well so hopefully those issues are solvable, and hopefully it's not too difficult to set up mobile development with Visual Studio.

One issue with supporting mobile platforms is some of the interactions become impossible, user's cannot hold down keys, they cannot middle-click, and scrolling to zoom in or zoom out is much less intuitive than the pinching that's normally used to zoom on mobile. And I don't know anything about gesture recognition on mobile.

The [ScottPlot Roadmap](https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md) may provide additional context regarding current goals and future directions.

**Comment by swharden** [comment]
Hey @bclehmann! I'll leave this issue open so I can consider it more deeply. For now, here are a few quick thoughts.

1) **I'm pretty sure `System.Drawing` is not supported on Xamarin or WASM** (e.g., I couldn't use it with Blazor). When you try to create a `Graphics` it throws something like a `System not supported` exception. However, if a future version of this library supports arbitrary renderers like ImageSharp or SkiaSharp, then it may be useful to add controls for more targets. SkiaSharp is cool because it can use OpenGL acceleration, but has some tricky build steps to get it right for your platform. ImageSharp is cool, and on the opposite end of the spectrum. I don't find it particularly performant, but it's a pure .NET Standard library, so it should be able to run anywhere .NET can run.

2) **Non-interactive plots can be extremely useful.** I know a mobile app wouldn't support right-click-drag, but consider that some users might simply want to display highly customized static plots of large datasets. For example, consider all the possibilities achieved with server-side image rendering https://github.com/ScottPlot/ScottPlot#plot-in-the-cloud ... this makes me think these directions are worth perusing, even if interactivity is largely different or even absent.
