### ISSUE TITLE
GetColormaps() throws on second call

### ISSUE THREAD

**Issue by StendProg** [ScottPlot/ScottPlot#767]
`ScottPlot.Drawing.Colormap.GetColormaps()` throws on second call.
There is related with `Reflection` exception.

```cs
var colormaps = ScottPlot.Drawing.Colormap.GetColormaps();
var colormaps1 = ScottPlot.Drawing.Colormap.GetColormaps();
```

**Comment by swharden** [comment]
Hi @StendProg, I added some tests for this but am unable to reproduce the exception. What version of ScottPlot does this occur on, and are you running it from source or from the NuGet package?

I have learned a lot more about C# since I first wrote this method, so I refactored this method to be simpler and use Reflection. Perhaps something in this change will improve the issue?

```cs
public static Colormap[] GetColormaps() =>
    Assembly
        .GetExecutingAssembly()
        .GetTypes()
        .Where(type => type.Namespace == "ScottPlot.Drawing.Colormaps")
        .Select(colormapType => (IColormap)Activator.CreateInstance(colormapType))
        .Select(colormapInstance => new Colormap(colormapInstance))
        .ToArray();
```

```cs
[Obsolete("https://github.com/ScottPlot/ScottPlot/issues/767")]
public static Colormap[] GetColormapsOld()
{
    IColormap[] ics = AppDomain.CurrentDomain.GetAssemblies()
                        .SelectMany(s => s.GetTypes())
                        .Where(p => p.IsInterface == false)
                        .Where(p => p.ToString().StartsWith("ScottPlot.Drawing.Colormaps."))
                        .Select(x => x.ToString())
                        .Select(path => (IColormap)Activator.CreateInstance(Type.GetType(path)))
                        .ToArray();

    return ics.Select(x => new Colormap(x)).ToArray();
}
```

**Comment by StendProg** [comment]
Hi @swharden,
sorry for missed information,
I get it in Winforms app, .NET Framework 4.7, `4.1.6-beta` nuget package.

**Comment by StendProg** [comment]
I just want to fill combobox with available `Colormaps` names.
Then user change selection i want to create new `Colormap` by provided name.
It's possible to achive with existing `GetColormaps()` method, but i get `LoadType` exception.

Maybe it worth to make hard-coded list of available colormaps, and realise 2 additional api methods:
1. `GetAvailableColormapsNames()`;
2. `CreateColormap(string name)`; 

As far as I understand, reflection is used to simplify the addition Colormaps, but one way or another, all Colormaps are hard-coded in these methods:
https://github.com/ScottPlot/ScottPlot/blob/d2055308885c747443c902053749882a4be0b174/src/ScottPlot/Drawing/Colormap.cs#L13-L43
Maybe we should give up the use of reflection?

**Comment by swharden** [comment]
## New Colormap Methods
I like your suggestions of these methods! They seem very useful, especially when populating listboxes in GUI applications.

* `string[] GetAvailableColormapsNames()`
* `Colormap CreateColormap(string name)`

## Recreating the Error

I find it interesting that I am unable to recreate this exception, even in a new project

#### ConsoleApp.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ScottPlot" Version="4.1.6-beta" />
  </ItemGroup>
</Project>
```

#### Program.cs
```cs
using System;
using System.Linq;
Console.WriteLine(string.Join(", ", ScottPlot.Drawing.Colormap.GetColormaps().Select(x => x.Name)));
Console.WriteLine(string.Join(", ", ScottPlot.Drawing.Colormap.GetColormaps().Select(x => x.Name)));
```

#### Output
```
Algae, Amp, Balance, Blues, Curl, Deep, Delta, Dense, Diff, Grayscale, GrayscaleR, Greens, Haline, Ice, Inferno, Jet, Magma, Matter, Oxy, Phase, Plasma, Rain, Solar, Speed, Tarn, Tempo, Thermal, Topo, Turbid, Turbo, Viridis
Algae, Amp, Balance, Blues, Curl, Deep, Delta, Dense, Diff, Grayscale, GrayscaleR, Greens, Haline, Ice, Inferno, Jet, Magma, Matter, Oxy, Phase, Plasma, Rain, Solar, Speed, Tarn, Tempo, Thermal, Topo, Turbid, Turbo, Viridis
```

## Determining Available Colormaps

> Maybe we should give up the use of reflection?

A hard-coded dictionary (with `string` and `Colormap`) could achieve this. However, I'm very surprised that this is not possible with Reflection. The dictionary would certainly work, but it would be more satisfying to get the reflection method working.

Perhaps reflecting on the type (rather than assembly) will solve this issue?

Since I can't recreate the original error, it's hard to know if this fixes it.

```cs
public static Colormap[] GetColormaps() =>
        typeof(Colormap)
        .GetProperties()
        .Where(x => x.PropertyType == typeof(Colormap))
        .Select(x => (Colormap)x.GetValue(x))
        .ToArray();
```

**Comment by StendProg** [comment]
>ConsoleApp.csproj

I just now realized that this is most likely the case, I got this error in a fairly old project, the project file was created in the old version of the VS2015 or older and has the old format, most likely this is the case.
In general, the problem is most likely on my side, sorry to bother you.
But getting this 2 methods without reflection would still be great, and without creating 20+ `Colormaps` objects just to pull names out of them.
