### ISSUE TITLE
AddPoint() should have a "label" argument

### ISSUE THREAD

**Issue by AlgoExecutor** [ScottPlot/ScottPlot#787]
Would it be possible to add the label property/parameter for the method AddPoint so it appears in the legend? Looks like there is currently no legend support.

**Comment by swharden** [comment]
Hi @AlgoExecutor, 

Your suggestion is to add a `string label` argument to this list for `AddPoint()`. I think this is a good idea since `AddScatter()` has a label like this.

For now, you can make a point appear in the legend by assigning to its `Label` field. I think something like this will work (although I'm just typing it in the browser and haven't tested it yet), and should work for most plot types
```cs
var plt = new ScottPlot.Plot();
var pt = plt.AddPoint(123, 456);
pt.Label = "my point";
plt.Legend()
```

**Comment by AlgoExecutor** [comment]
Hi @swharden , 

thanks for the quick response and the nice hint! For consistency this would be nice when AddPoint get the label feature as well.

**Comment by AlgoExecutor** [comment]
The hint works nice for one Point. But what if a lazy programmer add points in a loop (creating point cloud manually) then i got this:

![image](https://user-images.githubusercontent.com/79081847/107986147-bfb0a080-6fcb-11eb-8a01-fb681961b56a.png)

Of course i can only label one of the points. Then the result looks good. Does it make sense if the legend groups or eats the labels with the exact same text and the same symbol? Maybe you can think about it if it makes sense?

**Comment by swharden** [comment]
Does `AddScatterPoints()` help address your goal? It has a label and only appears once in the legend, regardless of how many points are plotted.
https://swharden.com/scottplot/cookbooks/4.1.7-beta/category/plottable-scatter-plot/#markers-only

**Comment by AlgoExecutor** [comment]
Ah sorry i din't see this function yet. I think this is it! It would be nice if this function could also control the marker size as described here: #784.
