### ISSUE TITLE
Legend should consider lineWidth: 0

### ISSUE THREAD

**Issue by AlgoExecutor** [ScottPlot/ScottPlot#790]
If you use **AddScatter** and **lineWidth: 0** to visualize point clouds, the legend should also show them as points. Currently it is still displayed as line + point. Otherwise it confuses the viewer. Here is an example:

![image](https://user-images.githubusercontent.com/79081847/107984793-ff29bd80-6fc8-11eb-9851-e4cd0d9074a0.png)

Used Version: **ScottPlot 4.1.6-beta**

Used Code:
```cs
...
 formsPlot.Plot.AddScatter(xDate.ToArray(), ci.Data.ToArray(), Color.DeepPink, lineWidth: 0, 5, MarkerShape.filledSquare, label: "2");
formsPlot.Plot.XAxis.DateTimeFormat(true);
formsPlot.Plot.Title($"Test");
formsPlot.Plot.Legend();
formsPlot.Render();
```

**Comment by swharden** [comment]
Thanks for reporting this @AlgoExecutor! I fixed this and will upload a NuGet package in a few minutes 👍 

The problem was that System.Drawing renders a 1px line when asked to draw a line with a pen that has a line width of 0 🙄 

After the fix things look good!

```cs
var plt = new ScottPlot.Plot();
plt.AddScatter(new double[] { 1, 2, 3 }, new double[] { 1, 4, 9 }, lineWidth: 0, label: "no line");
plt.AddScatter(new double[] { 1, 2, 3 }, new double[] { 2, 5, 10 }, markerSize: 0, label: "no marks");
plt.Legend();
```

![image](https://user-images.githubusercontent.com/4165489/108018871-e6c89b80-6fe6-11eb-8d8c-c6f34cfa4b88.png)

**Comment by AlgoExecutor** [comment]
Thank you @swharden for the quick fix :+1:
