### ISSUE TITLE
OHLC should implement IComparable

### ISSUE THREAD

**Issue by ticool** [ScottPlot/ScottPlot#816]
Hello,

Im just saving your OHLC  to Entity framework  with Sqllight Core and when im trying to make queries using linkq i got this :

Property 'HistoricRates.OhlcItem' cannot be used as a key because it has type 'OHLC' which does not implement 'IComparable<T>', 'IComparable' or 'IStructuralComparable'. Use 'HasConversion' in 'OnModelCreating' to wrap 'OHLC' with a type that can be compared.'

```cs
public static List<OHLC> GetOhlcList(string cryptoCoinName, Granularity granularity)
{
     using (SqliteDbContext dbContext = new SqliteDbContext())
     {

      var c =  dbContext.HistoricRates.Where(s => s.MarketItemName == MarketItemName )     // Multiple market products
                                                    .Where(s => s.GranularityItem == granularity)                   // Multiple timeSpan  5 min 1 hour etc
                                                    .Select(s => new
                                                    {
                                                         s = s.OhlcItem
                                                    }).ToList();
     }
}


public class HistoricRates
{
        public string MarketItemName { get; set; }
        public Granularity GranularityItem { get; set; }
        public OHLC OhlcItem { get; set; }
}
```

Would be cool if OHLC  had IComparable<T> interface !

If you have better idea on how to implement that im open to new ideas ! :)

**Comment by bclehmann** [comment]
I agree it would be useful for OHLCs to implement `IComparable`, although I think it could be ambiguous whether it should compare them based on open or closing price.

For the timebeing, you can try following the error message by creating a value converter and registering it with `HasConversion`: https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations. I haven't messed with that specific aspect of EF Core so I don't have any further advice. I believe this assumes you have control over `SqliteDbContext` and that it's not autogenerated, although even in that case you may be able to extend that class and override `OnModelCreating` regardless. If that class overrides `OnModelCreating` itself (often used for seeding data) then that could get hairy.

Another option instead of setting up value conversions between a wrapper class that implements `IComparable` is to just put that wrapper class in the database and not bother registering an automatic conversion.

**Comment by ticool** [comment]
Ok thx for suggestion !

**Comment by swharden** [comment]
It seems easy enough to implement comparison functionality in OHLCs. Rather than price, I think comparing the `DateTime` makes sense (especially when considering sorting).

Would something like this address the issue? (#818)
https://github.com/ScottPlot/ScottPlot/pull/818/files

**Comment by bclehmann** [comment]
I agree `DateTime` may make more sense as the field to compare, but unfortunately I think that just makes it *more* ambiguous what the comparison does. I now am unsure that this feature is a good choice. If we stored individual points of a scatterplot as a `Point` struct it would be the same issue, in certain contexts it makes more sense to compare on the x or y value but in general it just adds more confusion. 

I'm of the opinion that a feature shouldn't be added if its behaviour (as interpreted by the user, not the compiler or runtime) is ambiguous. Especially when a wrapper class with behaviour of the user's choosing is trivially implemented.

**Comment by swharden** [comment]
> I think that just makes it more ambiguous what the comparison does. 

> I now am unsure that this feature is a good choice. 

> Especially when a wrapper class with behavior of the user's choosing is trivially implemented

After thinking about it some more, I feel the same way. To me it doesn't make intuitive sense to sort or compare candles anyway! Adding extra code just to support an external frameworks is probably not a pattern we want to get into the habit of adopting 😅
