### ISSUE TITLE
The candle stick  graph change to scatter when using zoom to fit data !

### ISSUE THREAD

**Issue by ticool** [ScottPlot/ScottPlot#856]
The issue doesn't happen in your example solution ! Thats strange any ideas ?

![image](https://user-images.githubusercontent.com/393970/110221158-97b0b080-7e98-11eb-939c-b07afdc6f9e2.png)

![image](https://user-images.githubusercontent.com/393970/110221173-a6976300-7e98-11eb-9c2f-23e9a2a34017.png)

**Comment by swharden** [comment]
> The candle stick graph change to scatter when using zoom to fit data ... the issue doesn't happen in your example solution

I can zoom in to finance plots on my system, and it sounds like it works for you too using my example solutions. Therefore I think this bug is in your code somewhere. 

If you can provide a code example demonstrating how to reproduce this bug I can take a closer look, but based on the information provided so far I don't think this issue is actionable so I'll close it for now. Feel free to open it back up again if you have more information 👍
