### ISSUE TITLE
Legend GetBitmap throws System.ArgumentException: 'Parameter is not valid.'

### ISSUE THREAD

**Issue by mzemljak** [ScottPlot/ScottPlot#860]
_ScottPlot 4.1.09-beta_

I'm having problem displaying and saving Legend. 
Legend doesn't shows on the Plot.
When calling ` Plot3.Plot.Legend().GetBitmap(false)` an exception `System.ArgumentException: 'Parameter is not valid.'` is thrown.

Code for using and updating Plot in an WPF .net 5 aplication.
```cs
public WpfPlot Plot3
{
    get { return _plot3; }
    set { SetProperty(ref _plot3, value); }
}
```

```xaml
<ContentControl Grid.Column="2" MinWidth="200" MinHeight="200" Content="{Binding Plot3}"></ContentControl>
```

```cs
var legendBitmap = Plot3.Plot.Legend().GetBitmap(false);
```

**Comment by swharden** [comment]
Hi @mzemljak, thanks for reporting this!

It looks like the problem arises when using the old API to request the legend before the plot has been rendered. I'll update the code so it performs the expected behavior. For now, here's a quick fix using the latest beta / pre-release version

```cs
var plt = new ScottPlot.Plot();
plt.AddSignal(ScottPlot.DataGen.Sin(51), label: "test");
plt.Legend().OutlineColor = System.Drawing.Color.Transparent;
System.Drawing.Bitmap bmp = plt.RenderLegend();
bmp.Save("legendTest.bmp");
```

PS: Note the transparent outline is required to ensure the 1px border doesn't show-up in the saved image. I'll fix this when I work on the rest of this issue.

**Comment by swharden** [comment]
I added an improved exception error message when trying to get the bitmap before it's rendered, and I fixed the issue that required the transparent outline hack.

I'll release this on NuGet tonight. Thanks for the initial report @mzemljak!

```cs
System.Drawing.Bitmap bmp = plt.RenderLegend();
```
