### ISSUE TITLE
Improve point render performance with spatial index

### ISSUE THREAD

**Issue by AlgoExecutor** [ScottPlot/ScottPlot#870]
Hi @swharden & Team,

perhaps I had mentioned it before. The point drawing performance becomes very slow with large dataset's Here is an example with 2.5 million points. In this view i zoomed in so that about 1000 points are visible:
![image](https://user-images.githubusercontent.com/79081847/111229072-8d538c80-85e5-11eb-9a4d-f39df13937d1.png)

As you can see, a lot of render time is wasted. Probably all points are rendered? The `AddScatterPoints` function was used. Is it perhaps useful to use a spatial index like the **R-tree**? You can think about it :-)

Version: **ScottPlot 4.1.9-beta** 
Thank You!

**Comment by StendProg** [comment]
Hi @AlgoExecutor,

I don’t fully understand exactly what type of Plottable you are using, could you please clarify.

I once carried out optimization for rendering polygons, this resulted in a separate `PlottablePolygons`.
From produces a clipping of polygons beyond the visible boundaries, and draws a single point instead of a polygon if it is too small.
These optimizations have some effect, but the performance will still be unacceptable when trying to render millions of polygons at the same time.

To carry out optimization, it is necessary to impose some additional restrictions, as is implemented in signals. It is impossible to obtain a gain in the general setting of the problem.
If you describe what you want to get in more detail, we may be able to come up with something.

In the case you described, even if you cut off the points outside the visible boundaries and get an acceptable performance, after AxisAuto () you will still have 2.5 million points to draw, which will take minutes.

**Comment by AlgoExecutor** [comment]
Hi @StendProg ,

thank you for your fast response 👍 . The idea is to visualize many points or scroll through them. Points or Markers are drawn by this code:

```csharp
formsPlot.Plot.AddScatterPoints(xDate.ToArray(), ci.Trades.Select(x => (double)x.Price).ToArray(),
                    Color.DarkViolet, 5, MarkerShape.filledSquare, label: "Binance");
```
I am also thinking which approach would be better. One could clip points at the edges. That would probably be the simplest approach. Or you could work with spatial operators like the R-Tree. Then there is a more general approach. This is extensible to other geometries like lines or polygons...

This current case is a little bit special, because the X axis is time and there are only points. So you could even clip by time here if the plot knows the boundaries. A more general approach wouldn't be bad either, of course ;)
I think all Scatter functions for point drawing are affected by this.

The problem you point out would of course exist if all points be displayed at once. Here you would improve the speed only with point clustering. So points that are close or can not be displayed by the resolution can be grouped together. But i think this is maybe the next level?

Thank You!

**Comment by StendProg** [comment]
> One could clip points at the edges. That would probably be the simplest approach.

You can try using it now with `PlottablePolygons`. You just need to spend a little time converting to the required format.

I was thinking about R-tree for `PlottablePolygons` (although I have 0 experience in this area, I think that the problem is solvable).
You offered a good idea for clustering points, although there are also nuances there. The main problem is that sooner or later you will face a situation when the points are evenly distributed on the plane and you still need to draw a million points , which is absolutely beyond the capabilities of the GDI+.

If we look at the problem from the other side, when for each pixel of the screen we only need to find whether it is covered by any of the point of the plot. And a structure like R Tree will help quickly answer this question. Then the resulting rectangular field can be quickly rendered using a bitmap, as `PlottableHeatmap` does.
I have positive experience in a similar direction, the problem is that there are really a lot of pixels and this task is beyond the power of the CPU, but it is perfectly solved on the GPU. It would be possible to go in this direction, but it will create the need for an additional dependency (I am using ManagedCuda for example) which violates the main objectives of ScottPlot.

Another big problem is that as soon as we introduce some kind of additional structure on the data, then our `Plottable` instantly turns into a `PlottableConst`, and when the initial data changes, we need to update this structure as well. This goes beyond the basic concept of ScottPlot, which I think is permissible, `SignalConst` do the same, but this approach should be avoided whenever possible.

**Comment by AlgoExecutor** [comment]
Thank you for your valuable input. I can totally understand not turning the whole concept of the lib upside down right away. 3D can actually be an exit. But i think that may not be necessary. 

Like you said. You can't actually draw more points than there are pixels on the display. Just learned there is a term for that: **Overplotting**
Fighting it seems to be an art and there are several ways to do it. Here I found a paper which might be useful: 
https://www.researchgate.net/publication/220586609_Generalized_Scatter_Plots

If you look on the net there are many other sources. Some more, some less useful. I find generalization the best. If you manage to reduce the number of points simply and e.g. stop drawing when the pixel is already occupied. Which possibilities are there to recognize if a pixel is already occupied? Would the Headmap approach fit in? That sounds pretty nasty :D

I haven't quite understood the scatter - lines relation not yet. Wouldn't it be useful to have a function that visualizes only points without complex dependencies? Would that give more freedom when clipping points?

If I see this correctly, there are two scenarios:
a) I only see a part of the data like when i zoomed-in. I could clip at boundaries or use a spatial index. 
b) I see the complete data set and i'm overplotting. So i need to reduce data/points 

At some point, of course, the boundary between a+b becomes blurred...

**Comment by StendProg** [comment]
I just briefly read the article on the link, as I understand it, they solve a slightly different problem, on the contrary, they try to shift the overlapping points in order to see more information. In our case, the task is not to give the same point multiple times for drawing to GDI+. 

What we came to, is to write our own rasterizer on a rectangular grid, instead of GDI+, for some particular case (points are always squared, for example), yes it is possible, and maybe even faster, but this can be done only with a lot of restrictions , the colors of the points are the same, without antialiasing, etc. abandoning a large number of opportunities GDI+. I would not be surprised that similar algorithms for optimizing overlapping points have already been implemented somewhere in SkiSharp out of the box, it works very fast.

> haven't quite understood the scatter - lines relation yet. Wouldn't it be useful to have a function that visualizes only points without complex dependencies? Would that give more freedom when clipping points?

I just wanted to clarify that ScatterPlot in terms of this library is a little different. We are talking about a `Point cloud`, for example, or whatever else it can be called. Undoubtedly, such an opportunity is useful, and at least somehow it seems to be solved, in contrast to the `Lines` case.

**Comment by AlgoExecutor** [comment]
Hi @StendProg ,

yes, you are right. In this case it is a point cloud. Therefore, it might make sense to have a separate renderer for it? I also see the problem that things quickly become complicated when clipping at the boundaries if lines involved. For this, the lines would have to have a real line representation and not just points. So at least two points for a segment. This would also be important for the R-Tree.

The idea with the rasterizer would probably be the next level. If you go this way then you will need the algo in the paper. This should improve the visible representation. Might be too much in a first optimization step? At least you could optimize quite a lot on the GDI+ side. 

I played a little bit :-)
Just filtering out the points that lie on top of each other brings considerable progress in the initial view. So it is possible to reduce the points from `2.557.503` to `871.267`. **66**% reduction. Not bad far a start. Code I used:
```csharp
HashSet<PointF> hash = new HashSet<PointF>();
for (int i = from; i <= to; i++)
{
  ...
  PointF pp = new PointF(x, y);
  if (!hash.Contains(pp))
  {
	  points.Add(pp);
	  hash.Add(pp);
  }
}
```
So quite simple. 

If you do clipping of the boundaries it will be really fast if you zoom in. Probably an R-tree could do more. But the clipping only works if you leave the lines out of consideration...

Thank you!

**Comment by StendProg** [comment]
Hi @AlgoExecutor, 
> I played a little bit :-)
Just filtering out the points that lie on top of each other brings considerable progress in the initial view. So it is possible to reduce the points from 2.557.503 to 871.267. 66% reduction. Not bad far a start. Code I used:

The solution is very interesting for its simplicity, I think you can get a greater effect if the coordinates are previously rounded to integer values.

It was very pleasant to participate in the discussion and many ideas were expressed. But I guess I'll take a break until I get to coding and try to dig deeper on my own, otherwise we'll just talk about what.

**Comment by AlgoExecutor** [comment]
Hi @StendProg ,

that's totally ok. The conversation with you was really nice and I could implement the small quickfix. And as you say, even this can be improved with integer rounding. Would be nice if you could find point cloud solution from which other users of ScottPlot can benefit without writing their own renderer ;-)

If I think of anything else on the subject I'll write it here...
