### ISSUE TITLE
Sub-Day time resolution for bar charts

### ISSUE THREAD

**Issue by AlgoExecutor** [ScottPlot/ScottPlot#871]
Hi @swharden & Team,
 
is it possible to support sub-day time resolution for Bar charts as well? Like it is possible with OHLC data and the timespan for example? I'm using `Plot.XAxis.DateTimeFormat(true);` for the Bar chart and get the following problem: 
![image](https://user-images.githubusercontent.com/79081847/111231490-ae1de100-85e9-11eb-96f4-36ef7043a01f.png)

Would be cool if you could use bar charts on the minute too :)

Version: **ScottPlot 4.1.9-beta**
Thank you!

**Comment by swharden** [comment]
Hi @AlgoExecutor, 

I think the issue here is that the default width of bars is `1.0` and when you use a date time axis each `1.0` units means 1 day. Your bars should probably be much smaller, so set their width as a fraction of a day. I'll make a cookbook example to make this clearer then close this issue 👍 

```cs
// display the bar plot using a time axis
var bar = plt.AddBar(values, positions);
plt.XAxis.DateTimeFormat(true);

// indicate each bar width should be 1/24 of a day then shrink sligtly to add spacing between bars
bar.BarWidth = (1.0 / 24) * .8;

// adjust axis limits so there is no padding below the bar graph
plt.SetAxisLimits(yMin: 0);
```

![image](https://user-images.githubusercontent.com/4165489/111890874-09721980-89c4-11eb-8a41-5202adffc581.png)

**Comment by AlgoExecutor** [comment]
Thank you for the solution @swharden . I had already guessed that I'm missing something :)
