### ISSUE TITLE
"bug" defaults constructors

### ISSUE THREAD

**Issue by paviano** [ScottPlot/ScottPlot#873]
Hi Scott!

Little "bug": I got a dynamic application which stores Plottables, but I cant serialize them without a default ctor.
Coult it be implemented everywhere?
Apparently the problem is raised on PlottablePolygon.

Little "request": possibility to control the margins between y axis an container.

My special congrats to this project,
chart have **amazing** (❤❤) performance and still be pretty.

**Comment by StendProg** [comment]
Hi @paviano,

It seems to me that it is not worth solving the problem using objects that were not originally intended for this.

I see a fairly simple solution to the described problem.
Create DTO objects for the required Plottables and a couple of methods for converting back and forth.
```c#
[Serializable]
public class SerializablePolygon
{
  public double[] XS {get;set;}
  public double[] YS{get;set;}
  ...
}

...

public static SerializablePolygon ConvertTo(this Polygon source)
{
...
}

public static Polygon ConvertTo(this SerializablePolygon source)
{
 ...
}

```

Yes, this will require writing a certain amount of code, but it will be very simple, and you will have complete control over these objects. (for example you can throw out the properties of an object that you are not interested in).

Introducing default constructors for Plottable is not a good idea, existing parameterized constructors ensure the integrity of objects. Yes, this is just an additional layer of protection, but since it is, let it remain.

> Little "request": possibility to control the margins between y axis an container.

Written rather briefly, I think it would be a good idea to go into more detail and create a separate Issue.

**Comment by paviano** [comment]
> Written rather briefly, I think it would be a good idea to go into more detail and create a separate Issue.

What I mean is just have the ability to re-set the margin/padding between the chart (axis) and the container of the chart.
At this moment there's a big space between the container left border and the y axis. It's not a problem, but having the possibility to set these parameters would be good. I'll open a feature request.

Thank you for your time
