### ISSUE TITLE
SignalXY does not respect OffsetX or OffsetY

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#890]
```cs
var sig = plt.AddSignalXY(/* random walk data starting at (0, 0) */);
sig.OffsetX = 10_000;
sig.OffsetY = 100;
```

I would expect the data to start at `(10000, 100)` not `(0, 0)`. Automatic axis limit detection works as expected though.

![image](https://user-images.githubusercontent.com/4165489/111887264-2d286600-89aa-11eb-917b-df15c70eb4e4.png)

**Comment by StendProg** [comment]
Hi @swharden,
I made PR #894 to fix that.

But I would like to discuss the very necessity of using offsets.
As far as I understand, it all started with a `Signal`, where `OffsetX` is the only way to set an offset from 0 and its use is fully justified. `OffsetY` was added rather for symmetry, since you can always add an offset manually to the `ys` array on the user side.
`SignalXY` has both arrays `xs` and `ys`, and personally I don't see any particular problem adding an offset on my own to this arrays.

I fully admit that my vision is very limited, and for many, the ability to set the offset may be a very convenient feature. I just wanted to bring my opinion up for discussion.
From my point of view, these parameters do not significantly degrade performance, significantly complicate the `SignalXY` code, and will never be used (at least by me).

**Comment by swharden** [comment]
Thanks for #894 @StendProg!

## X/Y Offset Use Case

> I would like to discuss the very necessity of using offsets

Hi @StendProg, you raise a fair point! Many people may not have a need for offsets, and even so it is possible to achieve an offset effect by manipulating original data.

The use case I typically have for offsets is when displaying electrical signals over time. These signals are long and continuous recordings, but they are often separated into "sweeps" where a repetitive action occurs every several seconds. I often write GUIs which switch between different display styles, so it is not convenient to modify the data of the array every time I want to change the offset strategy. Also some of these recordings are very long (millions of data points), so manipulating the data points can be costly. Finally, I often want the user to adjust a slider to change the offset settings, and applying these offsets at the pixel level (rather than the raw data level) is much faster. Here are some screenshots to illustrate the type of plots I typically create:

It is common to display this data as overlapping sweeps:

![image](https://user-images.githubusercontent.com/4165489/112759154-b994e300-8fbf-11eb-92a9-e227edadedee.png)

However it is also very common to display data as "stacked sweeps", so the Y offset becomes useful here:

![image](https://user-images.githubusercontent.com/4165489/112759149-b6015c00-8fbf-11eb-85c8-350c777149ec.png)

This data is 12 one-second sweeps. Using X offset it can be displayed to appear as one continuous signal:

![image](https://user-images.githubusercontent.com/4165489/112759319-72f3b880-8fc0-11eb-9e4a-45e86ef69f31.png)

Using both X and Y offsets, 3D effects are achievable too:

![image](https://user-images.githubusercontent.com/4165489/112759139-ad108a80-8fbf-11eb-989c-804191961fc4.png)
