### ISSUE TITLE
Updated data in a graph.

### ISSUE THREAD

**Issue by FoxTes** [ScottPlot/ScottPlot#905]
Hi Scott.

I am trying to create a simple graph with data.
First I create the data, then I clear the graph (to remove the old data) and add the new ones.

First time, it works. When you add the following data, the graph is not redrawn. But if you move the graph with the mouse, you can see that the data has been updated.

At this point I have solved the problem by creating a new graph.
```cs
_plot = PlotControl.Plot;
```

It seems to me that the problem is in the _plot.Clear () method.

```cs
var random = new Random(); 
var data = DataGen.RandomWalk(random.Next(10,100));

_plot.Clear();
_plot.AddSignal(data);
_plot.AxisAuto();
_plot.Render();
```
Thanks for the help.

**Comment by StendProg** [comment]
Hi @FoxTes ,
You need to call PlotControl.Render() at the end, instead of PlotControl.Plot.Render().

**Comment by FoxTes** [comment]
Yes, it works. 
@StendProg, thanks.

I advise you to point out the difference between these methods in the documentation.

**Comment by StendProg** [comment]
@FoxTes Your remark is very correct, it is confusing when all manipulation takes place through the `Plot`, but the `Render` must be called for the `Control`.
A good solution would be to change the name of `Plot.Render` so that it would not occur to the user to call it, but this change is very significant. Hopefully @swharden will come up with something when he has time.

**Comment by swharden** [comment]
Hi @FoxTes, thank you for this question! I agree it can be difficult for beginners to learn relationship between the `Plot` object and the user controls (`FormsPlot`, `WpfPlot`, etc). I'll continue to work to improve the documentation to make this more discoverable in the future!

More information on this topic can be found in the ScottPlot FAQ:
https://swharden.com/scottplot/faq/#user-control-live-data

> A good solution would be to change the name of Plot.Render

Thanks for the suggestion @StendProg! `Render()` can be confusing because `Plot.Render()` and `FormsPlot.Render()` don't do exactly the same thing (one renders a bitmap while the other renders-and-displays a bitmap).

`FormsPlot.Invalidate()` makes sense for WinForms, but it may not be intuitive for newer C# programmers. Perhaps `FormsPlot.Redraw()`? I'll continue to think about another method name I can add to the user controls!
