### ISSUE TITLE
Alternative name for Render() in user controls

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#913]
When plots are modified in user controls, the programmer must request a render programmatically. This may not be immediately obvious (#912). Further, `Plot.Render()` and `FormsPlot.Render()` do different things:

* `Plot.Render()` redraws the plot and returns a Bitmap

* `FormsPlot.Render()` redraws the plot and updates the screen

Consider changing the user control's render method to a different and more descriptive name. Perhaps, `FormsPlot.Redraw()`?

**Comment by FoxTes** [comment]
Hi @swharden
So is the `plot.Render()` method needed? 
Perhaps it should be made private so that development won't be able to use it?

Maybe `FormsPlot.Update()`?

**Comment by StendProg** [comment]
I think that `Controls` do not have any problems with `Render`, the problem here is in the `Plot.Render` name.
It looks like it will solve the control update problem, but in fact it doesn't. If `Plot` didn't have such a misleading method name (`Render`), then I think users would quickly find what they need to call `Render` for `Control` without too many problems.
`Plot.GetBitmap` could be a more accurate description of its current behavior. 

The huge problem here is that the current naming conventions are already well established. And it is difficult to predict what problems this renaming may lead to.

**Comment by swharden** [comment]
> The huge problem here is that the current naming conventions are already well established

Very true. This problem can probably be solved with high quality XML documentation, and clear code examples. 

No change is required
