### ISSUE TITLE
Horizontal Bar Chart Not Appear

### ISSUE THREAD

**Issue by Moo1211** [ScottPlot/ScottPlot#944]
My sample code to generate horizontal stacked bar chart with datetime to be display as x-axis. However, when I was try to set x-axis limit to the range of `minDateTime.AddSeconds(-1).ToOADate() till maxDateTime.ToOADate()`, the bar chart does not displayed out. I had to zoom out to certain scale only the chart appear. 

P/S: minDateTime is the minimum datetime of datasets in the chart, whereas maxDateTime is the maximum datetime of datasets in the chart. 

```cs
Random r = new Random();
mcChartObj.Insert(0, new MCChartObject()
{
    xs = new double[] { 1 },
    ys = new double[] { DateTime.Now.AddMinutes(count).ToOADate() },
    color = !machineRunning 
        && !machineError ? System.Drawing.Color.Yellow : machineRunning 
        && !machineError ? System.Drawing.Color.GreenYellow : System.Drawing.Color.Red,
});

mcChart.plt.Clear(p => p is PlottableBar);

foreach (MCChartObject model in mcChartObj)
{
    mcChart.plt.PlotBar(model.xs, model.ys, fillColor: model.color, horizontal: true, barWidth:0.1);
}

var min = mcChartObj.Min(x => x.ys[0]);
DateTime minDateTime = DateTime.FromOADate(min);

var max = mcChartObj.Max(x => x.ys[0]);
DateTime maxDateTime = DateTime.FromOADate(max);
mcChart.plt.Axis(minDateTime.AddSeconds(-1).ToOADate(), maxDateTime.ToOADate());
mcChart.plt.Ticks(dateTimeX: true);

Application.Current.Dispatcher.Invoke(() => { mcChart.Render(true); });
count++;
```

**Comment by Moo1211** [comment]
Something that i want:
 (but i would like to have my axis limit start with DateTime.Now.addMinutes(-1).ToOADate(), unfortunately the chart does not show the bar chart. It only worked for axis limit start with DateTime.Now.addHours(-1).ToOADate())
mcChart.plt.Axis(x1:DateTime.Now.addHours(-1).ToOADate(), x2:maxDateTime.AddMinutes(1).ToOADate());
![image](https://user-images.githubusercontent.com/71800625/113559765-8a701880-9634-11eb-87d4-c32458c93adb.png)

Situation when axis limit is set with
 mcChart.plt.Axis(x1:DateTime.Now.ToOADate(), x2:maxDateTime.AddMinutes(1).ToOADate(), y1:0, y2:2);
![image](https://user-images.githubusercontent.com/71800625/113559607-467d1380-9634-11eb-8d9c-9e4dcb17e5d6.png)

**Comment by swharden** [comment]
Hi @Moo1211,

Unfortunately I'm having a very difficult time understanding your question. This is why I didn't reply earlier, and I suspect it's why others have not offered suggestions too.

> sample code to generate horizontal stacked bar chart with datetime to be display as x-axis

If you haven't already, check out the **DateTime Bar Plot cookbook demo**: 

https://swharden.com/scottplot/cookbooks/4.1.13-beta/category/plottable-bar-graph/#datetime-bar-plot

It's pretty hard to tell from your code why you are experiencing a problem. Consider making known DateTime objects and plotting those, then add complexity like determining min/max DateTimes. I suspect something in your DateTime logic (not your plotting code) may be causing your issue here.

Hope it helps!
