### ISSUE TITLE
Problem with Y-Axis values ​​disappearing and the size of the chart

### ISSUE THREAD

**Issue by saklanmazozgur** [ScottPlot/ScottPlot#945]
Hello @swharden, I have detected two errors. I don't know if the problem is solved in new versions. I looked in general but couldn't find a solution.

## Auto-Resize

It resizes its outer area based on the data in the chart. You can comfortably understand the position of Angle-1 text in the video below.

https://user-images.githubusercontent.com/4165489/113585824-bd95b600-95fa-11eb-8e51-2e489824813b.mp4

## Disappearing Tick Label

If only one value remains on the y-axis of the chart, it is deleted and does not appear. An example is given in the video below.

https://user-images.githubusercontent.com/4165489/113585846-c4bcc400-95fa-11eb-9d17-3210511646c6.mp4

**Comment by swharden** [comment]
Hi @saklanmazozgur, I modified your post to include the videos inline with the comment.

Regarding the first issue (auto-resize to fit data), I don't filly understand the problem. Is the problem that the axis limits are automatically adjusted to fit the data every time new data is added, but you don't want this behavior to occur? 

If it helps, this example shows how new data only expand the axis limits horizontally without modifying the vertical axis limits https://swharden.com/scottplot/faq/live-data/#growing-data-with-partial-array-rendering

If I misunderstand your problem still, can you re-state it so I might better understand it? Thanks

Regarding the second issue (missing tick label if just one tick), I actually think this was fixed in the most recent release last weekend. Can you ensure you're running the latest version on NuGet? If it's still an issue I can take a closer look for sure.

Thanks for the feedback!

**Comment by swharden** [comment]
Regarding the tick issue, I realize I fixed it this week (#828, #725, #925) but haven't published it to NuGet yet. I plan to publish a new package tonight (version 4.1.12-beta) so let me know if that doesn't fix it as expected 👍

**Comment by saklanmazozgur** [comment]
@swharden  Thank you very much,

Now I noticed that if the values ​​are 4 digits, it shrinks the frame. I guess the desired behavior. I can set the decimal place of the data I sent. I think this will fix the problem.

I am waiting for the new package. After trying it I can give feedback.

**Comment by audun** [comment]
I believe something similar to the first issue was a problem for me too. If you display several plots with a shared x-axis, but different y-axis, the plots do not line up.

![image](https://user-images.githubusercontent.com/454644/114013515-ea023a00-9867-11eb-946a-25a69735d5a0.png)

However, you can fix it by using the Layout method, like `plt.YAxis.Layout(0, 100, 100);`

![image](https://user-images.githubusercontent.com/454644/114013751-2fbf0280-9868-11eb-9120-afa566643c32.png)

**Comment by swharden** [comment]
Finally uploaded a new package to NuGet (ScottPlot 4.1.12-beta) and this should be fixed now. Thanks for everyone's help!
