### ISSUE TITLE
PlotScatter fails plotting a single point when line width is >0

### ISSUE THREAD

**Issue by avshiza** [ScottPlot/ScottPlot#948]
We are facing the same issue [PlotScatter fails plotting a single point #126
](https://github.com/ScottPlot/ScottPlot/issues/126) in ScottPlot nuget version 4.0.48 (.net framework 4.7.2) when using PlotScatter and line width is set to >1. Is this fix mentioned in the related link avaiable in this version?
Error Details
```
Parameter is not valid.
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawLines(Pen pen, PointF[] points)
   at ScottPlot.PlottableScatter.Render(PlotDimensions dims, Bitmap bmp, Boolean lowQuality)
   at ScottPlot.Renderer.DataPlottables(Settings settings)
   at ScottPlot.Plot.RenderBitmap()
   at ScottPlot.Plot.SaveFig(String filePath, Boolean renderFirst)
```

This is the code we are using:
```cs
var pltNew = new ScottPlot.Plot(640, 480);
pltNew.PlotScatter(new double[1] { 0 }, new double[1] { 2 }, markerSize: 1, lineWidth: 1, color: ColorTranslator.FromHtml("#FF4848"));
pltNew.SaveFig(string.Format(@"{0}test.png", Program.pathPrefix));
```

**Comment by swharden** [comment]
Thanks for noting this @avshiza! This just got fixed in #949 by https://github.com/ScottPlot/ScottPlot/pull/949/files#diff-1ea41615b8a5a5a7bae1acbce3a617b8dd1d3562ed62b1a95f89bffbc99391a1

I won't release a new 4.0 package on NuGet for several more days though (#716 ), but if you want to make this change yourself you can download the 4.0 branch of ScottPlot here https://github.com/ScottPlot/ScottPlot/tree/4.0-stable

PS: These issues are all connected: #948, #949, #126, #822, #764
