### ISSUE TITLE
AddBar: what should the order of arguments be?

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#977]
## ScottPlot 4.0

```cs
PlotBar(xs, ys);
```

## ScottPlot 4.1.12-beta

Argument order has been designed to be consistent across all overloads ([fuget](https://www.fuget.org/packages/ScottPlot/4.1.12-beta/lib/netstandard2.0/ScottPlot.dll/ScottPlot/Plot))

```cs
AddBar(values);
AddBar(values, positions);
```

## Is this better?

It's more consistent with ScottPlot 4.0, and more consistent with other methods in that the order is "Xs, Ys"

It's a breaking change (a bad one - it fails invisibly), but only affects the beta / pre-release.

```cs
AddBar(values);
AddBar(positions, values);
```

I'm inclined to make this change in the next release, but I welcome feedback

**Comment by bclehmann** [comment]
I think it's more important that less important parameters (including by definition optional parameters) should always be last. Specifying an extra parameter should make the result more specific, instead of radically changing the meaning.

I think always putting x before y makes sense when they're both equally important, but in this case I don't think they are.

**Comment by swharden** [comment]
> I think always putting x before y makes sense when they're both equally important, but in this case I don't think they are.

Sounds good to me!

I also think this is a non-issue with well-named arguments and high quality XML docs.
