### ISSUE TITLE
New plot type: Dendrogram

### ISSUE THREAD

**Issue by FoggyFinder** [ScottPlot/ScottPlot#987]
Not very popular but still useful type of graph

Details:

[Dendrogram](https://www.d3-graph-gallery.com/dendrogram)
[Dendrogram](https://www.data-to-viz.com/graph/dendrogram.html)

Some images taken from the link above

![Img1](https://www.data-to-viz.com/graph/dendrogram_files/figure-html/unnamed-chunk-1-1.png)
![Img2](https://www.data-to-viz.com/graph/dendrogram_files/figure-html/unnamed-chunk-4-1.png)

**Comment by bclehmann** [comment]
I have considered adding more graph and tree-like ideas but never moved forward with it for a few reasons:
- They don't really rely on coordinate space, although this also applies to things like pie charts which *have* been added
    - Thus they're not *really* plottables
    - This also makes the scope for interaction low, it would mostly just be the user zooming in to read small text
- They are often (though certainly not always) static, so the user is often better served by using (La)TeX
    - This is not unique to this proposal, things like `SignalConst` are always static
- Work on graphs or trees is unlikely to transfer to other plottables
- It seems difficult

The last point is in my mind the main reason I have not put any effort into this area. As I pointed out, pie charts don't really fit into coordinate space but I worked on it anyways because it was easy. Plenty of plottables are mostly or entirely static, that is also not reason in and of itself to not consider it.

On top of the challenges above, I wonder if it fits just in terms of scope? This does seem like something a diagramming library should do instead. I'm noticing that there are not particularly many options for diagramming libraries, and most of them are not open source or even free. Perhaps that's an opportunity but I don't think it quite fits within ScottPlot's existing scope.

**Comment by swharden** [comment]
This is an interesting idea! On one hand it definitely seems doable, but on the other hand it seems outside the scope of what a typical plotting library would be expected to do. This almost seems like something you should use a SVG library to implement.

I added this to the plottable section of triaged tasks (#1028) next to wiggle plots (#450). It might get implemented one day, but it's not actively being worked on so I'm going to close this issue for now.
