### ISSUE TITLE
Plot Settings - Data export, option for multiple curve export

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#997]
Hello!

It would be great if there was an option to export multiple curve data to a single csv file.
As I see, now there is only option to select a single curve to export.
Selection for multiple Plottable Objects could be done in the common way: mouse + shift / mouse + ctrl would select all lines between / select individual lines separately.
Thanks! :)

![image](https://user-images.githubusercontent.com/51174971/116384365-103c4980-a818-11eb-8a22-b61fba2fef6e.png)

**Comment by bclehmann** [comment]
I assume you're referencing the `GetCSV` or `SaveCSV` methods that were in ScottPlot 4.0.x. These methods are not in the 4.1.x betas and from what I know there is no intention to add them.

There are two reasons for this:
- It's not really related to plotting
    - There are some parts in this library which are more for convenience than plotting, however they generally make plotting easier, as opposed to being something more suited for a CSV library
- It does not let the user do anything new, the user already has all of the data and can export it as they please
    - Since ScottPlot is not a serialization library it does not offer anywhere near the features that would be necessary to be a useful option. And developing those features would be a massive increase in scope, which is difficult to justify when plenty of other libraries exist and do the job very well.

Since this feature is not likely to be part of ScottPlot 4.1 I think it's difficult to justify working on it further, aside from things like bug fixes. I would recommend you develop your own solution or look at existing CSV libraries. Even if ScottPlot were to continue to develop these functions it would never reach the level of flexibility or feature completeness that a dedicated CSV library has.

Sorry for the inconvenience.

**Comment by StendProg** [comment]
Even if this were the goal of the library, then the problem you proposed is unsolvable in general. `Plottables` can have a different number of points, different values of X, it may not have X values at all, what about the arrows, labels etc. It is possible to combine data into one file only knowing the specific task, which remains on the user's side.

**Comment by swharden** [comment]
> It would be great if there was an option to export multiple curve data to a single csv file

This is an interesting thought! On one hand it would be convenient for some users, but on the other hand it does seem outside the scope of plotting, and could be challenging to implement in a way that would benefit most users.

My quick thoughts are:
* ScottPlot 4.1 has removed this settings dialog from the WinForms control
* ScottPlot 4.1 has removed CSV export from plottables
* File export should probably be handled by the developer most familiar with their data (not by a charting library)

For these reasons I'll go ahead and close this issue, but I'm glad the topic came up! It gave ScottPlot the opportunity to solidify its opinion that it will take care of data _visualization_ tasks but data _management_ tasks (input, transformation, export) are to be accomplished by the programmer.

> the problem you proposed is unsolvable in general ... different values of X or no X values at all

lol, yes, there's also this 🧐
